### ISSUE TITLE
Any plans for using external rendering engine or smth?

### ISSUE THREAD

**Issue by andresKM** [kataras/iris#102]
Any thoughts to use external template packages like https://github.com/valyala/quicktemplate or something like that?
I know that speed isn`t about everything but maybe it will be a good idea.

**Comment by kataras** [comment]
Before 1 -2 weeks the (small)community decided that we  don't need any external renderer/template parser build'n inside Iris ( we have already middleware for pongo2) and one of the best html/template support. But the last days I'm thinking this again, valyala/quicktemplate seems a good point ( which is good because we're using fasthttp also) but it's like ,html/template, not a complete solution.

You opened this discussion again, I'm tagging this issue as `Debate`, if the community respond positively I'll change the build'n renderer/template parser on whatever ,again, you(the community) agree on.

**Comment by xpbliss** [comment]
a pluggable template engine may be more better.
May be In config file : 
template.Engine=pongo2   #go, quicktemplate, and anyother template engine.........

**Comment by kataras** [comment]
Yes.. this I'm thinking of right now but I need more stable and well tested suggestions, the renderer must be the most stable thing here

**Comment by qskousen** [comment]
From Gitter chat, @kataras has at least started implementing this, at least for Quicktemplate. The template engine is configurable.

**Comment by kataras** [comment]
No its not ready then, I just wokeup from hangover I will start this today, the template engine's code is creepy I just wrote it to remember what to do

**Comment by insionng** [comment]
@xpbliss It will not have too much import? If you are using the import template engine should be better?

**Comment by kataras** [comment]
@insionng  v3.0.0-alpha is workable , you can switch template engines from IrisConfig, build'n support for html/template and pongo2,  and for the future the quicktemplate also. Read [here for more](https://kataras.gitbooks.io/iris/content/render.html)

**Comment by insionng** [comment]
https://github.com/valyala/fasttemplate  look great too.
Also, why not by middleware to support the template engine?

**Comment by kataras** [comment]
You don't need a middleware for fasthttp and quicktemplates, Iris is build on top of fasthttp, if you want the fasthttp's context just do that `ctx.GetRequestCtx()` :) quicktemplate is faster than fasthttptemplate( from the same author), quicktemplate will be build in supported at the next revision

**Comment by insionng** [comment]
My template is currently based on the pongo2, is dynamic. Whether migrating to quicktemplate? Or is that migrated to the fasttemplate is better?

**Comment by kataras** [comment]
quicktemplate, fasthttptemplate is nothing compared to quicktemplate... take look at its code and compare them :)  The quicktemplate will be the next build'n supported template engine
