### ISSUE TITLE
Set int value into session (using redis db), but can not get it out!

### ISSUE THREAD

**Issue by jaggerwang** [kataras/iris#1020]
## Problem

Very strange problem! I can set string value into session (using redis db) and can get it out, but not working with int value.

Set("id", "10005") => GetString("id") OK
Set("id", "10005") => GetInt("id") OK
Set("id", 10005) => GetString("id") Fail
Set("id", 10005) => GetInt("id") Fail

```go
func newSession(db sessions.Database) *sessions.Sessions {
	sess := sessions.New(sessions.Config{
		Cookie:  viper.GetString("session.cookieName"),
		Expires: time.Duration(viper.GetInt64("session.expireHours")) * time.Hour,
	})

	sess.UseDatabase(db)

	return sess
}

func newSessionDb() *redis.Database {
	return redis.New(service.Config{
		Addr:     viper.GetString("session.db.addr"),
		Password: viper.GetString("session.db.password"),
		Database: viper.GetString("session.db.database"),
	})
}

func RunApp() {
	app := iris.New()
	app.Use(recover.New())
	app.Use(logger.New())

	sessdb := newSessionDb()
	defer sessdb.Close()
	iris.RegisterOnInterrupt(func() {
		sessdb.Close()
	})
	sess := newSession(sessdb)

	mvc.New(app.Party("/")).Handle(controller.NewIndex())
	mvc.New(app.Party("/oauth/")).Register(sess.Start).Handle(controller.NewOAuth())
	mvc.New(app.Party("/account/")).Register(sess.Start).Handle(controller.NewAccount())

	fmt.Println("load views from", viper.GetString("web.viewDir"))
	app.RegisterView(iris.HTML(viper.GetString("web.viewDir"), ".gohtml"))

	fmt.Println("web service listen on", viper.GetString("web.listenAddr"))
	app.Run(iris.Addr(viper.GetString("web.listenAddr")))
}

func (c *Account) GetLogin(ctx iris.Context) {
	c.Session.Set("currentUserID", "10005")
}

func (c *Account) GetInfo(ctx iris.Context) {
	id, err := c.Session.GetInt("currentUserID")
	...
}
```

## Env

Go: go version go1.10.2 darwin/amd64
Iris: 10.6.5:https://github.com/kataras/iris/blob/master/HISTORY.md#mo-21-may-2018--v1065

**Comment by kataras** [comment]
I I know where the problem is, you'll have a fix for that in 24hours from now :) Thank you @jaggerwang for the bug report.

**Comment by kataras** [comment]
Fixed, although `GetFloat64` would work because redis stores the go's int as float64, it was an easy fix, on the `GetInt` we added a check for `float64` as well (alongside with `int64` and `string` we already have there).

Please complete the user experience form whenever you feel free to: https://goo.gl/forms/lnRbVgA6ICTkPyk02 and [star the iris project](https://github.com/kataras/iris/stargazers) if you love the fast fixes:)

Upgrade with: `go get -u github.com/kataras/iris`, automatic updater will not work because I'm waiting some days more for pushing the new release. Thank you @jaggerwang , have a nice day!
