### ISSUE TITLE
errors.go:34:11: assignment mismatch: 2 variables but 1 values

### ISSUE THREAD

**Issue by chenliejun** [kataras/iris#1025]
go run main.go
#${project-name}vendor/github.com/kataras/iris/core/errors
vendor\github.com\kataras\iris\core\errors\errors.go:34:11: assignment mismatch: 2 variables but 1 values

**Comment by kataras** [comment]
You have an older version of github.com/satori/go.uuid, I am assuming this is happening because you're using external tools for dependency managment, while you don't need it, iris is vendored. The `vendor/github.com/satori/go.uuid` that iris contains it's the latest one, it will work if you do `go get -u github.com/kataras/iris`

**Comment by chenliejun** [comment]
yeah,I use godep instead of dep for dependency managment because of GFW,I delete the vendor folder it works,but how can I understand iris is vendored,after all  I didn't see the vendor folder under my project.
