### ISSUE TITLE
Why are you deleting my comments?

### ISSUE THREAD

**Issue by kgregorczyk** [kataras/iris#1028]
Hi, I submitted quite a serious issue here:
https://github.com/kataras/iris/issues/997

Then I wrote  a better explanation and it got deleted

1. Could you tell me why?
2. Could you reopen the issue? 

It's quite a big pain in the as without using redis pubsub mechanism as a backend for websockets there will be troubles with scailing.

WIth two instances of the same application one client can get connected to 1st one, other client can get connected to 2nd instance and if 1 instance publishes a message which should be received by both clients it will be received only by clients connected to 1st instance, not to all of them. 

I'm going to create a screenshot of that :)

**Comment by kataras** [comment]
You must read our Code of Conduct before any comment here, this is not a fan place, this is the Iris' github issues you must respect and show love for each member of this Community, otherwise you have no place here, pelase stop creating new accounts in order to insult us, stop using Iris if you think that it's not suitable for your needs, I doubt if you can find anything better but this is your choice, I can't force you for anything.

**Comment by kataras** [comment]
About your "issue" as I told you, I need a code snippet to reproduce that because I think it's not valid report, as I told you in your previous comment but your response was inappropriate.

**Comment by kgregorczyk** [comment]
My response was "inappropriate"? What was inappropriate in it?

There's no code snipped, it's an architecture problem.

**Comment by kataras** [comment]
Excuse me, what can I do for you?

**Comment by kgregorczyk** [comment]
At least try to resolve the problem, as I said before, there's no code snippet because it's an architecture problem, run two instances of iris with websockets behind a simple load balancer.

**Comment by kataras** [comment]
You can read more at: https://yeti.co/blog/establishing-a-websocket-pubsub-server-with-redis-and-asyncio-for-the-light-sensor/, take levarage of iris websocket library and convert that to Go and you will be ready to go, I am not recommending extending websockets via redis, this is why we don't built'n support it, as many things, we choose what to support in order to be maintainable and fun to work with, it's up to you how you will use Iris, a low-level web framework, to extend its capabilities for your own use case or even create a general-purpose library for (iris) websockets + redis and share it with us!

**Comment by kataras** [comment]
Why should I try to resolve a problem that I don't think it's an iris' problem? I just have 24 hours per day and I have to give time on bigger things, this is not important and it's not relative to Iris in any way, you must make more research to understand that but you will!

**Comment by kgregorczyk** [comment]
It is iris problem as it doesn't provide any kind of backend module for
websockets, it does for sessions as an example. Not having such module
makes websockets unusable in a real production environment where you need
to scale.
*[image: unnamed.gif]*

*  •  **Kamil Gregorczyk*
*  •  *Application Developer
*  •  *kgregorczyk@google.com
  •  +48 722 229 482




pt., 22 cze 2018 o 16:09 Gerasimos (Makis) Maropoulos <
notifications@github.com> napisał(a):

**Comment by kataras** [comment]
What websocket library does that in Go? We use the gorilla/websocket as the underline connection.

**Comment by kataras** [comment]
As for the real production, let me know better xD, companies use Iris and I have great internal feedback from people working and be paid because of Iris.
