### ISSUE TITLE
Bug with 10.6.6 using go 1.10.3

### ISSUE THREAD

**Issue by Toyz** [kataras/iris#1030]
When building iris even the example is get the following error in my console

`github.com\kataras\survey\confirm.go:53:30: cannot use os.Stdin (type *os.File) as type terminal.Stdio in argument to terminal.NewRuneReader`

Is there any work around or fix inbound for this?

**Comment by kataras** [comment]
Is this the same as: https://github.com/kataras/iris/issues/1029 ?

**Comment by kataras** [comment]
Because we tested iris with the latest go version today as well and examples are running successfully, nothing changed on `github.com/kataras/survey` these days, the last change was at Nov 2, 2017 as you can see [here](https://github.com/kataras/survey). Please provide more information whenever you can so I can help you personally.

**Comment by kataras** [comment]
The *error message your comment describes is also wrong*, it says `as type terminal.Stdio` but the `NewRuneReader` (that is used on the [kataras/survey/confirm.go:53](https://github.com/kataras/survey/blob/master/confirm.go#L53)) accepts an `*os.File`, look [here](https://github.com/kataras/survey/blob/master/terminal/runereader.go#L14), so there is not error anywhere I don't know why you get this error, maybe your dependency manager didn't download its subfolder? the `github.com/kataras/survey/terminal` package

**Comment by kataras** [comment]
OK something strange happens with the tools that GO developers use these days for dependency managing, they are useless and they make your life harder instead of solving problems, it downloaded the  `AlecAivazis/survey` version (which accepts a `terminal.Stdio`) instead of the `kataras/survey` but as you can see in [code](https://github.com/kataras/iris/search?q=AlecAivazis&unscoped_q=alecAivazis), Iris doesn't even contain that library neither its dependencies. Change your dependency manager and simply do `go get -u github.com/kataras/iris` and you'll be fine, Iris is fully vendored no need for external software. Hopefully the Go team and Russ will do the job and find and complete a decent solution to the dependency managing soon, until then **don't use external dependency managers like dep and gp, I said that from the day zero and I feel very listened when Russ did the same**.

**Comment by kataras** [comment]
OK something strange happens with the tools that GO developers use these days for dependency managing, they are useless and they make your life harder instead of solving problems, it downloaded the  `AlecAivazis/survey` version (which accepts a `terminal.Stdio`) instead of the `kataras/survey` but as you can see in [code](https://github.com/kataras/iris/search?q=AlecAivazis&unscoped_q=alecAivazis), Iris doesn't even contain that library neither its dependencies. Unistall your dependency manager and simply do `go get -u github.com/kataras/iris` and you'll be fine, Iris is fully vendored no need for external software. Hopefully the Go team and Russ will do the job and find and complete a decent solution to the dependency managing soon, until then **don't use external dependency managers like dep and gp, I said that from the day zero and I feel very listened when Russ did the same**.
