### ISSUE TITLE
golang iris return directly template html

### ISSUE THREAD

**Issue by nirnava** [kataras/iris#1034]
question is here.
https://stackoverflow.com/questions/51099508/golang-iris-return-directly-template-html

this project : github.com/kataras/iris/_examples/mvc/overview
path : web/controllers/hello_controller.go
var helloView = mvc.View{
	Name: "hello/index.html",
	Data: map[string]interface{}{
		"Title":     "Hello Page",
		//"MyMessage": "Welcome to my awesome website",//Comment this line
	},
}
The result I want is <html> <head> <title>{{.Title}} - My App</title> </head> <body> <p>{{.MyMessage}}</p> </body> </html>
 but actual results <html> <head> <title> - My App</title> </head> <body> <p></p> </body> </html>

**Comment by kataras** [comment]
Do you register a 'view engine' at your 'app.RegisterView? as _examples/views folder shows? Please so us the main code snippet

**Comment by kataras** [comment]
Hello @nirnava, it seems that you didn't comment anything since you posted this, but the **issue you're describing is invalid**, here are my results from the [mvc/overview example](https://github.com/kataras/iris/tree/master/_examples/mvc/overview), as expected:

![invalid_issue_1034](https://user-images.githubusercontent.com/22900943/42347408-84fae43c-80ae-11e8-8ff6-f4016de602ee.png)

Can I help you with something?
