### ISSUE TITLE
request hero DI new feature 

### ISSUE THREAD

**Issue by venjiang** [kataras/iris#1037]
I like DI container,but hero is simple,it only provide "Handle" method inject context.Handle,I hope it like  [dig](https://github.com/uber-go/dig), can inject "DataRepository,DB,Service..." ,thanks.

**Comment by kataras** [comment]
Hello @venjiang , I didn't know about the `dig` library.

But `hero` package are for handlers and mvc methods for the **web**, it can inject `DataRepository` `DB` or anything else it doesn't matter, it can also inject **dynamic web properties, dig can not as I can see**, our `hero` package has no limits, `dig` has. If you like `dig` you can go with it, no problem. I will close this issue because actually you don't ask a feature, we have it already, just read the examples, we have screenshots there as well :)

Thank you,
Gerasimos Maropoulos

**Comment by venjiang** [comment]
thanks.
