### ISSUE TITLE
Application.Logger() return the same instance of golog.Logger object

### ISSUE THREAD

**Issue by terender** [kataras/iris#1075]
In the ```New()``` function of ```iris.Application``` the ```logger``` is set to ```golog.Default```, that is pointer to the same ```golog.Logger``` object. 

```go
func New() *Application {
	config := DefaultConfiguration()

	app := &Application{
		config:     &config,
		logger:     golog.Default,
		APIBuilder: router.NewAPIBuilder(),
		Router:     router.NewRouter(),
	}

	app.ContextPool = context.New(func() context.Context {
		return context.NewContext(app)
	})

	return app
}
```

No matter how many ```Application```  is created using ```New()```,  their ```logger``` is the same, and the log is wrote to the same output if default ```requestLogger``` middleware is used.
Of course implement another logger middleware could resolve it. 
But it's a little bit unconvenient if I want to create multiple web applications in the same program using 
a shorthand just like ```iris.Default()```

**Comment by kataras** [comment]
You have right, this is by-design, the idea is because you may have more than one iris application running, and normally, you have one log output, so the use of the default `golog` instance is a good idea. **This is documented, so it is not a surprise as well, look at:** https://github.com/kataras/iris/blob/master/iris.go#L256 You can also change the logger's output (`io.Writer` compatible) to something that can check the "source-application" and make decisions etc.

**Comment by kataras** [comment]
I can add a `app.SetLogger` if you want but the default behavior: sharing the same golog instance is useful not only between many iris apps but between your entire application, you can use the `golog.$func` and it will have the same output as your iris app server(s).

**Comment by terender** [comment]
I've just been confused by the log output mixed all together from different iris apps. 
But That's fine if it is in purpose because using a custom middleware logger instead of the default ```requestLogger``` could achieve the goal.
Thank you 👍

**Comment by kataras** [comment]
Exactly, You are welcome @terender. Don't hesitate to ask more!
