### ISSUE TITLE
ReadForm got error when no query parameter

### ISSUE THREAD

**Issue by haritsfahreza** [kataras/iris#1095]
Hi 👋 

I found that `context.ReadForm` function would throw an error `An empty form passed on ReadForm` if there is no form that sends to the API.

What I need is, I have an endpoint like `GET /users?name=iris` to get users that have `iris` word in their name. And if I do not send the query parameter like `GET /users`, I want to get all of the users. So the `name` is a non-mandatory parameter.

Here is a snippet code of my handler:

```go
type userHTTPHandler struct {
	config config.Config

	userSvc users.Service
}

type UserQuery struct {
	Serial   string `form:"serial"`
	Serials  string `form:"serials"`
	Name     string `form:"name"`
	Email    string `form:"email"`
	PageSize int    `form:"pageSize"`
	Page     int    `form:"page"`
}

func (h *userHTTPHandler) FindByQuery(ctx iris.Context) {
	ctx.ContentType("application/json")
	var userQuery users.UserQuery
	err := ctx.ReadForm(&userQuery)
	if err != nil {
		ctx.StatusCode(http.StatusBadRequest)
		ctx.JSON(api.NewErrorResponse(0, err.Error()))
		ctx.Application().Logger().Error(err)
		return
	}

	result := h.userSvc.FindByQuery(context.Background(), &userQuery)
	ctx.JSON(result)
}
```

Is there any solution for me?

Thanks before 🙏

**Comment by kataras** [comment]
Hello @haritsfahreza,

The form does throw an error if nothing founds and it will also return an error if it has trouble to read something. I think you have a point here but the issue is not that we return an error for empty values, **the issue in my opinion is that we don't return an error that you can validate and check for**. Therefore I pushed that commit a second ago: [context#ErrEmptyForm ](https://github.com/kataras/iris/commit/5e79a86c5a0f528bc12020ffbcb0904f12832313). With this you can check the error value, example:

```go

import (
    "github.com/kataras/iris/context"
    // ...
)
func (h *userHTTPHandler) FindByQuery(ctx context.Context) {
	ctx.ContentType("application/json")
	var userQuery users.UserQuery
	err := ctx.ReadForm(&userQuery)
	if err != nil && err != context.ErrEmptyForm { 
                // it has an error but it is not the values are empty error value.
		ctx.StatusCode(http.StatusBadRequest)
		ctx.JSON(api.NewErrorResponse(0, err.Error()))
		ctx.Application().Logger().Error(err)
		return
	}

	result := h.userSvc.FindByQuery(context.Background(), &userQuery)
	ctx.JSON(result)
}
```

However, if you still propose a design change on that function we can discuss it for the [v11](https://github.com/kataras/iris/v11) branch that I am working on for the next Iris release.


**More...**

Note that I don't know the implementation of your `userSrv.FindByQuery` but the best place to make these type of changes is there and not in your route. You have to make the correctness checks of your query inside that `userSrv.FindByQuery`, i.e check if  `userQuery's Name is empty and if it is then fetch by all, if it not fetch the user based on that Name` and etc.

Although there is a solution that **depends on a named route path parameter and does not depend on url parameters or form at all**, that could be more "preferable" **if you just have one main property** that fetching from the datastore operation depends, example:

Split your "/users" route :
```go
   app.Get("/users/{name}", FindByQuery)
   app.Get("/users", FindByQuery)
```

Check the parameters instead of reading the whole form (if you just require the "name" for fetching)
```go
func FindByQuery(ctx iris.Context) { // or context.Context (from kataras/iris/context package)
   if name := ctx.Params().Get("name"); name !="" { 
    // because we may register this handler for two routes,
    // one of those accepts a path parameter.

    /* [...here fetch by "name"] */
    return
   }

   /* [...here fetch all] */
}
```

**Comment by kataras** [comment]
We can change that behavior and return nothing if was nothing to read from, but we can't do it on the current `v10` because it is a breaking change. I will push a commit to the `v11` instead.

**Comment by haritsfahreza** [comment]
Cool! thankyou @kataras 🙏  can't wait until v11 released!
