### ISSUE TITLE
When controller struct using private field with interface type, calling private field's method in struct method got "bad access" error.

### ISSUE THREAD

**Issue by jaggerwang** [kataras/iris#1096]
When change field `userRepo` to `UserRepo` to make it public, the error will disappear.

Controller:

```go
package controller

type Account struct {
	Base
	// IUser is a interface type
	userRepo          accountRepo.IUser
}

func (c *Account) PostLogin() {
	...
	// Got "bad access" error
	c.userRepo.ByUsername(username)
	...
}
```

Repository Factory:

```go
package factory

type RepositoryFactory struct {
}

func NewRepositoryFactory() *RepositoryFactory {
	return &RepositoryFactory{}
}

func (f *RepositoryFactory) NewUser() *accountRepo.User {
	return &accountRepo.User{NewDBFactory().GetDefault()}
}
```

Controller Factory:

```go
package factory

type ControllerFactory struct {
}

func NewControllerFactory() *ControllerFactory {
	return &ControllerFactory{}
}

func (f *ControllerFactory) NewAccount() *controller.Account {
	repositoryFactory := NewRepositoryFactory()
	return &controller.Account{
		UserRepo:          repositoryFactory.NewUser(),
	}
}
```

App: 

```go
app := iris.New()
app.Use(recover.New())
app.Use(logger.New())

ctlFactory := factory.NewControllerFactory()
mvc.New(app.Party("/account/")).Register(ses.Start).Handle(
	ctlFactory.NewAccount())

app.Run(iris.Addr(viper.GetString("web.listenAddr")), iris.WithoutVersionChecker)
```

**Comment by kataras** [comment]
Yes, just don't use private fields when binding there, it is a golang "best practise" at general.

All examples from https://github.com/kataras/tree/master/_examples/mvc are using exported fields(capitalized) like this one: https://github.com/kataras/iris/blob/master/_examples/mvc/login/web/controllers/user_controller.go#L32 which is something similar to your code snippet.

Only something like `visits uint64` or `prefix string` would work for static binding even unexported because they are not referring to pointers. The correct error though it would be to return something like "invalid memory address or nil pointer dereference" when trying to access that `userRepo` because the [binder](https://github.com/kataras/iris/tree/master/hero/di) will not bind it to your `ctlFactory.NewAccount()` because it will never find that unexported field.
