### ISSUE TITLE
do not use fasthttp?

### ISSUE THREAD

**Issue by yale8848** [kataras/iris#1105]
Examples for the Iris project can be found at
<https://github.com/kataras/iris/tree/master/_examples>.

Documentation for the Iris project can be found at
<https://godoc.org/github.com/kataras/iris>.

Love iris? Please consider supporting the project:
👉  https://iris-go.com/donate

Care to be part of a larger community? Fill our user experience form:
👉  https://goo.gl/forms/lnRbVgA6ICTkPyk02

**Comment by kataras** [comment]
From version 6 and up, of course not. Fasthttp does not support HTTP/2 and maybe will never do, the original author is also dissapear leaving the project to the hands of unexperienced developers, we are "luckies" because I made the transformation a long time ago, a year+, so we don't have to deal with irresponsibilities from that side, look the current project manager of that project and you will be dissapointed as well, it was a good library though I learnt some things from there at my first steps as well.
