### ISSUE TITLE
modelbinder in golang

### ISSUE THREAD

**Issue by majidbigdeli** [kataras/iris#1137]
I'm going to convert all 1610 characters to character 1603, like the following in C#

```
public class StringModelBinder : DefaultModelBinder
    {
        public override object BindModel(ControllerContext controllerContext, ModelBindingContext bindingContext)
        {
            object value = base.BindModel(controllerContext, bindingContext);

            if (value == null)
            {
                return value;
            }

            return value.ToString().Replace((char)1610, (char)1740).Replace((char)1603, (char)1705);
        }
    }
```

**Comment by kataras** [comment]
Wrong repository my friend?

**Comment by majidbigdeli** [comment]
I use iris. I want to replace Arabic letters into Persian. In other words,or convert numbers from arabic to english in server . fore example convert arabic 1610 unicode to 1740 Persian unicode

**Comment by majidbigdeli** [comment]
hi My friend . 
I use Iris .  I want Text normalization in Iris

There are often several ways to represent the same string. For example, an é (e-acute) can be represented in a string as a single rune ("\u00e9") or an 'e' followed by an acute accent ("e\u0301"). According to the Unicode standard, these two are "canonically equivalent" and should be treated as equal.

**Comment by majidbigdeli** [comment]
One solution is that
        name := ctx.Params().Get("name")
And Then convert

**Comment by majidbigdeli** [comment]
Iwant convert Arabic Letters to Persian  Letters for example "علیِ" to "علی"  and Then insert to database

**Comment by majidbigdeli** [comment]
persian.FixArabic("علي")
=> "علی"
get  ctx.Params() and fix arabic character in the all api

**Comment by majidbigdeli** [comment]
> One solution is that
> name := ctx.Params().Get("name")
> Persianname := persian.FixArabic(name)

**Comment by majidbigdeli** [comment]
change all ctx.Params  before start api

**Comment by kataras** [comment]
How to chnage all ctx.Params, they are dynamic, per request. The keys are in english, i.e `/path/{paramName:string}` , you want to convert its value, no its key. You get the value by `name := ctx.Params().Get("name")` and you convert its value to whatever you want, make functions and reuse them, Iris has nothing to do with it.

**Comment by majidbigdeli** [comment]
Sorry, my English language is weak

**Comment by kataras** [comment]
Don't be sorry @majidbigdeli, weak language does not matter here, even english. I am worst than you :)
I often use google translator to give practical answers to our beloved chinese community members' questions and problems, I don't have any issue with the language if I understand the real issue correctly I help anybody, but because I didn't understand I told you to write to chat so others may help you, as I said this is not iris relatively, that was the reason of closing this issue, remember; github issues is for bugs/questions/feature requests specifically for iris, for general golang you can use google or forums or our chat.
