### ISSUE TITLE
Type mismatch in jade.Parse

### ISSUE THREAD

**Issue by dibyendu** [kataras/iris#1162]
Probably #1126 is not revolved in 11.1.0 yet.

![screenshot 2018-12-29 at 11 43 20 pm](https://user-images.githubusercontent.com/524664/50544482-ae766100-0bc4-11e9-85ea-39851d18d59b.png)

In one of my automatic dependency management PR, that tried to bump iris from 11.0.0 to 11.1.0, the travis build failed with error:

```
$ go build
# app/vendor/github.com/kataras/iris/view
vendor/github.com/kataras/iris/view/pug.go:21:15: cannot use jade.Parse (type func(string, string) (string, error)) as type func(string, []byte) (string, error) in assignment
The command "go build" exited with 2.
```

Some potential type mismatch here:

https://github.com/kataras/iris/blob/91118c6b07fc9ad466df139f0846267aed1734b1/view/pug.go#L21

**Comment by kataras** [comment]
Hmm that's strange because I see that Iris uses the correct `jade.Parse` definition, same for its `go.mod` version and `vendor` folder. 

See: 
- upstream: https://github.com/Joker/jade/blob/master/template.go#L37
- upstream v1.0.0: https://github.com/Joker/jade/releases/tag/v1.0.0 (if you download the source and navigate to Template#Parse you will see the same `Parse(string, []byte) (string, error)` definition)
- gomod: https://github.com/kataras/iris/blob/master/go.mod#L6
- vendor: https://github.com/kataras/iris/blob/master/vendor/github.com/Joker/jade/template.go#L37
- view#html.middleware: https://github.com/kataras/iris/blob/master/view/html.go#L35
