### ISSUE TITLE
How to add a value into the request context from a middleware function?

### ISSUE THREAD

**Issue by Julio-Guerra** [kataras/iris#1180]
Hi!

I am implementing a middleware function and I would like to store a value into the request context so that handlers can access it from the Iris context but also from the request context, in case they only pass the request to sub-functions in their handlers.

Storing a value into the Iris context from a middleware function is indeed easy (`c.Values().Set(key, val)`), but what about the request's:

```go
req := c.Request()
ctx := context.WithValue(req.Context(), key, val)
req = req.WithContext(req)
```

But from there, I couldn't find any way to store the new request created by `WithContext()` into Iris' context.

I thought `FromStdWithNext()` would help me on this but the request pointer passed to `next()`  is ignored (https://github.com/kataras/iris/blob/master/core/handlerconv/from_std.go#L75).

Thanks for your help!

**Comment by kataras** [comment]
I see, so you need a way to override/wrap the `ctx.request` field which is unexported, you have read-only access to the http.Request via `ctx.Request()`. We have a [ctx.ResetResponseWriter](https://github.com/kataras/iris/blob/master/context/context.go#L113), we can add a `ctx.ResetRequest` if you think that's useful, sounds great?

However, I have an obligation to warn you that the std `context.WithValue` thing and `req.WithContext` are bit slow because they do copies. Prefer to stick with iris-defined [ctx.Values()](https://github.com/kataras/iris/blob/master/core/memstore/memstore.go#L714-L1009) whenever you can.

**Comment by Julio-Guerra** [comment]
You went fast :smile: But indeed, other Go frameworks have similar `SetRequest()` methods to set it from middlewares.

> However, I have an obligation to warn you that the std `context.WithValue` thing and `req.WithContext` are bit slow because they do copies. Prefer to stick with iris-defined [ctx.Values()](https://github.com/kataras/iris/blob/master/core/memstore/memstore.go#L714-L1009) whenever you can.

Yes, it does a shallow copy. I am not a fan of this `WithContext()` also, but it's the only way for now and some of our users only pass the request or the request context to functions called by handlers.

Thanks for your support!

**Comment by kataras** [comment]
Yes, I was in turbo mode yesterday as well :) We could check the `request.Context().Value` before returning from `ctx.Values().Get(key)` but the limitation is that the `ctx.Values()` returns a `memstore.Store` from our `core` package, it is de-coupled by-design and I think it's better to keep it that way, if you think otherwise I can createa  new wrapper for store that we can pass the *http.Request value.

I thank you for the question!!

**Comment by kataras** [comment]
Hello @Julio-Guerra, sorry for the delay but I've just read an issue inside your go-agent project 28 days ago, [here](https://github.com/sqreen/go-agent/pull/22#issuecomment-503583595), I thought that was solved with `ctx.ResetRequest(newRequest)` as implemented after this issue of yours.

https://github.com/kataras/iris/blob/3cd0837383b4c0a29048b625e97250ca64d8b44a/context/context.go#L117-L128

Let's give you a sample code and tell me if that suits your case:

```go
newRequest := ctx.Request().WithContext(yours go-agent's sql standard context.Context)
ctx.ResetRequest(newRequest)
```

Also the [FromStdWithNext](https://github.com/kataras/iris/blob/3cd0837383b4c0a29048b625e97250ca64d8b44a/core/handlerconv/from_std.go#L75) sets this for any case the net/http Request's context modified.

Did you mean that you wait the v11.2.0 to be released or the solution doesn't fix your issue? (although you can `go get github.com/kataras/iris@v11.2.0`)

Thanks!
