### ISSUE TITLE
Jsonpb support

### ISSUE THREAD

**Issue by siehc** [kataras/iris#1188]
It would be great to support [jsonpb](https://godoc.org/github.com/golang/protobuf/jsonpb).
Standard library's json package has an [issue](https://github.com/golang/protobuf/issues/189) to work with protobuf.

**Comment by kataras** [comment]
Hello, I really don't understand what you want from Iris, `proto`s are not the same as JSON, we can't do `Marshal/Unmarshal` on-fly of any object. You can do it by-hand by your own, iris has nothing to do with this matter. [There is](https://github.com/tnarg/protoc-go-plugins/blob/master/protoc-gen-go-jsonpb/main.go) already **proto cli plugin** which will generate masrhal/unmarshal functions for each of your proto payloads.

Could you please explain us better what exactly is that you want?

Thanks,
Gerasimos Maropoulos

**Comment by siehc** [comment]
Sorry for not explaining it clearly.

I use iris as an gateway to grpc microservices.
Sending grpc response to client by ctx,JSON() will cause wrong json field name [issue](https://github.com/golang/protobuf/issues/189).
It would be great to have a ctx.JSONPB() which invoke jsonpb marshaler to generate JSON instead of standard json library.

**Comment by kataras** [comment]
Ofc, send us a link of a jsonpb marshaler lib that you tested and we can use which is not a CLI app/generator and we can add a function like this on the `Context`.

**Comment by siehc** [comment]
Here is the [jsonpb lib](https://godoc.org/github.com/golang/protobuf/jsonpb) and sample code.

	func SendJsonPB(ctx iris.Context, p proto.Message) {
		j := &jsonpb.Marshaler{}
		r, _ := j.MarshalToString(p)
		ctx.ContentType(context.ContentJSONHeaderValue)
		ctx.WriteString(r)
	}

**Comment by jjhesk** [comment]
@siehc i think its better to have it break it part and just making the separate repo to work with iris.context
@kataras is that possible?
the code base is too big for now, i think we should split it up to have other repo to work directly with iris.Context. i think the Context is pretty stable and robust now.

**Comment by siehc** [comment]
Or, let json marshaller used by context.JSON() configurable?

**Comment by kataras** [comment]
@siehc the `context.JSON` as all of the context methods can **be overriden** by custom implementations, take a look at the [_examples/routing/custom-context](https://github.com/kataras/iris/blob/6c054a9b5516583c03454c649143917444507bd8/_examples/routing/custom-context/method-overriding/main.go#L54-L59).

@jjhesk The `jsonpb` library is huge because it depends on the `github.com/golang/protobuf` library itself... so you know why we can't add this, the avg time to download and install Iris will probably took x4 time than it currently does, I am sorry we can't add everything, this is why Iris is so modular, so you can add your own things if you want so like the `SendJsonPB` method you wrote above.

Thanks.

**Comment by kataras** [comment]
@siehc just letting you know about the new context methods for protos:

- `Context.Protobuf(proto.Message)` sends protobuf to the client
- `Context.ReadProtobuf(ptr)` binds request body to a proto message
- `Context.ReadJSONProtobuf(ptr, ...options)` binds JSON request body to a proto message
