### ISSUE TITLE
undefined: iris.Controller

### ISSUE THREAD

**Issue by optimus-su** [kataras/iris#1202]
i use Go 1.11, but when i test this example  https://docs.iris-go.com/overview.html

i see this error at line:
type ExampleController struct {
	iris.Controller
}
 how i can fix it?

**Comment by kataras** [comment]
Hello @bpmvn, 

You are right, gitbook's `MVC` section is updated but its overview page was not for almost a year and a half. This is fixed now. However, I want to be honest with you, the `docs.iris-go.com` does not contain the whole list of features and things you can do with Iris. Because feature requests are growning so much that I haven't yet found the time to fill the gitbook and nobody is willing to help on that so far, this is why all today's links are referring to our [_examples](https://github.com/kataras/iris/tree/master/_examples) folder instead which is fully updated and contains  tests as well.

Sincerely,
Gerasimos Maropoulos

**Comment by bpmvn** [comment]
thanks you so much

**Comment by kataras** [comment]
You are welcome.
