### ISSUE TITLE
MVC with parameters and context

### ISSUE THREAD

**Issue by apuckey** [kataras/iris#1205]
According to the documentation iris.Context can be passed in as the first argument to a MVC function like so:

```go
type Controller struct {}

func (c *Controller) BeforeActivation(b mvc.BeforeActivation) {
	b.Handle("GET", "/test", "Get")
	b.Handle("GET", "/test/{id:string}", "GetById")
}

func (c *Controller) Get(ctx iris.Context) mvc.Result {
	return mvc.Response{
		ContentType: "application/json",
		Text:        "{\"welcome\": true}",
	}
}

func (c *Controller) GetById(ctx iris.Context, id string) mvc.Result {
	return mvc.Response{
		ContentType: "application/json",
		Text:        "{\"welcome\": false}",
	}
}
```
Using the Get() function works however using GetById is resulting in an application panic:
```
[WARN] 2019/02/27 17:00 Recovered from a route's Handler('github.com/kataras/iris/mvc.(*ControllerActivator).handlerOf.func2')
At Request: 200 /test/stre GET ::1
Trace: reflect: Call using zero Value argument
```
I'm registering the controller as follows:
```
mvc.New(app).Handle(new(test.Controller))
```

**Comment by kataras** [comment]
Hello @apuckey,

This is expected failure because you don't need the path parameter's bindable input arguments(`(id string) mvc.Result ...`) when you bind the `Context` itself (which contains those via `ctx.Params()...`). And in the other hand you don't need to require `Context` at method level, you can move it to your controller and it will be available via `c.Ctx`.

You are the first dev raised this as an issue, however I agree with you, you expected something else and something other happened. Give me a chance to, at least, fix that behavior on the [upcoming release](#1175).

Thank you,
Gerasimos Maropoulos

**Comment by apuckey** [comment]
No worries, 

Thanks!
