### ISSUE TITLE
write tcp [::1]:8099->[::1]:64820: wsasend: An established connection was aborted by the software in your host machine.

### ISSUE THREAD

**Issue by huamoran** [kataras/iris#1213]
Examples for the Iris project can be found at
<https://github.com/kataras/iris/tree/master/_examples>.

Documentation for the Iris project can be found at
<https://godoc.org/github.com/kataras/iris>.

Love iris? Please consider supporting the project:
👉  https://iris-go.com/donate

Care to be part of a larger community? Fill our user experience form:
👉  https://goo.gl/forms/lnRbVgA6ICTkPyk02

**Comment by huamoran** [comment]
write tcp [::1]:8099->[::1]:64820: wsasend: An established connection was aborted by the software in your host machine.

**Comment by kataras** [comment]
The error is very generic and can be caused by many reasons, can you please post a code snippet of your server and your client-side so I can help you more? Is it a websocket error? (if so, then wait for v11.2 I am designing a new library that it is capable to serve more than 10million connections at mid-cost machine)

**Comment by jjhesk** [comment]
@kataras i had the similar errors from the machine too. got 1006 and sometimes it was aborted from the clients.

**Comment by kataras** [comment]
Fixed through Iris 11.2 release. Read more at: https://dev.to/kataras/iris-version-11-2-released-22bc
