### ISSUE TITLE
StatusInternalServerError ,Custom  data can‘t be returned

### ISSUE THREAD

**Issue by hoysoft** [kataras/iris#1214]
**IF StatusCode == 500, Always returns:**`   Internal Server Error`

**The two test examples are as follows**
```
func Test(ctx iris.Context) {
    ctx.StatusCode(500)
    ctx.WriteString("show me")
}

result  RESPONSE:   
         content-type -->  text/plain; charset=utf-8
         Body  Raw -->  Internal Server Error
```

```
func Test1(ctx iris.Context) {
    ctx.StatusCode(500)
    ctx.JSON(map[string]string{
	 	"key": "xxx",
		 "val":  "9999",
    })
}

result RESPONSE:   
        content-type -->  ""
        Body  Raw -->  Internal Server Error
```

**Comment by kataras** [comment]
Hello @hoysoft. I think you are doing something wrong at your app because I tested your examples and they are working as expected. Check the results below:

![1214_1](https://user-images.githubusercontent.com/22900943/54037964-1306fb00-41c8-11e9-88c6-46c3530f9ff2.png)

![1214_2](https://user-images.githubusercontent.com/22900943/54037968-169a8200-41c8-11e9-8f17-33ef4ea86997.png)

![1214_3](https://user-images.githubusercontent.com/22900943/54037973-18644580-41c8-11e9-8e73-a2f268af9aed.png)


Please provide me more info if you believe that something is not working as expected.

Thanks,
Gerasimos Maropoulos

**Comment by hoysoft** [comment]
@kataras, thank you
I found the reason. It's really my code
My api Using the yaag middleware.
now, After removing the yaag middleware, No problem.

tks
