### ISSUE TITLE
ctx.ReadForm crashed with HTTP 500 when try to cast string to number

### ISSUE THREAD

**Issue by vzool** [kataras/iris#1219]
Hi, I made this form request struct:

```golang
// City Request
type City struct {
	ID   uint64 `form:"id"`
	Name string `form:"name"`
}

data := request.City{}
err := ctx.ReadForm(&data)

if err != nil {
	ctx.JSON(iris.Map{
		"status":   "ERROR",
		"message1": err.Error,
	})
	return
}
```

So, I expected when it fails it should fall inside `if` condition. But, I faced a strange situations, which I will explain here:

- If I sent request with extra fields not exists it fails, and it should be ignored and pass valid ones.

![Screenshot from 2019-03-10 15-38-36](https://user-images.githubusercontent.com/4952736/54085118-f3e4a680-434a-11e9-8403-0258758802f5.png)

- When I send wrong data type, and it should catch the error and pass it to `error` struct. 

![Screenshot from 2019-03-10 15-38-49](https://user-images.githubusercontent.com/4952736/54085117-f34c1000-434a-11e9-97f0-0f552512757c.png)

All these errors should be catched by `if` condition and it does not do that and every time it gives me **500 Internal Server Error** with this strange word `Unexpected 'I'`.

Thanks <3

**Comment by kataras** [comment]
Hello @vzool  and welcome, sorry for the delay but I had to implement a lot of new features for the 11.2 release, excuse me, this is not the common time to response :)

**1.**
> If I sent request with extra fields not exists it fails, and it should be ignored and pass valid ones.

This can be done if you ignore the path error: `if err != nil && !iris.IsErrPath(err)`

**2.**
> When I send wrong data type, and it should catch the error and pass it to error struct.

If you pass invalid value for ID (uint64), a string for example it will return an error of `converting value for \"id\"`

**3.**
> and 500 Internal Server Error with this strange word Unexpected 'I'.

This is happens because your code has an issue, you pass the `err.Error` which is a function so it can't be JSONed, the correct should be `err.Error()` :

```go
ctx.JSON(iris.Map{
	"status":   "ERROR",
	"message1": err.Error(), // you missed the parenthesis, ()
})
```
