### ISSUE TITLE
unexpected parameter type: file -> GET::/single_file/{myfile:file}

### ISSUE THREAD

**Issue by jmesyan** [kataras/iris#1220]
example from :https://www.studyiris.com/doc/irisDoc/DynamicPathParameters.html:
```
// http://localhost:8080/single_file/app.js
	app.Get("/single_file/{myfile:file}", func(ctx iris.Context) {
		ctx.Writef("file type validates if the parameter value has a form of a file name, got: %s", ctx.Params().Get("myfile"))
	})
```
build the code ,come the error:
```
unexpected parameter type: file -> GET::/single_file/{myfile:file}
```
how to fixed the error

**Comment by kataras** [comment]
Hello @jmesyan you are right and I am very sorry for the delay, I am very sick and I haven't internet connection in the hospital. 

I **'ve just fixed it** on `master`, `v11` and `v11-without-mod-test` branches so you can update to the latest one. The issue was a missing entry of the macros list, also please checkout the `_examples/routing/dynamic-path` for the most recent documentation and path parameters types(macros), we have many more of them on v11.
