### ISSUE TITLE
how to reset header

### ISSUE THREAD

**Issue by shehuaqigai** [kataras/iris#1228]
i want rewrite header (Authorization  eyJ0eXAi....)  to  header (Authorization  Bearer eyJ0eXAi....) 

help me

because in iris jwt middleware 

// FromAuthHeader is a "TokenExtractor" that takes a give context and extracts
// the JWT token from the Authorization header.
func FromAuthHeader(ctx context.Context) (string, error) {

	authHeader := ctx.GetHeader("Authorization")
	if authHeader == "" {
		return "", nil // No error, just no token
	}
// TODO: Make this a bit more robust, parsing-wise
	authHeaderParts := strings.Split(authHeader, " ")
	if len(authHeaderParts) != 2 || strings.ToLower(authHeaderParts[0]) != "bearer" {
		return "", fmt.Errorf("Authorization header format must be Bearer {token}")
	}

	return authHeaderParts[1], nil
}

**Comment by kataras** [comment]
Hello @shehuaqigai , sorry for the delay I am a bit sick these days and I am not able to use my computer as much as I want to so far.

Just for the issue's title: this is not about reseting a header, you can reset a header by giving it an empty value, i.e `ctx.Header("X-Header", "")` this will clear the header on the response, you can also use the `ctx.ResponseWriter().` which implements the `http.ResponseWriter` which contains a field with the headers map on the response and `ctx.Request().` for the client's incoming headers.

Anyway, let's deep into your feature request. You are speaking about the https://github.com/iris-contrib/middleware/tree/master/jwt middleare to parse the "Bearer %s" value %s as the token when possible.
It seems that you are the second person asking for something like this, I am open to add a feature that you would be able to customize the whole `token extract method`, so you can add custom headers or features like "extract by cookie" as recommended [there](https://github.com/iris-contrib/middleware/issues/47).

Please give me some time to get better and I will implement it.

> P.S: Please next time post issues at the correct repository so other users can find what they're looking for much easier.

**Comment by kataras** [comment]
@shehuaqigai This is question similar to the https://github.com/iris-contrib/middleware/issues/47, both of them are already implemented and you can do it, I don't understand the problem here.

 `Authorization: "Bearer "+$tokenValue` works, if you need from "Authorization: Bearer $tokenValue" to "Authorization: $tokenValue" then you just set a `TokenExtractor` on the jwt [middleware](https://github.com/iris-contrib/middleware/tree/master/jwt)'s Configuration: 

```go
myJwtMiddleware = jwtmiddleware.New(jwtmiddleware.Config{
	Extractor: func(ctx iris.Context) (string, error) {
            // or any custom code here.
            return ctx.GetHeader("Authorization"), nil 
	},
})
```

Another example is by url parameter (although not recommended) but you see how easy it gets:

https://github.com/iris-contrib/middleware/blob/00dac7c43ee72333a1f7c23aa213a1d7ab40ec1c/jwt/jwt.go#L115-L121
