### ISSUE TITLE
How to use jsoniter - extra

### ISSUE THREAD

**Issue by sootma** [kataras/iris#1245]
hi,
Jsoniter has a very useful function, extra
"github.com/json-iterator/go/extra"

How to use this feature in iris, such as RegisterTimeAsInt64Codec

or, provide an interface, let's set up own json Marshal  to iris
thanks

**Comment by kataras** [comment]
Hello @sootma,

`json-iterrator` is used automatically by Iris on `context#ReadJSON/JSON` when you pass the `iris.WithOptimizations` configurator to your `app.Run`: `app.Run(iris.Addr(...), iris.WithOptimizations)`.

You just do whatever you want with the `github.com/json-iterator/go/extra` and they will be reflected to the `ctx.ReadJSON/JSON`, nothing special to do more.

Keep note that you can always go deeper by using any third-party tool that accepts an `io.Writer` and an `io.Reader`:  `context#ResponseWriter()` returns an `http.ResponseWriter / io.Writer` and `context#Request().Body` returns an `io.Reader` of the request body.

Thanks,
Gerasimos Maropoulos

**Comment by sootma** [comment]
package main
import(	
	"time"
	"github.com/kataras/iris"
	"github.com/json-iterator/go/extra"
)
func main() {
	app := iris.New()
	app.Get("/test.json", test)
	app.Run(iris.Addr(":80"), iris.WithOptimizations)
	// app.Run(iris.Addr(":80"), iris.WithConfiguration(iris.Configuration{
	// 	EnableOptimizations: true,
	// }))
}

type xx struct {
	Id          int64 `json:"id,string"`
	UpdatedTime time.Time
}

func test(ctx iris.Context) {
	extra.RegisterTimeAsInt64Codec(time.Second)
	x := &xx{
		Id:          1234567890123456789,
		UpdatedTime: time.Now(),
	}
	// fmt.Println(json.ToJson(x))
	ctx.JSON(x)
}

I hope to get {" id ":" 1234567890123456789 ", "UpdatedTime" : "1555735040"}, 
but is {"id":"1234567890123456789","UpdatedTime":"2019-04-20T12:37:20.6667404+08:00"}

**Comment by sootma** [comment]
"fmt.Println(str)" got "{"id":"1234567890123456789","updatedTime":1556114674}"  
, but ctx.JSON(x) got {"id":"1234567890123456789","UpdatedTime":"2019-04-24T22:06:37.0763092+08:00"}

**Comment by kataras** [comment]
@sootma Sorry for the delay but I am working hard on plenty of project to get things done for the next Iris release. 

The solution you were looking for is: remove your `$GOPATH/src/github.com/kataras/iris/vendor/github.com/json-iterator` and it works.

Why? Because the issue is that Go sees the iris/context import path of `json-iterator/go` as differnet than your `package main's` so any `json-iterator/go/extra.$CALL` don't have any effect on the context's `json-iterator` one. This was a big problem at general but it's fixed after the new go modules, so I can say that we don't need to keep vendoring the `json-iterator` or any other library that a developer can use and directly interact with Iris anymore. The vendor for the `json-iterator` and for the `pongo2 (django view engine + pongo2-addons)` are being removed from the vendor folder of the upcoming Iris [v11.2.0](https://github.com/kataras/iris/pull/1175), its `go.mod` and `go get` should keep you safe and stable from upstream changes.

Thanks.

**Comment by kataras** [comment]
@sootma Sorry for the delay but I am working hard on plenty of different projects to get things done for the next Iris release. 

The solution you were looking for is: remove your `$GOPATH/src/github.com/kataras/iris/vendor/github.com/json-iterator` and it works.

Why? Because the issue is that Go sees the iris/context import path of `json-iterator/go` as differnet than your `package main's` so any `json-iterator/go/extra.$CALL` don't have any effect on the context's `json-iterator` one. This was a big problem at general but it's fixed after the new go modules, so I can say that we don't need to keep vendoring the `json-iterator` or any other library that a developer can use and directly interact with Iris anymore. The vendor for the `json-iterator` and for the `pongo2 (django view engine + pongo2-addons)` are being removed from the vendor folder of the upcoming Iris [v11.2.0](https://github.com/kataras/iris/pull/1175), its `go.mod` and `go get` should keep you safe and stable from upstream changes.

Thanks.
