### ISSUE TITLE
Error return value of `app.Run` is not checked (errcheck)go-lint 

### ISSUE THREAD

**Issue by WuJiY** [kataras/iris#1263]
It has some errors when i use golint.
Error tips like `"Error return value of `app.Run` is not checked (errcheck)go-lint "`.
// and app.Run...  ctx.JSON ...

thanks

**Comment by kataras** [comment]
Hello @WuJiY, as I can understand from the question you are a new comer, right? Welcome to Go and Iris community!

Iris source code is 100% "golint clean" but examples are not all "golint clean" for your own readability reasons, keep note that stdlib itself is not  "golint clean" too. Some examples shows you how to check/handle errors from the `app.Run` error and `ctx.JSON` and all that but other example that want to learn you something else they don't do it because they are focused on something else.

This is not a problem for you, as an end-developer, at the opossite;  Iris gives you the ability to check error on every step that an error may caused. Just use `golog.Fatal/log.Fatal(app.Run....)` and do checks of errors inside your apps as examples show, i.e on `ctx.JSON` which can return an error, you can do:

```go
err:= ctx.JSON(...)
if err != nil {
  // [handle error...]
}
```

**Comment by WuJiY** [comment]
Yes,  I can understand you! I just think it‘s not necessary to return an error on like` ctx.JSON` func.
Thank you for your answer.
