### ISSUE TITLE
Not resolved jwtHandler.Serve

### ISSUE THREAD

**Issue by Mahdihp** [kataras/iris#1269]
Not resolved jwtHandler.Serve when use Jwt Middelware:

`app := iris.New() jwtHandler := jwtmiddleware.New(jwtmiddleware.Config{ ValidationKeyGetter: func(token *jwt.Token) (interface{}, error) { return []byte("My Secret"), nil }, SigningMethod: jwt.SigningMethodHS256, }) app.Use(jwtHandler.Serve)`

**Comment by kataras** [comment]
Did you installed the `jwt` middleware? it's not built-in.

```
go get -u github.com/iris-contrib/middleware/...
```

The `Serve` method exists: https://github.com/iris-contrib/middleware/blob/master/jwt/jwt.go#L88

**Comment by Mahdihp** [comment]
How to add to dep(Gopkg.toml) : github.com/iris-contrib/middleware/...

**Comment by Mahdihp** [comment]
Not work install go get -u github.com/iris-contrib/middleware/...

**Comment by kataras** [comment]
So you use `dep` to manage your dependencies... I don't quite understand why a part of the community still uses an external tool instead of the native go modules (which in that case will resolve your issue) but it's totally up to you. However, can you post over the `Gopkg.toml` and `Gopkg.lock` files too so I can be more helpful?

**Comment by Mahdihp** [comment]
What tool do I use to manage dependencies in Golang?
This solution did not work([[constraint]]
  branch = "master"
  name = "github.com/iris-contrib/middleware/jwt").

**Comment by kataras** [comment]
You should use the 'go modules', just make a google search and you will find a ton of helpful articles. OK this worked man, the jwt middleware's Serve func is found. Now the problem is that you have older version of the pongo2 package, go to the Gopkg.toml -> search for pongo2 and set its 'branch' attritube to 'master', Iris' has correctly vendor it but for some reason the'dep' tool ignores it, relative to: https://github.com/kataras/iris/issues/1143#issuecomment-472035292
