### ISSUE TITLE
Middlewares with annotated handlers

### ISSUE THREAD

**Issue by massanchik** [kataras/iris#127]
Is it possible to use middlewares with annotated handlers?
[book section](https://kataras.gitbooks.io/iris/content/using-annotated.html)

**Comment by kataras** [comment]
This is a good question, you cannot use middlewares with annotated. I 'm already thinking to remove /or change them and transform to 'controller' thing with `GetMyFunc` `PostMyFunc`  and so on. Do not use handle annotated because it will change I will remove from docs also. Your question was very important

**Comment by massanchik** [comment]
Ok, Thanks!
