### ISSUE TITLE
webrtc - websocket auto disconnected

### ISSUE THREAD

**Issue by rebootcode** [kataras/iris#1276]
Hi,

I am sending `WebRTC - RTCSessionDescription offer` packet to other connected "webrtc" PEER in a socket and as soon as I send `RTCSessionDescription offer` packet, my WebSocket sends me a signal, I am disconnected and the "RTCSessionDescripotion offer packet" never reaches to other peers.

Here is my WebSocket configuration:

```
ws := websocket.New(websocket.Config{
	ReadBufferSize:  10240,
	WriteBufferSize: 10240,
})

ws.OnConnection(func(c websocket.Connection) {
    c.On("message", func(message string) {
	var dataIs map[string]string
	byteMsg := []byte(message)
	_ = json.Unmarshal(byteMsg, &dataIs)
        c.To(dataIs["room"]).Emit("message", dataIs["message"])
    })
    c.OnDisconnect(func() {
			c.EmitMessage([]byte("Connection Closed!"))
			fmt.Println("Closing Connection")
			ws.Disconnect(c.ID())
		})
})
```
And it prints on loop "on disconnect" message.

Any clue? on why, it is not able to handle "RTCSessionDescription Offer of WebRTC" ?

**Comment by kataras** [comment]
Hello @rebootcode

First of all I want you to know that in a few days the new release will be published, the websocket library I am designing for the past 3months is almost ready, you can already use it: https://github.com/kataras/neffos ( the /kataras/neffos.js repository offers a modern websocket client for javascript (nodejs(!) & browser)), and you can already **check an iris example which makes use of it on the v11.2.0** branch [here](https://github.com/kataras/iris/tree/v11.2.0/_examples/websocket/basic).

I saw the code you sent me over e-mail, I took a quick view.

About the `loop "on disconnect" message` it's happening because you fire `ws.Disconnect(c.ID())` on the `c.OnDisconnect` event which makes it to call it again.

About the actual issue with `webrtc`: I don't have enough time to validate it at the moment because simply I can't re-produce the program at all,  I need time to setup it and I am on-fire with the new iris' website as well.

**Comment by rebootcode** [comment]
Thanks bro

I will move on to "neffos" library as soon as it is a stable version. :+1:
