### ISSUE TITLE
readForm() can parse time string "2006-01-02", but readJSON can not

### ISSUE THREAD

**Issue by schooltech** [kataras/iris#1277]
context.ReadForm() can parse form field input string "2006-01-02", but when using context.ReadJSON() to parse json date string like this,  error message : parsing time \"\"2019-06-07\"\" as \"\"2006-01-02T15:04:05Z07:00\"\": cannot parse \"\"\" as \"T\"

**Comment by kataras** [comment]
Hello @schooltech, I think you are new to Go, therefore I welcome you to our community!
Let's jump to your issue:

This is not entirely an iris-specific question, you have to learn more about the [encoding/json](https://golang.org/pkg/encoding/json/) standard package and read some articles about JSON dates in Go (you will find plenty of them online), they must have a specific **layout** to be formatted and most of the times we use `int64` and `timestamps` instead of strings like `"2006-06-07"`. 

If you read the documentation you will find out that the `encoding/json` package (which `context#ReadJSON` depends on), gives you the ability to customize go struct value -> json output and json input -> go struct value by implementing the `MarshalJSON() ([]byte, error)` and `UnmarshalJSON(b []byte) error` respectfully.

Here is a good example but you can always modify it to your needs:

```go
package main

import (
	"bytes"
	"errors"
	"strconv"
	"time"

	"github.com/kataras/iris"
)

const layout = "2006-01-02 15:04:05 GMT"

type myDate struct {
	time.Time
}

func (m *myDate) UnmarshalJSON(b []byte) error {
	if len(bytes.Split(b, []byte("-"))) != 3 {
		return errors.New("invalid format, expected [year-month-day]")
	}

	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}

	s += " 00:00:00 GMT"

	t, err := time.Parse(layout, s)
	if err != nil {
		return err
	}
	m.Time = t

	return nil
}

func (m *myDate) MarshalJSON() ([]byte, error) {
	format := m.Format(layout)
	return []byte(format), nil
}

type myValue struct {
	Date myDate `json:"date,string"`
	// [...]
}

//
// OR keep the `time.Time` but do marshal for each struct's field:
//
// type myValue struct {
// 	Date time.Time `json:"date,string"`
// 	// [...]
// }

// func (v *myDate) UnmarshalJSON(b []byte) error {
// 	// do this on each field.
// }
// func (v *myValue) MarshalJSON() ([]byte, error) {
// 	// the result should be the complete json of this struct.
// }

func main() {
	app := iris.New()
	app.Post("/", func(ctx iris.Context) {
		var v myValue
		err := ctx.ReadJSON(&v)
		if err != nil {
			ctx.StatusCode(500)
			ctx.Writef("error on read json: %v\n", err)
			return
		}

		ctx.Writef("read: %#+v\n\n", v)
		ctx.Writef("Year: %d. Month: %d. Day: %d\n", v.Date.Year(), v.Date.Month(), v.Date.Day())
	})

	app.Run(iris.Addr(":8080"))
}
```

An input of  `{"date": "2006-06-07"}` can work with the above code. Check the result:

![outputforu](https://user-images.githubusercontent.com/22900943/59377927-dc5af680-8d5b-11e9-9156-58cc8838b460.png)

-------

However, I encourage you to use **unix timestamps** instead of strings like that, best wishes!
