### ISSUE TITLE
Build failed in WSL v1/2

### ISSUE THREAD

**Issue by greenhat616** [kataras/iris#1280]
Like the Pic below:
![image](https://user-images.githubusercontent.com/41122242/59610000-11e05500-914b-11e9-9deb-0846f6fc2870.png)

I can't build successfully via WSL. Do you know any solution?

**Comment by kataras** [comment]
Hello @greenhat616. The issue is that your machine has downloaded an older version of `flosch/pongo2` instead of the latest one, which Iris is using on `django` view.

I've just did an installation via `go modules` (`go.mod`, `go.sum`) and it works without errors on a clean machine. So, I assume the issue is coming from an external tool that manages your dependencies, such as `dep` or `glide`.

If you're using `dep`, edit your `Gopkg.toml` file as @mcsakoff 's guidelines: 

```
[[override]]
  name = "github.com/flosch/pongo2"
  branch = "master"

[[constraint]]
  name = "github.com/kataras/iris"
  version = "11.1.1"

[prune]
  go-tests = true
  unused-packages = true
```

If not, please clear your `pkg/mod` cache directory and re-try a `go get -u github.com/kataras/iris`, this should solve the issue.

Please verify if the above heped you, thank you.

**Comment by greenhat616** [comment]
![image](https://user-images.githubusercontent.com/41122242/59652606-04fe4880-91c1-11e9-85b5-7a0626f48a55.png)
![image](https://user-images.githubusercontent.com/41122242/59652787-d5037500-91c1-11e9-81f6-d49089dcf2b5.png)

Thanks a lot. Direat install Successfully via `go get` .

**Comment by kataras** [comment]
Great!!
