### ISSUE TITLE
How to use jet template in iris ？

### ISSUE THREAD

**Issue by wx85278161** [kataras/iris#1281]
jet template
<https://github.com/CloudyKit/jet>

**Comment by kataras** [comment]
Hello @wx85278161, 

Let's start by saying that you can use any template engine with Iris, i.e herotemplate or even quicktemplate, check the [herotemplate example](https://github.com/kataras/iris/tree/master/_examples/http_responsewriter/herotemplate) and [quicktemplate engine](https://github.com/kataras/iris/tree/master/_examples/http_responsewriter/quicktemplate), the tutorial on both sides tells you how to do it pretty easy, all you wan to know is that the `iris.Context.ResponseWriter()` is an `http.ResponseWriter` which is an `io.Writer` as well, so you can `execute` any template that accepts an `io.Writer` parameter.

Let's take for example the `jet` you posted above, there is an example on its repository: [example/todos/main.go](https://github.com/CloudyKit/jet/blob/master/examples/todos/main.go). Take look for example at this [code block](https://github.com/CloudyKit/jet/blob/62edd43e4f88c6be452fd5feac77f716f546ebf6/examples/todos/main.go#L102-L113):

**for standard net/http**
```go
	http.HandleFunc("/todo", func(w http.ResponseWriter, r *http.Request) {
		view, err := views.GetTemplate("todos/show.jet")
		if err != nil {
			log.Println("Unexpected template err:", err.Error())
		}
		id := r.URL.Query().Get("id")
		todo, ok := todos[id]
		if !ok {
			http.Redirect(w, r, "/", http.StatusNotFound)
		}
		view.Execute(w, nil, todo)
})
```
let's convert it to **iris**, the only thing we have to change is the `view.Execute(w, nil, todo)` to -> `view.Execute(ctx.ResponseWriter(), nil, todo)`:

```go
func (iris.Context) {
		view, err := views.GetTemplate("todos/show.jet")
		if err != nil {}
		id := ctx.URLParam("id") // == ctx.Request().URL.Query().Get("id")
		todo, ok := todos[id]
		if !ok {
			ctx.Redirect("/", iris.StatusNotFound)
		}
		view.Execute(ctx.ResponseWriter(), nil, todo) // < -----
}
```

Super simple, right?

**Comment by wx85278161** [comment]
Thank you. I found that this jet template syntax works well, but some of its functions are not as useful as ctx. view. I look forward to iris having its own template. Thanks again.

**Comment by kataras** [comment]
Iris will never create its own template engine, we can't ignore the world arround us, there are ton of nice template parsers written in Go that are all compatible with `net/http` and `iris`. As an extra bonus Iris has built'n support for 6 different template engines including the standard go html, what more can someone ask?

**Comment by kataras** [comment]
Iris will never create its own template parser, we can't ignore the world arround us, there are ton of nice template parsers written in Go that are all compatible with `net/http` and `iris`. As an extra bonus Iris has built'n support for 6 different template engines including the standard go html, what more can someone ask?

**Comment by kataras** [comment]
I forgot to mention it @wx85278161, but you can `app.RegisterView` custom view engines too, and use the `ctx.View` and any other features that iris gives to built'n view engines as well. 

A custom view engine is any structure that completes the [view.Engine](https://github.com/kataras/iris/blob/6564922661686d43954b8bcf1d4f469a3d2c3fa3/view/engine.go#L24-L31) (and optionally the [view.EngineFuncer](https://github.com/kataras/iris/blob/6564922661686d43954b8bcf1d4f469a3d2c3fa3/view/funcs.go#L7-L10)).

However, I understand that, probably, you are not in the position to do it by yourself because you are afraid of mistakes, but give it a try - there is nothing better than learning something new in programming. Because I want to serve each Iris user, as much as I can physical can; I am thinking of *adding built-in support for jet template parser**. That way you will also learn how you can do it by yourself, this will give you a good taste of interfaces usecases in Go :)

**Comment by wx85278161** [comment]
Thank you very much

**Comment by kataras** [comment]
It's done @wx85278161.

The commit you may want to read, to learn how I did it is that one: https://github.com/kataras/iris/commit/82aa362f27dbe8c21cb7655cd218902008289239

You will be able to use it when I make the `v11.2.0` officialy available. Until then, you can take look at the two examples:

- https://github.com/kataras/iris/tree/v11.2.0/_examples/view/template_jet_0
- https://github.com/kataras/iris/tree/v11.2.0/_examples/view/template_jet_1_embedded

Have fun!

**Comment by wx85278161** [comment]
Thank you for your answer and effort.
