### ISSUE TITLE
Django using pongo2 but how to add the filters such as timesince, filesizeformat that implemented in the pongo2-addons

### ISSUE THREAD

**Issue by johngovr** [kataras/iris#1284]
Some filters implemented in the pongo2-addons, following the <https://github.com/flosch/pongo2-addons> I added it like this 
"_ "github.com/flosch/pongo2-addons""  into the django.go source file, and then rebuild the iris. but when I use them in the html like "LVT:{{ rig.LastQueryTime |timesince }}",  the error is printed like 
"[ERRO] 2019/06/21 11:12:27.084 view: [Error (where: parser) in listcfgs.html | Line 9 Col 66 near 'timesince'] Filter 'timesince' does not exist."

Who has similar experience, please give me some advice.

**Comment by kataras** [comment]
Hello @johngovr, the problem is that they don't work as expected, the docs of pongo2-addons says that if you import it after the main pongo2 import path then they will be registered but if you go to `kataras/iris/view/django.go` and do it by yourself you will see that they still don't work. Another bad design of that pongo2-addons is that all of its functions are **not exported** so we can't register them manually via an iris view option. The ideal is to clone that repository, make all of these filters functions exported and register them with somethng like `tmpl.UseAddons()` on the `view.Django`. I will proceed with this but will be available for use on the upcoming version, sounds great?

**Comment by kataras** [comment]
The problem is that its `pongo2.RegisterFilter` refers to same package name but because we have vendored the pongo2 itself go thinks it's another, so the actual `RegisterFilter` of the `pongo2` package that `kataras/iris/view/django.go` uses never called.

I was aware of this problem but back then we didn't have type aliases neither the go modules feature, so it was a limitation. It's already fixed on the upcoming `v11.2.0` but if you need this **fix now**, you can do it locally:  just remove your `$GOPATH/src/github.com/kataras/iris/vendor/github.com/flosch` folder.

**Comment by johngovr** [comment]
Thank you, kataras. It worked as your recommended "just remove your `$GOPATH/src/github.com/kataras/iris/vendor/github.com/flosch` folder."
Except stability in the `v11.2.0` release.
