### ISSUE TITLE
Redis sessions slow request when benmark

### ISSUE THREAD

**Issue by long25vn** [kataras/iris#1285]
Hi everyone
i used [wrk](https://github.com/wg/wrk) to benmark my app 
```
 wrk -t12 -c300 -d20s http://localhost:8080/blog/id
```
My app use:
 - redis to store sessions (run on docker)
 - database postgres ( run on docker)

But when i run benmark, Requests/sec very slow
![image](https://user-images.githubusercontent.com/31624384/59958966-ed80d180-94d8-11e9-8201-133787924cf2.png)

app log:

![image](https://user-images.githubusercontent.com/31624384/59958994-42244c80-94d9-11e9-87fd-3320c21edebd.png)

But when i change to  Badger, Requests/sec:   7000 - 8000

**Comment by kataras** [comment]
Hello, first of all, the numbers are very small, probably u have a lot job in ur handlers, would you like to share the code of this with us? or you running those from a low-end machine? Anyway, I am aware of redis sessiondb slow performance: I am writing this to the docs, recommend badger sessiondb because is faster, redis is a lot slower than badger at general, however, if you have more experience with redis and expected different results, you are free of edit the redis sessiondb and try out different redis commands because I really cant help you on this, last time I changed the HGET command and I saw no difference. Thank you.

**Comment by kataras** [comment]
I ran some benchmarks with the same flags as you did to see the difference between redis and badger on my machine as well: on redis I got `6549` requests and on badger `988430` (at 20 seconds with 300 simultaneously connections). So the results, about the difference between those two are quite the same. I will take a closer look, redis expected to be slower but not like this.

**Comment by kataras** [comment]
So far we used: https://github.com/gomodule/redigo but I wanna try to pack the features we have on sessiondb with https://github.com/mediocregopher/radix which as far as I read is faster and not as buggy as the redigo, give me some time and I will come back later with better results, we need this fix before v11.2.0.

**Comment by kataras** [comment]
OK the change has been done, redis has a `Timeout` option and a `MaxActive` connections for the pool now in-used, also fixed a bug on redis Clear() when it removed its session ID entry too which was an invalid oparation, the performance difference is still there, I can't do anything, this is redis' problem and probably advanced redis users can configure their services to overcome this problem, this has nothing to do with Iris and redis golang implementations.
