### ISSUE TITLE
ctx.Request().body only fetch once

### ISSUE THREAD

**Issue by wyanlord** [kataras/iris#1297]
I get it in middleware. And I cannot get it in handler again.

**Comment by kataras** [comment]
Hello @wyanlord, this is a net/http behavior which you can override by `app.Run(iris.Addr(...), iris.WithoutBodyConsumptionOnUnmarshal)`.

Read more at: https://github.com/kataras/iris/issues/1265

**Comment by wyanlord** [comment]
I hope I can keep it in the iris.context structure after form param parsed.
This native body is used in many places.

**Comment by wyanlord** [comment]
`// 获取iris的请求体
func RequestBody(ctx context.Context) string {
	var requestBody string
	data, err := ioutil.ReadAll(ctx.Request().Body)
	if err == nil {
		requestBody = string(data)
		ctx.Request().Body = ioutil.NopCloser(bytes.NewBuffer(data))
	}
	return requestBody
}`

`// 请求日志记录
func NewAccessLogMdw() iris.Handler {
	return func(ctx context.Context) {
		fmt.Println(helper.RequestBody(ctx))

		fmt.Println(ctx.FormValues())

		fmt.Println(helper.RequestBody(ctx))

		ctx.Next()
	}
}`

when post `http://localhost:8080/users?c=5` with `b=3`.
The result is: 
`
b=3
map[b:[3] c:[5]]
nil
`

**Comment by kataras** [comment]
So your issue here was the `ctx.FormValues`.

**Fixed** with https://github.com/kataras/iris/commit/bf3f3065645606c4b51f2382eff0c6dcd334547d on the upcoming **v11.2** release.

That was a good bug report, thank you a lot @wyanlord and sorry for the duplicate label but please next time provide me a code snippet like this from the first place so I can be more helpful
