### ISSUE TITLE
Does iris support http request timeout?

### ISSUE THREAD

**Issue by codinggg** [kataras/iris#1311]
golang native http package has timeout set method, like this:
> srv := &http.Server{  
    ReadTimeout: 5 * time.Second,
    WriteTimeout: 10 * time.Second,
}
log.Fatal(srv.ListenAndServe())

In iris, How to get alike method? I search website and project example, I don't found it.

**Comment by kataras** [comment]
Hello @codinggg. Of course Iris supports everything that `net/http` offers.

If you read the [Host Wiki page](https://github.com/kataras/iris/wiki/Host) you will see that you can actually run Iris with a net/http server instance exactly as you provided using the `iris.Server` instead of `iris.Addr`.


```go
srv := &http.Server{
ReadTimeout: 5 * time.Second,
WriteTimeout: 10 * time.Second,
}
app.Run(iris.Server(srv)) // you are done.
```

**Comment by codinggg** [comment]
Thank you. Iris is very powerful !
