### ISSUE TITLE
I had an installation problem because of the env variable.

### ISSUE THREAD

**Issue by wyg27** [kataras/iris#1347]
Iris's doc wrote: 

`$ go get github.com/kataras/iris@master`

When I tried this command, I got an error message "**cannot use path@version syntax in GOPATH mode**".

I got a solution from google is setting a env variable first:

`$ export GO111MODULE=on`

Then I ran the installation command smoothly.

Probably not everyone has this problem, but I hope the Iris's doc could mention about it.

Thanks! 😄

**Comment by kataras** [comment]
Yes this happens because you are trying to install from your $GOPATH but recent Go versions allows you to use "go modules" (such as Iris) outside of $GOPATH, on the next Go releases this message will disappear and it will be defaulted to use GO MODULES. But yes, I assume, we can add this for now on docs too.
