### ISSUE TITLE
content overriding example question

### ISSUE THREAD

**Issue by lmq1117** [kataras/iris#1390]
hi @kataras when i run _examples/routing/custom-context/method-overriding/main.go 
and visit http://localhost:8080/hi/firstname
the page didn't show the firstname 

shuld we set firstname value first? it's the code 
```
// should always print "($PATH) Handler is executing from 'MyContext'"
func recordWhichContextJustForProofOfConcept(ctx iris.Context) {
	ctx.Values().Set("firstname",ctx.Params().Get("firstname")) //add this line
	ctx.Application().Logger().Infof("(%s) Handler is executing from: '%s'", ctx.Path(), reflect.TypeOf(ctx).Elem().Name())
	ctx.Next()
}
```

**Comment by lmq1117** [comment]
func recordWhichContextJustForProofOfConcept used two times in this file and one need， the other didn't need  3q

**Comment by kataras** [comment]
Hello @lmq1117, you are right but the example was wrong in the `app.Handle("GET", "/hi/{firstname:alphabetical}")` it had `ctx.Values().Get...` instead of `ctx.Params().Get`, it's fixed with the latest commit.

https://github.com/kataras/iris/blob/146804515e6575f9d7b186282c2234daa659ad67/_examples/routing/custom-context/method-overriding/main.go#L72-L79
