### ISSUE TITLE
iris-contrib get error

### ISSUE THREAD

**Issue by CulionBEAR** [kataras/iris#1392]
I havn't got where "github.com/kataras/iris/v12" is.
but "github.com/iris-contrib/middleware/cors/cors.go" get an error:
cannot find package "github.com/kataras/iris/v12/context"

**Comment by kataras** [comment]
@CulionBEAR you have to update both `iris-contrib/middleware/XXX` and `github.com/kataras/iris/v12` in your project, in order to be compatible with each one. Minimum required go version is `1.13`. If you copy-paste the example in your desktop and run `go build or go run main.go` it will work, it fetches the dependencies automatically. See below:

![image](https://user-images.githubusercontent.com/22900943/68764099-b5faf900-0622-11ea-9777-2a892afad577.png)

**Comment by ddesign84** [comment]
Thanks Reply
