### ISSUE TITLE
[netlify] website is blocked in Russia

### ISSUE THREAD

**Issue by afansv** [kataras/iris#1394]
Please, move to another IP. You are losing russian community.

**Comment by kataras** [comment]
@afansv I didn't know it, the website is hosted at [netlify](https://www.netlify.com/). I will submit a question about it and will come back to you.

**Comment by kataras** [comment]
@afansv The issue is real for almost **every website hosted by netlify.com**, described by others at: [community.netlify.com: Netlify CDN or DNS blocked in Russia?](https://community.netlify.com/t/netlify-cdn-or-dns-blocked-in-russia/372/13). The last answer was 7days ago saying that they(netlify team members) are trying to fix it. However, there is a "solution" in the link above which I followed too.

The problem should be fixed, according to some webtests I ran (link: http://ping-admin.ru/free_test/result/1573759945n8b6kc59w3ds74l2bjkvz.html). Can you please verify it?

Thanks,

**Comment by afansv** [comment]
@kataras it's okay now. Thanks.
