### ISSUE TITLE
gin vs iris

### ISSUE THREAD

**Issue by harishanumula** [kataras/iris#1396]
I know there might be a bias when I am asking this here. But I want to understand in what cases Gin is better and in what cases iris is better. I see the github stars are increasing more for Gin than any other framework, so was wondering what would be better for the long-term.

https://star-history.t9t.io/#go-kit/kit&gin-gonic/gin&labstack/echo&gobuffalo/buffalo&micro/go-micro&kataras/iris&astaxie/beego

**Comment by kataras** [comment]
Hello @harishanumula that's a great question, you can check the issues and examples to learn more about their differences (in short: iris has everything gin provides plus a ton of other features and most complete solutions). However, I can write down some numbers about them: 

### Gin
- 240 contributors
- 6+ years old
- Routing based on httprouter, simple and no support for wildcard + dynamic param + static parameter at the same path prefix, neither support for [macros](https://github.com/kataras/iris/wiki/Routing-path-parameter-types) or [mvc](https://github.com/kataras/iris/wiki/MVC) or [handlers and dependency injection](https://github.com/kataras/iris/wiki/dependency-injection) like Iris does
- It's more like a router than a complete web framework, most of its parts depending on other third-parties and abandoned libraries which gin has no any access for modification over if a user requests something that does not exist yet
- With no user support at all. Take for example the gin issue/question/feature request: [does Gin has Internationalization support(i18n)?](https://github.com/gin-gonic/gin/issues/1382) which was posted on Jun 6, **2018 and still nothing** and a relative of Iris: [i18n -with subdirectories, like www.site.com/en](https://github.com/kataras/iris/issues/1369) posted at Oct 1, **2019 answered and completed**
- **179 open issues, most of them bug reports and feature requests or questions**

### Iris
- 65 contributors (including myself with 98% commits and issues response rate)
- 3 years old - Gin has more fans around, it's older and its contributors are advertising it on blogs, golang slack chat and reddit. **I am not part of any clique in go community and that means that Iris is fighting alone with its speed, user support and features as its only strength**.
- Routing based on muxie - faster than gin/httprouter, with a small difference but in the same time it accepts ton of features that if gin had too it would make it even slower like the gorilla's one.
- Iris is more like fast, complete web framework, supports websocket, sessions (both with native scaling capabilities), mvc, versioning, full i18n for subdomains, path prefix, url parameter or any custom method, DI, 5+ view engines and many [other features](https://github.com/kataras/iris/wiki) **that's why the last year more and more developers are turning to Iris from echo and gin**.
- Iris has a ton of [examples](https://github.com/kataras/iris/tree/master/_examples) to learn from
- Iris user support is one of the best you can find at open-source community. You can see it on your own github issue, **posted 18 minutes ago and I am writing** this message to you immediately, the majority of Gin's issues were never answered at all and others are late for months to get an answer.
- **7 open issues**, 1 question, 1 bug (fixed), 1 feature request (completed) and others are community-relative.

**Comment by kataras** [comment]
Hello @harishanumula that's a great question, you can check the issues and examples to learn more about their differences (in short: iris has everything gin provides plus a ton of other features and most complete solutions). However, I can write down some numbers about them: 

### Gin
- 240 contributors
- 6+ years old
- Routing based on httprouter, simple and no support for wildcard + dynamic param + static parameter at the same path prefix, neither support for [macros](https://github.com/kataras/iris/wiki/Routing-path-parameter-types) or [mvc](https://github.com/kataras/iris/wiki/MVC) or [handlers and dependency injection](https://github.com/kataras/iris/wiki/dependency-injection) like Iris does
- It's more like a router than a complete web framework, most of its parts are depending on other third-parties and abandoned libraries which gin developers have no access for modification over it, what happens if a user opens a request for something that does not exist yet? Nothing.
- With no user support at all. Take for example the gin issue/question/feature request: [does Gin has Internationalization support(i18n)?](https://github.com/gin-gonic/gin/issues/1382) which was posted on Jun 6, **2018 and still nothing** and a relative of Iris: [i18n -with subdirectories, like www.site.com/en](https://github.com/kataras/iris/issues/1369) posted at Oct 1, **2019 answered and completed**
- **179 open issues, most of them bug reports and feature requests or questions.**

### Iris
- 65 contributors (including myself with 98% commits and issues response rate)
- 3 years old - Gin has more fans around, it's older and its contributors are advertising it on blogs, golang slack chat and reddit. **I am not part of any clique in go community and that means that Iris is fighting alone with its speed, user support and features as its only strength**.
- Routing based on [kataras/muxie](https://github.com/kataras/muxie) - **faster than gin and httprouter**, not huge difference but if gin had the routing features that iris provides it would be a lot slower like gorilla's one
- Iris is more like fast, complete web framework, supports websocket, sessions (both with native scaling capabilities), mvc, versioning, full i18n for subdomains, path prefix, url parameter or any custom method, DI, 5+ view engines and many [other features](https://github.com/kataras/iris/wiki) **that's why the last year more and more echo and gin developers are turning their attention into Iris instead**
- Iris has more than 100+ useful [examples](https://github.com/kataras/iris/tree/master/_examples) to learn from
- Iris **user support is one of the best you can find at open-source community**. You can see it by your own github issue, **posted 18 minutes ago and I am writing** this message to you immediately, the majority of Gin's issues were never answered at all, and others waiting for months to get an answer
- **7 open issues**, 1 question, 1 bug (fixed), 1 feature request (completed) and others are community-relative.

**Comment by kataras** [comment]
Hello @harishanumula that's a great question, you can check the issues and examples to learn more about their differences (in short: iris has everything gin provides plus a ton of other features and most complete solutions). However, I can write down some numbers about them: 

### Gin
- 240 contributors
- 6+ years old
- Routing based on httprouter, simple and no support for wildcard + dynamic param + static parameter at the same path prefix, neither support for [macros](https://github.com/kataras/iris/wiki/Routing-path-parameter-types) or [mvc](https://github.com/kataras/iris/wiki/MVC) or [handlers and dependency injection](https://github.com/kataras/iris/wiki/dependency-injection) like Iris does
- It's more like a router than a complete web framework, most of its parts are depending on other third-parties and abandoned libraries which gin developers have no access for modification over it, what happens if a user opens a request for something that does not exist yet? Nothing.
- With no user support at all. Take for example the gin issue/question/feature request: [does Gin has Internationalization support(i18n)?](https://github.com/gin-gonic/gin/issues/1382) which was posted on Jun 6, **2018 and still nothing** and a relative of Iris: [i18n -with subdirectories, like www.site.com/en](https://github.com/kataras/iris/issues/1369) posted at Oct 1, **2019 answered and completed**
- **179 open issues, most of them bug reports and feature requests or questions.**

### Iris
- 65 contributors (including myself with 98% commits and issues response rate)
- 3 years old - Gin has more fans around, it's older and its contributors are advertising it on blogs, golang slack chat and reddit. **I am not part of any clique in go community and that means that Iris is fighting alone with its speed, user support and features as its only strength**.
- Routing based on [kataras/muxie](https://github.com/kataras/muxie) - **faster than gin and httprouter**, not huge difference but if gin had the routing features that iris provides it would be a lot slower like gorilla's one
- Iris is more like fast, complete web framework, supports websocket, sessions (both with native scaling capabilities), mvc, versioning, full i18n for subdomains, path prefix, url parameter or any custom method, DI, 5+ view engines and many [other features](https://github.com/kataras/iris/wiki) **that's why the last year more and more echo and gin developers are turning their attention into Iris instead**
- Iris has more than 100+ useful [examples](https://github.com/kataras/iris/tree/master/_examples) to learn from
- Iris **user support is one of the best you can find at open-source community**. You can see it by your own github issue, **posted 18 minutes ago and I am writing** this message to you immediately, the majority of Gin's issues were never answered at all, and others waiting for months to get an answer
- **7 open issues**, 1 question, 1 bug (fixed), 1 feature request (completed) and others are community-relative.


UPDATE: You can also read an older but fame enough (with more than 1.94k claps) blog post about their differences: [Top 6 web frameworks for Go as of 2017](https://blog.usejournal.com/top-6-web-frameworks-for-go-as-of-2017-23270e059c4b).

Thanks,
Gerasimos Maropoulos

**Comment by harishanumula** [comment]
Thanks so much for the prompt response, I see that you are very active in this, compared to most other repos. I am convinced to use Iris for my use-case, I hope other new golang developers will also get a good idea from your answer.

**Comment by kataras** [comment]
That's great news @harishanumula, you can [request](https://bit.ly/iris-req-book) for `pdf` and `epub` versions of the Iris E-Book too. Tell us if you need anything at all,
- [chat](https://chat.iris-go.com),
- [email](mailto:iris-go@outlook.com),
- [facebook](https://www.facebook.com/iris.framework),
- [issues](https://github.com/kataras/iris/issues/new),
- [stackoverflow](https://stackoverflow.com/questions/tagged/go-iris).
