### ISSUE TITLE
[BUG] logger can't get the result of ctx.StatusCode

### ISSUE THREAD

**Issue by wk1216123** [kataras/iris#1413]
**Describe the bug**
The logger middleware calls ctx.GetStatusCode() to get the current status code for logging, and ctx.GetStatusCode returns ctx.writer.StatusCode(), which can be different after calling ctx.StatusCode() to set a custom status.
ctx.StatusCode() calls ctx.writer.WriteHeader(statusCode) and change the status code of ctx.writer.WriteHeader, but doesn't change the status of ctx.writer.

**To Reproduce**
1. enable logger middleware
2. call ctx.StatusCode in handler function

**Expected behavior**
The logger record the actual status of http response after executing handler function

**Screenshots**
![image](https://user-images.githubusercontent.com/11704131/71540192-421e7100-2982-11ea-85c8-7db0ee08cfcb.png)

**Comment by kataras** [comment]
Hello @wk1216123,

The writer works as expected, it writes the `writer.statusCode` (which returned by `.StatusCode()`) on `writer.WriteHeader`. The status code of the response is not changed directly, it sets **only right before the response fire** in order to avoid direct multiple write header calls. I am not in my office atm, will check the logger middleware when I'll be back, until then you can check out its source code at: https://github.com/kataras/iris/tree/master/middleware/logger. One more thing, could you please post the code snippet you are using to reproducible this output?

Thanks,
Gerasimos Maropoulos.

**Comment by kataras** [comment]
Seems like there is no such issue, I will let it open until your response, maybe an example will help to find out what's wrong in your code or inside Iris. Screenshot: 

![1413](https://user-images.githubusercontent.com/22900943/71544405-bf001980-2987-11ea-920d-2f1b616716db.png)

**Comment by wk1216123** [comment]
Dear Kataras,

I 'm sorry to bother you, it 's all my fault to cause the problem.
The problem is caused because I use iris.MVC in a wrong way. I defined a response struct and use it as return value, and in order to have the same response struct when error occured, I just slack off and handle the error in the following way, which caused the logging problem...
``` (go)
func (c *MyController) GetBy(id int64) *MyResponse {
    ...
    // when error occured
    c.Ctx.StatusCode(iris.StatusBadRequest)
    c.Ctx.JSON(&MyResponse{errorInfo:"sth"})
    return nil
    ...
}
```
I will try to define some custom error handlers later...
Thank you very much for your kindly reply, and I'm sorry for any inconvenience I've brought to you

Carl

**Comment by kataras** [comment]
No worries @wk1216123 have a nice one!
