### ISSUE TITLE
[FEATURE REQUEST] WrapRouter for iris.Party

### ISSUE THREAD

**Issue by Dexus** [kataras/iris#1435]
**Is your feature request related to a problem? Please describe.**
I would like to add a special wrapper to some routes. But not all of them. Therefore I would like the possibility to use the WrapRouter also for iris.Party.

**Describe the solution you'd like**
When I add a WrapRouter to an iris.Party, I want this wrapper to run. Example: https://github.com/kataras/iris/wiki/HTTP-method-override

**Describe alternatives you've considered**
The alternative would be to set different routes via iris.party, which you can optionally set the method override option.

**Additional context**
https://github.com/kataras/iris/wiki/HTTP-method-override but for iris.Party or via *router.Route settings

**Comment by kataras** [comment]
Hello @Dexus,

The `WrapRouter` it's called before the router itself, a group of routes based on **path prefix or subdomain** (iris.Party) are selected after that, in the trie-based search and match router state. The initial idea of `WrapRouter` cannot be implemented inside iris.Party without performance cost which, in reality does not worth here because it can be done with existing features already.

Here is an alternative for a case like yours.  Take for example that you want only the `/path1/...` to use the method override wrapper. Call the method override wrapper  only on that path prefix by setting a custom `router wrapper func` which will call the method override wrapper whenever is required.

```go
package main

import (
    "net/http"
    "strings"

    "github.com/kataras/iris/v12"
    "github.com/kataras/iris/v12/middleware/methodoverride"
)

func main() {
    app := iris.New() 

    mo := methodoverride.New() 
    app.WrapRouter(func(w http.ResponseWriter, r *http.Request, router http.HandlerFunc) {
        if strings.HasPrefix(r.URL.Path, "/path1") {
               mo(w, r, router)
               return
       }

       router(w, r)
    })

    app.Post("/path1", func(ctx iris.Context) {
        ctx.WriteString("post response")
    })

    app.Delete("/path1", func(ctx iris.Context) {
        ctx.WriteString("delete response")
    })

    // [...app.Run]
}
```

**Comment by Dexus** [comment]
Thank you. I will look, how we can doit.
