### ISSUE TITLE
[BUG] jet.View - urlpath error (also maybe update dep)

### ISSUE THREAD

**Issue by Dexus** [kataras/iris#1438]
**Describe the bug**

[HTTP Server] http: panic serving [::1]:35074: interface conversion: interface {} is func(jet.Arguments) reflect.Value, not jet.Func

**To Reproduce**

iris: v12.1.5
make jet.View and use "urlpath" like `{{urlpath("pathname")}}` Example (https://github.com/kataras/iris/blob/master/_examples/routing/reverse/main.go)

if i use something like
```

	rv := router.NewRoutePathReverser(app)

	tmpl.AddFunc("urlpath2", func(a view.JetArguments) reflect.Value {
		a.RequireNumOfArguments("urlpath2", 1, -1)
		var mapper []interface{}
		var i int
		for i = 1; i < a.NumOfArguments(); i++ {
			mapper = append(mapper, a.Get(i).String())
		}

		myrouteRequestPath := rv.Path(a.Get(0).String(), mapper...)
		return reflect.ValueOf(myrouteRequestPath)
	})
```
it works more or less with `{{ urlpath2("countriesDelete","1","2345") }}` but it don't work with uint/int etc currently.

**Expected behavior**

return the correct urlpath for the route

additional:
maybe an example with routes with placeholders like `/path/to/:id` to set the named placeholders

also a new v3 of jet is available.

**Comment by kataras** [comment]
Hello @Dexus,

You don't need to add your own url path function, the issue was just a wrapper around `jet.Func`. I also updated jet to the latest v3.0.0 which fixes some issues it had in the past (although, Iris had fixes about those by its side, those JetRanger "hacks" are removed from our code base as well).

Update to `v12.1.6`: `go get -u github.com/kataras/iris/v12@v12.1.6`


Thanks for the report!

**Comment by kataras** [comment]
Hello @Dexus,

You don't need to add your own url path function, the issue was just a wrapper around `jet.Func`. 

> Note that the /path/to/{id:int} -> `ctx.Params().GetIntDefault("id", 0)` works but you have to pass it as string argument in the `{{urlpath("my-route", "42")}} `

I also updated jet to the latest v3.0.0 which fixes some issues it had in the past (although, Iris had fixes about those by its side, those JetRanger "hacks" are removed from our code base as well).

Update to `v12.1.6`: `go get -u github.com/kataras/iris/v12@v12.1.6`


Thanks for the report!
