### ISSUE TITLE
How to register all function of a struct to function of template view?

### ISSUE THREAD

**Issue by minhvh93** [kataras/iris#1443]
**Is your feature request related to a problem? Please describe.**
Create a new function for template view from all function of struct

**Describe the solution you'd like**
- My example code something like that:
```
func main() {
        ......
	tmpl := iris.Jet("./app/views", ".jet") // <--
	tmpl.Reload(true)
	fns := reflect.TypeOf(ViewBuiler{})
	for i := 0; i < fns.NumMethod(); i++ {
	      method := fns.Method(i)
               tmpl.AddFunc(strings.ToLower(method.Name), method )
	 }
	b.RegisterView(tmpl)
}

type ViewBuiler struct {
}

func (ViewBuiler) Asset(a view.JetArguments) reflect.Value {
	path := a.Get(0).String()
	fmt.Println(os.Getenv("APP_URL"))
	return reflect.ValueOf(path)
}

func (ViewBuiler) Style(a view.JetArguments) reflect.Value {
	path := a.Get(0).String()
	s := fmt.Sprintf(`<link href="%v" rel="stylesheet"> `, path)
	return reflect.ValueOf(s)
}

func (ViewBuiler) Script(a view.JetArguments) reflect.Value {
	path := a.Get(0).String()
	s := fmt.Sprintf(`<script src="%v" ></script>`, path)
	return reflect.ValueOf(s)
}
```
**Describe alternatives you've considered**
- Something wrong at this code:
```tmpl.AddFunc(strings.ToLower(method.Name), method )```

**Additional context**
Please help me resolve it.
Thank you

**Comment by kataras** [comment]
Hello @minhvh93,

I am asleep but give me some minutes to see how we can do that.

**Comment by kataras** [comment]
I don't know why you want to use something like that, but it's better not to implement a feature like this builtin Iris because question: "request scope or singleton the fields of the 'ViewBuilder' structure"? We already have MVC at `kataras/iris/v12/mvc` which does care of it because it has a meaning, for static template functions  this has not any positive situation I can think of. And if not static, then dynamically add them on each request - it can be done for Jet engine but not for all engines such as handlebars, there are many "if s" and "why s" for a feature request like this, does not worth the ugly code that will produce on our codebase, if you need it you are ready to go, you have the solution above.

**Comment by minhvh93** [comment]
It working. Thank you so much @kataras

**Comment by kataras** [comment]
You are welcome @minhvh93!
