### ISSUE TITLE
[BUG] : HTTP method helper "Any" functionality has changed in the latest version.

### ISSUE THREAD

**Issue by BharathB23** [kataras/iris#1448]
Greetings!!!

I was making use of http method helpers Get and Any to restrict actions to read-only. And the Get helper had a handler associated to fetch the requested resource and Any to restrict any other HTTP methods.

Below is the code snippet used for the above scenario.
router := iris.New()
action := router.Party("/")
action.Get("/", listAll)
action.Any("/", sendError)

In v11.1.1, the behavior was as expected, but in v12.1.6, Any method is given precedence or handler defined for Get is being overwritten with that of Any, and for all operations on "/" path, am observing sendError handler being invoked.

Please let me know, if the behavior has been modified or my understanding is not inline with the usage.
And could the scenario described above be achieved in any other way, other than defining sendError handler for all HTTP methods except for GET.

**Comment by kataras** [comment]
Hello @BharathB23 this is an expected behavior, iris v11.1.x had a bug which new routes didn't override the old ones (it's not a common thing to write same route again and again though), which was fixed at the upcoming releases months ago.

So, you want to register route on all methods except the registered ones. We can introduce a new method for that purpose or add a configurable section like we have for [Party#SetExecutionRules](https://github.com/kataras/iris/blob/040e453cdd0b16398a63f3b929066d206f217550/_examples/mvc/middleware/without-ctx-next/main.go#L42) to override the default behavior of `app.Any`.

Do you have some suggestions that suit your needs?

**Comment by kataras** [comment]
Hello @BharathB23 this is an expected behavior, iris v11.1.x had a bug which new routes didn't override the old ones (it's not a common thing to write same route again and again though), which was fixed at the upcoming releases months ago.

So, you want to register route on all methods except the registered ones. We can introduce a new method for that purpose or add a configurable section like we have for [Party#SetExecutionRules](https://github.com/kataras/iris/blob/040e453cdd0b16398a63f3b929066d206f217550/_examples/mvc/middleware/without-ctx-next/main.go#L42) to override the default behavior of `app.Any`, e.g

```go
// RegisterRule is a type of uint8.
// Defines the register rule for new routes that already exists.
// Available values are: Override, Skip and Error.
//
// See `Party#SetRegisterRule`.
type RegisterRule uint8

const (
	// Override an existing route with the new one, the default rule.
	Override RegisterRule = iota
	// Skip registering a new route twice.
	Skip
	// Error log when a route already exists, shown after the `Build` state,
        // server never starts.
	Error
)

// SetRegisterRule sets a `RegisterRule` for this Party and its children.
// Available values are: Override (the default one), Skip and Error.
func (api *APIBuilder) SetRegisterRule(rule RegisterRule) Party {
	api.routeRegisterRule = rule
	return api
}
```

Do you have some suggestions that suit your needs? 

**UPDATE:**

It's almost ready, have to add some tests, I have to go for a meeting, if you (or anybody) reply with alternative until I come back we will discuss it further, otherwise the above API will be pushed today as v12.1.7 sounds fair?


Thanks and welcome to Iris,
Gerasimos Maropoulos

**Comment by kataras** [comment]
It's done @BharathB23,

You just have to upgrade to `v12.1.7`. Add: `app.SetRegisterRule(iris.RouteSkip)` and the previous behavior you are used to will be enabled.

Thanks,
Gerasimos Maropoulos

**Comment by BharathB23** [comment]
Thank you so much @kataras, for such a fast resolution.
Solution is apt for my use case and with the new method, expected behavior is observed.

**Comment by kataras** [comment]
Hi @BharathB23,

You are welcome! I always do things a bit faster than in other repositories in github, otherwise we couldn't hold this framewowrk vs the internet trolls...

Thank you for opening this issue, it was a good touch to the core code.

**Comment by BharathB23** [comment]
Hi @kataras ,

Yes, received the E-book, Thank you for sharing!!
