### ISSUE TITLE
Some error for Iris's Wiki docs

### ISSUE THREAD

**Issue by snowlyg** [kataras/iris#1451]
@kataras 
I translate iris's wiki docs to chinese ,which is help for learn iris ,but english is not well.

So,i found some error in iris,s wiki docs. 

Example:  Host - Any iris.Runner
![image](https://user-images.githubusercontent.com/45998760/74748191-13968580-52a3-11ea-936c-324d6294d1e0.png)

When , i use iris with qor admin like above example. It's not work.

![image](https://user-images.githubusercontent.com/45998760/74748714-ef877400-52a3-11ea-9d18-8942708babba.png)

This code is work well,when i change a little.

![image](https://user-images.githubusercontent.com/45998760/74748565-adf6c900-52a3-11ea-918e-38bc11b67ac3.png)

Of course ,i found other errors in wiki docs .  Your can found them on  [here](https://learnku.com/docs/iris-wiki/v12) - Iris wiki 中文文档。

I don't sure that errors all of them are right.

Forgive me for my bad english also.

**Comment by kataras** [comment]
Hello @snowlyg, 

First of all thanks for the effort on translating the wikis for Chinese (which can be converted to an e-book of PDF and EPUB and gitbook as well, I will do that for you).

About the error, yes that is error-ed there because of the &address{..}.$call. 

At general, you can **clone/fork the wiki** and put some fixes `in-time`, no need to open new issues for all of that you will find. Or if you don't want to have a second english-version of wiki fork then just add comments in this issue you opened until we fix all of them.

I saw the wikis, it's on external site and good for you but could you please share the wiki repo with me so I can add a sub domain like `zh-CH.docs.iris-go.com` pointing to a gitbook like the `docs.iris-go.com`?.

Thanks,
Gerasimos Maropoulos. Your english is fine, just as mines :)

**Comment by tingkai-zhang** [comment]
Hi @snowlyg , thanks for bringing this up.

I can read and write in Chinese and English. I like the simplicity and powerful features that iris brings. I'd love to help cooridination between you and @kataras to address the errors.

Welcome to join: https://gitter.im/iris_go/community 
and send a PM to me if you have any question.

**Comment by snowlyg** [comment]
@kataras Haha, wiki can clone/fork too ? I don't know this. It's my mistake. I will do this , when i found the new's question.

**Comment by snowlyg** [comment]
@tingkai-zhang Thank you ,  Do you have any other contact information?  For example, QQ or WeChat.

**Comment by tingkai-zhang** [comment]
> @tingkai-zhang Thank you , Do you have any other contact information? For example, QQ or WeChat.

Sent you a dm on gitter

**Comment by tingkai-zhang** [comment]
> @kataras Haha, wiki can clone/fork too ? I don't know this. It's my mistake. I will do this , when i found the new's question.
> 
> [Iris's wiki for chinese](https://github.com/snowlyg/iris/wiki)

Thanks. I think thats what kataras needs, as a wiki repo.

**Comment by kataras** [comment]
Thanks @tingkai-zhang!! Yes @snowlyg here is how you can clone it:

![image](https://user-images.githubusercontent.com/22900943/74842223-b5b17e80-5332-11ea-9d3c-9a106dea42cd.png)

```sh
$ git clone https://github.com/kataras/iris.wiki.git
$ cd iris.wiki
$ code .
```

**Comment by snowlyg** [comment]
@kataras Yes , i get other errors too. But i don't think that is importent.  All or them are come from the commet. example:

Routing context methods
![image](https://user-images.githubusercontent.com/45998760/74846604-b31f4b00-536b-11ea-8789-a3e5a1fef54c.png)

Of course , this commets are't effect to read the wikis.  My wikis is finished yet. But I not sure all of the wiki's content are correct.

**Comment by kataras** [comment]
OK this is fixed too. I will convert the Chinese wikis and give you the PDF and EPUB format to tell me if renders OK, could you please send me your e-mail at: iris-go@outlook.com? And also tell me if you want to add a donation button for your work under the e-mail template we send on request-iris-book.
