### ISSUE TITLE
 A code obsessive-compulsive disorder suggestion

### ISSUE THREAD

**Issue by 357711589** [kataras/iris#1494]
When I use Goland to write iris code

![image](https://user-images.githubusercontent.com/34570968/80347247-a3a60c00-889e-11ea-9f9e-da39e9abf8aa.png)

Write according to the sample code, there will be "uncaught error" warning, very annoying
```golang
        app := iris.New()

	app.Get("/", func(context iris.Context) {
		_, _ = context.JSON(iris.Map{"hallo": "world"})
		return
	})

```
It's very ugly to write like this

Is there any good way to solve this problem？

![image](https://user-images.githubusercontent.com/34570968/80347750-4eb6c580-889f-11ea-89b2-d1b0ecda7106.png)
Gin is very beautiful and In line with code habits。

**Comment by kataras** [comment]
@357711589 gin does not return any error from a **Write** to a client operation, that's **mistake**. Iris does return error because you may want to handle it by your own **that's idiomatic go**. In order to solve your IDE's issues, you must find the configuration/settings and disable it for `ctx.JSON` calls, I am not using Goglang so I don't know where is the setting, please open a ticket on the Gogland team and they will give you an answer, I am sure they have a solution for that.

**Comment by 357711589** [comment]
ok , thanks

**Comment by kataras** [comment]
@357711589 Open a ticket to Gogland team and map this issue. This can't change because write-to-a-client operations in Iris always return error and possible the length-written, we have more features that need to check those output values too.
