### ISSUE TITLE
problems that using module on iris-project caused

### ISSUE THREAD

**Issue by Niclausse** [kataras/iris#1499]
go module download the dependency according to the code tag, but the latest tag v12 is behind the master code.   This difference caused bugs when I swiched gopath-project to module-project. Why not  
Synchronize the tag codes?

**Comment by kataras** [comment]
Hello @Niclausse, I don't understand. You do `go get github.com/kataras/iris/v12@v12.1.8` and it conflicts because master(development) branch is ahead from `v12`? That version should be fetched from the release tag itself: https://github.com/kataras/iris/releases/tag/v12.1.8.

Give me 2 minutes, will try it on a clean system.

**Comment by kataras** [comment]
@Niclausse, the installation works fine.

```go
import "github.com/kataras/iris/v12"
```

1. empty `go.mod` with your project's name and  `go build`
```
module myproject

go 1.14
```
2. import Iris in your go.mod manually
```
module myproject

go 1.14

require (
	github.com/kataras/iris/v12 v12.1.8
)
```
3.  empty `go.mod` and `go get github.com/kataras/iris/v12@v12.1.8` from your working directory.

Please follow the [installation section](https://github.com/kataras/iris/wiki/Installation).

Post below the error message you've got so I can be more helpful to you.

Thanks,
Gerasimos Maropoulos. Author

**Comment by Niclausse** [comment]
hello @kataras I want to express that the newest tag' code is different from the master. You can see files under 'github.com/kataras/iris/mvc'.  And these differnces caused errors when I init my project to a module one.

**Comment by kataras** [comment]
No, that's what I am telling you. The latest release and the master branch do not contain such breaking changes. Let me explain your issue.

You started using Iris without reading its Installation section and also you didnt know about go modules. I bet that you use the github.com/kataras/iris import path instead the correct one github.com/kataras/iris/v12 (am I right?).

Because you used an import that was not compatible with go modules, your system downloaded the latest version which used that import path (the one without the v12 suffix) and that is the iris version 11.1 in your case. That's why you see changes, you probably used iris v11.1 thinking that you used the master or latest tagged version.


Again, can we see the logs of the error so I can confirm my theory? I though you open the issue to help you or to fix something, however until now we see zero logs or error messages in your issue body, why is that @Niclausse ?

Kindly,
Gerasimos Maropoulos
