### ISSUE TITLE
Missing Attribution / Incompatible License

### ISSUE THREAD

**Issue by julienschmidt** [kataras/iris#15]
The Attribution of HttpRouter, on which iris is obviously based, is missing completely. You may NOT remove the copyright headers. Please actually read [HttpRouter's license](https://github.com/julienschmidt/httprouter/blob/master/LICENSE).

Also MIT License is incompatible with the original BSD 3-clause license and may not be used. See also https://github.com/rs/xmux/issues/2

**Comment by kataras** [comment]
Ok @julienschmidt  I added your router recently I had used my own before, I am not planing to keep it that way I am thinking to introduce more cache to the router system, If I don't success my try and keep httprouter's modifiied code I will add the license (I tell everywhere that is urs but you are right I had to write it to the file also, I am sorry I didn't read the license I assumed that it was mit )

**Comment by julienschmidt** [comment]
In detail the following files violate my copyrights:
* [benchmark_github_test.go](https://github.com/kataras/iris/blob/10835ae080c45a4d41d1737515b3d1d04182abec/benchmark_github_test.go), from [julienschmidt/go-http-routing-benchmark](https://github.com/julienschmidt/go-http-routing-benchmark/tree/bcf0ab11745ff1924a6aedcf7a9066a884fa8df9) {routers.go, routers_test.go, bench_test.go, github_test.go)
* [node.go](https://github.com/kataras/iris/blob/2f61d08afc4fb13f2e3cd36bc35772111650eccd/node.go), from [julienschmidt/httprouter/tree.go](https://github.com/julienschmidt/httprouter/blob/b74da820a2aa53314008e35ee79631ddba491aa0/tree.go)
* [README.md](https://github.com/kataras/iris/blob/21beb5a863eb36f084c181c8da45901222345a06/README.md), from [julienschmidt/httprouter/README.md](https://github.com/julienschmidt/httprouter/blob/b74da820a2aa53314008e35ee79631ddba491aa0/README.md)

I ask you to attribute the origin  and re-add the copyright headers to benchmark_github_test.go and node.go (see [julienschmidt/httprouter/LICENSE](https://github.com/julienschmidt/httprouter/blob/master/LICENSE)) and and a)  note the different license of those files in your README.md, or b) Re-license the whole project. 
Alternatively you may purge any used code from this repository, including the git history.
(Otherwise I have every right to explore my legal options which include a DMCA takedown)

**Comment by kataras** [comment]
@julienschmidt  are you blind? //
// THIS TYPE OF BENCHMARKING WAS TAKEN BY https://github.com/julienschmidt/go-http-routing-benchmark
// I THINK THIS IS THE STANDAR WAY TO BENCHMARK ROUTERS AND WEB FRAMEWORKS,
// BECAUSE THIS I AM USING EXACTLY THE SAME ARCHITECTURE IN ORDER TO IRIS BE COMPARED TO OTHER FRAMEWORKS AND ROUTERS TOO.
// you dont see it ?

**Comment by kataras** [comment]
I just woke up, what are all these you are writing to me?

**Comment by julienschmidt** [comment]
My eye vision is alright

**Comment by kataras** [comment]
License added for files needed it, thanks for your notice

**Comment by kataras** [comment]
@julienschmidt Please I need an answer here when you come back, 

Hello
Actions

Gerasimos Maropoulos
6:58 PM
To: Julien Schmidt
kataras2006@hotmail.com
(2) https://github.com/kataras/iris/issues/230 I changed its title to add licenses for all third-party libraries and I added a comment also, please answer to the previous mail, I have to know otherwise I will do as I understand from your last message and I'm not sure if I understand it well, I have to add all third-party licenses on  the main iris LICENSE and on the source file that I use them also? on the header or at the code part? and also I dont understand the incompatible with GPL .. it is not your job to help me but it will be nice to know what I'm doing in order to do it right without any future worries, thanks you!!

(1, previous) Ok, look I dont want to do anything that will worry you or other person again without my itention, can you just make a pull request to do all the copyright things here:
https://github.com/kataras/iris/tree/dev ?


Note: You should see that https://github.com/kataras/iris/commit/c26668a4890fc101d691ac076ef1afcbeb5867d4#diff-b1565a35e89e517238cd86b848ec4bceR1 to understand that I wasn't lie you, I just forgot to add it on rc.3 and when the user remind me I added to THIRDPARTY with other because I though this way was the right way to do it, I close his issue because he didn't read the README for no other reason.

**Comment by kataras** [comment]
Done https://github.com/kataras/iris/commit/cd71b945b733be6638b963cb81344b56bdfc14c9, hope now I can continue develop the code I 'm boring of these things  I have no idea how it works, hopefuly now we are ok!! thanks for all!!

**Comment by kataras** [comment]
Done https://github.com/kataras/iris/commit/cd71b945b733be6638b963cb81344b56bdfc14c9, https://github.com/kataras/iris/commit/57ba8e89b5c48537683f66bf24fdf820dc99919f  hope now I can continue develop the code I 'm boring of these things  I have no idea how it works, hopefuly now we are ok!! thanks for all!!

**Comment by kataras** [comment]
Done https://github.com/kataras/iris/commit/cd71b945b733be6638b963cb81344b56bdfc14c9, https://github.com/kataras/iris/commit/57ba8e89b5c48537683f66bf24fdf820dc99919f. Hopefuly now we are ok in order continue develop the project as I used to. Thanks for all!!
