### ISSUE TITLE
[Question] How to serve iris route together with http handler

### ISSUE THREAD

**Issue by WLun001** [kataras/iris#1509]
The example below modified from [docs](https://docs.iris-go.com/iris/host)
```go

handler := http.NewServeMux()
handler.Handle("/health", healthCheck)

app.Get("/health2", func(c iris.Context) {
		_, _ = c.JSON(iris.Map{
			"message": "pong",
		})
	})

app.Run(iris.Server(&http.Server{Addr:":8080", Handler: handler}))
```

It only serve http handler `health`, `health2` from iris routes hit `NotFound`

**Comment by kataras** [comment]
Hello @WLun001, this is not the way to go.

The `Handler: handler` in your example is getting overridden by the Iris' handler itself.

You are trying to use two main handlers/routers on the same server instance, this is not possible without wrapping (`app.WrapRouter`). In your usecase there is no need to even wrap the main router. You can register your healthCheck http.Handler with: `app.Get("/health", iris.FromStd(healthCheck))`.

You can `app.Build` the Iris application which will make `app` a ready-to-use `http.Handler`  which you can register on any number of `http.Server` instances [example](https://github.com/kataras/iris/blob/v12/_examples/http-listening/custom-httpserver/multi/main.go).

**Comment by kataras** [comment]
Hello @WLun001, this is not the way to go. Let me explain a bit.

The `Handler: handler` in your example is getting overridden by the Iris' handler itself because there is no other servers registered to the Iris application to handle Iris requests (see `NewHost` below).

You are trying to use two main handlers/routers on the same server instance, this is not possible without wrapping (`app.WrapRouter`). In your usecase there is no need to even wrap the main router. You can register your healthCheck http.Handler with: `app.Get("/health", iris.FromStd(healthCheck))`.

- If you want to "attach" a new server (which its Handler not touched by Iris) you can use the [app.NewHost](https://github.com/kataras/iris/blob/b6ac39480bc98eab1d7f9dbe8ecb53be9851e848/iris.go#L584) before `app.Run/Listen`.

- Alternatively, if you want to use Iris as a common `http.Handler`, you can `app.Build` the Iris application which will make `app` a ready-to-use `http.Handler`  which you can register on any number of `http.Server` instances [example](https://github.com/kataras/iris/blob/v12/_examples/http-listening/custom-httpserver/multi/main.go).

- If you want to serve two servers in the same PORT, you can follow this example: [examples/http-listening/custom-listener/unix-reuseport](https://github.com/kataras/iris/blob/v12/_examples/http-listening/custom-listener/unix-reuseport/main.go).

Thanks,
Gerasimos Maropoulos

**Comment by WLun001** [comment]
Hi @kataras, 

Thanks for your details explanation. It is very helpful for half beginner like me (Not new to Go but a lot of things still don't understand).  


I tried `app.NewHost` and `iris.FromStd` approach, it does not work. Only `app.WrapRouter` works, adopt from [here](https://docs.iris-go.com/iris/routing/routing-wrap-the-router). 


```go
app.WrapRouter(func(w http.ResponseWriter, r *http.Request, router http.HandlerFunc) {
   path := r.URL.Path

   if strings.HasPrefix(path, "/static") {
      // acquire and release a context in order to use it to execute
     // our custom handler
    // remember: we use net/http.Handler because here
    // we are in the "low-level", before the router itself.
   ctx := app.ContextPool.Acquire(w, r)
	http.StripPrefix("/static/", fromStatik()).ServeHTTP(w, r)
	app.ContextPool.Release(ctx)
	return
  }

   if strings.HasPrefix(path, "/api") {
	ctx := app.ContextPool.Acquire(w, r)
       // mux is a new ServeMux whose internal mapping is empty, from grpc-gateway
       mux.ServeHTTP(w, r)
       app.ContextPool.Release(ctx)
      return
   }

// else continue serving routes as usual.
router.ServeHTTP(w, r)
})

app.Listen(":8081")
```

**Comment by kataras** [comment]
Hi @WLun001, yes with WrapRouter you can wrap anything but why `iris.FromStd` does not work? Let me do something for you, do you have a repository or something? I can literally convert your whole app from net/http to Iris in 1 day

**Comment by WLun001** [comment]
@kataras , how to enable CORS for `WrapRouter`?
The following code won't work


```go

	"github.com/rs/cors"
        // some code
	c := cors.New(cors.Options{
		AllowedOrigins: []string{"*"},
	})
	handler := c.Handler(mux)

app.WrapRouter(func(w http.ResponseWriter, r *http.Request, router http.HandlerFunc) {
		path := r.URL.Path

		if strings.HasPrefix(path, "/mobile") {
			handler.ServeHTTP(w, r)
			return
		}

		// else continue serving routes as usual.
		router.ServeHTTP(w, r)
	})


```

**Comment by kataras** [comment]
https://github.com/kataras/iris/blob/3c526c00676ef526b0be539651910f9b27d51e09/_examples/auth/cors/main.go#L23-L41

```go
"github.com/rs/cors"
       // some code
c := cors.New(cors.Options{
	AllowedOrigins: []string{"*"},
})

app.WrapRouter(func(w http.ResponseWriter, r *http.Request, router http.HandlerFunc) {
		if strings.HasPrefix(r.URL.Path, "/mobile") {
			c.ServeHTTP(w, r)
			return
		}

		// else continue serving routes as usual.
		router.ServeHTTP(w, r)
})
```
