### ISSUE TITLE
getting superfluous response.WriteHeader call on WrapRouter

### ISSUE THREAD

**Issue by WLun001** [kataras/iris#1525]
**Describe the bug**
response.WriteHeader call
```shell
[HTTP Server] http: superfluous response.WriteHeader call from github.com/kataras/iris/v12/context.(*responseWriter).tryWriteHeader (response_writer.go:199)
```

**To Reproduce**
```go
	app.WrapRouter(func(w http.ResponseWriter, r *http.Request, router http.HandlerFunc) {
		path := r.URL.Path

		if strings.HasPrefix(path, "/swagger") {
			// acquire and release a context in order to use it to execute
			// our custom handler
			// remember: we use net/http.Handler because here
			// we are in the "low-level", before the router itself.
			ctx := app.ContextPool.Acquire(w, r)
			handler.ServeHTTP(w, r)
			app.ContextPool.Release(ctx)
			return
		}


		// else continue serving routes as usual.
		router.ServeHTTP(w, r)
	})
```

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.4, go version go1.14 darwin/amd64, github.com/kataras/iris/v12 v12.1.8

**Comment by kataras** [comment]
Hello @WLun001, first of all the code is wrong, why you want to acquire a `ctx` when you never use it? 
```go
if strings.HasPrefix(path, "/swagger") {
	ctx := app.ContextPool.Acquire(w, r) // this is 
	handler.ServeHTTP(w, r)
	app.ContextPool.Release(ctx) // wrong
        return // because you never use the "ctx"
}
```

Do that instead:

```go
if strings.HasPrefix(path, "/swagger") {
    handler.ServeHTTP(w, r)
    return
}
```

However, let me give you more information about that error message:

This is not a bug, it's an expected behavior from net/http when you call `net/http/ResponseWriter#WriteHeader **directly** more than once. 

Iris has the `Context.StatusCode(code int)` which just sets the status code once at the end of the request, you should use that method.

You/the library probably call `w.WriteHeader` directly more than once somewhere in the code, e.g. if swagger set a status code, and iris does in the end then this is a "superfluous response.WriteHeader call". You should use the iris-designed swagger, take a look at the: https://github.com/iris-contrib/swagger/tree/master/example/basic.


Thanks,
Gerasimos Maropoulos

**Comment by WLun001** [comment]
@kataras, understood. The example i was taken from the docs, https://docs.iris-go.com/iris/routing/routing-wrap-the-router. 

Thanks.

**Comment by kataras** [comment]
You are welcome @WLun001, the example is using the ` myOtherHandler(ctx iris.Context)` which is an Iris handler, not an http.Handler, that's why it requires the Context Pool.Acquire/Release. [example code](https://github.com/kataras/iris/blob/master/_examples/routing/custom-wrapper/main.go).
