### ISSUE TITLE
[Feature Request] Optional configuration file

### ISSUE THREAD

**Issue by vadimyer** [kataras/iris#154]
Hello,

I've found a problem (as described in gitbook):
```
irisConfig := config.Iris { Profile: true, PathCorrection: false }
api := iris.New(irisConfig)
```

This shouldn't work as we've found out for at least Banner field, since the fields in this example are bool too. Because merging the default & custom configs doesn't work because mergo doesn't support it. And the solution @kataras proposed is to either user uint8 (-1 for false, 1 for true) or configuration files to stick with more generic way of configuration, because to change those bool values the only way now seems to do:
```
iris.Config().property = value
```

If anyone has better ideas, feel free to post them.

**Comment by kataras** [comment]
@vadimyer  I'm trying to make the configs load from file, but the problem is the iris' configuration has configs that are objects and functions... so this config-by-file it can be work only for strings, dates/time, int,booleans. It was good idea but cannot exists on the iris, so I decided to make the defaults to true to defaults to false, we have the problem only on two fields: `Log`and the `Banner`so we should rename them to `DisableLog = false `, `DisableBanner = false`so you can change them to true and be valid to merge them with the defaults configs, how is that sounds to you?

**Comment by xpbliss** [comment]
It is better for configure file.
https://github.com/goaltools/iniflag

**Comment by kataras** [comment]
I already took look all of these, but these cannot solve the problem I described.

The configs which are defaulted to true, they just renamed to `Disable+$oldName = false`
