### ISSUE TITLE
i want to use session_id in a different way than cookies. HTTP header?

### ISSUE THREAD

**Issue by telanflow** [kataras/iris#1543]
How do I take session_id from the HTTP header ?
or
session_id from the HTTP url ?

**Comment by telanflow** [comment]
Sorry, I don't speak English very well. Ha, ha, ha

**Comment by kataras** [comment]
Hello @telanflow,

Sessions should be used with cookies, because cookies have options like expiration, server-only, domain and other security options by protocol that headers do not.

However, you can extract a session id from a header through the `Config.SessionIDGenerator func(ctx context.Context) string`  e.g:

```go
	sess := sessions.New(sessions.Config{
		Cookie: "_session_id",
		Expires: time.Hour * 2,
		AllowReclaim: true,
		SessionIDGenerator: func(ctx iris.Context) string {
			id:= ctx.GetHeader("X-Session-Id")
			if id == "" {
				id = // [generate ID here and set the header]
				ctx.Header("X-Session-Id", id)
			}

			return id
		},
	})
```

Both header and cookie will have the same session id, you cannot avoid cookies in sessions manager.

**Comment by telanflow** [comment]
@kataras Okay thank you.

**Comment by kataras** [comment]
You are welcome!
