### ISSUE TITLE
[BUG] {app|customeRoute}.OnAnyErrorCode vs mvc.Response{Err}

### ISSUE THREAD

**Issue by Dexus** [kataras/iris#1557]
Hi Gerasimos @kataras ,

i find the behaviour of `mvc.Response` with the error not appropriate or consistent with the previously set `OnAnyErrorCode`.

There is a plain text error output that I would rather use as a message in an HTML page or JSON Object I previously provided with `OnAnyErrorCode`.

What did you think?

Regards, Josef

EDIT: as always it `master`

**Comment by kataras** [comment]
@Dexus, yes that's because the `hero.DefaultErrorHandler.HandleError` is fired on `Response.Err != nil` and overrides the API's error handlers. You could override the `DefaultErrorHander` to something like: `ctx.Application().FireErrorCode(status)`. 

I will change that behavior because the `hero/mvc.Response` and `hero/mvc.View` structures are the only ones that fires that error handler directly (with no chance to change it like you can do for handler's return values and controllers's errors).

I am also thinking to add a context value of that `Err` value so you don't lose its value.

Stay tuned.

**Comment by kataras** [comment]
OK @Dexus, the issue is fixed, thanks for the bug report.

I've also added two helpers:

```go
ctx.SetErr(err error)
ctx.GetErr() error
```

You can now use the `ctx.GetErr`  to retrieve the error stored on mvc.Response/mvcView's Err field inside your custom error handlers (`On(Any)ErrorCode`). And one more change, if that error is not nil, the API's default error handlers will use that as the body response instead of the status code's text.

**Comment by Dexus** [comment]
Thank you! @kataras

**Comment by kataras** [comment]
You are welcome @Dexus !
