### ISSUE TITLE
[QUESTION] Why v11 tags removed?

### ISSUE THREAD

**Issue by yogeshlonkar** [kataras/iris#1571]
**Describe the bug**
It seems v11 tags are removed from repo causing below error when`go get` is run in one of our projects
```shell
go: error loading module requirements
```

**Comment by zkozniak** [comment]
[BUG] Why v6 tags removed?

**Comment by quentinselle** [comment]
I confirm (https://gopkg.in/kataras/iris.v11), 

```bash
go: github.com/kataras/iris@v11.1.1+incompatible: unknown revision v11.1.1
go: error loading module requirements
```


I use go1.12, so I cannot move on iris v12.

**Comment by kataras** [comment]
All prior tags that used the `vendor` path have been removed as promised two years ago. There is a history entry explains: https://github.com/kataras/iris/blob/master/HISTORY.md (navigate to `Other Improvements:`). In-short, Installation was very slow  because its size was more than 55MB, while its real source code, including examples, is not even 8MB. Old branches used the `vendor` folder which, before `go modules` feature, it kept all the dependencies Iris required back then, these folders and files are kept inside the .git folder, so, with the help of a tool called `bfg` among with the `git-filter-branch` git command we managed to reduce the size. The old tags removed were very old and not supported at all, we SHOULD never promote users to use unsupported software, we had several issues supporting these old tags for nothing. The version 12.1.8 and the upcoming v12.2.0 will be lighter,  well-documented and with better support because we will focus only on this instead of consuming our valuable time by writing replies for software and 3rd-party libraries that many of them don't even exist today.

The promise was made several years ago, it should be done the last year (2019) but I kept those one more year in order to give you time to transit to newest releases. Please convert all your source code into latest Iris, it's more secure, more features and not buggy as the previous ones. However, I am very sorry if that comes with its downsides, but together we can by pass them.

As always, I am willing to personally convert all your projects to use Iris v12.x versions, even if you didn't use Iris at the first place. 

Thanks,
Gerasimos Maropoulos

**Comment by kataras** [comment]
All prior tags that used the `vendor` path have been removed as promised two years ago. There is a history entry explains: https://github.com/kataras/iris/blob/master/HISTORY.md (navigate to `Other Improvements:`). In-short, Installation was very slow  because its size was more than 55MB, while its real source code, including examples, is not even 8MB. Old branches used the `vendor` folder which, before `go modules` feature, it kept all the dependencies Iris required back then, these folders and files are kept inside the .git folder, so, with the help of a tool called `bfg` among with the `git-filter-branch` git command we managed to reduce the size. Tags that didn't support go modules were removed entirely. Why? Simply, because they were not supported at all, we SHOULD never promote users to use unsupported software, we had several issues supporting these old tags for nothing. The version 12.1.8 and the upcoming v12.2.0 will be lighter,  well-documented and with better support because we will focus only on this instead of consuming our valuable time by writing replies for software and 3rd-party libraries that many of them don't even exist today.

The promise was made several years ago, it should be done the last year (2019) but I kept those one more year in order to give you time to transit to newest releases. Please convert all your source code into latest Iris, it's more secure, more features and not buggy as the previous ones. However, I am very sorry if that comes with its downsides, but together we can by pass them.

As always, I am willing to personally convert all your projects to use Iris v12.x versions, even if you didn't use Iris at the first place. 

Thanks,
Gerasimos Maropoulos

**Comment by kataras** [comment]
All prior tags that used the `vendor` path have been removed as promised two years ago. There is a history entry explains: https://github.com/kataras/iris/blob/master/HISTORY.md (navigate to `Other Improvements:`). In-short, Installation was very slow  because its size was more than 55MB, while its real source code, including examples, is not even 8MB. Old branches used the `vendor` folder which, before `go modules` feature, it kept all the dependencies Iris required back then, these folders and files are kept inside the .git folder, so, with the help of a tool called `bfg` among with the `git-filter-branch` git command we managed to reduce the size. Tags that didn't support go modules were removed entirely. Why? Simply, because they were not supported at all, we SHOULD never promote users to use unsupported software, we had several issues supporting these old tags for nothing. The same goes for the Go releases, you SHOULD always use the latest ones whenever possible, they contain SERIOUS BUG FIXES AND SECURITY FIXES. The version 12.1.8 and the upcoming v12.2.0 will be lighter,  well-documented and with better support because we will focus only on this instead of consuming our valuable time by writing replies for software and 3rd-party libraries that many of them don't even exist today.

The promise was made several years ago, it should be done the last year (2019) but I kept those one more year in order to give you time to transit to newest releases. Please convert all your source code into latest Iris, it's more secure, more features and not buggy as the previous ones. However, I am very sorry if that comes with its downsides, but together we can by pass them.

As always, I am willing to personally convert all your projects to use Iris v12.x versions, even if you didn't use Iris at the first place. 

Thanks,
Gerasimos Maropoulos

**Comment by kataras** [comment]
All prior tags that used the `vendor` path have been removed as promised two years ago. There is a history entry explains: https://github.com/kataras/iris/blob/master/HISTORY.md (navigate to `Other Improvements:`). In-short, Installation was very slow  because its size was more than 55MB, while its real source code, including examples, is not even 8MB. Old branches used the `vendor` folder which, before `go modules` feature, it kept all the dependencies Iris required back then, these folders and files are kept inside the .git folder, so, with the help of a tool called `bfg` among with the `git-filter-branch` git command we managed to reduce the size. Tags that didn't support go modules were removed entirely. Why? Simply, because they were not supported at all, we SHOULD never promote users to use unsupported software, we had several issues and time-consuming actions relatively to these old tags, for nothing. The same goes for the Go releases, you SHOULD always use the latest ones whenever possible, they contain SERIOUS BUG FIXES AND SECURITY FIXES. The version 12.1.8 and the upcoming v12.2.0 will be lighter,  well-documented and with better support because we will focus only on this instead of consuming our valuable time by writing replies for software and 3rd-party libraries that many of them don't even exist today.

The promise was made several years ago, it should be done the last year (2019) but I kept those one more year in order to give you time to transit to newest releases. Please convert all your source code into latest Iris, it's more secure, more features and not buggy as the previous ones. However, I am very sorry if that comes with its downsides, but together we can by pass them ( see https://github.com/responsibility-act).

As always, I am willing to personally convert all your projects to use Iris v12.x versions, even if you didn't use Iris at the first place. 

Thanks,
Gerasimos Maropoulos

**Comment by quentinselle** [comment]
Ack, Thank you @kataras
