### ISSUE TITLE
【undefined: iris.Dir】Run example project login error: undefined: iris.Dir

### ISSUE THREAD

**Issue by zfanmy** [kataras/iris#1572]
Describe the issue you are facing or ask for help
Put login project out of iris/_example/mvc  folder,  run main.go, report an error:
 \#command-line-arguments
./main.go:31:27: undefined: iris.Dir

Need help!!

**Comment by kataras** [comment]
Hello @zfanmy, it's easy you just need to upgrade your Iris to the master one, because:
the default repository 's branch contains examples for the `master` branch, which is under active development status. So, in order to grab it in your projects you must run a go get command, as the `README.md` says, use the following code:
```sh
$ go get -u github.com/kataras/iris/v12@master
```
Now you are able to run all the master's examples.

However, If you are looking for the latest stable release check the [v12.1.8](https://github.com/kataras/iris/tree/v12.1.8) branch instead.

**Comment by zfanmy** [comment]
> Hello @zfanmy, it's easy you just need to upgrade your Iris to the master one, because:
> the default repository 's branch contains examples for the `master` branch, which is under active development status. So, in order to grab it in your projects you must run a go get command, as the `README.md` says, use the following code:
> 
> ```shell
> $ go get -u github.com/kataras/iris/v12@master
> ```
> 
> Now you are able to run all the master's examples.
> 
> However, If you are looking for the latest stable release check the [v12.1.8](https://github.com/kataras/iris/tree/v12.1.8) branch instead.

Thank you very much!

**Comment by kataras** [comment]
You are welcome @zfanmy !
