### ISSUE TITLE
[FEATURE REQUEST] Log when I18n Translation Fails?

### ISSUE THREAD

**Issue by AlbinoGeek** [kataras/iris#1593]
## Summary

A call to `ctx.Tr()` with an invalid or mistyped key might go unnoticed if it does not log the "key not found" somewhere.

There are many reasons this could happen:
- Perhaps something new was added in one language, but not in another?
- Perhaps someone simply fat-fingered or typo'd a translation key name.
- Maybe you were using dynamic key assembly in a template.
- Maybe the end-user had access to the translation files (a CRM)

**Comment by kataras** [comment]
@AlbinoGeek we had using `fmt.Sprintf` when a message couldn't be found but I removed it a day after, this thing can be easly added at [i18n.go#L315](https://github.com/kataras/iris/blob/1192e6f787e791deaa3d6a2d6ed825f6abe194f3/i18n/i18n.go#L315) and [i18n/loader.go#L257](https://github.com/kataras/iris/blob/1192e6f787e791deaa3d6a2d6ed825f6abe194f3/i18n/loader.go#L257). Why I removed it? because there are cases (in views) when a translation is missing to handle it and display a custom message e.g. `{{ if ` statement to check if the value is empty, and if it was then display something custom depending on the template data/funcs.

Maybe we can add a field which will let you control that behavior, something like:

 ```go
// or        FallbackMessage = func...
// or        MessageNotFound = func...
app.I18n.DefaultGetMessage = func(key string, args ...interface{}) string {
 // custom logic and return value...
}
```

**Comment by kataras** [comment]
@AlbinoGeek we had using `fmt.Sprintf` when a message couldn't be found but I removed it a day after, this thing can be easly added at [i18n.go#L315](https://github.com/kataras/iris/blob/1192e6f787e791deaa3d6a2d6ed825f6abe194f3/i18n/i18n.go#L315) and [i18n/i18n.go#L405](https://github.com/kataras/iris/blob/1192e6f787e791deaa3d6a2d6ed825f6abe194f3/i18n/i18n.go#L405) and [i18n/loader.go#L257](https://github.com/kataras/iris/blob/1192e6f787e791deaa3d6a2d6ed825f6abe194f3/i18n/loader.go#L257). Why I removed it? because there are cases (in views) when a translation is missing to handle it and display a custom message e.g. `{{ if ` statement to check if the value is empty, and if it was then display something custom depending on the template data/funcs. The `i18n.GetMessage` (accepts a Context, access to Locale) is fired on [Context.Tr](https://github.com/kataras/iris/blob/master/context/context.go#L1228-L1234)  and the `i18n.Tr` is used as a default template function on supported view engines (accepts lang as its first input parameter, access to both lang and locale).

Maybe we can add two fields which will let you control that behavior, something like:

 ```go
// or        FallbackMessage = func...
// or        MessageNotFound = func...
app.I18n.DefaultMessageFunc = func(locale iris.Locale, key string, args...interface{}) string {
 // custom logic and return value...
}
app.I18n.DefaultTrFunc= func(lang string, key string, args...interface{}) string {
 // custom logic and return value...
}
```

> Locale will be nil if the language was not found either.

Sounds good?

**Comment by kataras** [comment]
@AlbinoGeek we had using `fmt.Sprintf` when a message couldn't be found but I removed it a day after, this thing can be easly added at [i18n.go#L315](https://github.com/kataras/iris/blob/1192e6f787e791deaa3d6a2d6ed825f6abe194f3/i18n/i18n.go#L315) and [i18n/i18n.go#L405](https://github.com/kataras/iris/blob/1192e6f787e791deaa3d6a2d6ed825f6abe194f3/i18n/i18n.go#L405) and [i18n/loader.go#L257](https://github.com/kataras/iris/blob/1192e6f787e791deaa3d6a2d6ed825f6abe194f3/i18n/loader.go#L257). Why I removed it? because there are cases (in views) when a translation is missing to handle it and display a custom message e.g. `{{ if ` statement to check if the value is empty, and if it was then display something custom depending on the template data/funcs. The `i18n.GetMessage` (accepts a Context, access to Locale, which if language found its Locale.Language() returns it, otherwise it's the default locale) is fired on [Context.Tr](https://github.com/kataras/iris/blob/master/context/context.go#L1228-L1234)  and the `i18n.Tr` is used as a default template function on supported view engines.

Maybe we can add a field which will let you control that behavior, something like:

 ```go
// or        FallbackMessage = func...
// or        MessageNotFound = func...
app.I18n.DefaultMessageFunc = func(locale iris.Locale, key string, args...interface{}) string {
 // custom logic and return value...
}
```

> Locale will be nil if the language was not found either.

Sounds good?

**Comment by kataras** [comment]
@AlbinoGeek we had using `fmt.Sprintf` when a message couldn't be found but I removed it a day after, this thing can be easly added at [i18n.go#L315](https://github.com/kataras/iris/blob/1192e6f787e791deaa3d6a2d6ed825f6abe194f3/i18n/i18n.go#L315) and [i18n/i18n.go#L405](https://github.com/kataras/iris/blob/1192e6f787e791deaa3d6a2d6ed825f6abe194f3/i18n/i18n.go#L405) and [i18n/loader.go#L257](https://github.com/kataras/iris/blob/1192e6f787e791deaa3d6a2d6ed825f6abe194f3/i18n/loader.go#L257). Why I removed it? because there are cases (in views) when a translation is missing to handle it and display a custom message e.g. `{{ if ` statement to check if the value is empty, and if it was then display something custom depending on the template data/funcs. The `i18n.GetMessage` (accepts a Context, access to Locale, which if language found its Locale.Language() returns it, otherwise it's the default locale) is fired on [Context.Tr](https://github.com/kataras/iris/blob/master/context/context.go#L1228-L1234)  and the `i18n.Tr` is used as a default template function on supported view engines (accepts lang string as its first input argument).

Maybe we can add a field which will let you control that behavior, something like:

 ```go
// or        FallbackMessage = func...
// or        MessageNotFound = func...
app.I18n.DefaultMessageFunc = func(locale iris.Locale, key string, args...interface{}) string {
 // custom logic and return value...
}
```

> Locale will be the default one if the language was not found either.

> Note that currently, if a language found but its key is missing then it returns the default language's translation, a behavior which can be customized with that new DefaultMessageFunc too.

Sounds good?

**Comment by kataras** [comment]
The problem is that, due the previous issue of yours, now the Locale and GetMessage always return the default language, so we don't know what's the language the user tried, I will introduce a new context key to hold that value so we can pass it to the DefaultMessageFunc.

**Comment by kataras** [comment]
Hello @AlbinoGeek,  I pushed a commit which gives you a lot of info and you are able to both log and inject a value there too. Example: https://github.com/kataras/iris/blob/a491cdf7ef9c72eaeeec920affe278023180d71c/_examples/i18n/main.go#L28-L51

**Comment by AlbinoGeek** [comment]
That's awesome, I would say that **Resolved** this request, as I now have control to log or dynamically generate if required.
