### ISSUE TITLE
graceful shutdown doesn't work

### ISSUE THREAD

**Issue by tuhao1020** [kataras/iris#1600]
Press `CTRL+C` and the server stops immediately

``` go
package main

import (
	stdContext "context"
	"time"

	"github.com/kataras/iris/v12"
)

func main() {
	app := iris.New()

	iris.RegisterOnInterrupt(func() {
	  ctx, cancel := stdContext.WithTimeout(stdContext.Background(), 15 * time.Second)
	  defer cancel()
	  app.Logger().Warnf("Closing...")
	  app.Shutdown(ctx)
	})

	app.Get("/test", func(ctx iris.Context) {
	  time.Sleep(10 * time.Second)
	  ctx.Text("OK")
  })

	app.Run(iris.Addr(":8081"), iris.WithoutInterruptHandler)
}
```

**Expected behavior**
`/test` should successfully send response after pressing `CTRL+C`.

**Desktop (please complete the following information):**
 - OS: [windows 10]
 - golang: [1.15]

**iris.Version**
- v12@master

**Comment by kataras** [comment]
@tuhao1020 The `app.Shutdown(ctx)` calls the underline [*http.Server.Shutdown(ctx)](https://golang.org/pkg/net/http/#Server.Shutdown). The `net/http` has the same exactly behavior on your test:

```go
func main() {
	srv := &http.Server{
		Addr: ":8081",
		Handler: http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			time.Sleep(10 * time.Second)
			w.Write([]byte("OK"))
		}),
	}

	go func() {
		time.Sleep(5 * time.Second)

		ctx, cancel := stdContext.WithTimeout(stdContext.Background(), 15*time.Second)
		defer cancel()
		log.Println("Closing...")
		srv.Shutdown(ctx)
	}()

	log.Fatal(srv.ListenAndServe())
}
```

I don't think there is a problem here, this is how it supposed to work.

**Comment by kataras** [comment]
@tuhao1020 The `app.Shutdown(ctx)` calls the underline [*http.Server.Shutdown(ctx)](https://golang.org/pkg/net/http/#Server.Shutdown). The `net/http` has the same exactly behavior on your test:

```go
func main() {
	srv := &http.Server{
		Addr: ":8081",
		Handler: http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			time.Sleep(10 * time.Second)
			w.Write([]byte("OK"))
		}),
	}

	go func() {
		time.Sleep(5 * time.Second)

		ctx, cancel := stdContext.WithTimeout(stdContext.Background(), 15*time.Second)
		defer cancel()
		log.Println("Closing...")
		srv.Shutdown(ctx)
	}()

	log.Fatal(srv.ListenAndServe())
}
```

**Comment by kataras** [comment]
@tuhao1020 It's not a bug. The `app.Shutdown(ctx)` calls the underline [*http.Server.Shutdown(ctx)](https://golang.org/pkg/net/http/#Server.Shutdown). The `net/http` has the same exactly behavior on your test:

```go
func main() {
	srv := &http.Server{
		Addr: ":8081",
		Handler: http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			time.Sleep(10 * time.Second)
			w.Write([]byte("OK"))
		}),
	}

	go func() {
		time.Sleep(5 * time.Second)

		ctx, cancel := stdContext.WithTimeout(stdContext.Background(), 15*time.Second)
		defer cancel()
		log.Println("Closing...")
		srv.Shutdown(ctx)
	}()

	log.Fatal(srv.ListenAndServe())
}
```

The solution to your problem is to just add a `for {}` or a wait-for-ever channel after your `app.Run/Listen` because when `Shutdown` the underline http server's ListenAndServe is returned and if you don't wait then the program will exit, **this is how Go works, if main exits everything exit**.

```go
	app.Listen(":8081", iris.WithoutInterruptHandler)
        // HERE SIMULATE A WAIT SO ALL CONNECTION
        // CAN BE TERMINATED GRACEFULY BEFORE MAIN PROGRAM IS EXITED
        for {} // of course you don't want that, find a way to do it or comment below.
```

**Comment by kataras** [comment]
@tuhao1020 It's not a bug. The `app.Shutdown(ctx)` calls the underline [*http.Server.Shutdown(ctx)](https://golang.org/pkg/net/http/#Server.Shutdown). The `net/http` has the same exactly behavior on your test:

```go
func main() {
	srv := &http.Server{
		Addr: ":8081",
		Handler: http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			time.Sleep(10 * time.Second)
			w.Write([]byte("OK"))
		}),
	}

	go func() {
		time.Sleep(5 * time.Second)

		ctx, cancel := stdContext.WithTimeout(stdContext.Background(), 15*time.Second)
		defer cancel()
		log.Println("Closing...")
		srv.Shutdown(ctx)
	}()

	log.Fatal(srv.ListenAndServe())
}
```

The solution to your problem is to just add a `for {}` or a wait-for-x time `time.Sleep(20*time.Second)` or  channel after your `app.Run/Listen` because when `Shutdown` the underline http server's ListenAndServe is returned and if you don't wait then the program will exit, **this is how Go works, if main exits everything exit**.

```go
	app.Listen(":8081", iris.WithoutInterruptHandler)
        // HERE SIMULATE A WAIT SO ALL CONNECTION
        // CAN BE TERMINATED GRACEFULY BEFORE MAIN PROGRAM IS EXITED
        time.Sleep(20*time.Second) // of course you don't want that, see below.
```

Note that the underline http.Server does NOT wait for all shutdown listeners to finish, it runs them through `go` routines, see [here](https://golang.org/src/net/http/server.go?s=85127:85181#L2689) so we can't add listeners there to "wait for an x client to finish". So, if you read the code, in realitty it closes the connections, it does not wait for them to finish and for good reason. There are many alternatives, just read the golang/go issues. See below a recommended example to use:
```go
func main() {
	app := iris.New()
	app.Logger().SetLevel("debug")

	app.Get("/test", func(ctx iris.Context) {
		time.Sleep(10 * time.Second)
		ctx.Text("OK")
	})

	closed := make(chan bool, 1)

	iris.RegisterOnInterrupt(func() {
		ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
		defer cancel()
		app.Hosts[0].Server.SetKeepAlivesEnabled(false)
		now := time.Now()
		app.Shutdown(ctx)
		app.Logger().Debugf("Shutdown after: %s", time.Since(now))
		close(closed)
	})

	app.Listen(":8081", iris.WithoutInterruptHandler, iris.WithoutServerError(iris.ErrServerClosed))
	<-closed
}

```

**Comment by tuhao1020** [comment]
Thank you! I suggest that the graceful shutdown example can be updated.

**Comment by kataras** [comment]
Yeah I'll do that. Thanks for opening the issue. Please dont hesitate to ask more in the future. Dont forget to Star the repo if you didnt already!!
