### ISSUE TITLE
[QUESTION] What is the correct order of `WrapRouter`, `Subdomain`, `Party`, `mvc` and `SubdomainRedirect` ?

### ISSUE THREAD

**Issue by AlbinoGeek** [kataras/iris#1605]
Chances are some of my "bugs" actually come from me not understanding the intended order of attaching these things, so I thought I would just come out and ask, and plan to make a documentation piece based on the answer --- which order should the following be applied to work as described?

## Versions, etc.

|Thing|Version|
|-|-|
|Golang|1.14.6 linux/amd64|
|Iris|[master](https://github.com/kataras/iris/tree/master) commit ef5685b|
|Kernel|5.7.14-200.fc32.x86_64|
|OS|Fedora 32 (Workstation Edition)|

## Intention

```
static.example.com (assets)
CORS on only static.example.com
*UserController  on your.example.com/user
PublicController on your.example.com/
example.com      -> your.example.com
*.example.com    -> your.example.com
```

## Code

```golang
	// subdomain for static.example.com
	app.Subdomain("static"). // assets
		HandleDir("/", iris.Dir("./public"), iris.DirOptions{
			// ...
		})

	// CORS for static.example.com (currently also served on example.com, not intended)
	c := cors.New(cors.Options{
		AllowedOrigins:   buildDomainsList(true, "https://"),
		AllowCredentials: true,
	})
	app.WrapRouter(c.ServeHTTP) // CORS

	// subdomain for your.example.com
	your := app.Subdomain("your") // primary subdomain
	
	// _examples/mvc/authenciated-controller
	// party for your.example.com/user
	userRouter := your.Party("/user")
	userRouter.SetRegisterRule(iris.RouteOverlap)

	// controller for your.example.com/user/
	userApp := mvc.New(userRouter)
	userApp.Register(user.AuthDependency)
	userApp.Handle(new(user.AuthorizedUserController))
	userApp.Handle(new(user.UnauthorizedUserController))
	
	// controller for your.example.com/
	mvc.New(your).Handle(new(public.PublicController))

	// redirect for example.com -> your.example.com
	app.SubdomainRedirect(app, your)

	// redirect for *.example.com -> your.example.com
	// not using WildcardSubdomain because of route order bug
	for _, domain := range subDomains {
		if domain != "your" && domain != "static" {
			app.SubdomainRedirect(app.Subdomain(domain), your)
		}
	}
```

**Comment by kataras** [comment]
Hello @AlbinoGeek,

You have right, we are lacking documentation on that part, mostly because `UseRouter`, `UseError` are new keywords of v12.2.x, and the `WrapRouter` and `Use/UseGlobal` are easy to understand through examples. However, now we have more places to add handlers and intercept a request-response lifecycle, so we need better documentation. I will start by this issue.

![iris-middleware-flow](https://user-images.githubusercontent.com/22900943/91115708-6fe3c300-e693-11ea-9435-fb62d5ed3298.png)


## UseGlobal

A `UseGlobal` handler is registered on previous and next current Party's routes at the first position of their handlers chain. It is executed only on matched routes, by registration order (same applies for `Use` too). Middleware `func(ctx iris.Context)` and it requires `ctx.Next` to proceed (unless execution rules changed).

## UseRouter

A `UseRouter` handler is registered under a Party,  it runs on the path prefix of the Party. It is executed before the Iris Router, so it does not know the error code up-front (remember: it doesn't know if a route matched or not yet) and it is helpful because of that, you can change the path and e.t.c. to let router match or cancel a specific route you want. It's one level higher than the `WrapRouter` and one level lower than the `Use/UseGlobal`. Same as `Use and UseGlobal`, it's an `iris.Handler` and it requires `ctx.Next` to proceed to the next `UseRouter` or to the main `iris router` if it's the last one.

## WrapRouter

The `WrapRouter` wraps the main Server Handler, including any UseRouter and the Iris Router. Last registered wraps the previous ones, so last registered runs first. It's the lowest level. It is a `func(w http.ResponseWriter, r *http.Request, router http.HandlerFunc)` and a call of its `router(w,r)` is required to run the main router (if you want, it depends the needs of your implenentation, e.g. you can chaneg the host, path to match a specific route, like `UseRouter` or just make a fast redirection or to disallow a specific IP/client before even any router or middleware is being executed).


Do you write content on other `UseRouter`? If that's the case that's why you never get `404` because the status code is sent already there. Look that test to check see order of execution:

```go
func ExampleUseUseGlobalUseErrorUseRouterWrapRouterOrder(t *testing.T) {
	var (
		expectedBody         = "#1 .WrapRouter\n#2 .UseRouter\n#3 .UseGlobal\n#4 .Use\n#5 Main Handler\n"
		expectedNotFoundBody = "#1 .UseError\n#2 Main Error Handler\n"
		makeMiddleware       = func(body string) iris.Handler {
			return func(ctx iris.Context) {
				if ctx.Path() == "/" {
					ctx.WriteString(body)
				}

				ctx.Next()
			}
		}

		handler = func(ctx iris.Context) {
			ctx.WriteString("#5 Main Handler\n")
		}

		errorHandler = func(ctx iris.Context) {
			ctx.WriteString("#2 Main Error Handler\n")
		}

		useHandler = makeMiddleware("#4 .Use\n")
		useGlobal  = makeMiddleware("#3 .UseGlobal\n")
		useError   = func(ctx iris.Context) {
			// UseError has captured the status code, because it runs
			// after the router itself but only one error handlers.
			ctx.WriteString("#1 .UseError\n")
			ctx.Next()
		}
		useRouter  = makeMiddleware("#2 .UseRouter\n")
		wrapRouter = func(w http.ResponseWriter, r *http.Request, router http.HandlerFunc) {
			if r.URL.Path == "/" {
				w.Write([]byte("#1 .WrapRouter\n"))
				// Note for beginners, reading this test:
				// if we write something here on a not found page,
				// in the raw net/http wrapper like this one,
				// then the response writer sends 200 status OK
				// (on first write) and so any error handler will not be fired as expected,
				// these are basic things. If you w.WriteHeader you cannot change the status code later on too.
				// In Iris handlers, if you write before status code set, then it sends 200
				// and it cannot change too (if you want to change that behavior you use ctx.Record()).
				// However if you
				// just call ctx.StatusCode without content written then you are able to change the status code
				// later on.
			}

			router(w, r)
		}
	)

	app := iris.New()
	app.Use(useHandler)
	app.UseGlobal(useGlobal)
	app.UseError(useError)
	app.UseRouter(useRouter)
	app.WrapRouter(wrapRouter)

	app.OnErrorCode(iris.StatusNotFound, errorHandler)
	app.Get("/", handler)

	e := httptest.New(t, app)
	e.GET("/NotFound").Expect().Status(iris.StatusNotFound).Body().Equal(expectedNotFoundBody)
	e.GET("/").Expect().Status(iris.StatusOK).Body().Equal(expectedBody)
}
```

## About https://github.com/kataras/iris/issues/1604, 

The output is **expected** to be different between UseRouter and UseGlobal. They are doing a totally different thing.

**Comment by AlbinoGeek** [comment]
Thank you for this detailed explanation and test case!

This means I need to both `UseGlobal` and `UseError` things I expect to always execute.

This also means that `CORS` might be screwing up my error handling if it's not use a strict-enough path matcher.

**Comment by kataras** [comment]
Hello @AlbinoGeek,

Sorry, a `UseGlobal` handler is executed before  **every route (matched or error/not found)**.

> Whoops, one more thing, Where does Subdomain and SubdomainRedirect fit on this explanation?

Yes this is not a completed documentation I am trying to write the whole thing on the new e-book but as I am going I am adding more and more examples and I must find a balance between readability and deep understanding. 

- `Subdomain` is just a `Party` so, all that you can expect from a `Party`.
- [SubdomainRedirect](https://github.com/kataras/iris/blob/5e82fa5b893d67135f25fa0d9178add52d8acee7/iris.go#L210-L211) is a `Router Wrapper` but it's registered using the [AddRouterWrapper](https://github.com/kataras/iris/blob/5e82fa5b893d67135f25fa0d9178add52d8acee7/core/router/router.go#L304) instead of the [WrapRouter](https://github.com/kataras/iris/blob/5e82fa5b893d67135f25fa0d9178add52d8acee7/core/router/router.go#L295). The `WrapRouter` is wrapping the previous wrapper directly, when you call it, the difference is that, the `AddRouterWrapper` is appending to a list of wrappers that are wrapped in the end, so they are called first on **Build state**. So, the `SubdomainRedirect` wrapper should always run first (as it wraps any previous ones), even if the end-developer uses a feature (or manually) which calls the `WrapRouter`.

**Comment by kataras** [comment]
Hello @AlbinoGeek,

Sorry, a `UseGlobal` handler is executed before  **every route (matched or error/not found)**. A `UseError` is firing before any registered `OnErrorCode/OnAnyErrorCode`, or if nothing was registered, they are executed before the default error handler for each error status code.

> Whoops, one more thing, Where does Subdomain and SubdomainRedirect fit on this explanation?

Yes this is not a completed documentation I am trying to write the whole thing on the new e-book but as I am going I am adding more and more examples and I must find a balance between readability and deep understanding. 

- `Subdomain` is just a `Party` so, all that you can expect from a `Party`.
- [SubdomainRedirect](https://github.com/kataras/iris/blob/5e82fa5b893d67135f25fa0d9178add52d8acee7/iris.go#L210-L211) is a `Router Wrapper` but it's registered using the [AddRouterWrapper](https://github.com/kataras/iris/blob/5e82fa5b893d67135f25fa0d9178add52d8acee7/core/router/router.go#L304) instead of the [WrapRouter](https://github.com/kataras/iris/blob/5e82fa5b893d67135f25fa0d9178add52d8acee7/core/router/router.go#L295). The `WrapRouter` is wrapping the router and any previous wrappers directly, when you call it. The difference is that, the `AddRouterWrapper` is appending to a list of wrappers that are wrapped in the end -  **on Build state**. So, the `SubdomainRedirect` wrapper should always run first (as it wraps any previous ones), even if the end-developer uses a feature (or manually) which calls the `WrapRouter`.
 
But **please do not use the SubdomainRedirect** as I am thinking of deprecating it at all, or at least add a warning. There is a better solution, you remember the `rewrite` pdf I sent you over? Use [that instead](https://github.com/kataras/iris/tree/master/_examples/routing/rewrite). You can do the things you posted above more easier.

Example on your above case. All `SubdomainRedirect` calls can be replaced by:

```go
import (
	"github.com/kataras/iris/v12"
	"github.com/kataras/iris/v12/middleware/rewrite"
)
```

```go
app.Get...

// redirects := rewrite.Load("redirects.yml")
// ^ see _examples/routing/rewrite example for that.
//
// Now let's do that by code.
rewriteEngine, _ := rewrite.New(rewrite.Options{
	PrimarySubdomain: "your",
})
app.WrapRouter(rewriteEngine.Rewrite)
app.Listen/Run...
```

VS the old using `SubdomainRedirect`:

```go
your := app.Subdomain("your") // primary subdomain
your.Get...

// redirect for example.com -> your.example.com
app.SubdomainRedirect(app, your)

for _, domain := range subDomains { 
	if domain != "your" && domain != "static" {
		app.SubdomainRedirect(app.Subdomain(domain), your)
	}
}
```

So in reality you have one-spot to configure the primary subdomain with **a single line** and **no matter what name has your primary subdomain, "test" or "www"**,  you **don't need** to create a separate Party (which is limited compared to the main *Application instance (e.g. UseGlobal is only root's feature as it's registeres routes to all routes of all parties).

Also, the `WildcardSubdomain` thing is not bug, it works but not when you try to redirect from/to the **root Application** (high risk of redirect loop)[*](https://github.com/kataras/iris/blob/5e82fa5b893d67135f25fa0d9178add52d8acee7/core/router/router_subdomain_redirect.go#L77-L81).

**Comment by AlbinoGeek** [comment]
```golang
	// redirect RootDomain to PrimarySubdomain
	// app.SubdomainRedirect(app, your)

	// redirect all remaining domains to PrimarySubdomain
	// for _, domain := range viper.GetStringSlice("SubDomains") {
	// 	if domain != viper.GetString("PrimarySubDomain") &&
	// 		domain != viper.GetString("StaticSubDomain") {
	// 		golog.Info("Redirecting %s to PrimarySubdomain", domain)
	// 		app.SubdomainRedirect(app.Subdomain(domain), your)
	// 	}
	// }

	// set up SEO rewrites and domain redirect
	rewriteEngine, err := rewrite.New(rewrite.Options{
		// ReidrectMatch: []string{},
		PrimarySubdomain: viper.GetString("PrimarySubDomain"),
	})
	if err != nil {
		golog.Fatalf("error in setting up redirects: %v", err)
	}
	app.WrapRouter(rewriteEngine.Rewrite)
```

The new `rewrite` doesn't work for me at the moment, going to `your.` (PrimarySubDomain) gives me a `Not Found` and doesn't produce anything in the logs.

**Comment by kataras** [comment]
Hello @AlbinoGeek,

That's strange, I assume you have the `example.com` and `your.example.com` defined as virtual hosts, so, you get `404` meanining that the machine found the domain and subdomain, however this is even more strange.  Maybe it does not pass simple the `domainValidator`  (which does not allow localhost or 127.0.0.1 subdomains to be proceed (they are too buggy and it's easier to just use virtual hosts). Can you add some logs at: https://github.com/kataras/iris/blob/5e82fa5b893d67135f25fa0d9178add52d8acee7/middleware/rewrite/rewrite.go#L149 and tell me the results?

**Comment by kataras** [comment]
Hello @AlbinoGeek,

That's strange, I assume you have the `example.com` and `your.example.com` defined as virtual hosts, so, you get `404` meanining that the machine found the domain and subdomain, however this is even more strange.  Maybe it does not pass the simple [domainValidator](https://github.com/kataras/iris/blob/5e82fa5b893d67135f25fa0d9178add52d8acee7/middleware/rewrite/rewrite.go#L149)  (which does not allow localhost or 127.0.0.1 subdomains to be proceed (they are too buggy and it's easier to just use virtual hosts)). Can you upgrade and enable debug messages?

```go
app.Logger().SetLevel("debug")

rewriteEngine, _ := rewrite.New(....)
rewriteEngine.SetLogger(app.Logger()) // <---

app.Listen/Run(...)
```

This is working on me, example logs:

Request: `mydomain.com` (first time)

![image](https://user-images.githubusercontent.com/22900943/91228079-4af15d80-e730-11ea-8a99-636729bff122.png)

Request: `mydomain.com` second time in the same browser, with cache enabled (permant redirect to your.mydomain.com`:

![image](https://user-images.githubusercontent.com/22900943/91228144-6ceae000-e730-11ea-869e-89c6fdf5209c.png)

Request `your.mydomain.com` same as the above ^

**Comment by AlbinoGeek** [comment]
Okay, that's fair, I see the issue now, but not sure how to fix it:

```golang
[DBUG] 2020/08/25 14:21 rewrite: Begin request: full host: your.mydomain.com and root domain: mydomain.com
       Domain is not a loopback, requested subdomain: your.
       Request host field was modified to: mydomain.com. Proceed without redirection
```

Yet I have `Subdomain` registered on `your` and `admin` -- I wanted the requests to still be handled by `your` in this case, however, I think I can just change that to be a party on `/`. I didn't realize that you had to remove the `Subdomain` when doing this.

**Comment by kataras** [comment]
Yes @AlbinoGeek, you don't need a registered Party/Subdomain just to handle the primary subdomain anymore (see my [prev comments](https://github.com/kataras/iris/issues/1605#issuecomment-679929327)), this is the good part, you use the main application (APIBuilder instance, which is more featured than a simple Party (e.g. UseGlobal)) as you should from the beginning, as is the main application's hub no matter where it listens for requests.

**Comment by AlbinoGeek** [comment]
Totally fair, I would now consider this solved then 👍🏻
