### ISSUE TITLE
v12.1.9 can not be used with neffos v0.0.16 error report websocket: response does not implement http.Hijacker v12.1.8 is available

### ISSUE THREAD

**Issue by ezewu** [kataras/iris#1607]
v12.1.9 can not be used with neffos v0.0.16 error report websocket: response does not implement http.Hijacker
v12.1.8 is available

**Comment by kataras** [comment]
@ezewu Are you sure? I've just run all the [examples](https://github.com/kataras/iris/tree/master/_examples/websocket) and they are working fine... the response writer implements the `http.Hijacker`:

https://github.com/kataras/iris/blob/a46f71804a8eba18f4d1b1496735040c0db867d8/context/response_writer.go#L338-L356

**Comment by ezewu** [comment]
The code has been sent to your mailbox kataras2006@hotmail.com

**Comment by kataras** [comment]
That's awesome! I'll tale a look of it in a bit (writing some docs), we can use the https://chat.iris-go.com (you can click my name and start a private conversation too).

**Comment by kataras** [comment]
@ezewu the problem was that you are using [iris.Default()](https://github.com/kataras/iris/blob/9c56ed62611edc29fcc71b39b044bf5f3f1f6204/iris.go#L134-L143) which changes the response writer to a compression-enabled one, you must not use that with websockets because it will not only give you that hijacker is not available but even if it was then the application would fire an error like that: `[HTTP Server] http: response.Write on hijacked connection` because the compression writer flushes the data on response end, and by net/http nature it's not recommended to write from the original writer on a hijacked connection.

So, the solution to your problem is on `route/route.go` **replace** `app := iris.Default()` **with**: `app := iris.New()` instead. If you want to use logger and recovery, then just import them and use.

**Comment by ezewu** [comment]
Thanks, thank you for pointing out the problem

**Comment by kataras** [comment]
You are welcome @ezewu, I edited the comment to provide one more info.
