### ISSUE TITLE
[FEATURE REQUEST] I18N HTML Literals ("as is") func

### ISSUE THREAD

**Issue by AlbinoGeek** [kataras/iris#1614]
### My Problem

Well, sometimes you have an I18N string that contains a URL, and the placement of that URL within the string is non-obvious (for example, between drastically different grammatically-arranged languages, such as English and Japanese.) The naive approach would be to pass the URL into the call and have used a `%s` with embedded HTML to "embed" the link, but this doesn't work, as `ctx.Tr` appears to sanitize HTML-characters coming from the value.

### Proposed Solution

I want an alternative function (perhaps `TrUnsafe` or `TrLiteral` etc.,) that did not "sanitize" any HTML found within the value, for exceptional cases such as this, where workarounds like breaking up the variable around the link aren't feasible.

### Example

```ini
# locale_en-US.ini
userProfilePublicDescription = If you so choose, your profile can be viewed by others on the site either by giving them <a href="%s">this link</a> or your User ID. If you choose not to have a public profile, you will still appear on Leaderboards by the name selected above under "Display As", but your Display Picture will not appear.
```

```html
<!-- user/profile.html -->
  <section id="public">
    <div class="content">
      <div class="inner">
        <h2><i class="fas fa-star"></i> {{call .tr "userProfilePublic"}}</h2>
        <p>{{call .trUnsafe "userProfilePublicDescription" .Profile.PrimaryURL}}</p>
        <!-- ... -->
      </div>
    </div>
  </section>
```

**Comment by kataras** [comment]
@AlbinoGeek We don't have to add something here, this is a Go's thing. Solution:

_locale_en-US.ini_

```ini
userProfilePublicDescription = <a href="%s">profile description</a>
```

```go
import "html/template"
// [...]
"trUnsafe": func(message string, args ...interface{}) template.HTML {
	return template.HTML(ctx.Tr(message, args...))
},
```

**usage**

```html
{{call .trUnsafe "userProfilePublicDescription" "https://iris-go.com"}}
```

**Comment by AlbinoGeek** [comment]
Thank you for this example. I was used to handlebars simplicity of using triple brackets for a literal string `{{{thing}}}` and expecting a similar thing here. I have to ask, is there any overhead for adding lots of template functions?

**Comment by kataras** [comment]
> Thank you for this example. I was used to handlebars simplicity of using triple brackets for a literal string `{{{thing}}}` and expecting a similar thing here. I have to ask, is there any overhead for adding lots of template functions?

You are welcome Damon. Look, in general, the more data you bind, the more "heavy" the template becomes. But, you don't have to worry about it because the go team made a good work on the text/template package (which html/template is using), therefore by a lot we mean thousands of functions.

**Comment by kataras** [comment]
> Thank you for this example. I was used to handlebars simplicity of using triple brackets for a literal string `{{{thing}}}` and expecting a similar thing here. I have to ask, is there any overhead for adding lots of template functions?

You are welcome Damon, always. Look, in general, the more data you bind, the more "heavy" the template becomes. ~But, you don't have to worry about it because the go team made a good work on the text/template package (which html/template is using), therefore by a lot we mean thousands of functions.~ (<- I don't know about handlebars though, how they decide to register each runtime function, you must see its internal code base to get an honest answer).

The `template.HTML` type by itself, is just a singature which by-pass the safe-escaping html characters, it's not heavy at all*

**Comment by AlbinoGeek** [comment]
Oh wait, the same problem. Because `tr` is context-based, the above suggestion doesn't work. I re-remembered why I asked for this.

Effectively I'd have to call:

```hbs
{{call .trUnsafe .tr "userProfilePublicDescription" "https://iris-go.com"}}
```

**Comment by kataras** [comment]
Hello @AlbinoGeek,

You don't have to do that. In your initial example and feature request you used `tr` as request function but now you are trying to combine it with a template function (which has no access to the current Request Context).

Use `tr` and `trUnsafe` as context-binding data which is more easier because you dont' have to manually pass the locale (as you have with the template function, because it can't know the current request by itself).

The example I pushed that day:

https://github.com/kataras/iris/blob/d6867e1f9e92c8c25314327b3a4174fd4a6f4d5c/_examples/i18n/main.go#L79-L85

https://github.com/kataras/iris/blob/d6867e1f9e92c8c25314327b3a4174fd4a6f4d5c/_examples/i18n/views/index.html#L11-L13

**If you really want to use it as template function**  then you MUST pass the current language/locale, as the template functions registered by `AddFunc` are shared to all templates in all requests. **The app.I18n.Tr** and `ctx.GetLocale().Language()` are the keys here.

Example Code:

```go
app := iris.New()
app.I18n.Load()

engine.AddFunc("trUnsafe", func(language, message string, args ...interface{}) template.HTML {
	return  template.HTML(app.I18n.Tr(language, message, args...))
})

// [...]
```

**Usage**

```go
ctx.ViewData("currentLang", ctx.GetLocale().Language())
```

```html
{{ trUnsafe .currentLang"userProfilePublicDescription" "https://iris-go.com" }}
```
