### ISSUE TITLE
static fs serve issue?

### ISSUE THREAD

**Issue by ziyouchutuwenwu** [kataras/iris#163]
hi, i read the wiki and want to make a static fs file serve, but find something strange.

here is my static dir
```
.
├── static
│   ├── aaa.txt
│   └── bb
│       └── bbb.txt
```

```
iris.StaticFS("/","./static", 1)
```
works fine.

i'm confused, why the last arg is 1, why isn't 0?

here is the doc
```
// third parameter is the level (int) of stripSlashes
// * stripSlashes = 0, original path: "/foo/bar", result: "/foo/bar"
// * stripSlashes = 1, original path: "/foo/bar", result: "/bar"
// * stripSlashes = 2, original path: "/foo/bar", result: ""
```

it seems very strange,  is it a bug?

**Comment by kataras** [comment]
@ziyouchutuwenwu  Why you say 'bug' what's wrong with StaticFS? please take a look at [this example](https://github.com/iris-contrib/examples/tree/master/static_files) it uses  ` Static` but the stripSlashes parameter is the same as `StaticFS`, I can't explain it more than the docs already does, you can make your expirements and see the differents, the stripSlashes parameter is for system path.

> And please star iris if you like it.

**Comment by DJviolin** [comment]
Right now I use `staticFS` to expose my images, fonts, js, css files:

```go
iris.StaticFS("/files", "../../app/public", 1)
```

Which is making me to re-write every single static file routes in files from my node/express project to go/iris in the re-factoring process.

The reason that I want expose everything with one route, because my font-faces is in gazilion subfolders at `../../app/public/fonts/` folder, so defining every single folder one by one is not possible.

Is there another way to expose a folder and all of it's subfolders and files to the public without creating an ftp like folder structure to the public whose visiting `/files`?

First I tried `iris.StaticServe("/", "../../app/public")` and `iris.StaticWeb("/", "../../app/public", 1)` but both of them locked every other routes. :(
