### ISSUE TITLE
[QUESTION] How to ask `accesslog` to re-Open the file?

### ISSUE THREAD

**Issue by AlbinoGeek** [kataras/iris#1631]
## Summary

With `accesslog` how do I ask the Middleware to close and re-open the log file?

Why?

- Filename change (due to configuration reload)
- Log rotation implemented in the Operating System
- Some *nix applications do this when sent a `SIGHUP`
- Truncating the contents of the file (`os.Truncate(f, 0)`)

**Comment by kataras** [comment]
Hmm currently you can do it by adding a wrapper in the handler, which will create and use accesslog instances at servetime. However I think I have a better solution: add a `Reset(newWriter io.Writer)` method which will: wait for on-pending logs to be written in the previous writer, change the internal writer to a buffer, so new requests can be logged until until the new writer is attached and ready. Sounds good?

**Comment by kataras** [comment]
Hmm currently you can do it by adding a wrapper in the handler, which will create and use accesslog instances at servetime. However I think I have a better solution: add a `Reset(newWriter io.Writer)` method which will: wait for on-pending logs to be written in the previous writer, change the internal writer to a buffer, so new requests can be logged temporary until the new writer ready, when it's ready copy the buffer's contents to the new writer and set the output writer usually Sounds good?

About `os.Truncate`, this is read-write operation usually, while the accesslog accepts just an io.Writer, internally we check if it's a reader because we use that to read the first line on CSV.Header==true formatter, so it should be trivial to add a function like this.

**Comment by kataras** [comment]
Hmm currently you can do it by adding a wrapper in the handler, which will create and use accesslog instances at servetime. However I think I have a better solution: add a `Reset(newWriter io.Writer)` method which will: wait for on-pending logs to be written in the previous writer, change the internal writer to a buffer, so new requests can be logged temporary until the new writer ready, when it's ready copy the buffer's contents to the new writer and set the output writer usually Sounds good?

About `os.Truncate`, this is not in the scope of an io.Writer, internally we check if it's a Flusher (or a Reader because we use that to read the first line on CSV.Header==true formatter), so we could add a slice of `Truncaters` too, it should be trivial to add a function like this. 

Stay tuned.

**Comment by kataras** [comment]
Now you have `Truncate(n int)` (for buffered given writers, including the accesslog.File) and `TruncateFile(size int64) error` for raw files.

**Comment by AlbinoGeek** [comment]
It turned out the `Truncate` wasn't an issue, once I remembered to call `Flush` beforehand, it was respected. To anyone else who finds this later, this is the code I ended up using to Flush and Truncate the log file:

```golang
// we should flush before Truncating, to remove old entries
if err := c.AccessLog.Flush(); err != nil {
	return mvc.Response{
		Code: iris.StatusInternalServerError,
		Err: err,
		Text: "Unable to Flush Access Log",
	}
}

// clears the log file on disk, by setting its length to 0
if err := os.Truncate(accessLogFile, 0); err != nil {
	return mvc.Response{
		Code: iris.StatusInternalServerError,
		Err: err,
		Text: "Unable to Truncate Access Log",
	}
}
```

Now the only remaining ask is exactly as you described, some way to change the file or writer that the AccessLog would use at runtime, such as when application configuration changes dictate that the log file be redirected.

**Comment by kataras** [comment]
You can use the `c.AccessLog.TruncateFile(0)` if you don't have access to the file you used to create the accesslog middleware*

> Now the only remaining ask is exactly as you described, some way to change the file or writer that the AccessLog would use at runtime, such as when application configuration changes dictate that the log file be redirected.

Yeah, that is tricky I am coding and testing a safe and without performance cost way to do that...

**Comment by AlbinoGeek** [comment]
Requiring a `Flush` at that point is to be expected / not an unusual performance hit for closing and re-opening a logfile, so that part at least should not be a concern. Of course, there would be a small amount of time when the webserver was blocked from sending requests (at least, when `async=false`) due to the file not yet being open, but this (should be?) less than a handful of nanoseconds at worst.

**Comment by kataras** [comment]
> Thank you! A Truncate method definitely helps me not having to keep the filename around.

Yes, on the next commit you can remove your `Flush` method there too, it will be included inside the `TruncateFile`, as you correctly mentioned, it should be flushed before resize, at least for files.

> Of course, there would be a small amount of time when the webserver was blocked from sending requests (at least, when async=false) due to the file not yet being open

Can you try write nothing before server starts, and see if you still having that issue? (I think that's because of the initial Go file write, it's internal thing and should be fixed with zero bytes written)

```go
ac := accesslog.New/File(...)
ac.Write(nil) // <- HERE
// [...] 

app.UseRouter(ac.Handler)
```

**Comment by kataras** [comment]
OK @AlbinoGeek 

1. The `TruncateFile(0)` now calls `Truncate(0)` too (no need to flush the contents, we just clear the buffer too, if any).
2. I did **NOT** add a new method of `Reset`, instead the whole change writer thing is inside the `SetOutput`, which, now, can be used concurrently (as far as my tests but please perform some of your own too so we can sure, it has a comment of "experimental").

**Comment by kataras** [comment]
OK @AlbinoGeek 

1. The `TruncateFile(0)` now calls `Truncate(0)` first (no need to flush the contents, we just clear the buffer too, if any).
2. I did **NOT** add a new method of `Reset`, instead the whole change writer thing is inside the `SetOutput`, which, now, can be used concurrently (as far as my tests but please perform some of your own too so we can sure, it has a comment of "experimental").

**Comment by AlbinoGeek** [comment]
Wonderful! Would there be a way to know when the old file is ready/finished flushing and closing, perhaps by use of a channel?

`TruncateFile` works well, I can confirm (just deployed the change.) -- When it comes to the new `SetOutput` changes, I will experiment and get back to you.

**Comment by kataras** [comment]
> Would there be a way to know when the old file is ready/finished flushing and closing, perhaps by use of a channel?

Of course, write a wrapper of the *os.File, put your own Close method there and you are ready.

However, we can wait until close the old file, if you want on `SetOutput` (there is already an idea of that in the source code's comment :smile:)

**Comment by kataras** [comment]
OK I pushed a commit, which should work as you want, the `SetOutput` exits when the previous finished, it does not lock, so new requests should be able to write the new writer before the old ones are closed.

**Comment by AlbinoGeek** [comment]
@kataras What a great decision! Thank you, I have implemented this in the deployed sites now.

I would say this is solved at this point!

**Comment by kataras** [comment]
Excellent!
