### ISSUE TITLE
Done middleware does not  work?

### ISSUE THREAD

**Issue by hanyunmuyu** [kataras/iris#1644]
```

package main

import (
	"fmt"
	"github.com/kataras/iris/v12"
)

func main() {
	app := iris.Default()
	app.Done(func(c iris.Context) {
		fmt.Println("Done")
	})
	app.Get("/", func(c iris.Context) {
		/**
			Done middleware works
		c.Next()
		c.JSON([]int{1, 2})
		*/

		//Done middleware does not  work
		c.JSON([]int{1, 2})
	})
	app.Run(iris.Addr(":8080"))
}


```

**Comment by kataras** [comment]
Hello @hanyunmuyu,

This is fundamental, in order to proceed to the next handler **you have to call `ctx.Next()`**. Your code snippet missing this in the main handelr, that's why the `Done` is never, and it shouldn't, be called. Fix with:

```go
	app.Done(func(ctx iris.Context) {
		fmt.Println("Done")
	})
	app.Get("/", func(ctx iris.Context) {
		ctx.JSON([]int{1, 2})
                ctx.Next()
	})
```

**However,** In Iris you can **change that behavior**  and allow all Done to run without Context's Next too. You can do it by registering **execution rules per-party and its children**, there is actually an [example](https://github.com/kataras/iris/blob/master/_examples/routing/route-handlers-execution-rules/main.go) of that feature too. 

Code Snippet:

```go
package main

import "github.com/kataras/iris/v12"

func main() {
	app := iris.New()

	app.SetExecutionRules(iris.ExecutionRules{
		Done: iris.ExecutionOptions{Force: true}, // <- HERE
	})

	app.Done(func(ctx iris.Context) {
		fmt.Println("Done")
	})
	app.Get("/", func(ctx iris.Context) {
		ctx.JSON([]int{1, 2})
	})
	app.Listen(":8080")
}
```

Have fun!

**Comment by kataras** [comment]
Hello @hanyunmuyu,

This is fundamental, in order to proceed to the next handler **you have to call `ctx.Next()`**. Your code snippet missing this in the main handler, that's why the `Done` is never, and it shouldn't, be called. Fix with:

```go
	app.Done(func(ctx iris.Context) {
		fmt.Println("Done")
	})
	app.Get("/", func(ctx iris.Context) {
		ctx.JSON([]int{1, 2})
                ctx.Next()
	})
```

**However,** unlike other frameworks in the industry, In Iris you can **change that behavior**  and allow all Done to run without Context's Next too. You can do it by registering **execution rules per-party and its children**, there is actually an [example](https://github.com/kataras/iris/blob/master/_examples/routing/route-handlers-execution-rules/main.go) of that feature too. 

Code Snippet:

```go
package main

import "github.com/kataras/iris/v12"

func main() {
	app := iris.New()

	app.SetExecutionRules(iris.ExecutionRules{
		Done: iris.ExecutionOptions{Force: true}, // <- HERE
	})

	app.Done(func(ctx iris.Context) {
		fmt.Println("Done")
	})
	app.Get("/", func(ctx iris.Context) {
		ctx.JSON([]int{1, 2})
	})
	app.Listen(":8080")
}
```

Have fun!

**Comment by AlbinoGeek** [comment]
* This probably needs to be added to the mvc/middleware documentation in the book.
I also noticed that `Done` and `DoneGlobal` wasn't running, but didn't know why until now.

Thank you for explaining this :) .

**Comment by kataras** [comment]
You are welcome, there is an example though. Please yes, if you can add a PR to the book 👍
