### ISSUE TITLE
[BUG] I18N TR in the middle of a value clobbers prefixed text

### ISSUE THREAD

**Issue by AlbinoGeek** [kataras/iris#1648]
## Summary

If you use the ability for I18N values to contain other calls to `TR`, where the call is in the middle of your value (such that plaintext is both before and after the call), the text before the call is clobbered by the value returned by the nested call to `TR`.

## Versions, etc.

|Thing|Version|
|-|-|
|Golang|1.14.9 linux/amd64|
|Iris|master 7cfcf9f|
|Kernel|5.8.10-200.fc32.x86_64|
|OS|Fedora 32 Workstation|

### HTML

```html
<label for="hostCiphertext">{{call .TR "message.HostResult"}}</label>
```

### I18N File

```ini
[message]
Encrypted = Encrypted
Message = Message
EncryptedMessage = {{tr "message.Encrypted"}} {{tr "message.Message"}}
HostResult = Store {{tr "message.EncryptedMessage"}} Online
```

### Results

|Scenario|Output|
|-|-|
|Actual|`EncrypEncrypted Message Online`
|Expected|`Store Encrypted Message Online`

**Comment by kataras** [comment]
Hello @AlbinoGeek,

Thanks for the report but, this is already solved in my local version of i18n 🦾 

![image](https://user-images.githubusercontent.com/22900943/94430719-09275d00-019d-11eb-905b-0208b233620d.png)


The next commit of i18n package will introduce new and excited things, I didn't push it yet because need to make sure everything are working as epxected. Thanks for your patience :pray:

**Comment by kataras** [comment]
Hello @AlbinoGeek,

Thanks for the report but, this is already solved in my local version of i18n 🦾 

![image](https://user-images.githubusercontent.com/22900943/94431290-c1550580-019d-11eb-8e7a-4e8e1627cd8c.png)



The next commit of i18n package will introduce new and excited things, I didn't push it yet because need to make sure everything are working as epxected. Thanks for your patience :pray:

**Comment by AlbinoGeek** [comment]
Of course! I can't wait for sections support in a better file format than `.ini`.

Right now, I am forced to write improper English, avoiding the use of the symbols: `'"\`;:` which break `.ini` highlighting.

**Comment by kataras** [comment]
Fixed, commit is live @AlbinoGeek 🥇
