### ISSUE TITLE
when building on apline3.11 in iris dependency

### ISSUE THREAD

**Issue by hmadej** [kataras/iris#1660]
When trying to build I get a mismatch in checksum:

github.com/flosch/pongo2/v4@v4.0.0: checksum mismatch
	downloaded: h1:89EuG/yHG6NE7KFmeg5GwnHYiiPQQXA1SGr12O9umVE=
	go.sum:     h1:6eZe8NSNxtTTGwXgJqqXiiLEDAj7CvkwiYrZFQRW6cQ=

**To Reproduce**
1. go build in docker golang:1.13-alpine3.11

**Expected behavior**
No mismatch

**Desktop (please complete the following information):**
 - alpine3.8

**iris.Version**
github.com/kataras/iris/v12 v12.2.0-alpha

**Additional context**
Since commit https://github.com/kataras/iris/commit/ab7ee4a331db344920d3a4daa441d082ba8b3a4d#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6

**Comment by kataras** [comment]
Hello @hmadej,

You try to install it using go1.13. Iris supports go1.14 and go1.15 (always the last **two Go releases**). On the [installation section](https://www.iris-go.com/docs/#/) you see:

![image](https://user-images.githubusercontent.com/22900943/96179890-40865f80-0f3a-11eb-9fe6-37addc0e78af.png)

I clean my go module cache and try to install it, in order to make sure about my answer here, and the installation works as expected, no missmatch in checksum is shown: 

![image](https://user-images.githubusercontent.com/22900943/96180246-d3bf9500-0f3a-11eb-8bc7-415b266417eb.png)
