### ISSUE TITLE
timeout question

### ISSUE THREAD

**Issue by ruanhanqin** [kataras/iris#1668]
http.Server timeout setting didn't kil the backend tcp goroutine,   whether iris have some way to set request timeout when it timeout , iris can kill the backend goroutine process?

**Comment by kataras** [comment]
Hello @ruanhanqin, everything you know about [net/http](https://golang.org/pkg/net/http/) standard package applies to Iris too. To pass custom read/write timeout values you can attach an `&http.Server` with `app.Run(iris.Server(srv))` instead of `app.Listen`. Example:

```go
app := iris.New()

// [...]
srv := &http.Server{
    ReadTimeout: 5 * time.Second,
    WriteTimeout: 10 * time.Second,
}
app.Run(iris.Server(srv))
```

In net/http there is also a [TimeoutHandler](https://golang.org/pkg/net/http/#TimeoutHandler) that we can port for Iris to control timeouts **per request handler instead of globally as we've shown above**. However, I always recommend to my students to avoid that and make your "slow" operations accept a standard `context.Context` and add deadlines there instead. Example:

```go
import "context"
// [...]

func slowJob(ctx context.Context) string {
	t := NewTimer(2*time.Second) // simulate a slow job.
	select {
	case <-ctx.Done():
                // CANCELED (in production code you return an error probably).
                return ""
	case <-t.C:
		log.Printf("Slow API call done after %d seconds.\n", d)
		return "foobar"
	}
}

func handleSlow(ctx iris.Context) {
        reqContext := ctx.Request().Context() // returns the context.Context inside the *http.Request
        // here you can modify it, e.g.
        jobCtx, cancelCtx := context.WithTimeout(reqContext, 3*time.Second) // wait max of 3 seconds, your timeout value.
        defer cancelCtx()
	res := slowJob(jobCtx)
	ctx.WriteString(res)
}
```

Please do not hesitate to ask for more if you didn't understand. 

Please [star](https://github.com/kataras/iris/stargazers) this open source project to attract more developers so that together we can improve it even more!

Yours,
Gerasimos Maropoulos

**Comment by kataras** [comment]
Hello @ruanhanqin, everything you know about [net/http](https://golang.org/pkg/net/http/) standard package applies to Iris too. To pass custom read/write timeout values you can attach an `&http.Server` with `app.Run(iris.Server(srv))` instead of `app.Listen`. Example:

```go
app := iris.New()

// [...]
srv := &http.Server{
    ReadTimeout: 5 * time.Second,
    WriteTimeout: 10 * time.Second,
}
app.Run(iris.Server(srv))
```

In net/http there is also a [TimeoutHandler](https://golang.org/pkg/net/http/#TimeoutHandler) that we can port for Iris to control timeouts **per request handler instead of globally as we've shown above**. However, I always recommend to my students to avoid that and make your "slow" operations accept a standard `context.Context` and add deadlines there instead. Example:

```go
import "context"
import "time"
// [...]

func slowJob(ctx context.Context) string {
	t := time.NewTimer(2*time.Second) // simulate a slow job.
	select {
	case <-ctx.Done():
                // CANCELED (in production code you return an error probably).
                return ""
	case <-t.C:
		return "result"
	}
}

func handleSlow(ctx iris.Context) {
        reqContext := ctx.Request().Context() // returns the context.Context inside the *http.Request
        // here you can modify it, e.g.
        jobCtx, cancelCtx := context.WithTimeout(reqContext, 3*time.Second) // wait max of 3 seconds, your timeout value.
        defer cancelCtx()
	res := slowJob(jobCtx)
	ctx.WriteString(res)
}
```

Please do not hesitate to ask for more if you didn't understand. 

Please [star](https://github.com/kataras/iris/stargazers) this open source project to attract more developers so that together we can improve it even more!

Yours,
Gerasimos Maropoulos

**Comment by ruanhanqin** [comment]
Thank you for your enthusiasm answer,  you mean the slow process should be in a function alone,  that the handler can use context to control it ,  yeah it is another way to control the timeout backend goroutine.  my project is use iris, iris will be a great framework!

**Comment by kataras** [comment]
Exactly @ruanhanqin and we do this in order to be able to share your logic code with other parts of your application, not only http-specific. Thank you for your nice words, I really appreciate it!

**Comment by sado0823** [comment]
@kataras hi, is there a way to do in `iris` like this in `net/http`?
```golang
func TimeoutHandler(duration time.Duration) func(http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		if duration > 0 {
			return http.TimeoutHandler(next, duration, reason)
		}

		return next
	}
}
i want to set a http timeout, and get `503` code

```

**Comment by sado0823** [comment]
@kataras 
in this way , when timeout , i can not get any response and header
```golang
srv := &http.Server{
    Addr: ":8080",
    ReadTimeout: 5 * time.Second,
    WriteTimeout: 10 * time.Second,
}
app.Run(iris.Server(srv))
```
