### ISSUE TITLE
ReadQuery  schema: converter not found for some type

### ISSUE THREAD

**Issue by ruanhanqin** [kataras/iris#1671]
iris:v12.2.0-alpha
validator:v10.4.0

```
var uid struct {
		Id primitive.ObjectID `url:"id" validate:"required"`
	}
if err := ctx.ReadQuery(&uid); err != nil {
             // primitive.ObjectID is a mongo ObjectID
              //  schema: converter not found for primitive.ObjectID, it get string,  but ReadJSON work better. 
		...
	}
```

**Comment by kataras** [comment]
ObjectID is `type ObjectID [12]byte`. You have to register a converter for that custom type. ReadJSON works because the 
ObjectID has a `MarshalJSON` method which `encoding/json` uses as a converter. See here: https://godoc.org/go.mongodb.org/mongo-driver/bson/primitive#ObjectID.MarshalJSON.

To register a converter import the `github.com/iris-contrib/schema` and call [schema.Query.RegisterConverter(value interface{}, converterFunc Converter)](https://github.com/iris-contrib/schema/blob/4fafd0845ed1b8cc46cfc3a2a9ba64f2000ff405/decoder.go#L67). The `Converter` is just a type of `func(string) reflect.Value`, you can see examples [here](https://github.com/iris-contrib/schema/blob/4fafd0845ed1b8cc46cfc3a2a9ba64f2000ff405/converter.go#L33).

It's not a bug. However, we miss documentation and example on how to register a custom Query/Form/Headers/Params converters. I am on it.

**Comment by ruanhanqin** [comment]
thank you !  @kataras   it's great !

**Comment by kataras** [comment]
You are welcome @ruanhanqin. Don't hesitate to ask more!
