### ISSUE TITLE
[QUESTION] v12.2.0 mvc-post request failed

### ISSUE THREAD

**Issue by hjzCy** [kataras/iris#1699]
**Describe the bug**

When registering the mvc structure, if the field is a custom type, the post request fails and returns:
`unexpected end of JSON inputunexpected end of JSON input`

**To Reproduce**

register mvc：
```go
func main() {
    app := iris.Default()
    mvc.New(app.Party("/sms")).Handle(new(tables.SmsSend))
    app.Logger().Fatal(app.Listen(":221"))
}
```

mvc struct：
```go
type SmsSend struct {
    ID         int        `gorm:"column:ID;primaryKey" json:"ID"`
    Mobile     string     `gorm:"column:S_Mobile;type:varchar(30)" json:"Mobile"`
    Msg        string     `gorm:"column:S_Msg;type:varchar(140)" json:"Msg"`
    SetMobile  string     `gorm:"column:S_SetMobile;type:varchar(30)" json:"SetMobile"`
    SendLevel  int        `gorm:"column:S_SendLevel;default:0" json:"SendLevel"`
    SendTime   types.Time `gorm:"column:S_SendTime;type:datetime;default:getdate()" json:"SendTime"`
    WorkerID   string     `gorm:"column:WorkerID;type:varchar(20)" json:"WorkerID"`
    WorkerName string     `gorm:"column:WorkerName;type:varchar(20)" json:"WorkerName"`
}
```

get request（Function is normal）：
```go
func (tb *SmsSend) GetSend(c iris.Context) stru.Response {
    print("GetSend --------------")
    return stru.Response{Status: 1, Data: "succeed"}
}
```

post request（Failed to access api）：
```go
func (tb *SmsSend) PostSend(c iris.Context) stru.Response {
    print("PostSmsSend  --------------")
    return stru.Response{Status: 1, Data: "succeed"}
}
```

types.time：
```go
type Time time.Time

// Scan 由 DB 转到 Go 时被调用
func (t *Time) Scan(value interface{}) error {
	if v, ok := value.(time.Time); ok {
		*t = Time(v)
	}
	return nil
}

// Value 由 Go 转到 DB 时被调用
func (t Time) Value() (driver.Value, error) {
    if time.Time(t).IsZero() {
    return nil, nil
    }
    return time.Time(t).Format("2006-01-02 15:04:05.000"), nil
}

func (t Time) MarshalJSON() ([]byte, error) {
    if time.Time(t).IsZero() {
    return []byte(`""`), nil
    }
    return []byte(time.Time(t).Format(`"2006-01-02 15:04:05"`)), nil
}

func (t Time) String() string {
    return time.Time(t).Format("2006-01-02 15:04:05")
}
```

Same api, post request failed (404) ：`unexpected end of JSON inputunexpected end of JSON input`。
I found that the problem lies in the custom field: `SendTime`，Type is `types.Time`。If you switch to the system's `time.Time` type, the post request is also normal.
There is no problem at all on v12.1.8。

**Desktop (please complete the following information):**
 - OS: windows

**iris.Version**
- v12.2.0-alpha or master

**Comment by kataras** [comment]
Hello @hjzCy, did you register the response as the controller or is this a mistake? Maybe the code snippet is missing something, I don't see the `stru.Response` which returns the error you describe, can you please give me an example that produces the error so I can help you more? Nothing changed from v12.1.8 to v12.0.0-alpha, the json encoding package is the same :) I can't investigate ur issue without a response or request payload :/

**Comment by hjzCy** [comment]
This is a brand new GO project, based on GO1.15.6, IRIS v12.2.0-alpha.0.20210109035706-DB59CBA1B05E, and the operating system is Window。

Here's my **`main.go`** ：

```go
package main

import (
    "awesomeProject/tables"
    "github.com/kataras/iris/v12"
    "github.com/kataras/iris/v12/mvc"
)

func main() {
    app := iris.Default()

    sms := app.Party("/sms")
    mvc.New(sms).Handle(new(tables.SmsSend))

    app.Logger().Fatal(app.Listen(":8080"))
}
```

**`types/time.go`** :

```go
package types

import (
    "database/sql/driver"
    "time"
)

type Time struct {
    time.Time
}

// Scan 由 DB 转到 Go 时被调用
func (t *Time) Scan(value interface{}) error {
    if v, ok := value.(time.Time); ok {
        *t = Time{Time: v}
    }
    return nil
}

// Value 由 Go 转到 DB 时被调用
func (t Time) Value() (driver.Value, error) {
    if t.IsZero() {
        return nil, nil
    }
    return t.Format("2006-01-02 15:04:05.000"), nil
}

func (t Time) MarshalJSON() ([]byte, error) {
    if t.IsZero() {
        return []byte(`""`), nil
    }
    return []byte(t.Format(`"2006-01-02 15:04:05"`)), nil
}

func (t Time) String() string {
    return t.Format("2006-01-02 15:04:05")
}
```

**`table/SMS_Send.go`** :

```go
package tables

import (
    "awesomeProject/types"
    "fmt"
    "github.com/kataras/iris/v12"
)

type SmsSend struct {
    ID         int        `gorm:"column:ID;primaryKey" json:"ID"`
    Mobile     string     `gorm:"column:S_Mobile;not null;type:varchar(30)" json:"Mobile"`
    Msg        string     `gorm:"column:S_Msg;type:varchar(140)" json:"Msg"`
    // If the `time.Time` type is used, the Post method can also be executed normally.
    SendTime   types.Time `gorm:"column:S_SendTime;default:getdate()" json:"SendTime"`
    WorkerID   string     `gorm:"column:WorkerID;type:varchar(20)" json:"WorkerID"`
    WorkerName string     `gorm:"column:WorkerName;type:varchar(20)" json:"WorkerName"`
}

// **important**
// Request Post http://localhost:8080/sms/send
// Did not enter the method body, and return a 404 error: 
//     unexpected end of JSON inputunexpected end of JSON input
// At this time, the iris log output is as follows: 
//    2021-01-09 15:59:42|0s|400|POST|/sms/send|::1|0 B|56 B||
func (tb *SmsSend) PostSend(c iris.Context) {
    fmt.Println("PostSend -----------------------")
}

// Request Get http://localhost:8080/sms/send
// Can enter the method body, and everything is fine.
func (tb *SmsSend) GetSend(c iris.Context) {
    fmt.Println("GetSend -----------------------")
}
```

----

If I go back to v12.1.18 version:

```go
go get -u github.com/kataras/iris/v12@latest
```

Then the above problem no longer occurs, and the iris log is normal:

```shell
GetSend -----------------------
[INFO] 2021/01/09 16:21 200   0s ::1 GET /sms/send
PostSend -----------------------
[INFO] 2021/01/09 16:21 200   0s ::1 POST /sms/send
```

**Comment by kataras** [comment]
Hello @hjzCy,

About the `iris log is normal`, the v12.1.8 `iris.Default` function registers the [middleware/logger](https://github.com/kataras/iris/tree/master/middleware/logger) middleware, while the new v12.2.0-alpha registers the [middleware/accesslog](https://github.com/kataras/iris/tree/master/middleware/accesslog) which contains a lot of improvements and new features [as requested](https://github.com/kataras/iris/issues/1601) in previous issues. In production **never run with iris.Default**, instead use the **iris.New() and register whatever middleware you want manually**.

About the `app.Logger().Fatal(app.Listen/Run....` you do **NOT** need this, the `app.Run/Listen` will log the error anyways, you don't need to do that.

About the `SmsSend` type:

```go
type SmsSend struct {
    ID         int        `gorm:"column:ID;primaryKey" json:"ID"`
```

This is your model that clients sends to your server through JSON request body (or the server sends back to the client), **not** the controller it self. Instead you **MUST** do:

```go
mvc.New(...).Handle(new(SmsController ))
```

```go
type SmsController struct {

}

func (c *SmsController ) PostSend(sms SmsSend) string {
    // here you have access to the client request body of SmsSend JSON encoding.
    return sms.Msg
}
```

The `PostSend/GetSend(c iris.Context)`, the `iris.Context` in MVC methods is not required, you can accept a go type directly, e.g. `PostSend(sms SmsSend)` or register your own [dependency](https://github.com/kataras/iris/blob/db59cba1b05eb794c9ad61ec30a3e41aa47260b6/_examples/mvc/basic/main.go#L46).

The `unexpected end of JSON inputunexpected end of JSON input` error is fired because the request body you try to read is invalid. Usually in Iris MVC **POST** methods  accept a request body from the clients ( e.g. PostSend(sms SmsSend)), otherwise they are useless. That's happen to protect you from accidents, meaning that: when you don't expect a request body from the client you have to use `Get` instead (unless this is behind a proxy or something else).

The **custom Time JSON type**, the `MarshalJSON` looks good, this will help you to SEND the `SmsSend` to the clients but **you have to implement UnmarshalJSON** in order to **receive/decode from client's request body**, here is the code for that:

```go
func (t *Time) UnmarshalJSON(b []byte) error {
	if len(b) == 0 {
		return nil
	}

	s := strings.Trim(string(b), `"`)
	tt, err := time.Parse("2006-01-02 15:04:05", s)
	if err != nil {
		return err
	}

	*t = Time(tt)
	return nil
}
```

**Your problem is**: when your controller (in your case, wrongly it's the request payload) contains fields then those fields are readen through the request body via JSON (or any other registered dependencies, responsible for those field types). So what it tries to do is to read ID, Msg, Time...each time, so you end up with zero body, because only the first one will be filled (after the first ReadJSON the body is consumed, unless otherwise [configured](https://github.com/kataras/iris/blob/db59cba1b05eb794c9ad61ec30a3e41aa47260b6/configuration.go#L269)).

**Your solution is**: First of all [to read the MVC examples](https://github.com/kataras/iris/tree/master/_examples/mvc). Based on that, you can easly do that correct, here you are:

```go
package main

import (
	"database/sql/driver"
	"strings"
	"time"

	"github.com/kataras/iris/v12"
	"github.com/kataras/iris/v12/mvc"
)

func main() {
	app := iris.New()

	smsAPI := app.Party("/sms")
	{
		smsApp := mvc.New(smsAPI)
		smsApp.Handle(new(SmsController))
	}

	app.Listen(":221")
}

type SmsController struct{}

func (c *SmsController) GetSend() string {
	return "GET - SEND"
}

func (c *SmsController) PostSend(sms SmsSend) SmsSend {
	// Just for the example: send back the json SmsSend request.
	return sms
}

type SmsSend struct {
	ID         int    `gorm:"column:ID;primaryKey" json:"ID"`
	Mobile     string `gorm:"column:S_Mobile;type:varchar(30)" json:"Mobile"`
	Msg        string `gorm:"column:S_Msg;type:varchar(140)" json:"Msg"`
	SetMobile  string `gorm:"column:S_SetMobile;type:varchar(30)" json:"SetMobile"`
	SendLevel  int    `gorm:"column:S_SendLevel;default:0" json:"SendLevel"`
	SendTime   Time   `gorm:"column:S_SendTime;type:datetime;default:getdate()" json:"SendTime"`
	WorkerID   string `gorm:"column:WorkerID;type:varchar(20)" json:"WorkerID"`
	WorkerName string `gorm:"column:WorkerName;type:varchar(20)" json:"WorkerName"`
}

type Time time.Time

// Scan 由 DB 转到 Go 时被调用
func (t *Time) Scan(value interface{}) error {
	if v, ok := value.(time.Time); ok {
		*t = Time(v)
	}
	return nil
}

// Value 由 Go 转到 DB 时被调用
func (t Time) Value() (driver.Value, error) {
	if time.Time(t).IsZero() {
		return nil, nil
	}
	return time.Time(t).Format("2006-01-02 15:04:05.000"), nil
}

func (t Time) MarshalJSON() ([]byte, error) {
	if time.Time(t).IsZero() {
		return []byte(`""`), nil
	}
	return []byte(time.Time(t).Format(`"2006-01-02 15:04:05"`)), nil
}

func (t *Time) UnmarshalJSON(b []byte) error {
	if len(b) == 0 {
		return nil
	}

	s := strings.Trim(string(b), `"`)
	tt, err := time.Parse("2006-01-02 15:04:05", s)
	if err != nil {
		return err
	}

	*t = Time(tt)
	return nil
}

func (t Time) String() string {
	return time.Time(t).Format("2006-01-02 15:04:05")
}
```

**Example Request**

```sh
curl -L -X POST "http://localhost:221/sms/send" \
-H 'Content-Type: text/plain' \
--data-raw '{
    "ID": 5,
    "Msg": "Hello World",
    "SendTime": "2021-01-09 20:58:05.100"
}'
```

**Example Response**

```json
{
    "ID": 5,
    "Mobile": "",
    "Msg": "Hello World",
    "SetMobile": "",
    "SendLevel": 0,
    "SendTime": "2021-01-09 20:58:05",
    "WorkerID": "",
    "WorkerName": ""
}
```

![image](https://user-images.githubusercontent.com/22900943/104106387-108ef400-52be-11eb-8cbd-925fb738f695.png)


**Have fun and stay safe**. Please close this issue if your problem is solved.

Thanks,
Gerasimos Maropoulos.

**Comment by kataras** [comment]
Hello @hjzCy,

About the `iris log is normal`, the v12.1.8 `iris.Default` function registers the [middleware/logger](https://github.com/kataras/iris/tree/master/middleware/logger) middleware, while the new v12.2.0-alpha registers the [middleware/accesslog](https://github.com/kataras/iris/tree/master/middleware/accesslog) which contains a lot of improvements and new features [as requested](https://github.com/kataras/iris/issues/1601) in previous issues. In production **never run with iris.Default**, instead use the **iris.New() and register whatever middleware you want manually**.

About the `app.Logger().Fatal(app.Listen/Run....` you do **NOT** need this, the `app.Run/Listen` will log the error anyways, you don't need to do that.

About the `SmsSend` type:

```go
type SmsSend struct {
    ID         int        `gorm:"column:ID;primaryKey" json:"ID"`
```

This is your model that clients sends to your server through JSON request body (or the server sends back to the client), **not** the controller it self. Instead you **MUST** do:

```go
mvc.New(...).Handle(new(SmsController ))
```

```go
type SmsController struct {

}

func (c *SmsController ) PostSend(sms SmsSend) string {
    // here you have access to the client request body of SmsSend JSON encoding.
    return sms.Msg
}
```

The `PostSend/GetSend(c iris.Context)`, the `iris.Context` in MVC methods is not required, you can accept a go type directly, e.g. `PostSend(sms SmsSend)` or register your own [dependency](https://github.com/kataras/iris/blob/db59cba1b05eb794c9ad61ec30a3e41aa47260b6/_examples/mvc/basic/main.go#L46).

The `unexpected end of JSON inputunexpected end of JSON input` error is fired because the request body you try to read is invalid. Usually in Iris MVC **POST** methods  accept a request body from the clients ( e.g. PostSend(sms SmsSend)), otherwise they are useless. That's happen to protect you from accidents, meaning that: when you don't expect a request body from the client you have to use `Get` instead (unless this is behind a proxy or something else).

The **custom Time JSON type**, the `MarshalJSON` looks good, this will help you to SEND the `SmsSend` to the clients but **you have to implement UnmarshalJSON** in order to **receive/decode from client's request body**, here is the code for that:

```go
func (t *Time) UnmarshalJSON(b []byte) error {
	if len(b) == 0 {
		return nil
	}

	s := strings.Trim(string(b), `"`)
	tt, err := time.Parse("2006-01-02 15:04:05", s)
	if err != nil {
		return err
	}

	*t = Time(tt)
	return nil
}
```

**Your problem is**: when your controller (in your case, wrongly it's the request payload) contains fields then those fields are readen through the request body via JSON (or any other registered dependencies, responsible for those field types). So what it tries to do is to read ID, Msg, Time...each time, so you end up with zero body, because only the first one will be filled (after the first ReadJSON the body is consumed, unless otherwise [configured](https://github.com/kataras/iris/blob/db59cba1b05eb794c9ad61ec30a3e41aa47260b6/configuration.go#L269)).

**Your solution is**: First of all [to read the MVC examples](https://github.com/kataras/iris/tree/master/_examples/mvc). Based on that, you can easly do that correct, here you are:

```go
package main

import (
	"database/sql/driver"
	"strings"
	"time"

	"github.com/kataras/iris/v12"
	"github.com/kataras/iris/v12/mvc"
)

func main() {
	app := iris.New()

	smsAPI := app.Party("/sms")
	{
		smsApp := mvc.New(smsAPI)
		smsApp.Handle(new(SmsController))
	}

	app.Listen(":221")
}

type SmsController struct{}

func (c *SmsController) GetSend() string {
	return "GET - SEND"
}

func (c *SmsController) PostSend(sms SmsSend) SmsSend {
	// Just for the example: send back the json SmsSend request.
	return sms
}

type SmsSend struct {
	ID         int    `gorm:"column:ID;primaryKey" json:"ID"`
	Mobile     string `gorm:"column:S_Mobile;type:varchar(30)" json:"Mobile"`
	Msg        string `gorm:"column:S_Msg;type:varchar(140)" json:"Msg"`
	SetMobile  string `gorm:"column:S_SetMobile;type:varchar(30)" json:"SetMobile"`
	SendLevel  int    `gorm:"column:S_SendLevel;default:0" json:"SendLevel"`
	SendTime   Time   `gorm:"column:S_SendTime;type:datetime;default:getdate()" json:"SendTime"`
	WorkerID   string `gorm:"column:WorkerID;type:varchar(20)" json:"WorkerID"`
	WorkerName string `gorm:"column:WorkerName;type:varchar(20)" json:"WorkerName"`
}

type Time time.Time

// Scan 由 DB 转到 Go 时被调用
func (t *Time) Scan(value interface{}) error {
	if v, ok := value.(time.Time); ok {
		*t = Time(v)
	}
	return nil
}

// Value 由 Go 转到 DB 时被调用
func (t Time) Value() (driver.Value, error) {
	if time.Time(t).IsZero() {
		return nil, nil
	}
	return time.Time(t).Format("2006-01-02 15:04:05.000"), nil
}

func (t Time) MarshalJSON() ([]byte, error) {
	if time.Time(t).IsZero() {
		return []byte(`""`), nil
	}
	return []byte(time.Time(t).Format(`"2006-01-02 15:04:05"`)), nil
}

func (t *Time) UnmarshalJSON(b []byte) error {
	if len(b) == 0 {
		return nil
	}

	s := strings.Trim(string(b), `"`)
	tt, err := time.Parse("2006-01-02 15:04:05", s)
	if err != nil {
		return err
	}

	*t = Time(tt)
	return nil
}

func (t Time) String() string {
	return time.Time(t).Format("2006-01-02 15:04:05")
}
```

**Example Request**

```sh
curl -L -X POST "http://localhost:221/sms/send" \
-H 'Content-Type: application/json' \
--data-raw '{
    "ID": 5,
    "Msg": "Hello World",
    "SendTime": "2021-01-09 20:58:05.100"
}'
```

**Example Response**

```json
{
    "ID": 5,
    "Mobile": "",
    "Msg": "Hello World",
    "SetMobile": "",
    "SendLevel": 0,
    "SendTime": "2021-01-09 20:58:05",
    "WorkerID": "",
    "WorkerName": ""
}
```

![image](https://user-images.githubusercontent.com/22900943/104106387-108ef400-52be-11eb-8cbd-925fb738f695.png)


**Have fun and stay safe**. Please close this issue if your problem is solved.

Thanks,
Gerasimos Maropoulos.

**Comment by kataras** [comment]
Hello @hjzCy,

About the `iris log is normal`, the v12.1.8 `iris.Default` function registers the [middleware/logger](https://github.com/kataras/iris/tree/master/middleware/logger) middleware, while the new v12.2.0-alpha registers the [middleware/accesslog](https://github.com/kataras/iris/tree/master/middleware/accesslog) which contains a lot of improvements and new features [as requested](https://github.com/kataras/iris/issues/1601) in previous issues. In production **never run with iris.Default**, instead use the **iris.New() and register whatever middleware you want manually**.

About the `app.Logger().Fatal(app.Listen/Run....` you do **NOT** need this, the `app.Run/Listen` will log the error anyways, you don't need to do that.

About the `SmsSend` type:

```go
type SmsSend struct {
    ID         int        `gorm:"column:ID;primaryKey" json:"ID"`
```

This is your model that clients sends to your server through JSON request body (or the server sends back to the client), **not** the controller it self. Instead you **MUST** do:

```go
mvc.New(...).Handle(new(SmsController ))
```

```go
type SmsController struct {

}

func (c *SmsController ) PostSend(sms SmsSend) string {
    // here you have access to the client request body of SmsSend JSON encoding.
    return sms.Msg
}
```

The `PostSend/GetSend(c iris.Context)`, the `iris.Context` in MVC methods is not required, you can accept a go type directly, e.g. `PostSend(sms SmsSend)` or register your own [dependency](https://github.com/kataras/iris/blob/db59cba1b05eb794c9ad61ec30a3e41aa47260b6/_examples/mvc/basic/main.go#L46).

The `unexpected end of JSON inputunexpected end of JSON input` error is fired because the request body you try to read is invalid. Usually in Iris MVC **POST** methods  accept a request body from the clients ( e.g. PostSend(sms SmsSend)), otherwise they are useless. That's happen to protect you from accidents, meaning that: when you don't expect a request body from the client you have to use `Get` instead (unless this is behind a proxy or something else).

The **custom Time JSON type**, the `MarshalJSON` looks good, this will help you to SEND the `SmsSend` to the clients but **you have to implement UnmarshalJSON** in order to **receive/decode from client's request body**, here is the code for that:

```go
func (t *Time) UnmarshalJSON(b []byte) error {
	if len(b) == 0 {
		return nil
	}

	s := strings.Trim(string(b), `"`)
	tt, err := time.Parse("2006-01-02 15:04:05", s)
	if err != nil {
		return err
	}

	*t = Time(tt)
	return nil
}
```

**Your problem is**: when your controller (in your case, wrongly it's the request payload) contains fields then those fields are readen through the request body via JSON (or any other registered dependencies, responsible for those field types). So what it tries to do is to read ID, Msg, Time...each time, so you end up with zero body, because only the first one will be filled (after the first ReadJSON the body is consumed, unless otherwise [configured](https://github.com/kataras/iris/blob/db59cba1b05eb794c9ad61ec30a3e41aa47260b6/configuration.go#L269)).

**Your solution is**: First of all [to read the MVC examples](https://github.com/kataras/iris/tree/master/_examples/mvc). Based on that, you can easly do that correct, here you are:

```go
package main

import (
	"database/sql/driver"
	"strings"
	"time"

	"github.com/kataras/iris/v12"
	"github.com/kataras/iris/v12/mvc"
)

func main() {
	app := iris.New()

	smsAPI := app.Party("/sms")
	{
		smsApp := mvc.New(smsAPI)
		smsApp.Handle(new(SmsController))
	}

	app.Listen(":221")
}

type SmsController struct{}

func (c *SmsController) GetSend() string {
	return "GET - SEND"
}

func (c *SmsController) PostSend(sms SmsSend) SmsSend {
	// Just for the example: send back the json SmsSend request.
	return sms
}

type SmsSend struct {
	ID         int    `gorm:"column:ID;primaryKey" json:"ID"`
	Mobile     string `gorm:"column:S_Mobile;type:varchar(30)" json:"Mobile"`
	Msg        string `gorm:"column:S_Msg;type:varchar(140)" json:"Msg"`
	SetMobile  string `gorm:"column:S_SetMobile;type:varchar(30)" json:"SetMobile"`
	SendLevel  int    `gorm:"column:S_SendLevel;default:0" json:"SendLevel"`
	SendTime   Time   `gorm:"column:S_SendTime;type:datetime;default:getdate()" json:"SendTime"`
	WorkerID   string `gorm:"column:WorkerID;type:varchar(20)" json:"WorkerID"`
	WorkerName string `gorm:"column:WorkerName;type:varchar(20)" json:"WorkerName"`
}

type Time time.Time

// Scan 由 DB 转到 Go 时被调用
func (t *Time) Scan(value interface{}) error {
	if v, ok := value.(time.Time); ok {
		*t = Time(v)
	}
	return nil
}

// Value 由 Go 转到 DB 时被调用
func (t Time) Value() (driver.Value, error) {
	if time.Time(t).IsZero() {
		return nil, nil
	}
	return time.Time(t).Format("2006-01-02 15:04:05.000"), nil
}

func (t Time) MarshalJSON() ([]byte, error) {
	if time.Time(t).IsZero() {
		return []byte(`""`), nil
	}
	return []byte(time.Time(t).Format(`"2006-01-02 15:04:05"`)), nil
}

func (t *Time) UnmarshalJSON(b []byte) error {
	if len(b) == 0 {
		return nil
	}

	s := strings.Trim(string(b), `"`)
	tt, err := time.Parse("2006-01-02 15:04:05", s)
	if err != nil {
		return err
	}

	*t = Time(tt)
	return nil
}

func (t Time) String() string {
	return time.Time(t).Format("2006-01-02 15:04:05")
}
```

**Example Request**

```sh
curl -L -X POST "http://localhost:221/sms/send" \
-H 'Content-Type: application/json' \
--data-raw '{
    "ID": 5,
    "Msg": "Hello World",
    "SendTime": "2021-01-09 20:58:05.100"
}'
```

**Example Response**

```json
{
    "ID": 5,
    "Mobile": "",
    "Msg": "Hello World",
    "SetMobile": "",
    "SendLevel": 0,
    "SendTime": "2021-01-09 20:58:05",
    "WorkerID": "",
    "WorkerName": ""
}
```

![image](https://user-images.githubusercontent.com/22900943/104106410-5a77da00-52be-11eb-8a07-de74171f98f3.png)


**Have fun and stay safe**. Please close this issue if your problem is solved.

Thanks,
Gerasimos Maropoulos.

**Comment by hjzCy** [comment]
thank! Your tutorial is very detailed! My problem has been solved.

**Comment by kataras** [comment]
You are welcome @hjzCy !
