### ISSUE TITLE
Add a config to use valyala/fasthttp as http gateway

### ISSUE THREAD

**Issue by hamidrezakks** [kataras/iris#1700]
Hi Makis,

Great job on Iris! and Happy new year.
I'm following Iris for 2+ years now, I remember you used to use valyala/fasthttp as your http gateway.
Also in this issue https://github.com/kataras/iris/issues/1288 you explained why you don't user it anymore.

But valyala/fasthttp is actively being developed now,
Don't you think it's better to add an option to use fasthttp in server config?

Bests,
KK

**Comment by kataras** [comment]
Hello @hamidrezakks,

Thanks and happy new year! You remember well, Iris was the first web framework in the world used valyala/http instead of net/http but when  native Go net/http released HTTP/2 support, I did a survey (technical and with iris users) and our decision, back then, to move to net/http and http/2 was the smartest choice.

You saying that valyala/fasthttp is actively under development now, but I don't see http/2 coming at all, I think it will never happen. Until then we can't (and we shouldn't) add a "fasthttp port". Don't forget that something like that would bring huge breaking changes that I am not willing to sacrifice for nothing. If fasthttp is able to handle http/2 (and it's well tested) ever, then we can do a more technical-based conversation. Don't fall for fasthttp, trust me, I know from first hand :)

Kindly,
Gerasimos Maropoulos

**Comment by hamidrezakks** [comment]
Hi @kataras ,

Thank you for your response, 
Do you have any benchmark after and before using net/http instead of valyala/fasthttp?

Bests, 
KK

**Comment by kataras** [comment]
Hello @hamidrezakks,

That's the problem, fasthttp can't be compared with net/http-based frameworks, it doesn't support http/2 remember? And it's unfair to try to compare a system which has 1 version of the http subprotocol to parse and the other which adds extra check/code for the version 2 as well.

**Comment by kataras** [comment]
Hello @hamidrezakks,

That's the problem, fasthttp can't be compared with net/http-based frameworks **anymore**, it doesn't support http/2 remember? And it's unfair to try to compare a system which has 1 version of the http subprotocol to parse and the other which adds extra check/code for the version 2 as well.
