### ISSUE TITLE
host.ProxyHandler make a wrong request

### ISSUE THREAD

**Issue by tuhao1020** [kataras/iris#1702]
http://127.0.0.1:8681/userauth/uims/login ==> http://192.168.0.9:8899/uims/login

- Use host.ProxyHandler:  ❌ http://192.168.0.9:8899/uims/login/userauth/uims/login
```
app.Any("/userauth/{uri:path}", func(ctx iris.Context) {
    target, _ := url.Parse("http://192.168.0.9:8899/" + ctx.Params().Get("uri"))
    p := host.ProxyHandler(target)
    p.ServeHTTP(ctx.ResponseWriter(), ctx.Request())
}
```

- Use httputil.ReverseProxy: ✔️ http://192.168.0.9:8899/uims/login
```
app.Any("/userauth/{uri:path}", func(ctx iris.Context) {
    director := func(r *http.Request) {
        r.Host = "http://192.168.0.9:8899"
        r.URL, _ = url.Parse(r.Host + "/" + ctx.Params().Get("uri"))
    }
    p := &httputil.ReverseProxy{Director: director}
    p.ServeHTTP(ctx.ResponseWriter(), ctx.Request())
}
```

**Comment by kataras** [comment]
Hello @tuhao1020,

The `host.ProxyHandler` code looks like that:

```go
func ProxyHandler(target *url.URL) *httputil.ReverseProxy {
	targetQuery := target.RawQuery
	director := func(req *http.Request) {
		req.URL.Scheme = target.Scheme
		req.URL.Host = target.Host
		req.Host = target.Host

		req.URL.Path = path.Join(target.Path, req.URL.Path)

		if targetQuery == "" || req.URL.RawQuery == "" {
			req.URL.RawQuery = targetQuery + req.URL.RawQuery
		} else {
			req.URL.RawQuery = targetQuery + "&" + req.URL.RawQuery
		}

		if _, ok := req.Header["User-Agent"]; !ok {
			// explicitly disable User-Agent so it's not set to default value
			req.Header.Set("User-Agent", "")
		}
	}
	p := &httputil.ReverseProxy{Director: director}

	if netutil.IsLoopbackHost(target.Host) {
		transport := &http.Transport{
			TLSClientConfig: &tls.Config{InsecureSkipVerify: true}, // lint:ignore
		}
		p.Transport = transport
	}

	return p
}
```

At `req.URL.Path = path.Join(target.Path, req.URL.Path)` line you see that we append target path with the current requested path. 

There is no **make a wrong request** because in the documentation we explictly describe that behavior:

https://github.com/kataras/iris/blob/db59cba1b05eb794c9ad61ec30a3e41aa47260b6/core/host/proxy.go#L14-L20

That's done in order to proxy requests with the same path, e.g. `myapp.com/get/user` to `myotherapp.com/get/user` automatically, if you don't want that feature you are always free to use just the `httputil.ReverseProxy` which Iris depends on as well, there is nothing wrong with that.

**Comment by kataras** [comment]
For readers, new `host.ProxyHandlerRemote` and `host.NewProxyRemote` functions have been added by @tuhao1020 through [PR #1703](https://github.com/kataras/iris/pull/1703).
