### ISSUE TITLE
about json format

### ISSUE THREAD

**Issue by CulionBEAR** [kataras/iris#1711]
hello , I'm sorry to bother you again....
now i have a struct

type User struct {
    Password    string   `json:"password"`
}

When I receive this data from the client  , i use this function

func Ping(ctx iris.Context){
	var msg User
	if err := ctx.ReadJSON(&msg);err != nil{
		sendError(ctx,ErrJson,err.Error())
		return
	}
	sendNormalMessage(ctx,map[string]interface{}{
		"code":Success,
	})
}

when i send data from postman to service:
{
    "password":"admin"
}
the service return me "success"

but when i send this data from postman
{
    "a":"admin"
}
the service return me "success" too!
why err is nil?
please help me...

**Comment by kataras** [comment]
Hello @CulionBEAR,

You don't get an error because the json data you send `{"a":"admin"}` is parsed normally, without issues. The JSON encoder/decoder does NOT require all data to be known by the server by [default](https://golang.org/pkg/encoding/json/).

You have two options:

1. I've just pushed a commit which gives you the option to customize the json decoder and pass a field which disallows unknown json fields sent by a client (example [here](https://github.com/kataras/iris/blob/53b3ade7e0376dfc00fa24a2227e5b08a02fc077/_examples/request-body/read-json-stream/main.go#L44-L47)):


```sh
$ go get github.com/kataras/iris/v12@master
```

```go
	err := ctx.ReadJSON(&u, iris.JSONReader{
		// To throw an error on unknown request payload json fields.
		DisallowUnknownFields: true,
	})

	if err != nil {
		ctx.StopWithError(iris.StatusBadRequest, err)
		return
	}
	
	// [...]
}
```

2. Use a struct validator for more advanced features (example [here](https://github.com/kataras/iris/blob/master/_examples/request-body/read-json-struct-validation/main.go))

**Comment by kataras** [comment]
Hello @CulionBEAR,

You don't get an error because the json data you send `{"a":"admin"}` is parsed normally, without issues. The JSON encoder/decoder does NOT require all data to be known by the server by [default](https://golang.org/pkg/encoding/json/).

You have two options:

1. I've just pushed a commit which gives you the option to customize the json decoder and pass a field which disallows unknown json fields sent by a client (example [here](https://github.com/kataras/iris/blob/53b3ade7e0376dfc00fa24a2227e5b08a02fc077/_examples/request-body/read-json-stream/main.go#L44-L47)):


```sh
$ go get github.com/kataras/iris/v12@master
```

```go
err := ctx.ReadJSON(&u, iris.JSONReader{
	// To throw an error on unknown request payload json fields.
	DisallowUnknownFields: true,
})

if err != nil {
	ctx.StopWithError(iris.StatusBadRequest, err)
	return
}
	
// [...]
```

2. Use a struct validator for more advanced features (example [here](https://github.com/kataras/iris/blob/master/_examples/request-body/read-json-struct-validation/main.go))

**Comment by kataras** [comment]
Hello @CulionBEAR,

You don't get an error because the json data you send `{"a":"admin"}` is parsed normally, without issues. The JSON encoder/decoder does NOT require all data to be known by the server by [default](https://golang.org/pkg/encoding/json/).

You have two options:

1. I've just pushed a commit which gives you the option to customize the json decoder and pass a field which disallows unknown json fields sent by a client (example [here](https://github.com/kataras/iris/blob/53b3ade7e0376dfc00fa24a2227e5b08a02fc077/_examples/request-body/read-json-stream/main.go#L44-L47)):


```sh
$ go get github.com/kataras/iris/v12@master
```

```go
var msg User
err := ctx.ReadJSON(&msg, iris.JSONReader{
	// To throw an error on unknown request payload json fields.
	DisallowUnknownFields: true,
})

if err != nil {
	ctx.StopWithError(iris.StatusBadRequest, err)
	return
}
	
// [...]
```

2. Use a struct validator for more advanced features (example [here](https://github.com/kataras/iris/blob/master/_examples/request-body/read-json-struct-validation/main.go))

**Comment by CulionBEAR** [comment]
okk！thanks！♥
