### ISSUE TITLE
small typo in wiki

### ISSUE THREAD

**Issue by Neulhan** [kataras/iris#1715]
Hi, I'm Neulhan, a developer who has adopted iris instead of gin and is working on a personal project!

I found a small typo while looking for iris' validation system in the project's wiki.

I was very impressed with your project, and I want to be of help even if it is small.

Here is a link,
[https://github.com/kataras/iris/wiki/Model-validation](https://github.com/kataras/iris/wiki/Model-validation)

and here is a screenshot
<img width="698" alt="2021-01-27 00 18 03" src="https://user-images.githubusercontent.com/52434903/105865937-c4221300-6036-11eb-8459-cdc5044f79e9.png">

 I hope it helps!

**Comment by kataras** [comment]
Hello @Neulhan, I am glad you choose Iris, you wont regret it. The typo was fixed thanks to you, funny that we have that part of code in 4 places but only the (v12.1.8) wiki page had the issue ^_^

If you just started with Iris it's better to get to look to the latest updates (v12.2.0-alpha2+) instead of the wiki pages (that are pointed to the stable version v12.1.8). The [_examples](https://github.com/kataras/iris/tree/master/_examples#table-of-contents) and the book (optional) helps a lot to learn everything you need to know, and by time you will get deeper and deeper to the Iris ecosystem. There is a [live chat](https://chat.iris-go.com) that you can ask questions and discuss with other developers as well. I am here to help in any way I can too!

**Comment by Neulhan** [comment]
I would like to thank you for your kind reply😄. I want to contribute to this project in the future. Until then, I'll use Iris as you advised me!
