### ISSUE TITLE
About the project path of the iris

### ISSUE THREAD

**Issue by dxvgef** [kataras/iris#174]
Iris of the middleware and the core are in the same project path, the compiler of the binary file is larger, this will reduce the performance of it?
Why not create a separate project for each middleware?

**Comment by kataras** [comment]
@dxvgef 
> the compiler of the binary file is larger

It's not larger because of middlewares or other folders. The total **source code of iris is ~700kb**, its large because of /net dependecies.

> this will reduce the performance of it

No the performance is the same even with a separate project repository, the runtime performance doesn't care about the length of the executable file.

> Why not create a separate project for each middleware

No reason to do so, this is the best option for this framework, users just need to look the folder and ` import path`.

**Comment by dxvgef** [comment]
@kataras Ok, thank you for the reply.

**Comment by kataras** [comment]
You're welcome, if you have any further questions just ask :) Thanks you for your interest !
