### ISSUE TITLE
Wildcards or named parameters on "root" route?

### ISSUE THREAD

**Issue by ryanlath** [kataras/iris#178]
These work:
iris.Get("/anything/*randomName", func(c *iris.Context) { } )
iris.Get("/anything/:param", func(c *iris.Context) { } )

These don't seem to:
iris.Get("/*randomName", func(c *iris.Context) { } )
iris.Get("/:param", func(c *iris.Context) { } )

Is this by design?  If yes, is there a way to emulate this behavior?

**Comment by kataras** [comment]
@ryanlath 

>These work:
iris.Get("/anything/*randomName", func(c *iris.Context) { } )
iris.Get("/anything/:param", func(c *iris.Context) { } )

Are you sure? if you go to /anything/something , which handler will fire? the first or the second?, the first example is not working, neither the second, it's by design for your own good :)

**Comment by kataras** [comment]
@ryanlath 

>These work:
iris.Get("/anything/*randomName", func(c *iris.Context) { } )
iris.Get("/anything/:param", func(c *iris.Context) { } )

Are you sure? if you go to /anything/something , which handler will fire? the first or the second?, the answer for the first example is ' not working as expected , neither the second'.

> Is this by design? If yes, is there a way to emulate this behavior?

Yes it's by design for your own good :) 

You can emulate that simple using:

```go
iris.Get("/*path", func(ctx *iris.Context){
    requestPath := ctx.Param("path")
    if requestPath =="something" {
          mySomethingHandler(ctx)
    } // else if requestPath ==....
})
//... 
func mySomethingHandler(ctx *iris.Context){
    ctx.Write("Hello from /something = %s", ctx.PathString())
}

```

Hope this helps you, although I'm not recommending doing /*param neither /:param at the root because the rest of your API will be useless.

**Comment by kataras** [comment]
@ryanlath 
>These work:
iris.Get("/anything/*randomName", func(c *iris.Context) { } )
iris.Get("/anything/:param", func(c *iris.Context) { } )

Are you sure? if you go to /anything/something , which handler will fire? the first or the second?, the answer for the first example is ' not working as expected , neither the second'.

> Is this by design? If yes, is there a way to emulate this behavior?

Yes it's by design for your own good :) 

You can emulate that simple using:

```go
iris.Get("/*path", func(ctx *iris.Context){
    requestPath := ctx.Param("path")
    if requestPath =="/something" {
          mySomethingHandler(ctx)
    } // else if requestPath ==....
})
//... 
func mySomethingHandler(ctx *iris.Context){
    ctx.Write("Hello from /something = %s", ctx.PathString())
}

```

Hope that helped, although I'm not recommending doing /*param neither /:param at the root because the rest of your API will be useless.
