### ISSUE TITLE
[BUG] One request is executed twice!

### ISSUE THREAD

**Issue by murongg** [kataras/iris#1828]
**Describe the bug**

When I use a reverse proxy on the web front end!
One request is executed twice!

**To Reproduce**
bug code
```go
package main

import (
	"fmt"

	"github.com/kataras/iris/v12"
)

func main() {
	app := iris.Default()

	app.Get("/other/someGet", func(ctx iris.Context) {
		fmt.Println("request happen")
		ctx.Writef("Hello!")
	})
	app.Listen(":8080")
}

```

the terminal log:
![image](https://user-images.githubusercontent.com/38655613/143524793-8676d0c0-2d80-445c-badf-fb9ff586bc6e.png)

**Expected behavior**
filter http options request
**Screenshots**
![image](https://user-images.githubusercontent.com/38655613/143524861-b39c2139-9917-4a0c-bb23-c02cf526590c.png)

**Desktop (please complete the following information):**
 - OS: MacOS 11.5.2

**iris.Version**
- latest

Please make sure the bug is reproducible over the `master` branch:

```sh
$ cd PROJECT
$ go get -u github.com/kataras/iris/v12@master
$ go run .
```

**Additional context**

**Comment by kataras** [comment]
Hello @murongg ,

The problem you're describing is probably caused by your HTTP client and not the server (Iris). If you're using a web browser to re-produce that, please check the development tools and watch what your web browser is doing. The best way to test it though it's through Postman, please see below (1 request, not twice):

![image](https://user-images.githubusercontent.com/22900943/147824712-dcc34002-1926-4eed-b99e-bd15d8986014.png)
