### ISSUE TITLE
Why flash data stored in cookie?

### ISSUE THREAD

**Issue by dxvgef** [kataras/iris#186]
I want to use Flash in the service side of a one-time data transfer, but now flash data stored in a cookie, so unsafe, why not stored in the service side of it? Or Iris offers other solutions?

**Comment by qskousen** [comment]
@dxvgef flash is stored in cookie (and always has been) because it is faster than storing in session, if you have a busy app with a lot of flash messages it can make a big difference. Also note that the flash value is encrypted in the cookie, so it is pretty secure anyways.

@kataras is willing to make an option to store flash in session if you think it is important. A configuration option like `Config.Sessions.Flash = true` to enable storing flash values in session instead of cookie. Of course, the session variable is stored in a cookie as well, the same as every framework does it, so it will be slower for not much security gain. You probably should not be putting anything too sensitive in a flash message anyways.
