### ISSUE TITLE
Is there an easy way to identify / register request payload types to route handlers.

### ISSUE THREAD

**Issue by opusmagna** [kataras/iris#1867]
More of a question rather than reporting an issue.

I would like to implement a single request validator middleware either using gRPC or regular net/http server.

So I am curious if there is a way to identify or register the request payload struct to route handlers in an optimal way so that in a single middleware, the request payloads can be validated.

I did not follow any approach in regular route(party)/handler approach but with gRPC/mvc, I tried using protoc-gen-validate in conjunction with gRPC interceptors but could not reach anywhere. 

If with route(party)/handler approach then with I would go with go-playground/validator. 

Thank you in advance. In our community I trust!

**Comment by kataras** [comment]
Hello @opusmagna, sorry for the delay.

You want a single point of request validation, why does a middleware can't do the job? We have the `iris.Application.Validator` which you can register any compatible (or custom) validator any time server is reading JSON objects when `iris.Context.ReadJSON` is called. Example can be found [here](https://github.com/kataras/iris/blob/master/_examples/request-body/read-json-struct-validation/main.go#L19).

If it's not trouble for you I would like to learn more about the `protoc-gen-validate` method you tried to use. Can you open a personal repository with an example of that (please include a README on how to run it as well) so I can see what I can do in order to integrate it within Iris in a more builtin way?

Thanks!

**Comment by opusmagna** [comment]
Thank you for your response @kataras .

The example you provided with your written explanation makes the situation clearer for me, thanks again.

I will definitely prepare you a public repo for the gRPC gateway example in conjunction with `protoc-gen-validate` implementation with a proposal as soon as possible.

**Comment by kataras** [comment]
Thanks @opusmagna, do we have any news regarding your example?
