### ISSUE TITLE
[INVALID] v12 ratelimit example error

### ISSUE THREAD

**Issue by TimLiuDream** [kataras/iris#1879]
**Describe the bug**
The v12 ratelimie example import is error.
cannot found 

**To Reproduce**
`
cd _examples/request-ratelimit
go mod init
go mod tidy
`

**Expected behavior**
go: finding module for package github.com/kataras/iris/v12/middleware/rate
github.com/kataras/iris/_examples/request-ratelimit imports
        github.com/kataras/iris/v12/middleware/rate: module github.com/kataras/iris/v12@latest found (v12.1.8), but does not contain package github.com/kataras/iris/v12/middleware/rate

**Desktop (please complete the following information):**
 - OS: macos

**iris.Version**
- e.g. v12

**Comment by kataras** [comment]
Hello @TimLiuDream,

It's working fine, you just need to run the example under the iris directory, otherwise you must manually initialize a go.mod file and import the @master version of v12. See:


<img width="1512" alt="image" src="https://user-images.githubusercontent.com/22900943/166099488-21060d37-e47a-4b88-b8db-289828cd4763.png">

Run it with manual go.mod:

```
$ go mod init ratelimit-example
$ go get github.com/kataras/iris/v12@master
$ go run main.go
```
