### ISSUE TITLE
[BUG]URLParam can only parse the arguments between '/'

### ISSUE THREAD

**Issue by zyxkad** [kataras/iris#1893]
**Describe the bug**
I have a route like that
```txt
/v0
|- /ping
|- /0x{id: string} # or hex int, that's doesn't matter
```
And I'm trying to define the url param:
```golang
root.PartyFunc("0", func(group iris.Party){
  group.Get("/ping", func(ctx iris.Context){
    ctx.JSON(iris.Map{
	"status": "ok",
	"version": VERSION,
    })
  })
  group.Get("/0x{id:string}", func(ctx iris.Context){
    id := ctx.URLParam("id")
    ctx.JSON(iris.Map{
	"status": "ok",
	"id:": id,
    })
  })
})
```
And when I getting `/0/0x00`, the result is *404 Not Found*
```bash
$ curl -v http://127.0.0.1:25580/0/0x00; echo
*   Trying 127.0.0.1:25580...
* Connected to 127.0.0.1 (127.0.0.1) port 25580 (#0)
> GET /0/0x00 HTTP/1.1
> Host: 127.0.0.1:25580
> User-Agent: curl/7.77.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Date: Mon, 23 May 2022 21:07:53 GMT
< Content-Length: 9
< Content-Type: text/plain; charset=utf-8
< 
* Connection #0 to host 127.0.0.1 left intact
Not Found
```

**To Reproduce**
See before

**Expected behavior**
When I visiting `/0/0x00`, It will return `{"status":"ok", "id": "00"}`

**Screenshots**

**Desktop (please complete the following information):**
 - OS: go version go1.17.9 darwin/arm64

**iris.Version**
- v12.2.0-beta2.0.20220523084343-eeb7c67bc148

Please make sure the bug is reproducible over the `master` branch:

```sh
$ cd PROJECT
$ go get -u github.com/kataras/iris/v12@master
$ go run .
```

**Additional context**
I can fix it if I use `/0/0x/{id:string}`, but it's really ugly, and that's not what I want

**Comment by kataras** [comment]
Hello @zyxkad, 

Please read the documentation and/or examples carefully. The `ctx.URLParam` method retrieves the URL Query (e.g. `"/path/?id=1"`). The `ctx.Params().Get` is the method you need to retrieve dynamic path parameters.

And of course path parameters work between `/` with the exception of `{path}` type  which works as a wildcard. 

The `"/0x{id:string}"` route is not going to work, `/0x/{id:string}` will and it has nothing to do with hex or no hex, it's not a bug either, it's how this feature works and it should not give you the option for the opposite. API design is very important thing.

The `app.Get("/{id:string}", h)` will work but hex `#` is an exception because this part of the URL is called the "fragment identifier". The fragment identifier can only be processed by client-side JavaScript. Read more at: https://en.wikipedia.org/wiki/URI_fragment.

![image](https://user-images.githubusercontent.com/22900943/169914594-c8aa9608-ff38-4369-bfa9-fc51e23ac847.png)

**Comment by kataras** [comment]
Hello @zyxkad, 

Please read the documentation and/or examples carefully. The `ctx.URLParam` method retrieves the URL Query (e.g. `"/path/?id=1"`). The `ctx.Params().Get` is the method you need to retrieve dynamic path parameters.

And of course path parameters work between `/` with the exception of `{path}` type  which works as a wildcard. 

The `"/0x{id:string}"` route is not going to work, `/0x/{id:string}` will and it has nothing to do with hex or no hex, it's not a bug either, it's how this feature works and it should not give you the option for the opposite. API design is very important thing.

The `app.Get("/{id:string}", h)` will work but `#` character is an exception because this part of the URL is called the "fragment identifier". The fragment identifier can only be processed by client-side JavaScript. Read more at: https://en.wikipedia.org/wiki/URI_fragment.

![image](https://user-images.githubusercontent.com/22900943/169914594-c8aa9608-ff38-4369-bfa9-fc51e23ac847.png)

**Comment by zyxkad** [comment]
Thanks for help, I found I can use `/{id:string regexp(^0x[0-9a-f]+)}` to resolve it

And yeah, I need use `Params()` not `URLParam`

**Comment by kataras** [comment]
Yes, nice one @zyxkad !
