### ISSUE TITLE
[BUG]json: cannot unmarshal array into Go value of type neffos.NSConn

### ISSUE THREAD

**Issue by lczxhf** [kataras/iris#1907]
**Describe the bug**
In the example ->  vuejs-todo-mvc. 
If i  request the route(POST: /todos). and then response is "json: cannot unmarshal array into Go value of type neffos.NSConn"

**Expected behavior**
If the arguments of method Post is []todo.Item , and submit a json [{"id":1,"title":"asd","completed":false}] then the bug occur.
If the arguments of method Post is empty , and submit a json [{"id":1,"title":"asd","completed":false}] then the bug occur.
if the arguments change to todo.item , and submit a json {"id":1,"title":"asd","completed":false} then the result is ok.

and the bug occur on that controller includes websocket,  if is a normal mvc controller. it fine

**Screenshots**
![WX20220611-121021](https://user-images.githubusercontent.com/10428809/173172041-b8340bd7-2da4-43a3-b0e5-b1e97385e146.png)
![WX20220611-121045](https://user-images.githubusercontent.com/10428809/173172045-fb1912e2-c8a1-4e11-84bf-254ebce862a0.png)

![WX20220611-120209](https://user-images.githubusercontent.com/10428809/173171798-63f9ced9-3b22-4b2e-aaaf-89fcbda525e7.png)

**Desktop (please complete the following information):**
 - OS: mac

**iris.Version**
- v12.2.0-beta3

**Comment by kataras** [comment]
Hello @lczxhf, that's because the `NSConn` **field is set as "stateless"**, the [example](https://github.com/kataras/iris/blob/master/_examples/mvc/vuejs-todo-mvc/src/web/controllers/todo_controller.go#L18) **does not mark this field as stateleless**. Stateless tag value will make the controller to always trying to read from request when the method is POST and binds the stateless field.

Your issue does not occur if you send just a JSON object because it successfully binds it to NSConn, even if no fields are matched. The issue occurs if you send an array because it tries to bind the json array of objects to a single Go structure (NSConn) which leads to a standard json unmarshal error.

**Comment by kataras** [comment]
Hello @lczxhf, that's because the `NSConn` **field is set as "stateless"**, the [example](https://github.com/kataras/iris/blob/master/_examples/mvc/vuejs-todo-mvc/src/web/controllers/todo_controller.go#L18) **does not mark this field as "stateless"**. Stateless tag value will make the controller to always trying to read from request when the method is POST and binds the stateless field.

Your issue does not occur if you send just a JSON object because it successfully binds it to NSConn, even if no fields are matched. The issue occurs if you send an array because it tries to bind the json array of objects to a single Go structure (NSConn) which leads to a standard json unmarshal error.

**Comment by lczxhf** [comment]
> 

Thank you.
But even if i remove the "stateless" tag. It still have the same response (json: cannot unmarshal array into Go value of type neffos.NSConn)

**Comment by kataras** [comment]
Hello @lczxhf,

The example is running without the `stateless` tag, but anyways, try to split the websocket logic and classic request-response API controllers.

**Comment by lczxhf** [comment]
Thank You.

**Comment by kataras** [comment]
You're welcome @lczxhf
