### ISSUE TITLE
[BUG]Bugs while posting empty data array

### ISSUE THREAD

**Issue by waaadreamer** [kataras/iris#1910]
Hello!
I met a bug when posted an empty data (empty json) to the Go Iris server.
I found that PostValueInt function wouldn't return any error so that this argument can be any string and PostValueIntDefault function counldn't process properly, either.

After looking up the source code I discovered that PostValues function wouldn't return any error, too.
This is a serious security problem that some hackers may submit empty post to attack the server.
Can you give me some suggestions or ways to solve this problem? Thanks!

**Comment by kataras** [comment]
Hello @waaadreamer,

There is an error on empty form, but you have to enable a setting it in order to receive it (because most people don't want this), does the [FireEmptyFormError bool](https://github.com/kataras/iris/blob/9dc356c1d813821b3ce2970c51ba0707ae828e28/configuration.go#L781) setting suit you?

**Comment by kataras** [comment]
Hello @waaadreamer,

There is an error on empty form, but you have to enable a setting it in order to receive it (because most people don't want this), does the [FireEmptyFormError bool](https://github.com/kataras/iris/blob/9dc356c1d813821b3ce2970c51ba0707ae828e28/configuration.go#L781) setting suit you?

If you are referring about `ctx.PostValues`, there the method returns an array, you can check its length `len(values)` for empty data.
