### ISSUE TITLE
[QUESTION] It's possible to feed YAML configuration file from environment variables?

### ISSUE THREAD

**Issue by racastellanosm** [kataras/iris#2050]
I was wondering if this is possible to feed YAML with env vars, for example:

````yaml
Application:
    Name: '%%ENV:APPLICATION_NAME:default_value%%'
````

 Maybe if isn't  possible at time, can we ask for this feature and maybe contribute to build it?

Thanks, this is a great framework to work with.

**Comment by kataras** [comment]
Hello @racastellanosm,

YAML encoding and decoding is based on the [go-yaml/yaml](https://github.com/go-yaml/yaml) project. That's a great idea for them to work on, and you can contribute too!

We can't do anything from our side because you may have an integer or an array of integers that depend on env variable, and parsing from string (%%...%%) to integer wouldn't possible so we can't catch it from the configuration field value itself and fetch from the environment variables to match it against.

**Comment by kataras** [comment]
You can also check: https://github.com/kelseyhightower/envconfig

**Comment by racastellanosm** [comment]
Thanks for your answer @kataras 

You're a right, maybe i would apply a layer above (struct) the iris configuration to mix "my-application-related" configuration parameters (database, app related parameters, etc) and the Iris-Related configuration (host, port, etc)

I would add a YAML with iris and custom configuration parameters, apply a `os.ExpandEnv(str)` to the YAML and then pass to the struct and finally consume in the server/application initialization.

Thanks again for your faster response. 
I'll close this issue if you're agree.

**Comment by kataras** [comment]
Exactly @racastellanosm, good job!

You are welcomed anytime! And of course, It's ok to close it if you want

**Comment by kataras** [comment]
Exactly @racastellanosm, good job!

You are welcome anytime! And of course, It's ok to close it if you want
