### ISSUE TITLE
Could not get Iris caused by China golang.org/x/oauth2

### ISSUE THREAD

**Issue by dxvgef** [kataras/iris#212]
Iris just joined OAuth2 features, it imported `'golang.org/x/oauth2'` package, but I can not connect to golang.org in China, I try to use the `go get github.com/kataras/iris` or `go get -u github.com/kataras/iris` command to update the Iris, but an error occurred:
```
package golang.org/x/oauth2: unrecognized import path "golang.org/x/oauth2" (https fetch: Get https://golang.org/x/oauth2?go-get=1: dial tcp 216.58.203.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)
package github.com/kataras/iris/server: cannot find package "github.com/kataras/iris/server" in any of:
```

Maybe you can try using `github.com/golang/oauth2` to replace `golang.org/x/oauth2`?

**Comment by kataras** [comment]
Hello @dxvgef I edited your title to be more specific,

- Already, answered you to this problem before some days,
- The README also has a link which helps users from China to download `golang.org/x/` packages. 
- The gitbook also has a section of this [here](https://kataras.gitbooks.io/iris/content/install.html)
- this is not Iris' problem it's a general problem to all libraries.

> Maybe you can try using github.com/golang/oauth2 to replace golang.org/x/oauth2?

None of mine packages uses x/oauth2 but the packages iris imports uses that, and if they can't change to github.com/golang/oauth2  because of line 8 of the auth2.go https://github.com/golang/oauth2/blob/master/oauth2.go#L8 . 
 
> package github.com/kataras/iris/server: cannot find package "github.com/kataras/iris/server" 

This because the server package is moved to the http.go file, from the beggining of the 3.0.0-rc.1. Remove your $GOPATH/src/github.com/kataras/iris and try to install again.

**Comment by kataras** [comment]
Hello @dxvgef I edited your title to be more specific,

- Already, answered you to this problem before some days,
- The README also has a link which helps users from China to download `golang.org/x/` packages. 
- The gitbook also has a section of this [here](https://kataras.gitbooks.io/iris/content/install.html)
- this is not Iris' problem it's a general problem to all libraries.

> Maybe you can try using github.com/golang/oauth2 to replace golang.org/x/oauth2?

Iris doesn't imports x/oauth2 directly, but the package iris imports to do the oauth2 uses that, and can't be changed to github.com/golang/oauth2  because of line 8 of the auth2.go https://github.com/golang/oauth2/blob/master/oauth2.go#L8 . 
 
> package github.com/kataras/iris/server: cannot find package "github.com/kataras/iris/server" 

This because the server package is moved to the http.go file, from the beggining of the 3.0.0-rc.1. Remove your $GOPATH/src/github.com/kataras/iris and try to install again.

**Comment by kataras** [comment]
Hello @dxvgef I edited your title to be more specific,

- Already, answered you to this problem before some days,
- The README also has a link which helps users from China to download `golang.org/x/` packages. 
- The gitbook also has a section of this [here](https://kataras.gitbooks.io/iris/content/install.html)
- this is not Iris' problem it's a general problem to all libraries.

> Maybe you can try using github.com/golang/oauth2 to replace golang.org/x/oauth2?

Iris doesn't imports x/oauth2 directly, but the package iris imports to do the oauth2 uses that, and can't be changed to github.com/golang/oauth2  because of line 8 of the auth2.go https://github.com/golang/oauth2/blob/master/oauth2.go#L8 . 
 
> package github.com/kataras/iris/server: cannot find package "github.com/kataras/iris/server" 

This because the server package is moved to the http.go file, before 2 versions. Remove your $GOPATH/src/github.com/kataras/iris and try to install again.

**Comment by dxvgef** [comment]
Thank you. I'll try.

**Comment by kataras** [comment]
You're welcome, try googling it you will find an answer faster than my english :P

**Comment by kataras** [comment]
You're welcome, however, if you cannot fix it, try google it you will find better answer than my english :P

**Comment by dxvgef** [comment]
Access to Google in China is also very difficult :(

**Comment by kataras** [comment]
Oh sorry, you 're right, then read the section, noone else had problem with that before, and more of the 50% of iris' stars are came from China !

**Comment by dxvgef** [comment]
Yes, many people use Go language in China, we are discussing Echo and Iris and Beego, I'm Iris supporter, but I envy the stability of Echo, Because when each update Iris, my code will not work, a lot of people because of this problem to choose Echo used in the production environment.

**Comment by dxvgef** [comment]
Αυτό το πρόβλημα έχει λυθεί: p
