### ISSUE TITLE
Why HandleError can not catch the panic 

### ISSUE THREAD

**Issue by xieyj-apple** [kataras/iris#2121]
i want to define a global ErrorHandle Func, but i find that the panic error could not catched by my HandleError func

func main() {
	// ...
	app = iris.New()
	Mvc := mvc.New(app.Party('5tttt'))
	Mvc.Handle(new(DebugController))
	Mvc.HandleError(func(ctx iris.Context, err error){
     //...
      })
	// ...
}

// DebugController.go
type DebugController struct {
	
}

func (c *DebugController) PostTest(ctx iris.Context) mvc.Result {
	if ctx.FormValue("action") == "clear" {
		panic("123")
	}
	return nil
}

**Comment by kataras** [comment]
Hello @xieyj-apple,

`mvc.Application.HandleError` does not catch panics, because the http server does this for you. And if you want to catch a panic errors, please use/borrow the `middleware/recover` package. Or you can register a middleware and catch it, you can check the controller that panic-ed using the `ctx.Controller() reflect.Value` method as well.

```go
	app.UseRouter(func(ctx iris.Context) {
		defer func() {
			if err := recover(); err != nil {
				if ctx.IsStopped() { // handled by other middleware.
					return
				}

				if ctrl := ctx.Controller(); ctrl.IsValid() {
					// panic-ed from a controller's method.
					// do something here...
				}
				// do something here...
			}
		}()

		ctx.Next()
	})
```

**Comment by kataras** [comment]
Hello @xieyj-apple,

`mvc.Application.HandleError` does not catch panics, because the http server does this for you. And if you want to customize how to handle panic errors, please use/borrow the `middleware/recover` package; you can register a middleware and catch it, you can check the controller that panic-ed using the `ctx.Controller() reflect.Value` method as well.

```go
	app.UseRouter(func(ctx iris.Context) {
		defer func() {
			if err := recover(); err != nil {
				if ctx.IsStopped() { // handled by other middleware.
					return
				}

				if ctrl := ctx.Controller(); ctrl.IsValid() {
					// panic-ed from a controller's method.
					// do something here...
				}
				// do something here...
			}
		}()

		ctx.Next()
	})
```
