### ISSUE TITLE
[QUESTION] How to change the pool's return value Context，if I use v12.2.0

### ISSUE THREAD

**Issue by yezhibin** [kataras/iris#2122]
After the function named attach is removed from context/pool.go，How to change the pool's return value Context，if I use v12.2.0？

// Attach changes the pool's return value Context.
//
// The new Context should explicitly define the `Next()`
// and `Do(context.Handlers)` functions.
//
// Example: https://github.com/kataras/iris/blob/master/_examples/routing/custom-context/method-overriding/main.go
func (c *Pool) Attach(newFunc func() Context) {
}

**Comment by kataras** [comment]
Hello @yezhibin,

You cannot modify the context's pool anymore. The code comment you specify is from previous Iris versions. You cannot modify the context's pool anymore because in go 1.8 I saw a performance cost while using it, so I removed the ability. You have other ways to customize the response body, you may want to take a look at `iris.Patches().Context().Writers().` or use a base controller (if you are into MVC) or your own utility package(s).

**Comment by yezhibin** [comment]
> Hello @yezhibin,
> 
> You cannot modify the context's pool anymore. The code comment you specify is from previous Iris versions. You cannot modify the context's pool anymore because in go 1.8 I saw a performance cost while using it, so I removed the ability. You have other ways to customize the response body, you may want to take a look at `iris.Patches().Context().Writers().` or use a base controller (if you are into MVC) or your own utility package(s).

I'll try it，thank you very much.

**Comment by yezhibin** [comment]
> Hello @yezhibin,
> 
> You cannot modify the context's pool anymore. The code comment you specify is from previous Iris versions. You cannot modify the context's pool anymore because in go 1.8 I saw a performance cost while using it, so I removed the ability. You have other ways to customize the response body, you may want to take a look at `iris.Patches().Context().Writers().` or use a base controller (if you are into MVC) or your own utility package(s).

I'll try it，thank you very much.
