### ISSUE TITLE
Map key garbled

### ISSUE THREAD

**Issue by garyadamshannon** [kataras/iris#213]
The code below will produce garbled map key results (even when mutex locked):

```
package main

import (
        "github.com/davecgh/go-spew/spew"
        "strconv"
        "github.com/kataras/iris"
)

var listenHost string = "0.0.0.0"
var listenPort int = 8085
var cachedQueries = make(map[string]string)

func main() {
        // This will already be handled by a connection pool, so don't need to create a goroutine.
        iris.Get("/search/:test", func(c *iris.Context) {
                query := c.Param("test")
                spew.Dump(cachedQueries)
                cachedQueries[query] = "test"
                spew.Dump(cachedQueries)
                c.JSON(200, iris.Map{"Status": "Success"})
        })
        iris.Listen(listenHost + ":" + strconv.Itoa(listenPort))
}
```

The "fixed" code below will produce accurate map key results:

```
package main

import (
        "github.com/davecgh/go-spew/spew"
        "strconv"
        "github.com/kataras/iris"
)

var listenHost string = "0.0.0.0"
var listenPort int = 8085
var cachedQueries = make(map[string]string)

func main() {
        // This will already be handled by a connection pool, so don't need to create a goroutine.
        iris.Get("/search/:test", func(c *iris.Context) {
                query := c.Param("test")
                query = string([]byte(query))  
                spew.Dump(cachedQueries)
                cachedQueries[query] = "test"
                spew.Dump(cachedQueries)
                c.JSON(200, iris.Map{"Status": "Success"})
        })
        iris.Listen(listenHost + ":" + strconv.Itoa(listenPort))
}
```

The only difference here is:

`query = string([]byte(query))  `

If you inspect c.Param("test") at any point it produces an accurate result, it does not work when used in a map key however.

string([]byte(c.Param("test")) does work.

Example of bad output:
```
(map[string]string) (len=5) {
 (string) (len=6) "String": (string) (len=4) "test",
 (string) (len=9) "Stringier": (string) (len=4) "test",
 (string) (len=9) "Stringier": (string) (len=4) "test",
 (string) (len=19) "Notsuchabadstringre": <invalid>,
(string) (len=17) "Notsuchabadstring": (string) (len=4) "test"     
```

Tested using:

```
#!/bin/perl

$ENDPOINT = 'http://localhost:8085/search';

my @meetings = qw(String Stringies Stringier Otherlongstringhere Notsuchabadstring);
while($meeting = shift(@meetings)){
        print `curl $ENDPOINT/$meeting`;
}    
```
What is going on here?

**Comment by garyadamshannon** [comment]
For comparison, mux does not have this issue:

```
package main

import (
        "github.com/davecgh/go-spew/spew"
        "net/http"

        "github.com/gorilla/mux"
)

var listenHost string = "0.0.0.0"
var listenPort int = 8085
var cachedQueries = make(map[string]string)

func Handler(w http.ResponseWriter, r *http.Request) {
        vars := mux.Vars(r)
        query := vars["test"]
        spew.Dump(cachedQueries)
        cachedQueries[query] = "test"
        spew.Dump(cachedQueries)
}

func main() {
        // This will already be handled by a connection pool, so don't need to create a goroutine.
        r := mux.NewRouter()
        r.HandleFunc("/search/{test}", Handler).Methods("GET")
        http.Handle("/", r)
        http.ListenAndServe(":8085", nil)
}   
```

**Comment by kataras** [comment]
Hello @garyadamshannon , I am working to improve iris even more, right now. You're the first having an issue inside context.Param, I will look that later.

> Please star Iris if you like it

**Comment by kataras** [comment]
Hello @garyadamshannon , thanks for the question, I already knew this, this is the way things works with context's named parameters, your use-case is useless because you can just take all params with **` context.Params`** and save them anywhere you want with the **`copy`**  method and your example will work without need to convert anything.

If you take a look at the `http.go` file you will understand what's happening, if not try searching on google (it's a general golang question), my english are not the best to explain or write you a tutorial about these type of things, I'm sorry.

**Comment by kataras** [comment]
Hello @garyadamshannon , thanks for the question, I already knew this, this is a normal behavior for the context's named parameters, your use-case is useless because you can just take all params with **` context.Params`** and save them anywhere you want with the **`copy`**  method and your example will work without need to convert anything.

**Comment by kataras** [comment]
Hello @garyadamshannon , thanks for the question, I already knew this, this is a normal behavior for golang(search on google for tutorials) for the context's named parameters, your use-case is useless because you can just take all params with **` context.Params`** and save them anywhere you want with the **`copy`**  method and your example will work without need to convert anything.

**Comment by kataras** [comment]
Hello @garyadamshannon , thanks for the question, I already knew this, this is a normal behavior for the context's named parameters(` http.go file` ), your use-case is useless because you can just take all params with **` context.Params`** and save them anywhere you want with the **`copy`**  method and your example will work without need to convert anything.

**Comment by kataras** [comment]
Hello @garyadamshannon , thanks for the comment, this is a normal behavior for the context's named parameters(Read the ` http.go file` and you will understand why this happens, it's general golang's behavior). Just take all params with **` context.Params`** and save them anywhere you want with the **`copy`** standard method.

I saw that you made a comparison in the same time you even didn't star Iris, this is not good my man, 
If you don't like how Iris works, its totally fine, you can use other web framework, like your showcase( the gorilla's mux), hope you good luck with its performance & features.
