### ISSUE TITLE
mvc.Register and App.RegisterDependency

### ISSUE THREAD

**Issue by xieyj-apple** [kataras/iris#2158]
what diference between   mvc.Register and  App.RegisterDependency

```
App = iris.New()
App.RegisterDependency(xx)

_party := App .Party("/test")
mvc := mvc.New(_party)
mvc.Register(xxx)
```

**Comment by xieyj-apple** [comment]
controllerA ->  serviceB -> serviceC

when i use
 App.RegisterDependency(new(serviceB))
 App.RegisterDependency(new(serviceC))

result :B.C is empty

**Comment by kataras** [comment]
The only difference is that `app.RegisterDependency` registers one or more dependencies to all of the `mvc.New` apps coming after that, so you don't need to call `mvc.Register` on each of your controller group. I don't understand the `B.C is empty` thing, please post a re-producable go code snippet for these cases so we can give you a more specific answer to your question. Thanks @xieyj-apple

**Comment by xieyj-apple** [comment]
```

type A struct {
	b B
}

type B struct {
	c C
}

type C struct {
	Name string
}

func newC() *C {
	return &C{Name: "4234"}
}

type TestController struct {
	a A
}

func (h *TestController) Get(ctx iris.Context) {
	fmt.Println("h say hello...", h.a.b.c.Name)
}

func main() {
	IrisApp := iris.New()
	IrisApp.RegisterDependency(newC)
	IrisApp.RegisterDependency(new(B))
	IrisApp.RegisterDependency(new(A))

	_party := IrisApp.Party("test")
	irisMvc := mvc.New(_party)
	irisMvc.Handle(new(TestController))
	if err := IrisApp.Listen("0.0.0.0:9988"); err != nil {
		_ = IrisApp.Shutdown(context.Background())
	}
}

```

when i visit  http://localhost:9988/test   it print : "h say hello..."  not "h say hello...4234"     why?

**Comment by kataras** [comment]
@xieyj-apple  Because `TestController.a` is un-exported/private field and reflect has no access over it, so it can't set the `newC->new(A)` to the `TestController.a` dependency.

**Comment by xieyj-apple** [comment]
like this?  it not work
```

type A struct {
	B B
}

type B struct {
	C C
}

type C struct {
	Name string
}

func newC() *C {
	return &C{Name: "4234"}
}

type TestController struct {
	A A
}

func (h *TestController) Get(ctx iris.Context) {
	fmt.Println("h say hello...", h.A.B.C.Name)
}

func main() {
	IrisApp := iris.New()
	IrisApp.RegisterDependency(newC)
	IrisApp.RegisterDependency(new(B))
	IrisApp.RegisterDependency(new(A))

	_party := IrisApp.Party("test")
	irisMvc := mvc.New(_party)
	irisMvc.Handle(new(TestController))
	if err := IrisApp.Listen("0.0.0.0:9988"); err != nil {
		_ = IrisApp.Shutdown(context.Background())
	}
}
```

**Comment by kataras** [comment]
Fixed @xieyj-apple :)

**Comment by xieyj-apple** [comment]
had  new tag or version to  fixed it?

**Comment by kataras** [comment]
Hello @xieyj-apple, I wasn't sure about the stability of this change that's why I didn't move it to a release until today. Many apps will be broken if we change the default behavior like that. That's why I've added the `app.ConfigureContainer().EnableStructDependents()` and `mvc.Application.EnableStructDependents()` methods, you have to call this first in order for struct fields to be automatically binded based on previous dependencies that are structs. Here's a complete and working example:

```go
package main

import (
	"fmt"

	"github.com/kataras/iris/v12"
	"github.com/kataras/iris/v12/mvc"
)

type A struct {
	B *B
}

type B struct {
	C *C
}

type C struct {
	Name string
}

func newC() *C {
	return &C{Name: "4234"}
}

type TestController struct {
	A *A
}

func (h *TestController) Get(ctx iris.Context) {
	fmt.Println("h say hello...", h.A.B.C.Name)
}

func main() {
	app := iris.New()
	app.Logger().SetLevel("debug")

	app.ConfigureContainer().EnableStructDependents()
	app.RegisterDependency(newC())
	app.RegisterDependency(new(B))
	app.RegisterDependency(new(A))

	testAPI := app.Party("/test")
	m := mvc.New(testAPI)
	// OR
	// m.EnableStructDependents()
	// m.Register(newC())
	// m.Register(new(B))
	// m.Register(new(A))
	m.Handle(new(TestController))
	app.Listen(":8080")
}
```

The latest release tag is `[v12.2.1](https://github.com/kataras/iris/releases/tag/v12.2.1)`

**Comment by kataras** [comment]
Hello @xieyj-apple, I wasn't sure about the stability of this change that's why I didn't publish a new release, until today. Many apps would be broken if we change the default behavior like that. That's why I've added the `app.ConfigureContainer().EnableStructDependents()` and `mvc.Application.EnableStructDependents()` methods, you have to call this first in order for struct fields to be automatically binded based on previous dependencies that are structs. Here's a complete and working example:

```go
package main

import (
	"fmt"

	"github.com/kataras/iris/v12"
	"github.com/kataras/iris/v12/mvc"
)

type A struct {
	B *B
}

type B struct {
	C *C
}

type C struct {
	Name string
}

func newC() *C {
	return &C{Name: "4234"}
}

type TestController struct {
	A *A
}

func (h *TestController) Get(ctx iris.Context) {
	fmt.Println("h say hello...", h.A.B.C.Name)
}

func main() {
	app := iris.New()
	app.Logger().SetLevel("debug")

	app.ConfigureContainer().EnableStructDependents()
	app.RegisterDependency(newC())
	app.RegisterDependency(new(B))
	app.RegisterDependency(new(A))

	testAPI := app.Party("/test")
	m := mvc.New(testAPI)
	// OR
	// m.EnableStructDependents()
	// m.Register(newC())
	// m.Register(new(B))
	// m.Register(new(A))
	m.Handle(new(TestController))
	app.Listen(":8080")
}
```

The latest release tag is [v12.2.1](https://github.com/kataras/iris/releases/tag/v12.2.1)
