### ISSUE TITLE
CORS issue with local host

### ISSUE THREAD

**Issue by efealatan** [kataras/iris#218]
Hello,

i am trying to use the cors to use with local development as i am using node to serve the web app and am using iris as the api server and when i try and set the default or

 crs := cors.New(cors.Options{
            AllowedOrigins: []string{"http://localhost:8090"},
            Debug: true,
        })
    iris.Use(crs) 

the browser still gives cors error

any help would be appreciated

**Comment by kataras** [comment]
Hello @efealatan try to do ` iris.Any` instead of ` iris.Get` to register your routes and tell me if that fixes the issue

**Comment by kataras** [comment]
Hello @efealatan try to do ` iris.Any` instead of ` iris.Get` to register your routes and tell me if that fixes the issue.

> Star iris if you liked it!

**Comment by efealatan** [comment]
@kataras i tried it but it still not working

**Comment by kataras** [comment]
Preflight is for 'OPTIONS' with ` iris.Any` you should be ok.. I will look at this

**Comment by dustinblackman** [comment]
@kataras Is this issue really considered closed? The issue is still currently happening with your latest release (3.0.0-pre.release).  Setting the http verb to `Any` makes it more difficult to handle things such as 404s when the wrong verb is used against an endpoint. The temp solution is having to do `iris.Options` for every endpoint, when it sounds like every method should be registering `Options` as well automatically.

**Comment by kataras** [comment]
@dustinblackman Last release is v3.0.0, Cors is auto-checked now, no need for `iris.Any`

> Don't forget to star iris, if you liked it :)
