### ISSUE TITLE
[BUG] When I upgrade from v12.1.8 to v12.2.5, session writing becomes not work

### ISSUE THREAD

**Issue by conero** [kataras/iris#2196]
**Describe the bug**
When I upgrade from v12.1.8 to v12.2.5, session writing becomes not work.

**To Reproduce**

link: **https://github.com/conero/iris_bug_2196**

```go
// main.go
package main

import (
	"github.com/kataras/iris/v12"
	"github.com/kataras/iris/v12/sessions"
)

func main() {

	app := iris.New()
	//app.Use(iris.Compression)
	const sxKey = "jkkkkl"

	sess := sessions.New(sessions.Config{
		Cookie: "test-jc",
		// CookieSecureTLS: true,
		Expires:      -1,
		AllowReclaim: true,
	})

	app.Use(sess.Handler())
	app.Get("/", func(ctx iris.Context) {
		ctx.HTML("Hello <strong>%s</strong>!", "World")
	})

	//session
	app.Get("/add", func(ctx iris.Context) {
		sx := sessions.Get(ctx)

		count, _ := sx.GetInt64(sxKey)

		sx.Set(sxKey, count+1)
		ctx.JSON(map[string]any{
			"type": "set",
			"count": count,
		})
	})

	//
	app.Get("/get", func(ctx iris.Context) {
		sx := sessions.Get(ctx)

		count, _ := sx.GetInt64(sxKey)
		ctx.JSON(map[string]any{
			"type": "get",
			"count": count,
		})
	})

	app.Listen(":8081")

}

Using a browser to access addresses(`http://127.0.0.1:8081/add`), session accumulation not work.

```

**Expected behavior**
Using a browser to access addresses(`http://127.0.0.1:8081/add`), session accumulation work.

**Screenshots**

**Desktop (please complete the following information):**
 - windows

**iris.Version**
- v12.2.5

Please make sure the bug is reproducible over the `master` branch:

```sh
$ cd PROJECT
$ go get -u github.com/kataras/iris/v12@main
$ go run .
```
The anomaly is still present

**Comment by kataras** [comment]
Hello @conero, 

I have to investigate it, thanks for the issue. WIll come back soon with an answer!

**Comment by conero** [comment]
@kataras Thank for thak, I push code to url for it. https://github.com/conero/iris_bug_2196

**Comment by kataras** [comment]
Hello @conero, although '127.0.0.1' it's not a real domain and will not be used in production, let me explain, by-default Iris is sharing the cookie with all domain's subdomains (for 127.0.0.1 that's the localhost, that's why your code runs perfectly on localhost:8081 but not on 127.0.0.1:8081). 

1. https://github.com/kataras/iris/blob/24ba4e8933b9d58096a56e5c6f2de968f80eb602/sessions/sessions.go#L36
2. https://github.com/kataras/iris/blob/24ba4e8933b9d58096a56e5c6f2de968f80eb602/context/context.go#L5549
3. https://github.com/kataras/iris/blob/24ba4e8933b9d58096a56e5c6f2de968f80eb602/context/context.go#L1012

By-default Iris sessions can be shared with subdomains and that behavior sets the cookie's domain to the named or custom domain (for "127.0.0.1" is the "localhost"). You can make your code runs even on 127.0.0.1 by disabling this behavior, by setting the `DisableSubdomainPersistence` sessions configuration field to `true`:

```go
sess := sessions.New(sessions.Config{
Cookie: "test-jc",
// CookieSecureTLS: true,
Expires:                     -1,
AllowReclaim:                true,
DisableSubdomainPersistence: true,
})
```

However, I am not recommending it. Here are some possible other ways to fix/customize this behavior:

1. Set the `VHost` Iris [configuration](https://github.com/kataras/iris/blob/24ba4e8933b9d58096a56e5c6f2de968f80eb602/configuration.go#L634)'s field so the `ctx.Domain` method returns that custom name instead. 
2. Customize `context.Domain()` method by setting the `iris/context#GetDomain` package-level variable on program initialization.

**Comment by conero** [comment]
@kataras Thank you for your answer. I understand the reason for this question. For individual users or a certain comprehensive website backend, there may be some non domain web services (which have been deployed in production environments), and the latter is only a small feature of the comprehensive website that needs to be used for emergency purposes. This can be completely turned off through the `DisableSubdomainPersistence` property of `sessions.Config`, so this attribute is very necessary.

**Comment by kataras** [comment]
You are welcome @conero, of course! So, we are OK with the existing `DisableSubdomainPersistence`? I will add comments on that configuration field explaining what we discussed here so other end-devs know too.

**Comment by conero** [comment]
Yep, the `DisableSubdomainPersistence` is so good.
