### ISSUE TITLE
[BUG] The cache entry has not been truly deleted after expiration

### ISSUE THREAD

**Issue by CyJaySong** [kataras/iris#2210]
**Describe the bug**
 The cache entry has not been truly deleted after expiration. this will cause the program to consume more memory to store invalid data.

**To Reproduce**
see code in `https://github.com/kataras/iris/blob/main/cache/entry/entry.go`

The program logic only determines whether the expiration time has been reached. If it expires, it will be reset to the new content on the next request. If no new requests arrive, expired data will continue to occupy memory

**Screenshots**
<img width="784" alt="image" src="https://github.com/kataras/iris/assets/29367599/06e1b5df-54b9-4249-912e-02c64e0304d8">

**iris.Version**
- v12.2.5

**Comment by kataras** [comment]
Hello @CyJaySong, nice one, it's a chance for you to push a PR for that one! Do you want to give it a try?

**Comment by CyJaySong** [comment]
@kataras I‘m willing to try

**Comment by kataras** [comment]
@CyJaySong thanks, I have re-factored the code, so you can read my solution, the commit contains new features as custom max age function and **custom storage**, maybe your issue is solved as well, if so you don't need to do anything at all :) Check: https://github.com/kataras/iris/commit/28f49cd50d5d9f1364745d9fe8873e3b22c9e177

**Comment by CyJaySong** [comment]
@kataras  Nice, it's very useful

**Comment by kataras** [comment]
You are welcome🔥💪
