### ISSUE TITLE
Where are the tests?

### ISSUE THREAD

**Issue by bep** [kataras/iris#225]
This seem to be a popular repository, yet I see no sign of QA, aka. automatic tests? How do you you know that this actually works? Or, more important, how can you convince me and the other potential users that it works?

**Comment by kataras** [comment]
Please read the readme before posting any issue, thanks you very much and welcome to Iris :)

**Comment by bep** [comment]
>Is that the only reason you didn't star Iris yet?

No, plenty of other reasons. Should I elaborate?

**Comment by kataras** [comment]
Ok then, if you read the first question about tests you already know that on the final v3 the unit tests for frontend-tasks will be there (on [iris-contrib/tests](https://github.com/iris-contrib/tests) ). Until now I'm working exclusive for Iris all day all week, so many changes, features and fixes before final releases, the tests would took time to mantain the changes.

**Comment by kataras** [comment]
Ok then, it is totally your decision, we are not all perfect. If you read the first question about tests you already know that on the final v3 the unit tests for frontend-tasks will be there (on [iris-contrib/tests](https://github.com/iris-contrib/tests), you have to contribute if you need tests also). Until now I'm working exclusive for Iris all day all week, so many changes, features and fixes before final releases, it would took me much time to mantain the tests because of these changes.

**Comment by bep** [comment]
OK, I vote no, then. Making v3 with 100 commits and no real proof of "does it work" sounds funky.

**Comment by kataras** [comment]
Dublicated: https://github.com/kataras/iris/issues/211

**Comment by kataras** [comment]
[https://github.com/kataras/iris/issues/211]

Sorry for my previous upset, the answer to your question:

there is no ETA for tests yet, but I'll start writing some soon
