### ISSUE TITLE
Dublicate: xsrf protection

### ISSUE THREAD

**Issue by wolfgangmeyers** [kataras/iris#226]
Is there any existing or planned support for XSRF protection?

**Comment by kataras** [comment]
You mean a middleware, you can find many many solutions on internet for these things if you don't know how to do it

**Comment by kataras** [comment]
The post is dublicated, please search for solution in already posted issues before posting a new one.

 You mean a middleware, if you don't know how to do it already, you can find many many solutions on internet for these things. 

However I am open to approve any pull requests on [iris-contrib/middleware](https://github.com/iris-contrib/middleware) or suggest me a middleware that you used to work before(net/http) Iris and I can convert it in order to work with Iris ( although is not so hard to do it by yourself, some things are better to handled by developers themselves and no by frameworks)

**Comment by kataras** [comment]
**Iris** gives you the **freedom** to do whatever you want, **it is not like other frameworks you may knew** before.

> Is there any existing or planned support for XSRF protection?

You mean a middleware, **It is not so hard** to do it by yourself, some things are better to **handled by developers** themselves and no by frameworks however if you don't know how to do it already, **you can find many solutions** on google/yahoo/forums for these things.

Also keep note that I am open to **approve any pull requests on** [iris-contrib/middleware](https://github.com/iris-contrib/middleware) or **suggest me a middleware** that you used to work before(**net/http**) and I can **convert it** in order to work with **Iris**.

Thanks for the comment!

> The post is dublicated, please search for solution in already posted issues before posting a new one.
