### ISSUE TITLE
run the demo failed

### ISSUE THREAD

**Issue by sky3hao** [kataras/iris#236]
When I run the  demo : 
```
func main() {
    // render JSON
    iris.Get("/hi_json", func(c *iris.Context) {
        c.JSON(iris.StatusOK, iris.Map{
            "Name":  "Iris",
            "Born":  "13 March 2016",
            "Stars": 2440,
        })
    })
    iris.Listen(":8080")
}

```
Print the message:

> \# github.com/valyala/fasthttp
> github.com/valyala/fasthttp/bytebuffer.go:47: undefined: bytebufferpool.Acquire
> github.com/valyala/fasthttp/bytebuffer.go:55: undefined: bytebufferpool.Release

**Comment by kataras** [comment]
Hello @sky3hao  you have old version of fasthttp, you didn't install Iris with the command ` go get -u github.com/kataras/iris/iris` please do that in order to upgrade all dependecies, if that doesn't works let me know

**Comment by kataras** [comment]
Hello @sky3hao I just test the example and it's working,  you have old version of fasthttp, you didn't install Iris with the command ` go get -u github.com/kataras/iris/iris` please remove your ` $GOPATH/src/github.com/kataras` ,open your shell and run ` go get -u github.com/kataras/iris/iris `  do that in order to upgrade all dependecies, if that doesn't works for you, let me know

**Comment by sky3hao** [comment]
thank you @kataras , I reinstall that package,  then it is working!
