### ISSUE TITLE
Iris create command: Error with custom GOPATH

### ISSUE THREAD

**Issue by bvp** [kataras/iris#237]
I have a custom GOPATH division into local and remote repositories
I am trying to create a new project and I receive an error
`
D:\work\go\loc\src\bvp\irisTest>iris create

|-|
Problem while copying the basic package to the D:\work\go\ext;D:\work\go\loc;D:\work\bvp\Go\\src\irisTest. Trace: mkdir D:\work\go\ext;D:: The filename, directory name, or volume label syntax is incorrect.
`

More please pay attention to the launch of the directory and the directory that issued in error.
It may be the best choice to create a project in the current directory starting or prompt the user to specify where to create the project.

**Comment by kataras** [comment]
Hello @bvp, first of all thanks for posting this issue.

> It may be the best choice to create a project in the current directory

The first version of the ` iris create` was creating the folder in the current directory, but the program couldn't be started at a folder out of the `$GOPATH` (because of project's imports). So I think it's better to not go back then, and let's keep the today's way (create on $GOPATH and not at the current dir). 

> Problem while copying the basic package to the D:\work\go\ext;D:\work\go\loc;D:\work\bvp\Go\src\irisTest.

The $GOPATH is the ("GOPATH") system environment variable, but you have issue because has been setted a second custom GOPATH so it takes 2 paths combined, instead of 1. We can fix it by taking the last part of the $GOPATH env as the path for the create command (they are separated by `;` on windows, `:` on linux If i'm not mistaken).

The patch will be available soon

**Comment by kataras** [comment]
@bvp Fixed, upgrade with ` go get -u github.com/kataras/iris/iris` , thanks for the bug report!
