### ISSUE TITLE
Unnecessary output information

### ISSUE THREAD

**Issue by dxvgef** [kataras/iris#248]
In the iris/sessions/manager.go :125

**Comment by kataras** [comment]
Oh thanks you, I made some tests anbut forgot  to remove it it(lool), thanks !!. However For these smalls things better to come to [chat](https://kataras.rocket.chat/channel/iris) :P

**Comment by dxvgef** [comment]
Recently updated the Iris, its file path and usage changed some, I was busy modifying my project code so that it can be compatible with the latest version, It makes me feel terrible thing iris update :(

**Comment by kataras** [comment]
No man I didn't made any breaking changes after rc.3, how much weeks do you have to update?   ( weeks on pre-release versions is much time for iris :P )

**Comment by dxvgef** [comment]
I update the Iris for about a week, and the latest update has these changes:

- graceful from the Iris of the directory to the iris-contrib directory
- session from the middleware into the context integration, configuration and use a little change

**Comment by kataras** [comment]
Yes the first is last change, but sessions change from standalone package to -> context is here for a month or so, still has support to the low-level package, as before *

I just added a way to test your API with Iris very easly via the `iris/api.Tester(t)` function, I will finish the tests for iris and I will commit them in order to see how is working, you will like it!

**Comment by dxvgef** [comment]
Well, hope the structure of the iris can be stabilized as soon as possible.

**Comment by kataras** [comment]
Yes we finish with these, now some tests and some underline features(no changes) and we will be ready for the v3 final!
