### ISSUE TITLE
How iris support internationalization?

### ISSUE THREAD

**Issue by insionng** [kataras/iris#25]

**Comment by kataras** [comment]
So far no internationalization support, If you want to help it will be appriciate

**Comment by kataras** [comment]
@insionng  I am trying to make the internationalization feature as you asked but can you tell me how you manage to use the https://github.com/Unknwon/i18n package? ( which you told me you use it because of macaron) 
I maybe have issue, this is not working for me: 
It's just prints the 'hi' and the extra string Unknown, but it does on english(or the default key which is just 'hi')  not at greek(or chinese) for example

```go
// conf/locale/locale_el-GR.ini
// conf/locale/locale_en-US.ini
// conf/locale/locale_zh-CN.ini

package main

import (
	"fmt"
	"github.com/Unknwon/i18n"
)

func something() {
	c := &MyController{
		Locale: i18n.Locale{"el-GR"},
	}
	hi := c.Tr("hi", "Unknwon")
	fmt.Printf(hi)
}

func main() {
	something()
}

```
Outputs:
```
hi%!!(MISSING)(EXTRA string=Unknown)
```
This doesn't work either: 

```go
hi := i18n.Tr("zh-CN", "hi", "makis")
//prints hi%!(EXTRA string=makis)
```

The 
```go
println(i18n.Count())
//prints 0
``` 

Do I have to use the SetMessageWith/Desc function  ? it doesn't load automatically from the ./conf/locale ? and if So can you add to the readme.md how can we define the language files? Thanks you!!

**Comment by kataras** [comment]
@insionng  Happy news for you, I hope this will do the work: https://github.com/kataras/iris/tree/examples/middleware_internationalization_i18n

**Comment by insionng** [comment]
That's cool!

**Comment by kataras** [comment]
It uses the same library as you wanted to do ( the i18n from uknown)

**Comment by insionng** [comment]
@kataras Sorry, recent travel.
When I got home, I will test this middleware.

**Comment by kataras** [comment]
@insionng  Ok, no problem have happy holidays !!
