### ISSUE TITLE
two place of  fatal error: concurrent map writes

### ISSUE THREAD

**Issue by huziu235** [kataras/iris#252]
kataras/iris/render/template/engine/pongo/pongo.go:90 
p.templateCache[name], templateErr = set.FromString(string(buf))
p.templateCache should be locked
same problem occur in 
github.com/kataras/iris/sessions/providers/memory/store.go
values should be locked too 
and please take care of func GetAll(), it returns the whole values map.

**Comment by kataras** [comment]
Are you you new in Go lang?

- p.templateCache[name] on buildFromDir no need to be locked it is synchronized method, cannot run concurrent.

- GetAll, no need of locks because the provider does the locking already

Anyway thansk you and keep trying, better to talk on chat about these things in order to help you better
