### ISSUE TITLE
Routing issue:  Path's part conflicts with wildcard

### ISSUE THREAD

**Issue by tsl0922** [kataras/iris#281]
Given the code:

```
api := iris.Party("/v2")
{
    api.Put("/service_instances/:id", ps.handleProvision)
    api.Put("/service_instances/:instance_id/service_bindings/:id", ps.handleBinding)
}
```

Produces:

```
Error: Router: Path's part: ':instance_id/service_bindings/:id' conflicts with wildcard ':id' in the route path: '/v2/service_instances/:instance_id/service_bindings/:id' !
```

Is this by design? Can we add support for this type of route?

**Comment by kataras** [comment]
By Design, please read othe post issues before posting new, thanks you mate!

**Comment by tsl0922** [comment]
Hi, @kataras 

I've read the other similar issues and post this, so consider this issue as a feature request. 

This type of route is widely supported by other web frameworks, eg: sinatra(ruby), spring-mvc(java). It is very common and useful, hope iris has builtin support for it.

**Comment by kataras** [comment]
I am designing a secondary router as iris plugin, if you read the README, on feature requests, but the particular issue you have it can be fixed by this router also, I will not give you the solution, think it and you will find the solution soon or late, I am not accepting feature requests from people who didn't star Iris, I'm sorry , this is the strategy

**Comment by tsl0922** [comment]
f

**Comment by tsl0922** [comment]
I'm sorry, for your strategy. But I don't know why you deleted the comments above, this is ridiculous. If you want more people to contribute, you should be open to all users, not just who starred it.
