### ISSUE TITLE
Question: Websockets

### ISSUE THREAD

**Issue by hardcoar** [kataras/iris#295]
Supposedly i want my clients to join rooms based on url.
Example url: ```/us-rooms/nyc```

the examples show websocket setup is held inside the main func
```
websocketConfig := config.DefaultWebsocket()
	websocketConfig.Endpoint = "/my_endpoint" // the path which the websocket client should listen/registed to
	w := websocket.New(api, websocketConfig, api.Logger)
	var myChatRoom = "room1"
	w.OnConnection(func(c websocket.Connection) {

		c.Join(myChatRoom)

		c.On("chat", func(message string) {
			// to all except this connection ->
			//c.To(websocket.Broadcast).Emit("chat", "Message from: "+c.ID()+"-> "+message)

			// to the client ->
			//c.Emit("chat", "Message from myself: "+message)

			//send the message to the whole room,
			//all connections are inside this room will receive this message
			c.To(myChatRoom).Emit("chat", "From: "+c.ID()+": "+message)
		})

		c.OnDisconnect(func() {
			fmt.Printf("\nConnection with ID: %s has been disconnected!", c.ID())
		})
	})
```
first i thought of like a dynamic Endpoint ```websocketConfig.Endpoint = "/:my_endpoint"``` which i think is really hard if not impossible. so alternatively, i focused on c.Join() instead.

how will i be able to dynamically assign myChatRoom based on the url? i want to take advantage of iris routing say ```/us-rooms/:roomId``` and then c.Join(ctx.Params("roomId"))?
is this possible? this might be a feature request idk really but it would be awesome if this is possible.

thanks in advance!

**Comment by kataras** [comment]
Hello @hardcoar, first of all you can minify the code:
```go
iris.Config.Websocket.Endpoint = "/my_endpoint"
iris.Websocket.OnConnection(func(c iris.WebscoketConnection){
   //...c.On...c.Join...c.Emit
})
```
Answer:

> first i thought of like a dynamic Endpoint websocketConfig.Endpoint = "/:my_endpoint"

I can do that but it is wrong by design, I will explain later

> routing say /us-rooms/:roomId and then c.Join(ctx.Params("roomId"))?

Websocket has nothing to do with the `context(ctx)` , you have access to `Headers` only, ( which is not design-correct but I added it to manage your authentication via websocket also).

I will explain now why there is no need for dynamic path and other context's function inside websocket flow. 

Iris gives you a client-side library to work with iris websocket also, you can send messages and join to room via `javascript`, so you can **just take the address with javascript** and send a message to the websocket server, the server-side hook will be like that: ` On("joinRoom", func(roomName string)`  and do `c.Join(roomName)` .

You can send any type of message via websocket, rooms are dynamically, no need to have dynamic endpoint(or namespace like socket.io) when you can use unlimitted dynamic rooms. I think I answered you, the secret is to think client & server, not only server-side like you mostly with pure http connections.

If you have any questions, do not hesitate to ask further!

**Comment by kataras** [comment]
Hello @hardcoar, first of all you can minify the code:
```go
iris.Config.Websocket.Endpoint = "/my_endpoint"
iris.Websocket.OnConnection(func(c iris.WebsocketConnection){
   //...c.On...c.Join...c.Emit
})
```
Answer:

> first i thought of like a dynamic Endpoint websocketConfig.Endpoint = "/:my_endpoint"

I can do that but it is wrong by design, I will explain later

> routing say /us-rooms/:roomId and then c.Join(ctx.Params("roomId"))?

Websocket has nothing to do with the `context(ctx)` , you have access to `Headers` only, ( which is not design-correct but I added it to manage your authentication via websocket also).

I will explain now why there is no need for dynamic path and other context's function inside websocket flow. 

Iris gives you a client-side library to work with iris websocket also, you can send messages and join to room via `javascript`, so you can **just take the address with javascript** and send a message to the websocket server, the server-side hook will be like that: ` On("joinRoom", func(roomName string)`  and do `c.Join(roomName)` .

You can send any type of message via websocket, rooms are dynamically, no need to have dynamic endpoint(or namespace like socket.io) when you can use unlimitted dynamic rooms. I think I answered you, the secret is to think client & server, not only server-side like you mostly with pure http connections.

If you have any questions, do not hesitate to ask further!

**Comment by kataras** [comment]
Hello @hardcoar, first of all you can minify the code:
```go
iris.Config.Websocket.Endpoint = "/my_endpoint"
iris.Websocket.OnConnection(func(c iris.WebsocketConnection){
   //...c.On...c.Join...c.Emit
})
```
Answer:

> first i thought of like a dynamic Endpoint websocketConfig.Endpoint = "/:my_endpoint"

I can do that but it is wrong by design, I will explain later

> routing say /us-rooms/:roomId and then c.Join(ctx.Params("roomId"))?

Websocket has nothing to do with the `context(ctx)` , you have access to `Headers` only, ( which is not design-correct but I added it to manage your authentication via websocket also).

I will explain now why there is no need for dynamic path and other context's function inside websocket flow. 

Iris gives you a client-side library to work with iris websocket also, you can send messages and join to room via `javascript`, so you can **just take the address with javascript** and send a message to the websocket server, the server-side hook will be like that: ` On("joinRoom", func(roomName string)`  and do `c.Join(roomName)` .

You can send any type of message via websocket, rooms are dynamically, no need to have dynamic endpoint(or namespace like socket.io) when you can use unlimitted dynamic rooms. I think I answered you, the secret is to think client & server, not only server-side like you mostly do with pure http connections.

If you have any questions, do not hesitate to ask further!

**Comment by hardcoar** [comment]
@kararas thanks! im impressed on how detailed you answer. i implement it on the client side javascript like you said. thanks a lot. cheers!

**Comment by kataras** [comment]
You're welcome!!

**Comment by averrin** [comment]
So, but i can not control client side and its opened ws by "/Websocket?key=value", how i can get this value? Maybe its "wrong by design", but its fact. Can i use iris, or i need write my own ws implementation?

**Comment by sidharthqb** [comment]
@kataras I have the same question by @averrin.Hope you will give a solution.Thanks in advance

**Comment by averrin** [comment]
@sidharthqb i migrated to echo3. Maybe slower, but easier to code.
