### ISSUE TITLE
Context.After(middleware) or something similar - execute middleware after handler

### ISSUE THREAD

**Issue by cristian-sima** [kataras/iris#298]
Hi.

The idea is simple. I have multiple companies, and each one has invoices. So, I have a `iris.Party` for each company and a `iris.MuxAPI` for the invoices. 

Before I request or update the invoices, I want to connect to 2 databases, check the user has the right for that company and check if the account is login. This is done by my `ConnectToCompanyDatabase` array which contains an array of middlewares.

This is the code for what I've described:

```
func LoadAPI(api iris.MuxAPI) {
	cube := api.Party("/cube/:company", middleware.ConnectToCompanyDatabase...)
	{
		cube.API("invoices", invoiceAPI{})
	}
}
```

Good. *That works*

The problem which appears is that, **after** I've done my requests and I've finished with the handler, I am required to close the connections to the databases. So, the only option is to add the middle ware to do this, after each request. For instance: 

```
func (api invoiceAPI) Get() {

	// ... here I generate the response

	context.JSON(200, response)

	middleware.CloseDatabaseConnections(context)
}
```

As you can see, I have to repeat this for each handler: **add, delete, update** and so on. The same problem is if let's say a company has `invoices` and `clients`. So, you got the idea, after each handler I have to repeat the code. Also, the problem is that *I may omit the code*.

Therefore, I need a special function which I can call *after the handler has been called* inside an `iris.API` or `iris.Party`. Or another solution can be to insert the closing database's middleare at the definition of the `API` or `Party` in a way. Here is a idea:

```
func LoadAPI(api iris.MuxAPI) {
	cube := api.Party("/cube/:company", middleware.ConnectToCompanyDatabase...).Finish(middleware.CloseDatabaseConnections)
	{
		cube.API("invoices", invoiceAPI{})
	}
}
```

What do you think?

**Comment by cristian-sima** [comment]
I have previously work with [beego](https://github.com/astaxie/beego), another Golang framework

They provide a `Finish` function, which is run at the end of a request as this pictures illustrates:

![image](https://cloud.githubusercontent.com/assets/12199042/16926353/fcee5522-4d30-11e6-900f-6aed79322e4f.png)

**Comment by kataras** [comment]
You can already register a middleware after your API structure or after the party also, we are not beego I'm not making mistakes.

```go
// first way, declare the close on the party 
func LoadAPI(api iris.MuxAPI) {
    cube := api.Party("/cube/:company", middleware.ConnectToCompanyDatabase...)
    {
        cube.API("invoices", invoiceAPI{})
    }
    cube.Use(middleware.CloseDatabaseConnections)

}

// second way, to declare the close on the methods you want
func LoadAPI(api iris.MuxAPI) {
    cube := api.Party("/cube/:company", middleware.ConnectToCompanyDatabase...)
    {
        cube.API("invoices", invoiceAPI{},middleware.CloseDatabaseConnections)
    }
}
```

**Comment by kataras** [comment]
First of all you can already execute a middleware after a handler:

```go
iris.Get("/", myMiddleware1, myHandler, myMiddleware2,myMiddlewareLast)
```
You can already register a middleware after your API structure or after the party also, we are not beego I'm not making these types of mistakes.

```go
// first way, declare the close on the party 
func LoadAPI(api iris.MuxAPI) {
    cube := api.Party("/cube/:company", middleware.ConnectToCompanyDatabase...)
    {
        cube.API("invoices", invoiceAPI{})
    }
    cube.Use(middleware.CloseDatabaseConnections)

}

// second way, to declare the close on the methods you want
func LoadAPI(api iris.MuxAPI) {
    cube := api.Party("/cube/:company", middleware.ConnectToCompanyDatabase...)
    {
        cube.API("invoices", invoiceAPI{},middleware.CloseDatabaseConnections)
    }
}
```

**Comment by cristian-sima** [comment]
The examples **are not working**.

Let's take this simple full implementation with `Party` and `API`:

```go
package main

import "github.com/kataras/iris"

// --- middlewares

func _1stMiddlware(context *iris.Context) {
	context.Write("1. This is the first middleware \n")
	context.Next()
}

func _2ndMiddleware(context *iris.Context) {
	context.Write("2. This is the second middleware \n")
	context.Next()
}

func _3rdMiddleware(context *iris.Context) {
	context.Write("3. This is the 3rd middleware \n")
	context.Next()
}

func _4thMiddlware(context *iris.Context) {
	context.Write("4. This is the 4th middleware \n")
	context.Next()
}

var firstTwoMiddlewares = []iris.HandlerFunc{
	_1stMiddlware,
	_2ndMiddleware,
}

var lastTwoMiddlewares = []iris.HandlerFunc{
	_3rdMiddleware,
	_4thMiddlware,
}

// --- invoiceAPI

type invoiceAPI struct {
	*iris.Context
}

// GET /invoices
func (api invoiceAPI) Get() {
	api.Write("List all the invoices \n")
}

// GET /:param1 which its value passed to the id argument
func (api invoiceAPI) GetBy(id string) {
	api.Write("Get the invoice with id: %s", id, "\n")
}

// PUT /invoices
func (api invoiceAPI) Put() {
	api.Write("PUT invoice \n")
}

// POST /invoices/:param1
func (api invoiceAPI) PostBy(id string) {
	api.Write("POST invoice \n")
}

// DELETE /invoices/:param1
func (api invoiceAPI) DeleteBy(id string) {
	api.Write("Get the invoice with id: %s", id, "\n")
}

// --- main

func main() {

	api := iris.Party("/api")

	cube := api.Party("/company/:company", firstTwoMiddlewares...)
	{
		cube.API("invoices", invoiceAPI{})
	}
	cube.UseFunc(lastTwoMiddlewares...)

	iris.Listen("127.0.0.1:8000")
}

```

---

For your 2 examples: 

* If you go to `http://127.0.0.1:8000/api/company/16` you will get:

```
1. This is the first middleware 
2. This is the second middleware 
List all the invoices 
```

So in this case, **the last 2 middlewares** are **not executed**. This is not good, because the `CloseDatabseConnection` is not executed.

--- 

* If you include the middlewares inside the `API` function:

```go 
func main() {

	api := iris.Party("/api")

	cube := api.Party("/company/:company", firstTwoMiddlewares...)
	{
		cube.API("invoices", invoiceAPI{}, lastTwoMiddlewares...)
	}
	iris.Listen("127.0.0.1:8000")
}
```

and you will go to `http://127.0.0.1:8000/api/company/16`, you will get:

```
1. This is the first middleware 
2. This is the second middleware 
3. This is the 3rd middleware 
4. This is the 4th middleware 
List all the invoices 
```

So in this case, **the last 2 middlewares** are executed **before** the handler. This is not good, because it closes the connection and I can not use it inside the handler.

@kataras Any solution based on this example?

**Comment by kataras** [comment]
Of course, wait a second I found the solution and `Use` was not the solution in your issue because these middleware will be available on the next route, not previous registered, I'm thinking the `.Done` or `UseLast`, wait for answer, I'm coding atm

**Comment by kataras** [comment]
@cristian-sima 

Some notes first:

This code doesn't works for two reasons:

- on your api's method you never fired the `api.Next()` to go to the next middleware.
- the `.Use/UseFunc` was the wrong solution (by me) because it registers the handlers to the next routes, no to the already pre-defined, so now we are introducing the `Done/DoneFunc` .  ` cube := api.Party("/company/:company", firstTwoMiddlewares...).DoneFunc(lastTwoMiddlewares...)`  

**OR**

```go
    cube := api.Party("/company/:company", firstTwoMiddlewares...)
    {
        cube.API("invoices", invoiceAPI{})
    }
    cube.DoneFunc(lastTwoMiddlewares...)
```

`Done/DoneFunc` is new feature, requested by you. 

Note: 
`Done/DoneFunc` like `Use/UseFunc`, if you use them inside a Party then the child party will have these done middleware handlers also.

**Comment by kataras** [comment]
@cristian-sima 

Some notes first:

This code doesn't works for two reasons:

- on your api's method you never fired the `api.Next()` to go to the next middleware.
- the `.Use/UseFunc` was the wrong solution (by me) because it registers the handlers to the next routes, no to the already pre-defined, so now we are introducing the `Done/DoneFunc` .  ` cube := api.Party("/company/:company", firstTwoMiddlewares...).DoneFunc(lastTwoMiddlewares...)`  

**OR**

```go
    cube := api.Party("/company/:company", firstTwoMiddlewares...)
    {
        cube.API("invoices", invoiceAPI{})
    }
    cube.DoneFunc(lastTwoMiddlewares...)
```

`Done/DoneFunc` is new feature, requested by you. 

Note: 
`Done/DoneFunc` like `Use/UseFunc`, if you use them inside a Party then the child party will have these done middleware handlers also.


Verify it, please.

Examples:

- https://github.com/iris-contrib/examples/tree/master/middleware_2
- https://github.com/iris-contrib/examples/tree/master/middleware_3

**Comment by kataras** [comment]
@cristian-sima 

Some notes first:

This code doesn't works for two reasons:

- on your api's method you never fired the `api.Next()` to go to the next middleware.

```go
// GET /invoices
func (api invoiceAPI) Get() {
    api.Write("List all the invoices \n")
    api.Next() // add this
}

// GET /:param1 which its value passed to the id argument
func (api invoiceAPI) GetBy(id string) {
    api.Write("Get the invoice with id: %s", id, "\n")
    api.Next() // add this
}

// PUT /invoices
func (api invoiceAPI) Put() {
    api.Write("PUT invoice \n")
    api.Next() // add this
}

// POST /invoices/:param1
func (api invoiceAPI) PostBy(id string) {
    api.Write("POST invoice \n")
    api.Next() // add this
}

// DELETE /invoices/:param1
func (api invoiceAPI) DeleteBy(id string) {
    api.Write("Get the invoice with id: %s", id, "\n")
    api.Next() // add this
}
```

- the `.Use/UseFunc` was the wrong solution (by me) because it registers the handlers to the next routes, no to the already pre-defined, so now we are introducing the `Done/DoneFunc` .  ` cube := api.Party("/company/:company", firstTwoMiddlewares...).DoneFunc(lastTwoMiddlewares...)`  

**OR**

```go
    cube := api.Party("/company/:company", firstTwoMiddlewares...)
    {
        cube.API("invoices", invoiceAPI{})
    }
    cube.DoneFunc(lastTwoMiddlewares...)
```

`Done/DoneFunc` is new feature, requested by you. 

Note: 
`Done/DoneFunc` like `Use/UseFunc`, if you use them inside a Party then the child party will have these done middleware handlers also.


Verify it, please.

Examples:

- https://github.com/iris-contrib/examples/tree/master/middleware_2
- https://github.com/iris-contrib/examples/tree/master/middleware_3

**Comment by kataras** [comment]
@cristian-sima 

Some notes first:

This code doesn't works for two reasons:

- on your api's method you **never fired the `api.Next()`** to go to the next middleware.

```go
// GET /invoices
func (api invoiceAPI) Get() {
    api.Write("List all the invoices \n")
    api.Next() // add this
}

// GET /:param1 which its value passed to the id argument
func (api invoiceAPI) GetBy(id string) {
    api.Write("Get the invoice with id: %s", id, "\n")
    api.Next() // add this
}

// PUT /invoices
func (api invoiceAPI) Put() {
    api.Write("PUT invoice \n")
    api.Next() // add this
}

// POST /invoices/:param1
func (api invoiceAPI) PostBy(id string) {
    api.Write("POST invoice \n")
    api.Next() // add this
}

// DELETE /invoices/:param1
func (api invoiceAPI) DeleteBy(id string) {
    api.Write("Get the invoice with id: %s", id, "\n")
    api.Next() // add this
}
```

- the `.Use/UseFunc` was the wrong solution (by me) because it registers the handlers to the next routes, no to the already pre-defined, so now we are introducing the `Done/DoneFunc` .  ` cube := api.Party("/company/:company", firstTwoMiddlewares...).DoneFunc(lastTwoMiddlewares...)`  

**OR**

```go
    cube := api.Party("/company/:company", firstTwoMiddlewares...)
    {
        cube.API("invoices", invoiceAPI{})
    }
    cube.DoneFunc(lastTwoMiddlewares...)
```

`Done/DoneFunc` is new feature, requested by you. 

Note: 
`Done/DoneFunc` like `Use/UseFunc`, if you use them inside a Party then the child party will have these done middleware handlers also.


Verify it, please.

Examples:

- https://github.com/iris-contrib/examples/tree/master/middleware_2
- https://github.com/iris-contrib/examples/tree/master/middleware_3

**Comment by kataras** [comment]
@cristian-sima 

Some notes first:

This code doesn't works for two reasons:

- on your api's method you **never fired the `api.Next()`** to go to the next middleware.

```go
// GET /invoices
func (api invoiceAPI) Get() {
    api.Write("List all the invoices \n")
    api.Next() // add this
}

// GET /:param1 which its value passed to the id argument
func (api invoiceAPI) GetBy(id string) {
    api.Write("Get the invoice with id: %s", id, "\n")
    api.Next() // add this
}

// PUT /invoices
func (api invoiceAPI) Put() {
    api.Write("PUT invoice \n")
    api.Next() // add this
}

// POST /invoices/:param1
func (api invoiceAPI) PostBy(id string) {
    api.Write("POST invoice \n")
    api.Next() // add this
}

// DELETE /invoices/:param1
func (api invoiceAPI) DeleteBy(id string) {
    api.Write("Get the invoice with id: %s", id, "\n")
    api.Next() // add this
}
```

- the `.Use/UseFunc` was the wrong solution (by me) because it registers the handlers to the next routes, no to the already pre-defined, so now we are introducing the `Done/DoneFunc` .  ` cube := api.Party("/company/:company", firstTwoMiddlewares...).DoneFunc(lastTwoMiddlewares...)`  

**OR**

```go
    cube := api.Party("/company/:company", firstTwoMiddlewares...)
    {
        cube.API("invoices", invoiceAPI{})
    }
    cube.DoneFunc(lastTwoMiddlewares...)
```

`Done/DoneFunc` is new feature, requested by you. 

Note: 
`Done/DoneFunc` like `Use/UseFunc`, if you use them inside a Party then the child party will have these done middleware, as last handlers, also.


Verify it, please.

Examples:

- https://github.com/iris-contrib/examples/tree/master/middleware_2
- https://github.com/iris-contrib/examples/tree/master/middleware_3

**Comment by kataras** [comment]
@cristian-sima 

Some notes first:

This code doesn't works for two reasons:

- on your api's method you **never fired the `api.Next()`** to go to the next middleware.

```go
// GET /invoices
func (api invoiceAPI) Get() {
    api.Write("List all the invoices \n")
    api.Next() // add this
}

// GET /:param1 which its value passed to the id argument
func (api invoiceAPI) GetBy(id string) {
    api.Write("Get the invoice with id: %s", id, "\n")
    api.Next() // add this
}

// PUT /invoices
func (api invoiceAPI) Put() {
    api.Write("PUT invoice \n")
    api.Next() // add this
}

// POST /invoices/:param1
func (api invoiceAPI) PostBy(id string) {
    api.Write("POST invoice \n")
    api.Next() // add this
}

// DELETE /invoices/:param1
func (api invoiceAPI) DeleteBy(id string) {
    api.Write("Get the invoice with id: %s", id, "\n")
    api.Next() // add this
}
```

- the `.Use/UseFunc` was the wrong solution (by me) because it registers the handlers to the next routes, no to the already pre-defined, so now we are introducing the `Done/DoneFunc` .  ` cube := api.Party("/company/:company", firstTwoMiddlewares...).DoneFunc(lastTwoMiddlewares...)`  

**OR**

```go
    cube := api.Party("/company/:company", firstTwoMiddlewares...)
    {
        cube.API("invoices", invoiceAPI{})
    }
    cube.DoneFunc(lastTwoMiddlewares...)
```

`Done/DoneFunc` is new feature, requested by you. 

Note: 
`Done/DoneFunc` like `Use/UseFunc`, if you use them inside a Party then the child party will have these done middleware, as last handlers, also.


Verify it, please.

Examples:

- https://github.com/iris-contrib/examples/tree/master/middleware_2
- https://github.com/iris-contrib/examples/tree/master/middleware_3

Friendly note:

It's not right to wait 7 days more, for confirmation ,while att he same time I answer almost immediately to all community's issues, please watch the issues you write on in order to be notified :)

**Comment by cristian-sima** [comment]
Good. I will start by saying sorry for responding so late. 

Last week, on 20th, I had my *Graduation Ceremony* at University of Southampton (I am now an engineer with diploma). During that time, I was not able to create a proper response.

Usually I respond in a matter of hours/day. The next point:

I can now *confirm it is now working*.

```
1. This is the first middleware 
2. This is the second middleware 
List all the invoices 
3. This is the 3rd middleware 
4. This is the 4th middleware 
```

The only problem which remains is [293](https://github.com/kataras/iris/issues/293#issuecomment-234932432)

**Comment by kataras** [comment]
First of all **CONGRULATIONS**, good job!! I hope the bests and more!!!

> The only problem which remains is 293

Yes, I'm trying to find the source of problem, I will answer you there for the results

**Comment by cristian-sima** [comment]
Thank you. Waiting for it :)
