### ISSUE TITLE
Port Binding timing out on Heroku

### ISSUE THREAD

**Issue by itsbalamurali** [kataras/iris#309]
Port Binding timing out on Heroku.

Please help.

![image](https://cloud.githubusercontent.com/assets/1926303/16987291/13513ea0-4ea9-11e6-9607-4d297c00f614.png)

**Comment by kataras** [comment]
I can't help you on this man, I'm sorry... but I'm sure you will find the solution, it is not an Iris problem

**Comment by kataras** [comment]
I can't help you on this, I'm sorry... but I'm sure you will find the solution, it is not an Iris problem as I can see , but I can suggest you to upgrade iris ` go get -u github.com/kataras/iris/iris` & read the [HISTORY](https://github.com/kataras/iris/blob/master/HISTORY.md) for changes, you use 'old' version

**Comment by kataras** [comment]
I can't help you on this, I'm sorry... but I'm sure you will find the solution, it is not an Iris problem as I can see , but  for any case I suggest you to upgrade iris ` go get -u github.com/kataras/iris/iris` & read the [HISTORY](https://github.com/kataras/iris/blob/master/HISTORY.md) for changes, you use 'old' version and (we had bug reports on BSD system then which are fixed to the new version)

**Comment by kataras** [comment]
I can't help you on this, I'm sorry... but I'm sure you will find the solution, it is not an Iris problem as I can see , but  for any case I suggest you to upgrade iris ` go get -u github.com/kataras/iris/iris` & read the [HISTORY](https://github.com/kataras/iris/blob/master/HISTORY.md) for changes, you use 'old' version and (we had bug reports on BSD systems then which are fixed to the new version)

**Comment by kataras** [comment]
I can't help you on this, I'm sorry... but I'm sure you will find the solution, it is not an Iris problem as I can see , but  for any case I suggest you to upgrade iris ` go get -u github.com/kataras/iris/iris` & read the [HISTORY](https://github.com/kataras/iris/blob/master/HISTORY.md), [book](https://www.gitbook.com/book/kataras/iris/details) and [examples](https://github.com/iris-contrib/examples) for changes, you use 'old' version and (we had bug reports on BSD systems then which are fixed to the new version)

**Comment by kataras** [comment]
I can't help you on this, I'm sorry... but I'm sure you will find the solution, it is not an Iris problem as I can see , but  for any case I suggest you to upgrade iris ` go get -u github.com/kataras/iris/iris` & read the [HISTORY](https://github.com/kataras/iris/blob/master/HISTORY.md), [book](https://www.gitbook.com/book/kataras/iris/details) and [examples](https://github.com/iris-contrib/examples) for changes, you use 'old' version and (we had bug reports on BSD systems then which are fixed to the new version).

When you find the solution write it down, in order to help other users maybe have the same issue, thanks you!!
