### ISSUE TITLE
Expose Session Manager

### ISSUE THREAD

**Issue by ryanbyyc** [kataras/iris#316]
In v3, I created a persistence package for convenience methods to access session data. In v4, this isn't possible.

Please restore this functionality.

**Comment by kataras** [comment]
Can you give me an example of this? something like ` iris.Sessions.Start(ctx)` ?

**Comment by ryanbyyc** [comment]
main.go:
```
	iris.UseFunc(func(c *iris.Context) {
		persistence.SessMan = sessions.New(iris.Config.Sessions)
		persistence.Session = persistence.SessMan.Start(c)
		c.Next()
	})
```

persistence/session.go
```
var (
	// SessMan is our session manager
	SessMan *sessions.Manager

	// Session is our session manager
	Session store.IStore
)
type SessionCache struct {
	ID                   int64
	PublicID             string // used primarily for third party services such as chat
	Username             string
	PrefPagelimit        int
	PrefBrowseavatar     string
	PrefNewcontentpolicy string
	PrefNewcontentrating string
	PrefDisableprofile   bool
}

// Pagelimit is the users page limit preference
func Pagelimit() int {
	return Session.Get(SESSIONKEY).(*SessionCache).PrefPagelimit
}

**Comment by kataras** [comment]
with

```go
 persistence.SessMan = sessions.New(iris.Config.Sessions)
```
you create a whole new session manager on each call, you wanted that, right?

Do you use the `SessMan` anywhere else? This doesn't suits the needs?

```go
    iris.UseFunc(func(c *iris.Context) {
        persistence.Session = c.Session()
        c.Next()
    })
```

**Comment by ryanbyyc** [comment]
However, as it stands right now, c.Session() returns an interface{}. Without retyping it, I can't do
```
iris.UseFunc(func(c *iris.Context) {
        persistence.Session = c.Session()
        c.Next()
    })
```

Because we don't know the methods - https://github.com/kataras/iris/blob/077984bd60d12bad27de639c5c7b7b13ef1c3b86/context/context.go#L74 - the only way around this is to :
```
package persistence

var Session interface {
	ID() string
	Get(string) interface{}
	GetString(key string) string
	GetInt(key string) int
	GetAll() map[string]interface{}
	VisitAll(cb func(k string, v interface{}))
	Set(string, interface{})
	Delete(string)
	Clear()
}
```

Which to me indicates that it should be a struct.

**Comment by kataras** [comment]
It's the `session` struct

**Reason why I decidede to not use a standard interface like Session on context.go**

Yes, look this is awful I know but I hadn't choice (because of the context/context.go interface) I can't use two interfaces from other packages and be equal and I can't import them because of cycle, also I dont want to create a new folder only for this scope, so it returns an interface.

So if that is the only problem  I will create an unused interface which you can use like ` iris.Session(c.Session())` is that ok?

**Comment by ryanbyyc** [comment]
That works for me. Let's do that.

**Comment by kataras** [comment]
Ok I will find a better solution, so no export the whole manager ( it is not right, believe me) but make a Session interface to work with more correct way

**Comment by ryanbyyc** [comment]
Alright, let me know when it can be pulled? Thanks m8!

**Comment by kataras** [comment]
Ok, I will commit it, it wasn't hard I don't like that I do (because of name, nothing else)

I though to create a folder named 'domain' and pass the context/context.go inside the 'domain/context/context.go' and the Session interface(only) inside the 'domain/session/session.go', but again it is not right think to do so I just

create the interface Session inside `context/context.go` and use that inside the `/context.go:Session() context.Session` , iris already imports the `context` folder ( for the iris.H_, is used only for special cases by me*) so it is not problem except that you will have to import the `github.com/kataras/iris/context` in order to use the `context.Session` interface, is that allright with you?

**Comment by kataras** [comment]
Ok, I will commit it, it wasn't hard I don't like that I do (because of name, nothing else)

I though to create a folder named 'domain' and pass the context/context.go inside the 'domain/context/context.go' and the Session interface(only) inside the 'domain/session/session.go', but again it is not right thing to do so I just

create the interface Session inside `context/context.go` and use that inside the `/context.go:Session() context.Session` , iris already imports the `context` folder ( for the iris.H_, is used only for special cases by me*) so it is not problem except that you will have to import the `github.com/kataras/iris/context` in order to use the `context.Session` interface, is that allright with you?

**Comment by ryanbyyc** [comment]
I think that makes sense. I will have to test it out but it sounds good.

**Comment by kataras** [comment]
Ok, upgrade iris and tell me here what more need to change, thank you!!

**Comment by ryanbyyc** [comment]
Works like a dream. Thanks a bunch!

**Comment by kataras** [comment]
You're welcome!! Thank you !
