### ISSUE TITLE
Add Party onError

### ISSUE THREAD

**Issue by ryanbyyc** [kataras/iris#354]
Iris has the capability to catch errors such as 404s via something like:

``` go
        iris.OnError(404, func(ctx *iris.Context) {
            ctx.Write("My Custom 404 error page content")
            return
        })
```

However, I'd like to propose the feature of allowing party specific error catching. There are some scenarios (I have one I'm developing now) where I would like to catch errors such as 404s across the board, but also have party specific error catchers.

For example:

``` go
func addRoutes() {

    // add One OnError JUST for the user party
    uProfile := iris.Party("/p/:username", isLoggedInMiddleware, userByNameMiddleware)
    {
        uProfile.OnError(iris.StatusNotFound, func(ctx *iris.Context) {
            ctx.Write("404 for PARTY")
            return
        })
    }

    // Add the other for everything ELSE.
    iris.OnError(iris.StatusNotFound, func(ctx *iris.Context) {
        ctx.Write("Not found for everything else.")
        return
    })
}
```

**Comment by kataras** [comment]
That's a good idea, but the server couldn't know what was the user was looking for and what was the party's error, because you will never be sure if the Party's error will catch.How we could do that without performance cost? if the url is not registered it returns a 404 error, how we can 'calculate' what was the 'party' that the user wanted to go? we could do that by prefix but again it is not smart choice, because the router would have to 'imagine' what was the url that the user was looking for, and if some parties are conficts with each other?  I think the best solution is to do it manually, in order to know what to do, you can make a custom function to add errors on parties, via the global `iris.OnError` handler receiver, a simple example for your case it would be something like: 

`iris.OnError...func(ctx *Context){ if strings.HasPrefix(ctx.Path(),"/p/" { ctx.Write("/p/ 404 eror"}} } 

Note: Why you use 'return' inside Handlers? handler does not have an output parameter.

**Comment by kataras** [comment]
That's a good idea, but the server couldn't know what was the user was looking for and what was the party's error, because you will never be sure if the Party's error will catch.How we could do that without performance cost? if the url is not registered it returns a 404 error, how we can 'calculate' what was the 'party' that the user wanted to go? we could do that by prefix but again it is not smart choice, because the router would have to 'imagine' what was the url that the user was looking for, and if some parties are conficts with each other?  I think the best solution is to do it manually, in order to know what to do, you can make a custom function to add errors on parties, via the global `iris.OnError` handler receiver, a simple example for your case it would be something like: 

`iris.OnError...func(ctx *Context){ if strings.HasPrefix(ctx.Path(),"/p/" { ctx.Write("/p/ 404 eror"}} } `

Note: Why you use 'return' inside Handlers? handler does not have an output parameter.

**Comment by kataras** [comment]
That's a good idea, but the server couldn't know what was the user was looking for and what was the party's error, because you will never be sure if the Party's error will catch.How we could do that without performance cost? if the url is not registered it returns a 404 error, how we can 'calculate' what was the 'party' that the user wanted to go? we could do that by prefix but again it is not smart choice, because the router would have to 'imagine' what was the url that the user was looking for, and if some parties are conficts with each other?  I think the best solution is to do it manually, in order to know what to do, you can make a custom function to add errors on parties, via the global `iris.OnError` handler receiver, a simple example for your case it would be something like: 

`iris.OnError...func(ctx *Context){ if strings.HasPrefix(ctx.Path(),"/p/") { ctx.Write("/p/ 404 eror"}} } `

Note: Why you use 'return' inside Handlers? handler does not have an output parameter.

**Comment by ryanbyyc** [comment]
Hmmm. That's a good point. There are many scenarios where reverse mapping a route so an application could know its current state is a good thing, but I agree with you on the performance hit. I suppose prefix checking is one way to go, but in my mind that's a bit sloppy. Gorilla has methods to determine which route one is on, but since Gorilla Mux is slow, I can see how this is a difficult problem.

I'll close the issue, maybe we can try to tackle it in the future in a way that's performant.

Note: I used return cause of lazy copy/pasting. I was using c.RedirectTo() before. Heh.

**Comment by kataras** [comment]
Ok, look what I did so far, but I will do it better, this way has no perfomance lost if the developer doesn't registers an error on other Party except the "/" , which is the global if no other handler is served before, look it and tell me ur opinion:

```go
// OnError registers a custom http error handler
func (api *muxAPI) OnError(statusCode int, handlerFn HandlerFunc) {

	staticPath := api.relativePath

	// find the static path
	dynamicPathIdx := strings.IndexByte(api.relativePath, parameterStartByte) // check for /mypath/:param

	if dynamicPathIdx == -1 {
		dynamicPathIdx = strings.IndexByte(api.relativePath, matchEverythingByte) // check for /mypath/*param
	}

	if dynamicPathIdx > 1 { //yes after / and one character more ( /*param or /:param  will break the root path, and this is not allowed even on error handlers).
		staticPath = api.relativePath[0:dynamicPathIdx]
	}

	if staticPath == "/" {
		api.mux.registerError(statusCode, handlerFn) // register the user-specific error message, as the global error handler, for now.
		return
	}

	// get the previous
	errHandler := api.mux.errorHandlers[statusCode]
	if errHandler == nil {
		/*
		 make a new one with the standard error message,
		 this will be used as the last handler if no other error handler catches the error (by prefix(?))
		*/
		errHandler = HandlerFunc(func(ctx *Context) {
			ctx.ResetBody()
			ctx.SetStatusCode(statusCode)
			ctx.SetBodyString(statusText[statusCode])
		})
	}

	errHandler = HandlerFunc(func(ctx *Context) {
		if strings.HasPrefix(ctx.PathString(), staticPath) { // yes the user should use OnError from longest to lower static path's length in order this to work, so we can find another way, like a builder on the end.
			handlerFn.Serve(ctx)
			return
		}
		// serve with the user-specific global ("/") pure iris.OnError receiver Handler or the standar handler if OnError called only from inside a no-relative Party.
		errHandler.Serve(ctx)
	})

	api.mux.registerError(statusCode, errHandler)

}

```
