### ISSUE TITLE
data race in hi_json example

### ISSUE THREAD

**Issue by wangcn** [kataras/iris#357]
main code
`
api.Get("/hi_json", func(c *iris.Context) {
		c.JSON(iris.StatusOK, iris.Map{
			"Name":  "Iris",
			"Born":  "13 March 2016",
			"Stars": 3693,
		})
	})
`
go build --race main.go and test it with wrk. It warned data race.
`
WARNING: DATA RACE
Write by goroutine 91:
  runtime.slicecopy()
      /usr/local/go/src/runtime/slice.go:113 +0x0
  bytes.(*Buffer).Write()
      /usr/local/go/src/bytes/buffer.go:135 +0xfd
  github.com/iris-contrib/response/json.(*Engine).Response()
      /home/work/gopkg/src/github.com/iris-contrib/response/json/json.go:64 +0xa03
  github.com/kataras/iris.(*responseEngineMap).render()
      /home/work/gopkg/src/github.com/kataras/iris/response.go:132 +0x1ff
  github.com/kataras/iris.(*Context).RenderWithStatus()
      /home/work/gopkg/src/github.com/kataras/iris/context.go:539 +0x28a
  github.com/kataras/iris.(*Context).JSON()
      /home/work/gopkg/src/github.com/kataras/iris/context.go:586 +0x8e
`

my env:
openSUSE Leap 42.1
go 1.6.2
iris 4.0.0

**Comment by kataras** [comment]
@wangcn It's Harmless, if you navigate to the code you will understand, but thanks for the report, keep going!

Note: Please the next time try to post an issue on the correct repository, I splitted the repository in order to be more mantainable, [this is the resonse engines repository](https://github.com/iris-contrib/response).
