### ISSUE TITLE
HTTP Session and WebSocket Session

### ISSUE THREAD

**Issue by dem-waffles** [kataras/iris#372]
Is there a way to easily create a relationship between an HTTP Session (in the iris.Context) and a websocket session? This would be useful for getting session information in the handler for websockets.

**Comment by kataras** [comment]
Duplicated: https://github.com/kataras/iris/issues/358

HTTP and webosockets are not the same, you don't have access to the session directly, but you can send (via an API request(;)) the session id to the client, requested by client(via javascript call(;)) and send it via iris websocket client-side (javascript) to the iris websocket server

**Comment by dem-waffles** [comment]
Ah, sorry for the duplicate. Thanks!

**Comment by kataras** [comment]
`context.Session().ID()` is the method which returns the session id, send this to the client (after authentication, in order to be secure).  You're welcome, if you need anything else don't hesitate to ask or [chat](https://kataras.rocket.chat/channel/iris) with the community. If you want to receive updates about the framework's changes, star this repository and the [examples](https://github.com/iris-contrib/examples) repository, thank you!

**Comment by dem-waffles** [comment]
Just as an update, I've decided that the better way to do this, given that my use case doesn't require me to associate HTTP sessions to WS sessions, apart from authentication. The way I'm going to secure the WS connection is by protecting the WS endpoint using a middleware.

**Comment by kataras** [comment]
`*http.Request` access from Websockets

Example:

- https://github.com/iris-contrib/examples/blob/master/websocket/main.go#L34

Relative commits to kataras/go-websocket:

- kataras/go-websocket@550fc8b

- kataras/go-websocket@62c2d98

> use the `c.Request()` only when you really need it, websockets have everything you need already.
