### ISSUE TITLE
Rate Limit Feature

### ISSUE THREAD

**Issue by jnsone11** [kataras/iris#381]
Are there any plans to add rate limit capabilities?

E.g. limit the number of requests a client can do, based on ip address or configurable key (anything that might be accessible via iris.Context).

**Comment by kataras** [comment]
Already implemented, please take a look at [fasthttp](https://github.com/valhala/fasthttp) repo

**Comment by biaoqier** [comment]
@kataras The  fasthttp repo link is [fasthttp](https://github.com/valyala/fasthttp)

**Comment by ryanbyyc** [comment]
As far as I can tell, fasthttp does not do rate limiting - I looked around and couldn't find it.

Can you clarify this @kataras ?

**Comment by kataras** [comment]
@ryanbyyc @jnsone11  I think these are you're looking for:  https://github.com/valyala/fasthttp/blob/master/server.go#L189 , if these are I can add these to Iris, if not tell me what to do I'm in your services :)

**Comment by kataras** [comment]
@ryanbyyc @jnsone11  I think these are you're looking for:  https://github.com/valyala/fasthttp/blob/master/server.go#L189 , which on Iris, these: https://github.com/kataras/iris/blob/master/configuration.go#L670 , if these are not fills your needs you could always create a custom middleware and push it to the `iris-contrib/middleware` or post an idea there in order to me to do it, thanks!
