### ISSUE TITLE
fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by jinfei** [kataras/iris#389]
I found a problem today.As long as the resource does not exist, then it will be reported the following error. Is this iris.Static's  Bug?

2016/08/29 11:04:19 0.000 #0000000E0000001B - 127.0.0.1:9000<->127.0.0.1:54190 - GET http://www.dev.net:9000/uploads/20160727/2ea919de904b1ab81d0eb79c3fc24273.jpg - cannot open file "../frontend/public/uploads/20160727/2ea919de904b1ab81d0eb79c3fc24273.jpg": open ../frontend/public/uploads/20160727/2ea919de904b1ab81d0eb79c3fc24273.jpg: no such file or directory
2016/08/29 11:04:22 0.000 #0000000E0000001D - 127.0.0.1:9000<->127.0.0.1:54190 - GET http://www.dev.net:9000/uploads/20160801/dc87ffa4e18e4b601942b79f23e2d542.jpg - cannot open file "../frontend/public/uploads/20160801/dc87ffa4e18e4b601942b79f23e2d542.jpg": open ../frontend/public/uploads/20160801/dc87ffa4e18e4b601942b79f23e2d542.jpg: no such file or directory
2016/08/29 11:04:22 0.000 #0000000F00000027 - 127.0.0.1:9000<->127.0.0.1:54189 - GET http://www.dev.net:9000/uploads/20160801/7e3bcaaf43dcaa30c59d6f79a8aa3b0b.jpg - cannot open file "../frontend/public/uploads/20160801/7e3bcaaf43dcaa30c59d6f79a8aa3b0b.jpg": open ../frontend/public/uploads/20160801/7e3bcaaf43dcaa30c59d6f79a8aa3b0b.jpg: no such file or directory

fatal error: concurrent map read and map write

goroutine 4870 [IO wait]:
net.runtime_pollWait(0x150ce00, 0x72, 0x54)
	/usr/local/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc42036be20, 0x72, 0xc420e91a80, 0xc42000c098)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc42036be20, 0xd5ac00, 0xc42000c098)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x34

**Comment by jinfei** [comment]
go version
go version go1.7 darwin/amd64

**Comment by kataras** [comment]
Hello @jinfei  

This is not a bug, 

`iris.Static methods` are not used for **dynamic** files, I see that you have a dir called `frontend/public/uploads` this is a dynamic path because user can upload and remove any file in runtime, so you should use the `context's file serve methods` such as `context.ServeFile` ( https://github.com/kataras/iris/blob/master/context.go#L666 ) or `context.ServeContent` . use of `iris.Static` are for js,css,html or any type of big or small files that are static, means no they are not change in runtime, for example a favicon with `iris.Favicon` is a static file, it never changes, but a user's uploads directory is not a static, I hope you get he difference, thanks for your post!! 

> Please, the next time, post the code to be able to re-produce this error or create a repository.

**Comment by kataras** [comment]
Hello @jinfei  

This is not a bug, 

`iris.Static methods` are not used for **dynamic** files, I see that you have a dir called `frontend/public/uploads` this is a dynamic path because user can upload and remove any file in runtime, so you should use the `context's file serve methods` such as `context.ServeFile` ( https://github.com/kataras/iris/blob/master/context.go#L666 ) or `context.ServeContent` . use of `iris.Static` are for js,css,html or any type of big or small files that are static,  they are not changed in runtime, for example a favicon with `iris.Favicon` is a static file, it never changes, but a user's uploads directory is not a static, I hope you get he difference, thanks for your post!! 

> Please, the next time, post the code to be able to re-produce this error or create a repository.

**Comment by kataras** [comment]
Hello @jinfei  

This is not a bug, 

`iris.Static methods` are not used for **dynamic** files, I see that you have a dir called `frontend/public/uploads` this is a dynamic path because user can upload and remove any file in runtime, so you should use the `context's file serve methods` such as `context.ServeFile` ( https://github.com/kataras/iris/blob/master/context.go#L666 ) or `context.ServeContent` . use of `iris.Static` are for js,css,html or any type of big or small files that are static,  they are not changed in runtime, for example a favicon with `iris.Favicon` is a static file, it never changes, but a user's uploads directory is not a static, I hope you get he difference, thanks for your post!! 

> Please, the next time, specify a better title for the issue, also don't forget to post the code to be able to re-produce this error or create a repository.

**Comment by jinfei** [comment]
Okay, I understand the difference. Thanks for the reply, I will change my code. @kataras
