### ISSUE TITLE
TLS configuration in Iris

### ISSUE THREAD

**Issue by danilobuiatti** [kataras/iris#395]
I'm afraid I did not make myself clear on issue https://github.com/kataras/iris/issues/379. What I meant is that Golang has some TLS configurations available to use (https://golang.org/src/crypto/tls/common.go?s=9735:14940#L263) but I could not find a way to use those configurations in Iris. As far as I know, when using Iris with TLS you can only set the certificate and key. Is that right?

**Comment by kataras** [comment]
> As far as I know, when using Iris with TLS you can only set the certificate and key. Is that right?

Yes, also don't forget [automatic tls](https://github.com/kataras/iris/blob/master/iris.go#L485)


Many third-party packages depend on Iris compatibility with raw fasthttp server instances, like [httpexpect](https://github.com/gavv/httpexpect) does (passes the Iris' Handler to a raw fasthttp server instance)

So, I cannot break the current server's implementation because we need to be 100% compatible with raw fasthttp server instances.  **However**, you are free to open an issue to the [fasthttp](https://github.com/valyala/fasthttp) repo.

**Comment by danilobuiatti** [comment]
Ok, I've created an issue to fasthttp. Thank you!

**Comment by kataras** [comment]
Yes, I just saw it you did 18hours before, you already knew it, nice!

**Comment by kataras** [comment]
Yes it was my first though also, but I don't know... I think he asked other thing, let's wait for his answer

**Comment by kataras** [comment]
Yes I know that tls listener is just a wrapper for tcp.Listener... Ok wait a second I will respond back

**Comment by kataras** [comment]
You could always use the `go iris.AddServer(iris.ServerConfiguration{...}).Serve(ln)` and `iris.Go()` But I have to find a better way to add your custom server instead of this way, this is a chance for some server changes

**Comment by diegossilveira** [comment]
@kataras, I got the point, but I believe this could be a little bit easier and less intrusive, considering that using TLS (with full capabilities such as specifying which ciphers are used) is a common requirement for many web-based systems.

It would be really nice if we had a new `Serve` function that receives both, the address and an instance of tls.Config.

But I'll try that solution and let you know if works properly. Thank you for the attention!

**Comment by kataras** [comment]
You've right, I'm finishing my break and I will make different type of listeners to use and able to set your own inside a `Serve` function, remember that iris can listen to more than one server, because this reason is kind of 'strange' to set your listener at the moment

**Comment by kataras** [comment]
You've right, I'm finishing my break and I will make different type of listeners to use and able to set your own inside a `Serve` function, remember that iris can listen to more than one server, and a listening addresses are used inside template functions like `url and urlpath` and subdomains inside to the router , because of these reason is kind of 'strange' to set your listener at the moment

**Comment by kataras** [comment]
You've right, I'm finishing my break and I will make different type of listeners to use and able to set your own inside a `Serve` function, remember that iris can listen to more than one server, and  listening addresses are used inside template functions like `url and urlpath` and subdomains inside to the router , because of these reasons is kind of 'strange' to set your listener at the moment, but don't worry iris will have a cleaner server API until tomorrow

**Comment by diegossilveira** [comment]
Sounds great! Please, let me know when the new server API is released! Tks!

**Comment by kataras** [comment]
@diegossilveira 

New Server API is ready, a simple example how you can listen using a custom `net.Listener` is located here: https://github.com/iris-contrib/examples/tree/master/custom_net_listener 

Upgrade Iris: 
- delete folder `$GOPATH/src/github.com/kataras` (for any case)
- execute: `go get -u github.com/kataras/iris` 

please tell me if that suits your needs :)

**Comment by diegossilveira** [comment]
Thank you @kataras. As soon as I test this I'll let you know. But I'm pretty sure this fit our needs.
