### ISSUE TITLE
Add Iris Version checker

### ISSUE THREAD

**Issue by ryanbyyc** [kataras/iris#401]
I'm always forgetting to update Iris. It'd be nice if Iris could check for updates on application start (ideally, under the banner).

This should be false by default, and changed to true via something like `iris.CheckForUpdates = true` in my applications main.go.

**Comment by kataras** [comment]
Yes... good idea I had to do it on v3 but other things were most important, this will be implemented, good feature request!

**Comment by kataras** [comment]
@ryanbyyc OK, `iris.Config.CheckForUpdates` added, defaults to false. Verification that this feature is working 100% is possible only when a new version will be released, Thanks!

**Comment by ryanbyyc** [comment]
When using:
```go
iris.Config.CheckForUpdates = iris.Config.IsDevelopment
```

I get this response:
`INFO: Running with the latest version(4.2.4)`

As near as I can tell it is up and running. Will wait till next version to verify.

**Comment by kataras** [comment]
I added a new release (in order to test it too), seems that updater is working just fine,

 the results were:
![irisupdater1](https://cloud.githubusercontent.com/assets/2321588/18596711/3dc8513c-7c53-11e6-8de4-7561e74a4188.png)
![irisupdater2](https://cloud.githubusercontent.com/assets/2321588/18596710/3dc3c2de-7c53-11e6-9779-295d03747920.png)
