### ISSUE TITLE
Not work debug

### ISSUE THREAD

**Issue by legion-zver** [kataras/iris#402]
If Add import github.com/kataras/iris then not work delve (dlv debug) my project.
When there was a 1.6 version of the language all worked well (current 1.7)
And it's only package github.com/kataras/iris

**Comment by kataras** [comment]
How can I fix it? I'm not using delve lately..

**Comment by kataras** [comment]
Could you ,please, tell me how can I fix it? I'm not using delve lately..

**Comment by legion-zver** [comment]
panic: value for printf not a function
goroutine 1 [running]:
panic(0x47ddb80, 0xc420171130)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
text/template.addValueFuncs(0xc4201a8a80, 0xc4201a8a50)
	/usr/local/go/src/text/template/funcs.go:66 +0x41a
text/template.createValueFuncs(0xc4201a8a50, 0xc4201a8a50)
	/usr/local/go/src/text/template/funcs.go:54 +0x65
text/template.init()
	/usr/local/go/src/text/template/funcs.go:49 +0x8c2
html/template.init()

**Comment by kataras** [comment]
I don't think that's an Iris issue but I'll try to help you, please follow these steps: 
info: websocket.go ends on line 126 which has no code in this line.
**Recommendations**:
1. Unistall your Go and re-install it, maybe your local text/template has some issues 
2. **Remove** `$GOPATH/src/github.com/kataras & `$GOPATH/src/github.com/iris-contrib` and execute `go get -u github.com/kataras/iris` , try to run your code again if you get error again, continue to 3 & 4
3. Check your `/Users/Alexander/Documents/GoProjects/src/races/api/api_horse_owners.go` or write down it's source code in order to help you
4. write down your code snippet which you're using to set-up Iris

**Comment by kataras** [comment]
I don't think that's an Iris issue but I'll try to help you, please follow these steps: 
info: websocket.go ends on line 126 which has no code in this line.
**Recommendations**:
1. Unistall your Go and re-install it, maybe your local text/template has some issues 
2. **Remove** `$GOPATH/src/github.com/kataras` & `$GOPATH/src/github.com/iris-contrib` and execute `go get -u github.com/kataras/iris` , try to run your code again if you get error again, continue to 3 & 4
3. Check your `/Users/Alexander/Documents/GoProjects/src/races/api/api_horse_owners.go` or write down it's source code in order to help you
4. write down your code snippet which you're using to set-up Iris

**Comment by legion-zver** [comment]
thanks! the problem was to install a double delve. I initially set by brew, that did not work, and then according to the instructions and Brew version apparently interrupted the work of another version

**Comment by kataras** [comment]
You're welcome, happy coding!
