### ISSUE TITLE
Session not kept after rebooting

### ISSUE THREAD

**Issue by Allendar** [kataras/iris#414]
I'm using this instance configuration:

```
m = iris.New(iris.Configuration{
	IsDevelopment: true,
	DisableBanner: true,
	Gzip:          true,
	ProfilePath:   "/debug",
})
```

Every time I restart the server the session data is empty. In Gorilla Sessions you can set a session hash to maintain the sessions after restarting.

I'm using sessions through cookies.

How can this be achieved in Iris?

**Comment by kataras** [comment]
Yes, in Iris you can use a session database, read the docs and you will find a redis example

**Comment by Allendar** [comment]
Why did you close this issue? I meant that sessions with cookies didn't survive when the server was shut down and started again. The sessions expire or get made invalid for some reason. It's a question and at the same time a potential bug.

**Comment by kataras** [comment]
Sessions are kept in memory unless you use a session database like I told you before, there are examples that you can get help from, repository is here: https://github.com/iris-contrib/examples . If there is a bug post it but every time before I answer I check if your issue is valid or not, so I already test it, if you have more information to give me that's ok I am waiting for them but I can't help you more with that code snippet

**Comment by EtienneBruines** [comment]
Hmm, those are different things (sorry to dig up an old issue, but it's the same issue)

What @Allendar is talking about, is that the Gorilla Sessions allow you to store the session data at the client (using cookies). To make it somewhat secure, these are hashed by a secret hash on the server-side, so the client cannot alter it. 

In order to keep the sessions intact after server restart (super useful during development), one only needs to use the same hash as before, and one can read the cookie/session info. 

(Code here: https://github.com/gorilla/sessions/blob/master/store.go#L53 )

Is such a thing remotely possible? (without having to use an in-memory database like redis?) Something using only iris?

**Comment by Allendar** [comment]
Mostly what was important is the PHP/Apache(or Nginx) combo where after a restart you would still have the valid /someserver-dir/tmp/sessions/sess_2ec94b91da859daa02a9d440583b0a5f etc. files there to still able to act as valid sessions. In the current state all users get booted after every server-executable reboot.

**Comment by kataras** [comment]
I know the gorilla implementation, when I designed the sessions most people ask me this about cookie store support and I told, sorry no 'shits'  here. You can use leveldb or redis with Iris.
