### ISSUE TITLE
Context.ReadForm() does not handle multipart/form-data

### ISSUE THREAD

**Issue by adred** [kataras/iris#425]
So I posted a question about how to handle multipart/form-data here #424 and someone pointed me to see `Context.MultipartForm()`. I don't know what author means but I assume I'll have to handle the rest myself?

Anyway, I dug in and found out that `Context.ReadForm()` appears to handle multipart/form-data. However, in line 403 of context.go file:

`return errReadBody.With(formBinder.Decode(multipartForm.Value, formObject))` 

It's only processing `multipartForm.Value` which does not contain the `File` data. It's misleading as `Context.ReadForm()` does not deal with files at all while the documentation says it does. 

Can anyone please confirm? If I am missing something, please enlighten me.

**Comment by kataras** [comment]
@adred 

> It's misleading as Context.ReadForm() does not deal with files at all while the documentation says it does.

Where did you find this? The doc doesn't says that you can read files with ReadForm, the section is here: https://kataras.gitbooks.io/iris/content/request-body-bind.html . As docs says, supported types are:
```go
The supported field types in the destination struct are:

string
bool
int, int8, int16, int32, int64
uint, uint8, uint16, uint32, uint64
float32, float64
slice, array
struct and struct anonymous
map
interface{}
time.Time
url.URL
slices []string
custom types to one of the above types
a pointer to one of the above types
```

Secondly, 

> and someone pointed me to see Context.MultipartForm()

I pointed you there because you said that context.ReadForm doesn't fills your needs and you wanted to read files, `context.MultipartForm()` has a field for files, please look better next time, just type this with a dot `.` and you will see its fields in your code editor(if gocode is injected) 

Explain me what you want to do and why context.MultipartForm doesn't fills your needs, this is the only method you can get multipart/form-data manually and do whatever you want to do with these

**Comment by kataras** [comment]
Dear @adred 

> It's misleading as Context.ReadForm() does not deal with files at all while the documentation says it does.

Where did you find this? The doc doesn't says that you can read files with ReadForm, the section is here: https://kataras.gitbooks.io/iris/content/request-body-bind.html . As docs says, supported types are:
```go
The supported field types in the destination struct are:

string
bool
int, int8, int16, int32, int64
uint, uint8, uint16, uint32, uint64
float32, float64
slice, array
struct and struct anonymous
map
interface{}
time.Time
url.URL
slices []string
custom types to one of the above types
a pointer to one of the above types
```

So, please, better to change the title of this issue.  You already link your previous post issue, why you opened another one with the same question? 

Secondly, 

> and someone pointed me to see Context.MultipartForm()

I pointed you there because you said that context.ReadForm doesn't fills your needs and you wanted to read files, `context.MultipartForm()` has a field for files, please look better next time, just type this with a dot `.` and you will see its fields in your code editor(if gocode is injected) 

Explain me what you want to do and why context.MultipartForm doesn't fills your needs, this is the only method you can get multipart/form-data manually and do whatever you want to do with these

Cheers,
kataras
