### ISSUE TITLE
websocket config not work

### ISSUE THREAD

**Issue by chenshaobo** [kataras/iris#428]
```golang
ws := iris.Default.Websocket
iris.Default.Config.Websocket.ReadBufferSize = 10240
fmt.Printf("max:%v,ws pointer:%p default pointer:%p",ws.GetConfig().MaxMessageSize,ws.GetConfig(),iris.Default.Config.Websocket)
```
and the function GetConfig is  :
```golang
func (w *WebsocketServer) GetConfig() WebsocketConfiguration{
	return w.config
}
```

fmt print result:`max:0,ws pointer:%!p(iris.WebsocketConfiguration={0 0 0 0 false  0 0}) default pointer:%!p(iris.WebsocketConfiguration={0 0 0 10240 true /ws 10240 10240}) `

**Comment by kataras** [comment]
Dear @chenshaobo 

First of all, instead of `iris.Default.Websocket & Config` you can just use `iris.Websocket & iris.Config...` 

Secondly, Websocket source code ** doesn't have any GetConfig() function**, I don't know where did you find that, probably you have a very old Iris version, **solution**:

- Remove your `$GOPATH/src/github.com/kataras ` & `$GOPATH/src/github.com/iris-contrib`
- Open a shell, and execute: `go get -u github.com/kataras/iris/iris` 
- Re-run your application and you should be fine.

Cheers,
kataras

**Comment by chenshaobo** [comment]
@kataras  ,Thanks for your reply.
I current use Iris 4.2.2, which is websocket not work.
I think it is because :

**Comment by chenshaobo** [comment]
May be we should had a function to set WebsocketServer 's config before  `WebsocketServer.OnConnection ` is Invoked.

**Comment by kataras** [comment]
Docs says that correct, websocket configuration is setted before `iris.Listen` if that wasn't correct then the examples will not be able to run, but they run correctly...

**Comment by chenshaobo** [comment]
@kataras 
Yet,it can run.
But  set `iris.Default.Config.Websocket.ReadBufferSize = 10240` is not work
I set `iris.Config.Websocket.MaxMessageSize = 1024000`,but the [`Conn`](https://github.com/iris-contrib/websocket/blob/master/conn.go#L224) 's `readLimit` still is 1024 .

**Comment by kataras** [comment]
On iris-contrib/websocket you have right, because it's initialize on the first `OnConnection` no before `Listen`, https://github.com/kataras/iris/blob/master/websocket.go#L95 but general websocket config is working, now , the issue is visible and we can fix it, I will respond back, thank you!

**Comment by kataras** [comment]
Fixed, Fixed: https://github.com/kataras/go-websocket/commit/bfb19718e7dca519a9eb48e277c33f45a24b63b8 and https://github.com/kataras/iris/commit/60947d4f21df2caf4e5f913f618eaa69ac88d30e Thanks!
