### ISSUE TITLE
Is Redis 's Session MaxAgeSeconds  not working ?

### ISSUE THREAD

**Issue by jinfei** [kataras/iris#431]
Hello.I found a problem with redis session
//main.go
	restore := redis.New(service.Config{
		Network:       service.DefaultRedisNetwork,
		Addr:          service.DefaultRedisAddr,
		Password:      "",
		Database:      "",
		MaxIdle:       0,
		MaxActive:     0,
		IdleTimeout:   service.DefaultRedisIdleTimeout,
		Prefix:        "small",
		MaxAgeSeconds: 10}) 
iris.UseSessionDB(restore)

//middle.go
func CheckLogin(c *iris.Context) {

	url := c.RequestPath(true)
	user_id, _ := strconv.Atoi(c.Session().GetString("user_id"))
	fmt.Println("user_id", user_id)

	c.Next()

}

After 10 Seconds on my redis-cil

127.0.0.1:6379> keys *
(empty list or set)

But in the use of middleware can also print values

**Comment by kataras** [comment]
Yes, because you have setted the redis configuration, this configuration is only for redis 'behind' database . The session's expires can be set with the session's `Expires`,  `iris.Config.Sessions.Expires`, this will `Destroy` the session after 10 seconds of it's init (first call of `ctx.Session()`)

**Comment by kataras** [comment]
Dear @jinfei 

Yes, because you have setted the redis configuration, this configuration is only for redis 'behind' database . The session's expires can be set with the session's `Expires`,  `iris.Config.Sessions.Expires`, this will `Destroy` the session after 10 seconds of it's init (first call of `ctx.Session()`) .

Please post next issues about sessions, here: https://github.com/kataras/go-sessions

Cheers,
kataras

**Comment by jinfei** [comment]
@kataras   
Thank you for you helping . 
I think I can tell the difference between the two.
