### ISSUE TITLE
panic: listen tcp4 127.0.0.1:7070: bind: address already in use

### ISSUE THREAD

**Issue by chengshihard** [kataras/iris#439]
When I save the changes
panic: listen tcp4 127.0.0.1:7070: bind: address already in use

goroutine 1 [running]:
panic(0xaadc40, 0xc4202c6090)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
log.(*Logger).Panic(0xc42029c820, 0xc4201f1ce0, 0x1, 0x1)
	/usr/local/go/src/log/log.go:206 +0xc7
github.com/kataras/iris.(*Framework).Must(0xc42008cb40, 0xeffea0, 0xc4202c0050)
	/home/crazyboy/golang/src/github.com/kataras/iris/iris.go:470 +0xcf
github.com/kataras/iris.(*Framework).Listen(0xc42008cb40, 0xbb1524, 0xe)
	/home/crazyboy/golang/src/github.com/kataras/iris/iris.go:546 +0x10c
github.com/kataras/iris.Listen(0xbb1524, 0xe)
	/home/crazyboy/golang/src/github.com/kataras/iris/iris.go:537 +0x41
main.main()
	/home/crazyboy/golang/src/basic/backend/main.go:67 +0x263

I get this information

**Comment by jinfei** [comment]
I've had this problem too.Can only close the original process, restar a new process

**Comment by kataras** [comment]
Dear @chengshihard  and @jinfei 

So the problem is with [rizla](https://github.com/kataras/rizla) using `iris run` command, it doesn't closes the previous proc instance, could you please give me more information, such as
1. you're running on Windows? Mac? BSD? Ubuntu? 

2. Did you tried to do that, before posting the issue?: 

Delete`$GOPATH/src/github.com/kataras` , open shell and execute the command: `go get -u github.com/kataras/iris/iris` 

Thanks,
kataras

**Comment by kataras** [comment]
Dear @chengshihard  and @jinfei 

So the problem is with [rizla](https://github.com/kataras/rizla) using `iris run` command, it doesn't closes the previous proc instance, could you please give me more information, such as
1. you're running on Windows? Mac? BSD? Ubuntu? 


2. Did you tried to do that, before posting the issue?: 

Delete`$GOPATH/src/github.com/kataras` , open shell and execute the command: `go get -u github.com/kataras/iris/iris` 

Thanks,
kataras

**Comment by kataras** [comment]
Dear @chengshihard  and @jinfei 

So the problem is with [rizla](https://github.com/kataras/rizla) using `iris run` command, it doesn't closes the previous proc instance, could you please give me more information, such as
- you're running on Windows? Mac? BSD? Ubuntu? 


- . Did you tried to do that, before posting the issue?: 

Delete`$GOPATH/src/github.com/kataras` , open shell and execute the command: `go get -u github.com/kataras/iris/iris` 

Thanks,
kataras

**Comment by chengshihard** [comment]
go get -u github.com/kataras/iris/iris   
We get version 4.3.0

My system is: Ubuntu 16.04.1 LTS

I still did not solve the problem

**Comment by kataras** [comment]
Dear, are you sure you removed the previous kataras folder from your `$GOPATH/src/github.com/kataras` ?

**Comment by chengshihard** [comment]
Yes, I'm sure.
I downloaded it again.

**Comment by kataras** [comment]
The issue is not Iris, it's kataras/rizla, because of this I told you to remove the folder and re-download, I have ubuntu 16.04 with fresh install and it works, could you open this issue here too: https://github.com/kataras/rizla so I can look it further when I have more time?

Until we fix the issue, temporary, run your app with the `go run main.go` not `iris run main.go`

**Comment by chengshihard** [comment]
OK, Come on boy

**Comment by kataras** [comment]
Be sure that you have starred or watched the iris or rizla repository in order to be notified for a fix,soon,  thank you
