### ISSUE TITLE
Where is wrong??

### ISSUE THREAD

**Issue by raysole** [kataras/iris#442]
2016/09/27 14:31:14 error when serving connection "127.0.0.1:80"<->"127.0.0.1:62
259": error when reading request headers: need more data: cannot find trailing l
f. buf="\xfeE\x00\x00E\x01\x00 \x05\x015\x99\xdd֖\x00\x01\f\x000\x01\x9fxL\xae\
x81\xbc\xe6\x0e5ѵ\x85\tj\x90\x19\xd7\xe0 C\t\x14\x13\"\xe4W,!\x1b\x8f\xb6`\xa6\
x94t8\ty\xbcNY5F\xba\xc0q\x15\x00&\x02\r\xfeE\x00\x00E\x01\x00 \x05\x015\x99\xdd
֖\x00\x01\f\x000\x01\x9fxL\xae\x81\xbc\xe6\x0e5ѵ\x85\tj\x90\x19\xd7\xe0 C\t\x1
4\x13\"\xe4W,!\x1b\x8f\xb6`\xa6\x94t8\ty\xbcNY5F\xba\xc0q\x15\x00&\x02\r\xfeE\x0
0\x00E\x01\x00 \x05\x015\x99\xdd֖\x00\x01\f\x000\x01\x9fxL\xae\x81\xbc\xe6\x0e5
ѵ\x85\tj\x90\x19\xd7\xe0 C\t\x14\x13\"\xe4W,!\x1b\x8f\xb6`\xa6\x94t8\ty\xbcNY5F
\xba\xc0q\x15\x00&\x02\r\xfeE\x00\x00E\x01\x00 \x05\x015\x99\xdd֖\x00\x01\f\x00
0\x01\x9fxL\xae\x81\xbc\xe6\x0e5ѵ\x85\tj\x90\x19\xd7\xe0 C\t\x14\x13\"\xe4W,!\x
1b\x8f\xb6`\xa6\x94t8\ty\xbcNY5F\xba\xc0q\x15\x00&\x02\r"...""

**Comment by kataras** [comment]
I will reply the way you ask,

Nothing is wrong, 

First, go to [fasthttp](https://github.com/valyala/fasthttp), update your fasthttp repo and read the older issue, this happens because you made some shit and unsafe staff on the `Response.Header` 

Secondly, the next time provide a better title next time and give more information about your issue, such as the Operating system, Iris version... as the [CONTRIBUTING.md](https://github.com/kataras/iris/blob/master/CONTRIBUTING.md) prompts you to the top corner before post a new issue

**Comment by kataras** [comment]
I will reply the way you ask,

Nothing is wrong, 

First, go to [fasthttp](https://github.com/valyala/fasthttp), update your fasthttp repo and read the older issue, this happens because you made some shit and unsafe staff on the `Response.Header` 

Secondly, the next time provide a better title and give more information about your issue, such as the Operating system, Iris version... as the [CONTRIBUTING.md](https://github.com/kataras/iris/blob/master/CONTRIBUTING.md) prompts you to the top corner before submit a new issue.

**Comment by raysole** [comment]
updated iris ,, is not work...

**Comment by kataras** [comment]
Did you see? I didn't say to update iris

**Comment by raysole** [comment]
ok,i didn't say this is a bug, why do you have this hint?

**Comment by kataras** [comment]
Because I don't accept this type of post issue form, you didn't wrote when this error causes, you didn't give me your iris version, you didn't wrote the Operating System, you didn't write the golang version, all these are written in the CONTRIBUTING that github shows you before submit a new issue...

**Comment by kataras** [comment]
Because I don't accept this type of post issue form, you didn't wrote when this error causes, you didn't give me your iris version, you didn't wrote the Operating System, you didn't write the golang version, you didn't read other post issues, because this is asked many many times and you should search before posting a new. All these logical statements, are written in the CONTRIBUTING that github shows you before submit a new issue...

**Comment by kataras** [comment]
I'm writing you the solution and you reply like you didn't read that, you say about updating iris but I never said that here.

Also from the begging, you made a bad start, very bad start: you didn't wrote when this error causes, you didn't give me your iris version, you didn't wrote the Operating System, you didn't write the golang version, you didn't read other post issues, because this is asked many many times and you should search before posting a new. All these logical statements, are written in the CONTRIBUTING that github shows you before submit a new issue.
