### ISSUE TITLE
ReadJSON don't decode. Json Raw Data is OK.

### ISSUE THREAD

**Issue by celsosz** [kataras/iris#444]
Hi everyone!

The ReadJSON() function is not properly decoding. Notice that the HTTP Raw Data is correct. Can someone help me?

The "j.value" is blank. I already made some tests using "json.NewDecoder(strings.NewReader(string(data))" function.

Sorry for my english.

-----------BEGIN-----------

func POSTNewFeedEntry(ctx *iris.Context) {

	// json request
	type JSONPostFeedEntry struct {
		value string
	}

	//
	fmt.Println("-------------------------------")
	fmt.Println(ctx.Request.String())
	fmt.Println("-------------------------------")

	// obtem campos do header http
	XAccessToken := ctx.RequestHeader("x-access-token")
	XIdProfile := ctx.RequestHeader("x-id-profile")

	// usuario autenticado?
	if validAccessToken(XAccessToken, XIdProfile) {

		// vamos tratar o json recebido

		// estrutura para receber o json vindo da App
		j := &JSONPostFeedEntry{}

		// debug info
		data := ctx.RequestCtx.Request.Body()
		fmt.Printf("json string: %s\n", string(data[:]))

		// lendo json do body
		if err := ctx.ReadJSON(j); err != nil {
			// erro
			fmt.Println("erro em ctx.ReadJSON: ", err.Error())
		} else {

			// j.value is blank!!!
			fmt.Println("value: (", j.value, ")")

		}

	} else {

		//
		fmt.Println("access token inVALIDO - nao autenticado")

		//
		replyNotValidXAuth(ctx)

	}

}

-----------END-----------

-------------------------------
POST /api/v1/newfeedentry HTTP/1.1
User-Agent: -/1.0 (com.-.-; build:1; iOS 10.0.0) Alamofire/4.0.0
Host: 192.168.0.15:8080
Content-Type: application/json
Content-Length: 16
X-Access-Token: 2r&5HCR2sqcx}VqJM|wjQ5bo:|rg5=J/3ETllTp?.(*Jd82FLzJ;j/ze0@/!qt(Hf
Accept: */*
Connection: keep-alive
X-Id-Profile: 5
Accept-Language: en;q=1.0
Accept-Encoding: gzip;q=1.0, compress;q=0.5

{"name":"Celso"}
-------------------------------
json string: {"name":"Celso"}
value: (  )

**Comment by celsosz** [comment]
Fixed! Thanks.

**Comment by kataras** [comment]
There was never problem with ReadJSON but could you please share your steps with other users?, how you 'fix' that?

Thank you!!

**Comment by celsosz** [comment]
It is a strange solution. The variable's first character MUST BE in uppercase. Notice 'Value string' below. I made some tests, all of them only work using uppercase on first character (of course, you can use uppercase in middle too). I don't know why that. Maybe is a Golang mandatory syntax for "json.NewDecoder()" function.

// json request
type JSONPostFeedEntry struct {
    Value string
    FirstName string // OK
    lastName string // error!!!
}

I am a newbie in Golang, so ...

If you can help me ...

I am developing a backend server for an App. So far so good. You deserve a Donation for your Iris package. I will do that.

Best regards,
Celso.

**Comment by kataras** [comment]
Yes, go docs says that in order to encode json  all variables should be Uppercase(exported) otherwise this shouldn't work, encode JSON is using reflection, this is a general golang thing.

I can help you any time, this is all I do. I left from my colleague to develop iris and relative projects.

We have a chat too: https://kataras.rocket.chat/channel/iris discuss there anything you want :) 

About the donation, I will respect it, but it's ok if you don't, I will help you in both situations as I do for other users too :)

**Comment by kataras** [comment]
I just notified that you had already donated... thank you very much.

I have to ask you if you want/or don't have any problem if I make your donation public like I did with other donators here: 
 
https://github.com/kataras/iris/blob/master/DONATIONS.md#donors .

**Comment by kataras** [comment]
I just notified that you had already donated... thank you very very much, people are not usually donate to open source projects, you are very responsible.

I have to ask you if you want/or don't have any problem if I make your donation public like I did with other donators here: 
 
https://github.com/kataras/iris/blob/master/DONATIONS.md#donors . 

We have a special chat room for people who donated to Iris, could you please join to this channel:  https://kataras.rocket.chat/channel/iris in order to find your name and add you to the 'donors' group?
