### ISSUE TITLE
Custom Server name 

### ISSUE THREAD

**Issue by fungl164** [kataras/iris#447]
Hi,

It used to be the case that the server name could be set as part of the configuration.  Right now it seem fixed to ```DefaultServerName = "iris"``` which is a constant.  Will you make this an option again?

Thanxs!

**Comment by kataras** [comment]
Hello @fungl164 

I know that you can't understand my position, but I will explain to you, please do not misunderstood me, my english are not the best: I see that you even not starred Iris, you know that I left from my colleague to work explicit, as 'full-time job' to this framework? If you can't afford (or simply don't want to do )a small donation, at least star the repository before ask something like this.

Reasons I have that to const instead of var: Something must be 'visible' in order to understand which sites are using Iris.

A middle solution will be to add a ServerName but with a preffix of "iris_", is that ok with you, my friend?

Cheers,
kataras
