### ISSUE TITLE
Related to paths ending with '/' in iris.party

### ISSUE THREAD

**Issue by ansrivas** [kataras/iris#453]
Hi, 
First of all thank you for this wonderful implementation and the documentation.

I am trying to implement a simple example using `party`. I am a bit confused with the case of `POST` request.

Post requests to: 
- `http://localhost:8080/beta` doesn't work obviously. 
- `http://localhost:8080/beta/`  works as I have registered a `POST` handler with `/` 

Is there any recommended way to handle this particular case ?

Here is the code which I am currently using:
```
package main

import (
	"github.com/iris-contrib/middleware/logger"
	"github.com/kataras/iris"
)

func setupLogger() iris.HandlerFunc {
	return logger.New(logger.Config{
		// Status displays status code
		Status: true,
		// IP displays request's remote address
		IP: true,
		// Method displays the http method
		Method: true,
		// Path displays the request path
		Path: true,
	})
}

func main() {

	// api := iris.New(iris.OptionDisablePathCorrection(false))
	api := iris.New()

	errorLogger := setupLogger()
	api.Use(errorLogger)

	beta := api.Party("/beta")
	{
		beta.Post("/", func(c *iris.Context) { c.Write("hey from POST /beta") })
		// beta.Get("/", func(c *iris.Context) { c.Write("hey from /beta") })
		beta.Get("/hey", func(c *iris.Context) { c.Write("hey from /beta/hey") })
		beta.Post("/hey", func(c *iris.Context) { c.Write("hey from /beta/hey") })
	}

	api.OnError(iris.StatusNotFound, func(ctx *iris.Context) {
		errorLogger.Serve(ctx)
		ctx.Write("My Custom 404 error page ")
	})
	api.Listen(":8080")
}

```

**Comment by kataras** [comment]
Hello @ansrivas , thanks for your nice words, I do my bests,

If you haven't disabled the path correction, `/path` and `/path/` should be navigate to your `/path` handler , this is a bug caused by last changes if it's not worked, let me test it first

Thanks,
kataras

**Comment by kataras** [comment]
Hello @ansrivas , thanks for your nice words, I do my bests,

Look, it's working but not 100% correctly, as you expected,  but your "/beta/" redirects to "/beta" why you said that it was not found?  anyway the expected behavior was to be registered as "/beta", if path correction is not disabled, I fixed that but I have to make some internal tests before commit the changes, you will be notified from this post, it was a 'party unexpected behavior' issue 
Thanks,
kataras

**Comment by ansrivas** [comment]
Hi @kataras , 

Thanks for the quick response. I tried the new release.  Removed the `iris` dir from `$GOPATH` and installed the new version.

So, just to clarify once, w.r.t `iris` design,  : ( remaining code similar to above )
(*with default path correction*)

```
func main() {
    api := iris.New()

    errorLogger := setupLogger()
    api.Use(errorLogger)

    beta := api.Party("/beta")
    {
        beta.Post("/", func(c *iris.Context) { c.Write("hey from POST /beta") })
    }

    api.OnError(iris.StatusNotFound, func(ctx *iris.Context) {
        errorLogger.Serve(ctx)
        ctx.Write("My Custom 404 error page ")
    })
    api.Listen(":8080")
}
```

Post request example 1:

```python
In [76]: res = requests.post("http://localhost:8080/beta", data={1:"1"})

In [77]: res.text, res.status_code
Out[77]: (u'hey from POST /beta', 200)
```

Post request example 2:
- Path correction not applied ?? ( A bit confusing here, as from above I understood `NON-GET` methods will also behave like `GET` methods. ).
It also gets redirected to `GET` handler

```python
In [78]: res = requests.post("http://localhost:8080/beta/", data={1:"1"})

In [79]: res.text, res.status_code
Out[79]: (u'My Custom 404 error page ', 404)
```

Logs:
```
[IRIS] 2016/10/02 15:32:18 10/02 - 15:32:18 404 156ns 127.0.0.1 GET /beta
```

**Comment by kataras** [comment]
@ansrivas You're welcome, in order to understand I'll give you some statements:

If path correction == true 

  if `/beta` registered but `/beta/` requested then the server sends a StatusMovedPermantly(301)` to the client in order to redirect to the `/beta` 
  
 if `/beta/` registered but `/beta` requested then the server sends a StatusMovedPermantly(301)` to the client in order to redirect to the `/beta/`

end 

if path correction == false 

  if `/beta` registered but `/beta/` requested then the server sends a NOT FOUND (404)
  
  if `/beta/` registered but `/beta` requested then the server sends a  NOT FOUND (404)

end

So on POST methods because you can't test it from browser,GET it depends on your client if it's **ALLOWING/FOLLOW REDIRECTS** then the `request /beta/` goes STATUS 200 to `route /beta` else it shows a NOT FOUND (404). In that I can't help you, it depends from the client what to do with the 301 moved permanently (redirect) status

**Comment by kataras** [comment]
@ansrivas You're welcome, in order to understand I'll give you some statements:

If path correction == true 

  if `/beta` registered but `/beta/` requested then the server sends a StatusMovedPermantly(301)` to the client in order to redirect to the `/beta` 
  
 if `/beta/` registered but `/beta` requested then the server sends a StatusMovedPermantly(301)` to the client in order to redirect to the `/beta/`

end 

if path correction == false 

  if `/beta` registered but `/beta/` requested then the server sends a NOT FOUND (404)
  
  if `/beta/` registered but `/beta` requested then the server sends a  NOT FOUND (404)

end

So on POST methods because you can't test it from browser's navigation bar(GET) it depends on your client if it's **ALLOWING/FOLLOW REDIRECTS** then the `request /beta/` goes STATUS 200 to `route /beta` else it shows a NOT FOUND (404). In that I can't help you, it depends from the client what to do with the 301 moved permanently (redirect) status

**Comment by kataras** [comment]
@ansrivas You're welcome, in order to understand I'll give you some statements:

If path correction == true 

  if `/beta` registered but `/beta/` requested then the server sends a StatusMovedPermantly(301)` to the client in order to redirect to the `/beta` 
  
 if `/beta/` registered but `/beta` requested then the server sends a StatusMovedPermantly(301)` to the client in order to redirect to the `/beta/`

end 

if path correction == false 

  if `/beta` registered but `/beta/` requested then the server sends a NOT FOUND (404)
  
  if `/beta/` registered but `/beta` requested then the server sends a  NOT FOUND (404)

end

It depends on the client side what to do with the 301 MOVED Permantly status.
All browsers understand the 301 status and redirects to the correct path with the 200 OK status. 

It depends on what client you're using, most of the clients follows redirects on `GET` methods, like browsers, but for POST methods you have to make a research or implement that by yourself, it's a client-side job. You can lookup for an option like**ALLOWING/FOLLOW REDIRECTS**, if that's true then the `request /beta/` goes STATUS 200 to `route /beta` else it shows a NOT FOUND (404). In that I can't help you, it depends from the client what to do with the 301 moved permanently (redirect) status

**Comment by kataras** [comment]
@ansrivas You're welcome, in order to understand I'll give you some statements:

If path correction == true 

  if `/beta` registered but `/beta/` requested then the server sends a StatusMovedPermantly(301)` to the client in order to redirect to the `/beta` 
  
 if `/beta/` registered but `/beta` requested then the server sends a StatusMovedPermantly(301)` to the client in order to redirect to the `/beta/`

end 

if path correction == false 

  if `/beta` registered but `/beta/` requested then the server sends a NOT FOUND (404)
  
  if `/beta/` registered but `/beta` requested then the server sends a  NOT FOUND (404)

end

It depends on the client side what to do with the 301 MOVED Permantly status.
All browsers understand the 301 status and redirects to the correct path with the 200 OK status. 

It depends on what client you're using, most of the clients follows redirects on `GET` methods, like browsers, but for POST methods you have to make a research or implement that by yourself, it's a client-side job. You can lookup for an option like**ALLOWING/FOLLOW REDIRECTS**, if that's true then the `request /beta/` goes STATUS 200 to `route /beta` else it shows a NOT FOUND (404). 

For example the `curl` supports follows (you can find the command line flag if you do a small research on google),  `curl_setopt($curl, CURLOPT_FOLLOWLOCATION, true);`  resource: http://stackoverflow.com/a/22297856  

Hope that I helped you to understand the bigger picture and how HTTP works at general

**Comment by kataras** [comment]
@ansrivas You're welcome, in order to understand I'll give you some statements:

If path correction == true 

  if `/beta` registered but `/beta/` requested then the server sends a StatusMovedPermantly(301)` to the client in order to redirect to the `/beta` 
  
 if `/beta/` registered but `/beta` requested then the server sends a StatusMovedPermantly(301)` to the client in order to redirect to the `/beta/`

end 

if path correction == false 

  if `/beta` registered but `/beta/` requested then the server sends a NOT FOUND (404)
  
  if `/beta/` registered but `/beta` requested then the server sends a  NOT FOUND (404)

end

It depends on the client side what to do with the 301 MOVED Permantly status.
All browsers understand the 301 status and redirects to the correct path with the 200 OK status. 

It depends on what client you're using, most of the clients follows redirects on `GET` methods, like browsers, but for POST methods you have to make a research or implement that by yourself, it's a client-side job. You can lookup for an option like**ALLOWING/FOLLOW REDIRECTS**, if that's true then the `request /beta/` goes STATUS 200 to `route /beta` else it shows a NOT FOUND (404). 

For example the `curl` supports follows (you can find the command line flag if you do a small research on google),  `curl_setopt($curl, CURLOPT_FOLLOWLOCATION, true);`  resource: http://stackoverflow.com/a/22297856  

To make sure that your POST routes will listen on every redirection, because of the 301 moved, tries to redirect to the `GET`, so make sure that you have registered an `iris.Get` which executes the post method (if was redirected, you can see it by ref header when == "localhost:8080/beta/" ), 

```go
	betaPost :=  func(c *iris.Context) { c.Write("hey from POST /beta") }
	beta := api.Party("/beta")
	{
		beta.Post("/",betaPost)
		beta.Get("/", func(c *iris.Context) {  if allowLogic { betaPost(ctx)}})
		beta.Get("/hey", func(c *iris.Context) { c.Write("hey from /beta/hey") })
		beta.Post("/hey", func(c *iris.Context) { c.Write("hey from /beta/hey") })
	}
```



Hope that I helped you to understand the bigger picture and how HTTP works at general

**Comment by kataras** [comment]
@ansrivas You're welcome, in order to understand I'll give you some statements:

If path correction == true 

  if `/beta` registered but `/beta/` requested then the server sends a StatusMovedPermantly(301)` to the client in order to redirect to the `/beta` 
  
 if `/beta/` registered but `/beta` requested then the server sends a StatusMovedPermantly(301)` to the client in order to redirect to the `/beta/`

end 

if path correction == false 

  if `/beta` registered but `/beta/` requested then the server sends a NOT FOUND (404)
  
  if `/beta/` registered but `/beta` requested then the server sends a  NOT FOUND (404)

end

It depends on the client side what to do with the 301 MOVED Permantly status.
All browsers understand the 301 status and redirects to the correct path with the 200 OK status. 

It depends on what client you're using, most of the clients follows redirects on `GET` methods, like browsers, but for POST methods you have to make a research or implement that by yourself, it's a client-side job. You can lookup for an option like**ALLOWING/FOLLOW REDIRECTS**, if that's true then the `request /beta/` goes STATUS 200 to `route /beta` else it shows a NOT FOUND (404). 

For example the `curl` supports follows (you can find the command line flag if you do a small research on google),  `curl_setopt($curl, CURLOPT_FOLLOWLOCATION, true);`  resource: http://stackoverflow.com/a/22297856  

To make sure that your POST routes will listen on every redirection, because of the 301 moved, tries to redirect to the `GET`, so make sure that you have registered an `iris.Get` which executes the post method (if was redirected, you can see it by ref header when == "localhost:8080/beta/" ), 

```go
	betaPost :=  func(c *iris.Context) { c.Write("hey from POST /beta") }
	beta := api.Party("/beta")
	{
		beta.Post("/",betaPost)
		beta.Get("/", func(c *iris.Context) {  if allowLogic { betaPost(c)}})
		beta.Get("/hey", func(c *iris.Context) { c.Write("hey from /beta/hey") })
		beta.Post("/hey", func(c *iris.Context) { c.Write("hey from /beta/hey") })
	}
```



Hope that I helped you to understand the bigger picture and how HTTP works at general

**Comment by kataras** [comment]
That is a redirect-status-related issue , 301 moves to GET and forgets any POST data, I changed that to 307 http redirect status in order to keep the post-data and the method if the requested method  was POST, PUT or DELETE, but it's a temporary redirection instead of permanently as 301.

Try to upgrade again, and keep note that these status are sent from the server to the client, but the action depends on the client-side, `curl` for example has an option for **FOLLOW/ALLOW REDIRECTS**, `postman` has too, if you're designed your own client-side make sure you check for redirect http status, you can do a research on google, if you need any help I'm here,  thank you!

**Comment by kataras** [comment]
That is a redirect-status-related issue , 301 moves to GET and forgets any POST data, I changed that to 307 http redirect status in order to keep the post-data and the method if the requested method  was POST, PUT or DELETE, but it's a temporary redirection instead of permanently as 301.

Try to upgrade again, and keep note that these status are sent from the server to the client, but the action depends on the client, `curl` for example has an option for **FOLLOW/ALLOW REDIRECTS**, `postman` has too, if you're designed your own client-side make sure you check for redirect http status, you can do a research on google, if you need any help I'm here,  thank you!

**Comment by kataras** [comment]
That is a redirect-status-related issue , 301 moves to GET and forgets any POST data, I changed that to 307 http redirect status in order to keep the post-data and the method if the requested method  was POST, PUT or DELETE, but it's a temporary redirection instead of permanently as 301.

Try to upgrade again, and keep note that these status are sent from the server to the client, but the action depends on the client, `curl` for example has an option for **FOLLOW/ALLOW REDIRECTS**, `postman` has too, if you're designed your own clientmake sure you check for redirect http status, you can do a research on google, if you need any help I'm here,  thank you!

**Comment by skyflyer** [comment]
@kataras, I am puzzled by this design decision. Perhaps I don't understand how this feature is supposed to work. :)

Let's say I have a path configured like `p := api.Party("/some")` and then register a handler for `/` with `p.Get("/", func (ctx *iris.Context) { c.WriteString("Hi from /some/ root!") }`, the server is only responding to `/some` and returning 404 on `/some/`. 

To rephrase: If I leave the setting `DisablePathCorrection` to the default value (`false`), Iris will register above endpoint as `/some` instead of `/some/` as defined. I would expect that route registration would not be affected by path correction functionality, only route resolution.

Your thoughts on this?

**Comment by kataras** [comment]
> To rephrase: If I leave the setting DisablePathCorrection to the default value (false), Iris will register above endpoint as /some instead of /some/

If default value(false) on DisablePathCorrection, then /some/ is /some, BUT for the client it's the same,  client can request both /some/  and /some, if DisablePathCorrection is true then /some/ is requested only as /some/ and /some only as /some/ , the DisablePathCorrection to false is needed only when you want to register different handlers for /some and other handler for /some/ , what's the issue with this?

**Comment by kataras** [comment]
You have right, there is no need for something like this anymore, although it shouldn't be a problem because if you want to register different handlers for /some and /some/ then you should turn on the `DisablePathCorrection`, otherwise let it as default and bot /some and /some/ will be served from the /some's handler

**Comment by kataras** [comment]
@skyflyer  If you don't want to disable`PathCorrection` , but you don't want to register your **Party's root path /** as `/some`, but as `/some/` , you can now(v4.4.6) just pass double `//` `p:= api.Party("/some"); p.Get("//")`

**Comment by kataras** [comment]
@skyflyer Before this post issue, the party's root "/" was registered as you register it with `/some/` if Party("/some").Get("/") but @ansrivas  points me that was not the expected behavior (maybe optical yes, but like your app's root "/" it's not requested as localhost/ but as localhost, then the party's roots have also follow this rule). 

You can always disable this behavior with `DisablePathCorrection = true` 

**but**  If you don't want to disable`PathCorrection` , and you don't want to register your **Party's root path /** as `/some`, but as `/some/` , you can now(v4.4.6) just pass double `//` `p:= api.Party("/some"); p.Get("//")`.

So with these changes you can act to your party's root path as you desired while keeping path correction enabled, I hope I fill your needs and your question

**Comment by skyflyer** [comment]
@kataras you are very very quick :)

In my humble opinion, there is a little confusion here, especially now that you've added double slash registration. In my opinion, we should put this up for debate with the rest of the community (if they will want to chime in). Also note, that I don't think we really need "path correction functionality", but I don't mind if it is there. In essence, how I would _expect_ the framework to behave is:

## Path correction enabled

### Route URL is `/some`

1. `iris.Path` would return `/some` for the URL matching this route
1. The client request to `/some` would match
1. The client request to `/some/` would fail (see my remarks below)

### Route URL is `/some/` or party is `/some` and party's get/post is `/`

This scenario covers the situation where the handler is registered with `iris.Get("/some/", handler)` or where the handler is registered within a party:
```go
p := iris.Party("/some")
p.Get("/", handler)("routname")
```

1. `iris.Path` would return `/some/`
1. The client request to `/some/` would match
1. The client request to `/some` would fail, but since path correction is enabled, Iris would look up and see that `/some/` is registered and invoke that handler

> N.B.: path correction should only be applied to URL resolving/matching, not to URL construction.

## Path correction disabled

Essentially same as above, expect that the the last case would fail always (since it is not an exact match)

## Some further thoughts / brainstorming

I think that path correction functionality should not affect `iris.URL` or `iris.Path` or route registration methods (`iris.Get`, `iris.Post`, etc). If at all, it should only be applied to URLs not ending with `/` to add an optional `/` and only in cases where the original is not found. That would make it easy to understand and use.

Lastly, I personally don't use path correction as I rely on `iris.Path` for the path generation, so all of the URLs are correct. But that is just a personal view.
