### ISSUE TITLE
named parameter bug

### ISSUE THREAD

**Issue by hiEven** [kataras/iris#454]
## code for reproducing

```go
func apple(ctx *iris.Context) {
	fmt.Println("apple")
}

func fruit(ctx *iris.Context) {
	fmt.Println("fruit")
}

func main() {
  iris.Get("/pen/apple", apple)
  iris.Get("/pen/:fruit", fruit)
  iris.Listen(":" + config.Port)
}
```

## expect
`GET /pen/apple`: the terminal shows "apple"
`GET /pen/pineapple`: the terminal shows "fruit"

## problem
`GET /pen/apple`: the terminal shows "apple" correctly
`GET /pen/pineapple`: the terminal shows nothing and server gives me a 404 not found

## appendix
if I do `# iris.Get("/pen/apple", apple)`, then the terminal shows "fruit" correctly and that's the reason why I think there might be some bugs in `named route register`. 

## iris version
4.4.0

**Comment by kataras** [comment]
Hi @hiEven 

It's not a bug, it's expected behavior, if you had read older post issues or the gitbook (which is noticed that you can't have static and named parameter in the same path, for your own good) you should already know this 

However, thanks for posting and your interest,
kataras

**Comment by kataras** [comment]
Hi @hiEven 

It's not a bug, it's expected behavior, if you had read older post issues or the gitbook (which is noticed that you can't have static and named parameter in the same path, for your own good) you should already know this.

As I wrote to previous posts, if you want to have static and named parameters in the same path, you should use wildrcard `*` .for example:


```go
iris.Get("/pen/*path", func(ctx *iris.Context){
    path := ctx.Param("path")
    if path == "apple" {
         handleStaticApple(ctx)
    }else {
         handleDynamicFruit(ctx)
    }

})
```

However, thanks for posting and your interest,
kataras

**Comment by kataras** [comment]
Hi @hiEven 

It's not a bug, it's expected behavior, if you had read older post issues or the gitbook (which is noticed that you can't have static and named parameter in the same path, for your own good) you should already know this.

As I wrote to previous posts, if you want to have static and named parameters in the same path, you should use wildrcard `*` .for example:


```go
iris.Get("/pen/*path", func(ctx *iris.Context){
    path := ctx.Param("path")
    if path == "/apple" {
         handleStaticApple(ctx)
    }else {
         handleDynamicFruit(ctx)
    }

})
```

However, thanks for posting and your interest,
kataras

**Comment by hiEven** [comment]
wow, thanks for the quick reply. 👍

**Comment by kataras** [comment]
You're welcome, happy coding :)
