### ISSUE TITLE
Tests for main.go

### ISSUE THREAD

**Issue by itsbalamurali** [kataras/iris#458]
Hi @kataras ,

Can you help with writing tests for main.go https://gist.github.com/itsbalamurali/d097ae09ece5ea375fe1c1694ab7a4ce#file-main-go
and for files controller.
unable to execute the main.go file 
Screenshot: https://cl.ly/0i2E2y3M1h3m

**Comment by kataras** [comment]
Hi @itsbalamurali 
I see... you want closed-personal help for your project and you ask this on the github repo's issue list.... 
I want to help everybody personally, on each of their projects, but I can't do that, I don't have so much time. However there are articles on internet who can help you test your app with iris and httpexpect( you can navigate to the Iris web chat [here](https://kataras.rocket.chat/channel/iris) and see some of these articles in the history, as links, if the articles don't helps then you can ask for help from other iris users)

But If I was you, I could do a simple search on this github repository, which contains some tests. I could see the [http_test.go](https://github.com/kataras/iris/blob/master/http_test.go)  in order to understand  how the author of this project writes its tests. I hope I helped you enough. A code snippet which may helps you :  ` e:= iris.Tester(t *testing.T); e.Request("GET", "http://"+host).Expect().Status(iris.StatusOK).Body().Equal("something")` 

Keep note that as I saw you used net/http http recorder to build your tests, but the README page of this repository on the [TESTING](https://github.com/kataras/iris#testing) section says that you have to use httpexpect instead, iris is NOT based on net/http

Thanks,
kataras

**Comment by kataras** [comment]
Hi @itsbalamurali 

There are many examples on README page and this repository itself, but it's your first question so I can answer. 

First, The **screenshot's error** is caused becase you used net/http's recorder but the README page of this repository on the [TESTING](https://github.com/kataras/iris#testing) section says that you have to use httpexpect instead because iris is NOT based on net/http.

Examples, as README says, which you should read before post a issue but... 

- https://github.com/gavv/httpexpect/blob/master/example/iris_test.go
- https://github.com/kataras/iris/blob/master/http_test.go
- https://github.com/kataras/iris/blob/master/context_test.go

Secondly, I see that you want closed-personal help for your project and you ask this on the github repo's issue list, I want to help everybody personally, on each of their projects, but I can't do that, I don't have so much time. 

However there are articles on internet who can help you test your app with iris and httpexpect( you can navigate to the Iris web chat [here](https://kataras.rocket.chat/channel/iris) and see some of these articles in the history, as links, if the articles don't helps then you can ask for help from other iris users)

But If I was you, I could do a simple search on this github repository, which contains some tests. I could see the [http_test.go](https://github.com/kataras/iris/blob/master/http_test.go)  in order to understand  how the author of this project writes its tests. I hope I helped you enough. A code snippet which may helps you :  ` e:= iris.Tester(t *testing.T); e.Request("GET", "http://"+host).Expect().Status(iris.StatusOK).Body().Equal("something")` 


Thanks,
kataras

**Comment by kataras** [comment]
Hi @itsbalamurali , welcome

I see that you want closed-personal help for your project and you ask this on the github repo's issue list, I want to help everybody personally, on each of their projects, but, sadly I can't do that because of time, so it will be better to read the README or the docs or older posts or this github repository's source code before posting a new question, however it's your first post here and maybe you don't have experience of these things, so I will try to help you as much as I can.


First, The **screenshot's error** is caused becase you used net/http's recorder but the README page of this repository on the [TESTING](https://github.com/kataras/iris#testing) section says that you have to use httpexpect instead because iris is NOT based on net/http.

**Examples**, as README notes:

- https://github.com/gavv/httpexpect/blob/master/example/iris_test.go
- https://github.com/kataras/iris/blob/master/http_test.go
- https://github.com/kataras/iris/blob/master/context_test.go


Also you can take a look at many of the **articles on internet who can help you test your app with iris** and httpexpect( you can navigate to the Iris web **chat** [here](https://kataras.rocket.chat/channel/iris) and see some of these articles in the history, as links, if the articles don't helps then you can ask for help from other iris users)

But If I was you, I could do **a simple search** on **this** github **repository**, which **contains** some **tests**. I could see the [http_test.go](https://github.com/kataras/iris/blob/master/http_test.go)  **in order to understand**  how the author of this project writes its **tests**. I hope I helped you enough. A code snippet which may helps you :  ` e:= iris.Tester(t *testing.T); e.Request("GET", "http://"+host).Expect().Status(iris.StatusOK).Body().Equal("something")` 


Thanks,
kataras

**Comment by itsbalamurali** [comment]
@kataras the repo is open source trying to build a open source mobile backend based on iris 😃 
Thanks for the help and Have gone to the article understood the httpexpect and gone through but the main program is not executing, not the tests.
```go
    // @APIVersion 1.0.0
    // @APITitle Parse Server
    // @APIDescription Parse Mobile Backend API.
	// @Contact balamurali@live.com
	// @License MIT
	// @LicenseUrl https://github.com/itsbalamurali/parse-server/blob/master/LICENSE
	// @BasePath http://0.0.0.0:8080/1/
		package main

		import (
			"github.com/iris-contrib/middleware/cors"
			"github.com/iris-contrib/middleware/logger"
			"github.com/iris-contrib/middleware/recovery"
			//"github.com/itsbalamurali/parse-server/config"
			"github.com/itsbalamurali/parse-server/controllers"
			"github.com/itsbalamurali/parse-server/database"
			"github.com/itsbalamurali/parse-server/middleware"
			"github.com/itsbalamurali/parse-server/models"
			"github.com/kataras/iris"
			"os"
			"github.com/valyala/fasthttp"
		)

		func XparseHandler() fasthttp.RequestHandler {


			//iris.Config.Websocket.Endpoint = "/ws" parselive query
			iris.Config.DisableBanner = true
			iris.Config.LoggerPreffix = "xParse"

			//Enable Cors
			crs := cors.New(cors.Options{
				AllowedHeaders: []string{"X-Parse-Master-Key",
					"X-Parse-REST-API-Key",
					"X-Parse-Javascript-Key",
					"X-Parse-Application-Id",
					"X-Parse-Client-Version",
					"X-Parse-Session-Token",
					"X-Requested-With",
					"X-Parse-Revocable-Session",
					"Content-Type"},
				AllowedMethods: []string{"GET", "PUT", "POST", "DELETE", "OPTIONS"},
				AllowedOrigins: []string{"*"},
			}) // options here
			//set global middlewares
			iris.Use(logger.New())
			iris.Use(recovery.Handler)
			iris.Use(crs)
			iris.UseFunc(middleware.APIAuth)

			//Main Database Connection
			Db := database.MgoDb{}
			Db.Init()

			//Custom HTTP Errors
			iris.OnError(iris.StatusNotFound, func(ctx *iris.Context) {
				ctx.JSON(iris.StatusNotFound, models.Error{Code: iris.StatusNotFound, Message: "Resource Not Found"})
				iris.Logger.Printf("http status: 404 happened!")
			})

			//API Version 1
			v1 := iris.Party("/1")

			//V1 Routes
			//Classes
			class := new(controllers.ClassAPI)
			v1.Post("/classes/:className", class.Create)
			v1.Get("/classes/:className/:objectId", class.Get)
			v1.Put("/classes/:className/:objectId", class.Update)
			v1.Get("/classes/:className", class.GetAll)
			v1.Delete("/classes/:className/:objectId", class.Delete)

			//Users
			users := new(controllers.UserAPI)
			v1.Post("/users", users.Signup)
			v1.Get("/login", users.Login)
			v1.Post("/logout", users.Logout)
			v1.Get("/users/me", users.Me)
			v1.Get("/users/:objectId", users.Get)
			v1.Put("/users/:objectId", users.Update)
			v1.Delete("/users/:objectId", users.Delete)
			v1.Get("/users", users.GetAll)
			v1.Post("/requestPasswordReset", users.ResetPassword)

			//Sessions
			sessions := new(controllers.SessionAPI)
			v1.Post("/sessions", sessions.Create)
			v1.Get("/sessions", sessions.GetAll)
			v1.Get("/sessions/me", sessions.Get)
			v1.Get("/sessions/:objectId", sessions.Get)
			v1.Put("/sessions/me", sessions.Update)
			v1.Put("/sessions/:objectId", sessions.Update)
			v1.Delete("/sessions/:objectId", sessions.Delete)

			//Roles
			roles := new(controllers.RoleAPI)
			v1.Post("/roles", roles.Create)
			v1.Get("/roles/:objectId", roles.Get)
			v1.Put("/roles/:objectId", roles.Update)
			v1.Delete("/roles/:objectId", roles.Delete)

			//Files
			files := new(controllers.FileAPI)
			v1.Post("/files/:name", files.Upload)
			v1.Delete("/files/:name", files.Delete)

			//Analytics
			event := new(controllers.EventAPI)
			v1.Post("/events/AppOpened", event.AppOpened)
			v1.Get("/events/:eventName", event.GetAllEvents)
			v1.Post("/events/:eventName", event.CustomEvent)

			//Push Notifications
			push := new(controllers.PushAPI)
			v1.Post("/push", push.Create)

			//Installations
			installations := new(controllers.InstallAPI)
			v1.Post("/installations/:objectId", installations.Create)
			v1.Get("/installations/:objectId", installations.GetByID)
			v1.Put("/installations/:objectId", installations.Update)
			v1.Get("/installations", installations.GetAll)
			v1.Post("/installations", installations.Create)

			//Cloud Functions
			functions := new(controllers.FunctionAPI)
			v1.Post("/functions/:name", functions.ExecuteFunc)
			v1.Post("/jobs/:name", functions.TriggerJob)

			//Schemas
			schema := new(controllers.SchemaAPI)
			v1.Post("/schemas/:className", schema.Create)
			v1.Get("/schemas/:className", schema.GetByID)
			v1.Put("/schemas/:className", schema.Update)
			v1.Get("/schemas", schema.GetAll)
			v1.Delete("/className/:className", schema.Delete)

			//Apps
			apps := new(controllers.AppAPI)
			v1.Post("/apps/:appId", apps.Create)
			v1.Get("/apps/:appId", apps.GetByID)
			v1.Put("/apps/:appId", apps.Update)
			v1.Get("/apps", apps.Get)

			//Config
			conf := new(controllers.ConfigAPI)
			v1.Get("/config", conf.Get)
			v1.Put("/config", conf.Update)

			//Function Hooks
			hookfuncs := new(controllers.HFuncsAPI)
			v1.Post("/hooks/functions", hookfuncs.Create)
			v1.Get("/hooks/functions/:funcName", hookfuncs.GetByID)
			v1.Put("/hooks/functions/:funcName", hookfuncs.Update)
			v1.Delete("/hooks/functions/:funcName", hookfuncs.Delete)

			//Trigger Hooks
			hooktriggers := new(controllers.HTriggerAPI)
			v1.Post("/hooks/triggers", hooktriggers.Create)
			v1.Get("/hooks/triggers/:className/:triggerName", hookfuncs.GetByID)
			v1.Put("/hooks/triggers/:funcName/:triggerName", hookfuncs.Update)
			v1.Delete("/hooks/triggers/:funcName/:triggerName", hookfuncs.Delete)

			enableSwagger := true //TODO Get from viper
			if enableSwagger {
				//Serve Swagger UI
				iris.StaticWeb("/docs", "./public", 1)
				//Serves Swagger JSON API Spec
				v1.Get("/swagger.json", controllers.SwaggerJSON)
			}

			//iris.Listen(":" + port)
			iris.Build()
			return iris.Router
		}

		func main()  {
			//config.InitConfig()
			port := os.Getenv("PORT")
			if port == "" {
				port = "8080"
			}
			handler := XparseHandler()
			//Listen on port specified
			host , err := os.Hostname()

			if err != nil {
				iris.Logger.Println("Cant determine Hostname")
				host = "localhost"
			}

			fasthttp.ListenAndServe(":" + port,handler)
			iris.Logger.Println("xParse is running on: http://"+host+":"+port)
			enableSwagger := true //TODO Get from viper
			if enableSwagger {
				iris.Logger.Printf("You Access Swagger-UI at: http://"+host+":" + port + "/docs")

			}

		}

**Comment by kataras** [comment]
What are you doing? you're changing title and you 're using fasthttp inside iris? why?

if you need to use `fasthttp.ListenAndServe`, which I don't recommend you if you just listen to a port use the `iris.Listen(":myport")` . Then as **Docs** says you have to call `iris.Build()` and pass it's router inside, `fasthttp.ListenAndServe(iris.Router)`

**Comment by kataras** [comment]
What are you doing? you're changing title and you 're using fasthttp inside iris? why?

Why don't just use the `iris.Listen(":myport")/ListenTLS/ListenUNIX/ListenLETSENCRYPT/Serve`? no need to use fasthttp with Iris, iris is fully standalone, however you're free to use fasthttp also but I don't see any reason todo that in your app, anyway as **Docs** says, you have to call `iris.Build()` and pass it's router inside, `fasthttp.ListenAndServe(iris.Router)` 

example
```go
//I AM NOT RECOMMENDING THIS WAY, but the user asked how can do that, so I answer:
// .Get, .Use, .Post... your routes here

// at the very end before custom fasthttp server serves, call the .Build
iris.Build()
 // you have iris.Router which is a fasthttp.RequestHandler
fasthttp.ListenAndServe(":" + port, iris.Router)
```

Please read the [docs](https://www.gitbook.com/book/kataras/iris/details) and the [examples](https://github.com/iris-contrib/examples), your question has already answered both on book and examples and even the README.

**Comment by itsbalamurali** [comment]
if I do ```iris.Listen()``` then, how do I write tests? again in your tests example, only the handler is written which returns ```iris.Router``` and then in tests you call the handler function and attach it to httpexpect. but what about main program execution?

**Comment by kataras** [comment]
Look, to make tests without a live listening server you can just `iris.Build()` and get the `iris.Router` but if you are writing tests in a real server which running then you just call `iris.Listen()` and you have `iris.Router` also, `.Listen` calls the `.Build` automatically, view the links I sent you , I'm sure you will find the solution, I'm here for any further explanation
