### ISSUE TITLE
Error: Router - Path's part: 'register' conflicts with wildcard ':id'

### ISSUE THREAD

**Issue by Hany17** [kataras/iris#461]
Hello, first of all thank you for brilliant IRIS. I am having problems with some routes and middleware. Before update it worked fine. 

```
// Create new auth middleware
authMiddleware := bottleserver.NewAuthMiddleware(authService)

// userAPI is user part of API
userAPI := api.Party("/user")
{
	userAPI.Get("/", authMiddleware.Serve, userController.GetAll)
	userAPI.Get("/:id", authMiddleware.Serve, userController.GetByID)
	userAPI.Post("/register", userController.Create)
	userAPI.Post("/login", userController.Login)
	userAPI.Post("/activate/:hash", userController.Activate)
	userAPI.Put("/:id", authMiddleware.Serve, userController.Update)
	userAPI.Delete("/:id", authMiddleware.Serve, userController.Delete)
}
```
and than the error is:

```
[IRIS] 2016/10/05 12:42:01 Error: Router: Path's part: 'register' conflicts with wildcard ':id' in the route path: '/user/register' !
panic: Error: Router: Path's part: 'register' conflicts with wildcard ':id' in the route path: '/user/register' !


goroutine 1 [running]:
panic(0xd0dcc0, 0xc820152230)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
log.(*Logger).Panic(0xc820278820, 0xc8201c55b8, 0x1, 0x1)
        /usr/local/go/src/log/log.go:206 +0xbf
github.com/kataras/iris.(*serveMux).build(0xc82023ab80, 0xc8202a14a0)
        /home/tomas/go/src/github.com/kataras/iris/http.go:1070 +0x68e
github.com/kataras/iris.(*serveMux).BuildHandler(0xc82023ab80, 0xc8202a14a0)
        /home/tomas/go/src/github.com/kataras/iris/http.go:1104 +0x25
github.com/kataras/iris.(*Framework).Build.func1()
        /home/tomas/go/src/github.com/kataras/iris/iris.go:342 +0x4b2
sync.(*Once).Do(0xc8201fabf8, 0xc8201c5888)
        /usr/local/go/src/sync/once.go:44 +0xe4
github.com/kataras/iris.(*Framework).Build(0xc8201fabb0)
        /home/tomas/go/src/github.com/kataras/iris/iris.go:407 +0x45
github.com/kataras/iris.(*Framework).Serve(0xc8201fabb0, 0x7fc4b0467df0, 0xc8202aa440, 0x0, 0x0)
        /home/tomas/go/src/github.com/kataras/iris/iris.go:431 +0x117
github.com/kataras/iris.(*Framework).Listen(0xc8201fabb0, 0xc82016dc24, 0xc)
```
Thank you for your reply.

**Comment by kataras** [comment]
Hello @Hany17 Thanks for your nice words, I think you posted the wrong code snippet, because that you gave me is running
```go
package main

import (
	"github.com/kataras/iris"
)

func main() {
	// userAPI is user part of API
	userAPI := iris.Party("/user")
	{
		userAPI.Get("/", h)
		userAPI.Get("/:id", h)
		userAPI.Post("/register", h)
		userAPI.Post("/login", h)
		userAPI.Post("/activate/:hash", h)
		userAPI.Put("/:id", h)
		userAPI.Delete("/:id", h)
	}

	iris.Listen(":8080")
}

func h(ctx *iris.Context) {
	ctx.Write("Hello from %s", ctx.PathString())
}


```

**Comment by kataras** [comment]
Hello @Hany17 Thanks for your nice words, I think you posted the wrong/or/ incoplete code snippet, because that you gave me is running
```go
package main

import (
	"github.com/kataras/iris"
)

func main() {
	// userAPI is user part of API
	userAPI := iris.Party("/user")
	{
		userAPI.Get("/", h)
		userAPI.Get("/:id", h)
		userAPI.Post("/register", h)
		userAPI.Post("/login", h)
		userAPI.Post("/activate/:hash", h)
		userAPI.Put("/:id", h)
		userAPI.Delete("/:id", h)
	}

	iris.Listen(":8080")
}

func h(ctx *iris.Context) {
	ctx.Write("Hello from %s", ctx.PathString())
}

```

Anyway, for route's path issues please do a search at the older posts, I have answered more than 42 times I think :) 

Thank you very much again!

Cheers,
kataras

**Comment by kataras** [comment]
Hello @Hany17 Thanks for your nice words, I think you posted the wrong/or/ incomplete code snippet, because that you gave me is running
```go
package main

import (
	"github.com/kataras/iris"
)

func main() {
	// userAPI is user part of API
	userAPI := iris.Party("/user")
	{
		userAPI.Get("/", h)
		userAPI.Get("/:id", h)
		userAPI.Post("/register", h)
		userAPI.Post("/login", h)
		userAPI.Post("/activate/:hash", h)
		userAPI.Put("/:id", h)
		userAPI.Delete("/:id", h)
	}

	iris.Listen(":8080")
}

func h(ctx *iris.Context) {
	ctx.Write("Hello from %s", ctx.PathString())
}

```

Anyway, for route's path issues please do a search at the older posts, I have answered more than 42 times I think :) 

Thank you very much again!

Cheers,
kataras

**Comment by Hany17** [comment]
Ahh sorry I went through the old issues but did not find anything that fits my problem, probably I have problems somewhere else not in the routes. Thank you for your time and very quick response. Cheers.

**Comment by kataras** [comment]
No, you have problem on routes but you have to give me all of your registered routes code in order  to understand what's happens, if your issue is not answered already by other post issues, it's strange

**Comment by Hany17** [comment]
Sorry you were totally sure about incomplete code snippet. Problem isn't at the routes. Problem is if I combinate it with CORS. :) 
```
package main

import (
	"github.com/iris-contrib/middleware/cors"
	"github.com/kataras/iris"
)

func main() {
	// userAPI is user part of API
	iris.Use(cors.Default())

	userAPI := iris.Party("/user")
	{
		userAPI.Get("/", h)
		userAPI.Get("/:id", h)
		userAPI.Post("/register", h)
		userAPI.Post("/login", h)
		userAPI.Post("/activate/:hash", h)
		userAPI.Put("/:id", h)
		userAPI.Delete("/:id", h)
	}

	iris.Listen(":8080")
}

func h(ctx *iris.Context) {
	ctx.Write("Hello from %s", ctx.PathString())
}
```
In that case I am having problems with the errors as I posted previously...

**Comment by kataras** [comment]
That's strange because Iris only registers `iris.Options` if CORS middleware is used, globally, or per route and user didn't already set manually `iris.Options(path,handlers)` , Are you sure you don't have any `iris.Options("/register",h)` ?

**Comment by kataras** [comment]
That's strange because Iris only registers `iris.Options` if CORS middleware is used, globally, or per route and user didn't already set manually `iris.Options(path,handlers)` , Are you sure you don't have any `iris.Options("/user/register",h)` or.Party("/user")...Options("/register",h) ?

**Comment by kataras** [comment]
That's very strange because Iris only registers `iris.Options` if CORS middleware is used, globally, or per route and user didn't already set manually `iris.Options(path,handlers)` .

To find out what happen can you make some changes in your `$GOPATH/src/github/kataras/iris` (you have to delete the folder in order to upgrade iris in the future*) ?

./http.go line: **1070** : 	`mux.logger.Panic(err.(errors.Error).Format(r.Method()))`
./http.go line: **360**:  `errMuxEntryConflictsWildcard           = errors.New("Router: Path's part: '%s' conflicts with wildcard '%s' in the route path: '%s'. Method: %s !")`

I'll do my bests to help you, I think that a part of your app is registering a route twice somewhere, keep note that `/user/register/ conflicts with `/user/:id` static and dynamic are not allowed in the same path, search for any kind of these routes in your app, please, and tell me the results

**Comment by kataras** [comment]
That's very strange because Iris only registers `iris.Options` if CORS middleware is used, globally, or per route and user didn't already set manually `iris.Options(path,handlers)` .

To find out what happen can you make some changes in your `$GOPATH/src/github.com/kataras/iris` (you have to delete the folder in order to upgrade iris in the future*) ?

./http.go line: **1070** : 	`mux.logger.Panic(err.(errors.Error).Format(r.Method()))`
./http.go line: **360**:  `errMuxEntryConflictsWildcard           = errors.New("Router: Path's part: '%s' conflicts with wildcard '%s' in the route path: '%s'. Method: %s !")`

I'll do my bests to help you, I think that a part of your app is registering a route twice somewhere, keep note that `/user/register/ conflicts with `/user/:id` static and dynamic are not allowed in the same path, search for any kind of these routes in your app, please, and tell me the results

**Comment by kataras** [comment]
@Hany17 It should be fixed with the v4.4.9, please upgrade the cors middleware ( github.com/iris-contrib/middleware/cors) and iris (github.com/kataras/iris) . Could you verify it, please?

**Comment by Hany17** [comment]
@kataras Yup, thank you very much it is working now as it did before. :) Thank you for your great work and the library itself!

**Comment by kataras** [comment]
You're welcome, I thank you for the report!
