### ISSUE TITLE
go routines in handlers?

### ISSUE THREAD

**Issue by dpastoor** [kataras/iris#463]
I scoured the documentation and could not find anything to help. I am trying to figure out how to return a response after some work is done (db call, shell process, etc) without blocking the webserver

```go
package main

import (
	"fmt"
	"math/rand"
	"net/http"
	"time"

	"github.com/kataras/iris"
)

func main() {
	api := iris.Party("/api")
	v1 := api.Party("/v1")
	v1.Get("/flu", func(ctx *iris.Context) {
		go sendAsync(ctx)
	})
	iris.Listen(":8080")
}
// get request to localhost:8080/api/v1/flu

func sendAsync(ctx *iris.Context) {
	fmt.Println("emulate long-running process")
	time.Sleep(5000 * time.Millisecond)
	fmt.Println("done process...")
	ctx.JSON(http.StatusOK, iris.Map{
		"SomeNum": rand.Float64(),
	})
}
```

If I remove the go-routine and just directly call `sendAsync()` it works as expected (each request is handled 5 seconds later). I also figured that it could be because the handler routine is closing, so added a channel to keep it open, but of course that blocked the process the same as not running it in a go routine

eg

```go

func main() {
	response := make(chan iris.Context.JSON)
	api := iris.Party("/api")
	v1 := api.Party("/v1")
	v1.Get("/flu", func(ctx *iris.Context) {
		ch := make(chan bool)
		go sendAsync(ctx, response)
		<-ch
	})
	iris.Listen(":8080")
}

func sendAsync(ctx *iris.Context) {
	fmt.Println("waiting in go routine...")
	time.Sleep(5000 * time.Millisecond)
	fmt.Println("done waiting")
	ctx.JSON(http.StatusOK, iris.Map{
		"SomeNum": rand.Float64()
	})
	ch <- ctx
}
```

**Comment by kataras** [comment]
Each request has its own goroutine, you can use `channels` to communicate or `sync.WaitGroup` please search on google and you will find many examples, the is no difference from net/http at this particular subject

**Comment by kataras** [comment]
Each request has its own goroutine, the request is finish when the handler returns, so you cannot use goroutine and stay there, you have to wait for result in the same handler, you're not blocking the server by-design because **each request has its own goroutine by default**.  You can use `channels` to communicate or `sync.WaitGroup` please search on google and you will find many examples, the is no difference from net/http at this particular subject

**Comment by kataras** [comment]
Each request has its own goroutine, the request is finish when the handler returns, so you cannot use goroutine and stay there, you have to wait for result in the same handler, you're not blocking the server by-design because **each request has its own goroutine by default**.  You can use `channels` to communicate or `sync.WaitGroup` please search on google and you will find many examples, there is no difference from net/http at this particular subject

**Comment by kataras** [comment]
Each request has its own goroutine, the request is finish when the handler returns, so you cannot use goroutine and stay there, you have to wait for result in the same handler, you're not blocking the server by-design because **each request has its own goroutine by default**.  You can use `channels` to communicate or `sync.WaitGroup` .


Look, I don't undestand these lines:

```go
        ch := make(chan bool)
        go sendAsync(ctx, response)
        <-ch
```

You don't pass ch inside the sendAsync  (which there is no such thing, I recommend you to change its name, pass in goroutines the actions you want to process in the same handler for the same user instead).

```go
   v1.Get("/flu", func(ctx *iris.Context) {
        var wg sync.WaitGroup
        wg.Add(2)
        go  doTheThing(ctx.Sessions().GetInt("user_id"), wg)
        go otherThingInTheSameTime(wg)
        wg.Wait()
    })


   func doTheThing(userId int, wg sync.WaitGroup){
      time.Sleep(5*time.Second) //..... action here
      wg.Done()
   }

   func otherThingInTheSameTime(wg sync.WaitGroup){
      time.Sleep(3*time.Second) //..... action here
     wg.Done()
   }

// the code is written here in github*
```


Please search on google and you will find many examples, there is no difference from net/http, except that the Context is not allowed to be used after the handler returns,  at this particular subject

**Comment by kataras** [comment]
Each request has its own goroutine, the request is finish when the handler returns, so you cannot use goroutine and stay there, you have to wait for result in the same handler, you're not blocking the server by-design because **each request has its own goroutine by default**.  You can use `channels` to communicate or `sync.WaitGroup` .


Look, I don't undestand these lines:

```go
        ch := make(chan bool)
        go sendAsync(ctx, response)
        <-ch
```

You don't pass ch inside the sendAsync  (which there is no such thing, I recommend you to change its name, pass in goroutines the actions you want to process in the same handler for the same user instead).

```go
   v1.Get("/flu", func(ctx *iris.Context) {
        var wg sync.WaitGroup
        wg.Add(2)
        go  doTheThing(ctx.Sessions().GetInt("user_id"), wg)
        go otherThingInTheSameTime(wg)
        wg.Wait()
    })


   func doTheThing(userId int, wg sync.WaitGroup){
      time.Sleep(5*time.Second) //..... action here
      wg.Done()
   }

   func otherThingInTheSameTime(wg sync.WaitGroup){
      time.Sleep(3*time.Second) //..... action here
       wg.Done()
   }

// the code is written here in github*
```


Please search on google and you will find many examples, there is no difference from net/http, except that the Context is not allowed to be used after the handler returns,  at this particular subject

**Comment by kataras** [comment]
Each request has its own goroutine, the request is finish when the handler returns, so you cannot use goroutine and stay there, you have to wait for result in the same handler, you're not blocking the server by-design because **each request has its own goroutine by default**.  You can use `channels` to communicate or `sync.WaitGroup` .


Look, I don't undestand these lines:

```go
        ch := make(chan bool)
        go sendAsync(ctx, response)
        <-ch
```

You don't pass ch inside the sendAsync  (which there is no such thing, I recommend you to change its name, pass in goroutines the actions you want to process in the same handler for the same user instead).

```go
   v1.Get("/flu", func(ctx *iris.Context) {
        var wg sync.WaitGroup
        wg.Add(2)
        go  doTheThing(ctx.Session().GetInt("user_id"), wg)
        go otherThingInTheSameTime(wg)
        wg.Wait()
    })


   func doTheThing(userId int, wg sync.WaitGroup){
      time.Sleep(5*time.Second) //..... action here
      wg.Done()
   }

   func otherThingInTheSameTime(wg sync.WaitGroup){
      time.Sleep(3*time.Second) //..... action here
      wg.Done()
   }

// the code is written here in github*
```


Please search on google and you will find many examples, there is no difference from net/http, except that the Context is not allowed to be used after the handler returns,  at this particular subject

**Comment by kataras** [comment]
Each request has its own goroutine, the request is finish when the handler returns, so you cannot use goroutine and stay there, you have to wait for result in the same handler, you're not blocking the server by-design because **each request has its own goroutine by default**.  You can use `channels` to communicate or `sync.WaitGroup` .


Look, I don't undestand these lines:

```go
        ch := make(chan bool)
        go sendAsync(ctx, response)
        <-ch
```

You don't pass ch inside the sendAsync  (which there is no such thing, I recommend you to change its name, pass in goroutines the actions you want to process in the same handler for the same user instead).

Could you please try something like this, and tell me the results?
```go
   v1.Get("/flu", func(ctx *iris.Context) {
        var wg sync.WaitGroup
        wg.Add(2)
        go doTheThing(ctx.Session().GetInt("user_id"), wg)
        go otherThingInTheSameTime(wg)
        wg.Wait()
    })


   func doTheThing(userId int, wg sync.WaitGroup){
      time.Sleep(5*time.Second) //..... action here
      wg.Done()
   }

   func otherThingInTheSameTime(wg sync.WaitGroup){
      time.Sleep(3*time.Second) //..... action here
      wg.Done()
   }

// the code was written here in github*
```


Please search on google and you will find many examples, there is no difference from net/http, except that the Context is not allowed to be used after the handler returns,  at this particular subject

**Comment by kataras** [comment]
Each request has its own goroutine, the request is finish when the handler returns, so you cannot use goroutine and stay there, you have to wait for result in the same handler.

>  I am trying to figure out how to return a response after some work is done (db call, shell process, etc) without blocking the webserver

 No, in fact you cannot block the entire server from one handler, you're not blocking the server by-design because **each request has its own goroutine by default**.  If you still want to not block the code **inside the handler** then you can use `channels` to communicate or `sync.WaitGroup` .


Look, I don't undestand these lines:

```go
        ch := make(chan bool)
        go sendAsync(ctx, response)
        <-ch
```

You don't pass ch inside the sendAsync  (which there is no such thing, I recommend you to change its name, pass in goroutines the actions you want to process in the same handler for the same user instead).

Could you please try something like this, and tell me the results?
```go
   v1.Get("/flu", func(ctx *iris.Context) {
        var wg sync.WaitGroup
        wg.Add(2)
        go doTheThing(ctx.Session().GetInt("user_id"), wg)
        go otherThingInTheSameTime(wg)
        wg.Wait()
    })


   func doTheThing(userId int, wg sync.WaitGroup){
      time.Sleep(5*time.Second) //..... action here
      wg.Done()
   }

   func otherThingInTheSameTime(wg sync.WaitGroup){
      time.Sleep(3*time.Second) //..... action here
      wg.Done()
   }

// the code was written here in github*
```


Please search on google and you will find many examples, there is no difference from net/http, except that the Context is not allowed to be used after the handler returns,  at this particular subject

**Comment by kataras** [comment]
Each request has its own goroutine, the request **ends when the handler returns**,, you have to wait for result in the same handler.

>  I am trying to figure out how to return a response after some work is done (db call, shell process, etc) without blocking the webserver

 No, in fact you cannot block the entire server from one handler, you're not blocking the server by-design because **each request has its own goroutine by default**.  If you still want to not block the code **inside the handler** then you can use `channels` to communicate or `sync.WaitGroup` .


Look, I don't undestand these lines:

```go
        ch := make(chan bool)
        go sendAsync(ctx, response)
        <-ch
```

You don't pass ch inside the sendAsync  (which there is no such thing, I recommend you to change its name, pass in goroutines the actions you want to process in the same handler for the same user instead).

Could you please try something like this, and tell me the results?
```go
   v1.Get("/flu", func(ctx *iris.Context) {
        var wg sync.WaitGroup
        wg.Add(2)
        go doTheThing(ctx.Session().GetInt("user_id"), wg)
        go otherThingInTheSameTime(wg)
        wg.Wait()
    })


   func doTheThing(userId int, wg sync.WaitGroup){
      time.Sleep(5*time.Second) //..... action here
      wg.Done()
   }

   func otherThingInTheSameTime(wg sync.WaitGroup){
      time.Sleep(3*time.Second) //..... action here
      wg.Done()
   }

// the code was written here in github*
```


Please search on google and you will find many examples, there is no difference from net/http, except that the Context is not allowed to be used after the handler returns,  at this particular subject

**Comment by dpastoor** [comment]
Thanks for this info, actually it is a very strange behavior in chrome.

When curling from the command line, the above code works fine, but just hitting the url from 2 chrome windows on mac, causes the 2nd request to sit `pending` until the first completes.

That's why I was so confused, in reality, the proper behavior is occurring with just

```
func main() {
    api := iris.Party("/api")
    v1 := api.Party("/v1")
    v1.Get("/flu", func(ctx *iris.Context) {
        sendAsync(ctx) // no need for go routine
    })
    iris.Listen(":8080")
}

...
```


I still am not sure why chrome (mac) is exhibiting that behavior, but at least now I know its not iris!
