### ISSUE TITLE
html/template: "index.html" is undefined when running go built with supervisor

### ISSUE THREAD

**Issue by speedwheel** [kataras/iris#485]
- Version : **4.6.0**

- Operating System: Ubuntu 16.04

- [x] I have read the [book](https://docs.iris-go.com), [examples](https://github.com/iris-contrib/examples), [contributing file](https://github.com/kataras/iris/blob/master/.github/CONTRIBUTING.md) and I'm sure that this issue is not posted & answered before.

--------------

This is the code where I init the layout:

`api.UseTemplate(html.New(html.Config{
		Layout: "index.html",
	})).Directory("./views", ".html")`

- I built go executable with the command: "go install github.com/speedwheel/website"
- I run the command "website" and everything works fine
- Then I run the same command in supervisor so I can keep the server alive with "command= /root/work/bin/website" and the server start normally but shows white page and the error log "html/template: "index.html" is undefined"

Any thoughts?

**Comment by speedwheel** [comment]
I managed to fix it by putting the absolute path for the template and static content.

**Comment by kataras** [comment]
Dear @speedwheel , This is not the solution, I'll try to explain you because I think that you're new to Go.

When you `go build`  and you run the executable file from other location than your templates and all other static files it will not found them. **You have to bind the static files and templates inside your Go app** , you can do that using the [go-bindata](https://github.com/jteeuwen/go-bindata) package, and with Iris' template view system you can use the `.Binary` to use them as templates, I have already provided an **example of this**, navigate [there]https://github.com/iris-contrib/examples/tree/master/template_engines/template_binary) and you will figure out what's going on,

Welcome to Go and Iris Community.

Cheers,
kataras

**Comment by kataras** [comment]
Dear @speedwheel , This is not the solution, I'll try to explain you because I think that you're new to Go.

When you `go build`  and you run the executable file from other location than your templates and all other static files it will not found them. **You have to bind the static files and templates inside your Go app** , you can do that using the [go-bindata](https://github.com/jteeuwen/go-bindata) package, and with Iris' template view system you can use the `.Binary` to use them as templates, I have already provided an **example of this**, navigate [there](https://github.com/iris-contrib/examples/tree/master/template_engines/template_binary) and you will figure out what's going on,

Welcome to Go and Iris Community.

Cheers,
kataras

**Comment by speedwheel** [comment]
You are right, I am new to Go, I am checking now your link, I also realized that my solution is not very good. Thank you.

**Comment by speedwheel** [comment]
I installed go-bindata, but I get a different output that doesn't have the function AssetNames:

`package main

import (
    "bytes"
    "compress/gzip"
    "fmt"
    "io"
)

func bindata_read(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	return buf.Bytes(), nil
}

func views_home_html() ([]byte, error) {
	return bindata_read([]byte{
		0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x00, 0xff, 0x01, 0x00,
		0x00, 0xff, 0xff, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
		},
		"views/home.html",
	)
}

func views_index_html() ([]byte, error) {
	return bindata_read([]byte{
		0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x00, 0xff, 0xaa, 0xae,
		0x56, 0x28, 0x4a, 0xcd, 0x4b, 0x49, 0x2d, 0x52, 0x50, 0x2a, 0x49, 0xcd,
		0x2d, 0xc8, 0x49, 0x2c, 0x49, 0x2d, 0xd6, 0xcf, 0x48, 0x4d, 0x04, 0x8a,
		0xe8, 0x65, 0x94, 0xe4, 0xe6, 0x28, 0xd5, 0xd6, 0x72, 0x01, 0xd5, 0x54,
		0x66, 0xa6, 0xe6, 0xa4, 0x28, 0x40, 0xd8, 0x98, 0xea, 0xd3, 0xf2, 0xf3,
		0x4b, 0x90, 0xd4, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xb2, 0x96, 0x9c,
		0xed, 0x54, 0x00, 0x00, 0x00,
		},
		"views/index.html",
	)
}


// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	if f, ok := _bindata[name]; ok {
		return f()
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string] func() ([]byte, error) {
	"views/home.html": views_home_html,
	"views/index.html": views_index_html,

}
`

I see that .Binary gets 2 parameters, which 2 parameters should I pass from the code above? Also shold I create 2 binary files, one for html templates and on for assets like css/js/img?

**Comment by kataras** [comment]
> I tried to put both views and assets in the same binary, but the website is not loading the css js img, only the html: go-bindata views/... assets/...

`.Binary`, the method I saw you works with iris templates only, you have to read the go-bindata's README to think how you can do that with your other static files, you're developer, don't expect to have all things ready :) 

> How will this method work if you upload images to the website, will you have to manually recreate the binary each time?

No, there are dynamic files and you should point a directory relative to the executable file, or absolute path as you did before, only **static** files goes with go-bindata.

> this is with 2 gb o ram, so I guess that if you have a full blown website you would need 8gb ram + to build all those assets.

Hmm I am not author of go-bindata but I think this shouldn't happened, 2GB is enough, if your assets are bigger than 1GB then yes, but you told me js,css , so it shouldn't be a problem, you have to post an issue there if you think there is a bug with go-bindata and its memory usage.

**Comment by speedwheel** [comment]
Alright thanks for the reply.

What is the best way to convert the binary code into the original asset and serve it?

**Comment by kataras** [comment]
`iris.StaticContent` serves []byte and registers a route for static files(use it before other routes, outside of handlers), but if you need an `io.Writer` then you can use the `context.Response.BodyWriter()` inside route's handler `func(context *iris.Context){ context.Response.BodyWriter()....}`

**Comment by speedwheel** [comment]
I am getting very close to do it, I think the reason why is not working is because I am putting api.StaticContent inside api.Get, here is my code:

`api.Get("/assets/*path", func(ctx *iris.Context) {
			var contentType string
			filepath := fmt.Sprintf("assets%s", ctx.Param("path"))
			if s.HasSuffix(filepath, ".js") {
				contentType = "application/javascript"
			} else if s.HasSuffix(filepath, ".css") {
				contentType = "text/css"
			} else if s.HasSuffix(filepath, ".png") {
				contentType = "image/png"
			} else if s.HasSuffix(filepath, ".ico") {
				contentType = "image/x-icon"
			} else if s.HasSuffix(filepath, ".svg") {
				contentType = "image/svg+xml"
			} else if s.HasSuffix(filepath, ".jpg") {
				contentType = "image/jpg"
			}
			data, err := Asset(filepath)
			println(contentType);
			println(data);
			if err != nil {

			} else {
				api.StaticContent(filepath, contentType , data)
			}
		})`

Any thoughts how I can fix it?

**Comment by kataras** [comment]
I told you before, you **SHOULD NOT**use `.StaticContent` inside your handlers, `StaticContent` is a func like `.Get/.Post`, do you use them inside your handlers too?... if you don't know your filenames, then think it like a **dynamic** (it's static but think it as dynamic, because you don't know the filename here).

You don't have to do all that alone, if you search on iris.go you will see some code snippets and already-done functions which could helps you, **but,  I will try to explain to you** , note that I am not teacher, this is not my job here, and my english are so bad, so excuse me for these:

** first, file extension**  you dublicate code and low performance for 6 .HasSuffix without reason, use TypeByExtension instead**
```go
import "github.com/kataras/go-fs"

contentType := fs.TypeByExtension(filepath)

```

you do `api.StaticContent` inside handler, that's wrong, because `StaticConten`t it doesn't executes, it **registers a route for your static content,**, general route works for most cases: **if you are inside the context, use the `ctx` **
```go
// ....
import "github.com/kataras/go-fs"
// ....

api.Get("/assets/*path", func(ctx *iris.Context) {
   filepath := ctx.Param("path") // get from /assets/*path, this will take the  'path' part only not the /assets/ so I hope you execute go-bindata correctly

   contentType := fs.TypeByExtension(filepath)

   data, err := Asset(filepath)
   if err != nil { ctx.EmitError(500); return;  }
   // add the content type header
   ctx.Response.Header.Set("Content-Type", contentType)
  // set the status manually, no needed but ok
  ctx.SetStatusCode(iris.StatusOK) // 200 status OK

   ctx.Response.SetBody(data) // send the data
  // done, so easy
}
```

Tell me if that helped you :) , thanks!!

**Comment by kataras** [comment]
My dear, I told you before, that you **should not** use `.StaticContent` inside your handlers, `StaticContent` is a func like `.Get/.Post`, do you use them inside your handlers too?... if you don't know your filenames, then think it like a **dynamic** (it's static but think it as dynamic, because you don't know the filename here).

You don't have to do all that alone, if you search on iris.go you will see some code snippets and already-done functions which could helps you, **but,  I will try to explain to you** , note that I am not teacher, this is not my job here, and my english are so bad, so excuse me for these:

**first, file extension**  you dublicate code and low performance for 6 `.HasSuffix` without reason, use `TypeByExtension` instead
```go
import "github.com/kataras/go-fs"

contentType := fs.TypeByExtension(filepath)

```

you do `api.StaticContent` inside handler, that's wrong, because `StaticContent` it doesn't executes, it **registers a route for your static content,** 

General rule works for most cases: **if you are inside the context, use the `ctx`  **

```go
// ....
import "github.com/kataras/go-fs"
// ....

api.Get("/assets/*path", func(ctx *iris.Context) {
  // this returns the  'path' part only not the full /assets/+path part 
  filepath := ctx.Param("path") 


   contentType := fs.TypeByExtension(filepath)

   data, err := Asset(filepath)
   if err != nil { ctx.EmitError(500); return;  }
   // add the content type header
   ctx.Response.Header.Set("Content-Type", contentType)
   // set the status manually, no needed but ok
   ctx.SetStatusCode(iris.StatusOK) // 200 status OK

   ctx.Response.SetBody(data) // send the data
   // done, so easy
}
```

Tell me if that helped you :) , thanks!!

**Comment by kataras** [comment]
I'll create a function and an example on this and I will notify you, I'm sorry for my tune, I'm managing 42 projects every day I hope you understand

**Comment by speedwheel** [comment]
It works great,  only needed to change this line:
    filepath := fmt.Sprintf("assets%s", ctx.Param("path"))

I understand, thank you for doing Iris :)

**Comment by kataras** [comment]
Yes, for cache take a look , for example the `iris.StaticContent` method
```go
	modtime := time.Now()
	modtimeStr := ""
	h := func(ctx *Context) {
		if modtimeStr == "" {
			modtimeStr = modtime.UTC().Format(ctx.framework.Config.TimeFormat)
		}

		if t, err := time.Parse(ctx.framework.Config.TimeFormat, ctx.RequestHeader(ifModifiedSince)); err == nil && modtime.Before(t.Add(StaticCacheDuration)) {
			ctx.Response.Header.Del(contentType)
			ctx.Response.Header.Del(contentLength)
			ctx.SetStatusCode(StatusNotModified)
			return
		}

		ctx.Response.Header.Set(contentType, cType)
		ctx.Response.Header.Set(lastModified, modtimeStr)
		ctx.SetStatusCode(StatusOK)
		ctx.Response.SetBody(content)
	}

```

**Comment by speedwheel** [comment]
Your code makes sense.
That would be awesome, and other users will benefit from it. Thanks.

Also do you know if you can integrate also gzip into the function, or it's not up to you?

**Comment by kataras** [comment]
Done, 

**outline**
```go

// StaticEmbedded  used when files are distrubuted inside the app executable, using go-bindata mostly
// First parameter is the request path, the path which the files in the vdir(second parameter) will be served to, for example "/static"
// Second parameter is the (virtual) directory path, for example "./assets"
// Third parameter is the Asset function
// Forth parameter is the AssetNames function
//
// For more take a look at the
// example: https://github.com/iris-contrib/examples/tree/master/static_files_embedded
StaticEmbedded(requestPath string, vdir string, assetFn func(name string) ([]byte, error), namesFn func() []string) RouteNameFunc

```

**example**

You can view and run it from [here](https://github.com/iris-contrib/examples/tree/master/static_files_embedded) *

```go
package main

// First of all, execute: $ go get https://github.com/jteeuwen/go-bindata
// Secondly, execute the command: cd $GOPATH/src/github.com/iris-contrib/examples/static_files_embedded && go-bindata ./assets/...

import (
	"github.com/kataras/iris"
)

func main() {

	// executing this go-bindata command creates a source file named 'bindata.go' which
	// gives you the Asset and AssetNames funcs which we will pass into .StaticAssets
	// for more viist: https://github.com/jteeuwen/go-bindata
	// Iris gives you a way to integrade these functions to your web app

	// For the reason that you may use go-bindata to embed more than your assets, you should pass the 'virtual directory path', for example here is the : "./assets"
	// and the request path, which these files will be served to, you can set as "/assets" or "/static" which resulting on http://localhost:8080/static/*anyfile.*extension
	iris.StaticEmbedded("/static", "./assets", Asset, AssetNames)


	// that's all
	// this will serve the ./assets (embedded) files to the /static request path for example the favicon.ico will be served as :
	// http://localhost:8080/static/favicon.ico
	// Methods: GET and HEAD



	iris.Get("/", func(ctx *iris.Context) {
		ctx.HTML(iris.StatusOK, "<b> Hi from index</b>")
	})

	iris.Listen(":8080")
}

// Navigate to:
// http://localhost:8080/static/favicon.ico
// http://localhost:8080/static/js/jquery-2.1.1.js
// http://localhost:8080/static/css/bootstrap.min.css

// Now, these files are stored inside into your executable program, no need to keep it in the same location with your assets folder.


```

**Comment by speedwheel** [comment]
Your are hero, thanks you for implementing this.

One question, on the network tab why sometimes it shows status 200 (from cache) and sometimes status 304, shouldn't it be consistently serving from cache ?(I am not pressing f5)

**Comment by kataras** [comment]
You're welcome!!

You have to increase the global `StaticCacheDuration`, which is `20 seconds by default`  : 

```go
iris.StaticCacheDuration = 2 *time.Hour
```
