### ISSUE TITLE
Can't install from gopkg.in/kataras/iris.v4

### ISSUE THREAD

**Issue by yusufsyaifudin** [kataras/iris#500]
When I install katara/iris using `go get gopkg.in/kataras/iris.v4` it show a message like this 

**can't load package: package gopkg.in/kataras/iris.v4: code in directory /home/yusuf/GOPATH/src/gopkg.in/kataras/iris.v4 expects import "github.com/kataras/iris"**

which `/home/yusuf/GOPATH/` is my GOPATH location. 

I'm new in golang, so I don't know whether this message because of my GO configuration or from kataras/iris project code.

**Comment by kataras** [comment]
Welcome to Go @yusufsyaifudin then,

Your 'issue' is a general golang problem caused by this line: https://github.com/kataras/iris/blob/master/iris.go#L51 

**First and normal solution**


So whenever you see a package: package $name // import $store/$author/$package means that this package is allowed to be used only with `import store/author/package` , that means that you have to use Iris as examples shows:

```go
import "github.com/kataras/iris" // do this and your problem will be solved

func main() {
   iris.Get("/" , func(ctx *iris.Context){
     ctx.HTML(200, "<h1> Hello Iris!</h1>")
  })

  iris.Listen("127.0.0.1:8080")
}

``
Try to download and install the package as the [README:Installation](https://github.com/kataras/iris/blob/master/README.md#installation) points 


**Second solution**
Just go to your local iris and remove the line 51 part with the comment of `// import github.com/kataras/iris`  from the `iris.go` 

Cheers,
kataras

**Comment by kataras** [comment]
Welcome to Go @yusufsyaifudin then,

Your 'issue' is a general golang problem caused by this line: https://github.com/kataras/iris/blob/master/iris.go#L51 

**First and normal solution**


So whenever you see a package: package $name // import $store/$author/$package means that this package is allowed to be used only with `import store/author/package` , that means that you have to use Iris as examples shows:

```go
import "github.com/kataras/iris" // do this and your problem will be solved

func main() {
   iris.Get("/" , func(ctx *iris.Context){
     ctx.HTML(200, "<h1> Hello Iris!</h1>")
  })

  iris.Listen("127.0.0.1:8080")
}

```
Try to download and install the package as the [README:Installation](https://github.com/kataras/iris/blob/master/README.md#installation) points 


**Second solution**
Just go to your local iris and remove the line 51 part with the comment of `// import github.com/kataras/iris`  from the `iris.go` 

Cheers,
kataras

**Comment by kataras** [comment]
Welcome to Go @yusufsyaifudin then,

Your 'issue' is a general golang problem caused by this line: https://github.com/kataras/iris/blob/master/iris.go#L51 

**First and normal solution**


So whenever you see a package: package $name // import $store/$author/$namemeans that this package is allowed to be used only with `import store/author/name` , that means that you have to use Iris as examples shows:

```go
import "github.com/kataras/iris" // do this and your problem will be solved

func main() {
   iris.Get("/" , func(ctx *iris.Context){
     ctx.HTML(200, "<h1> Hello Iris!</h1>")
  })

  iris.Listen("127.0.0.1:8080")
}

```
Try to download and install the package as the [README:Installation](https://github.com/kataras/iris/blob/master/README.md#installation) points 


**Second solution**
Just go to your local iris and remove the line 51 part with the comment of `// import github.com/kataras/iris`  from the `iris.go` 

Cheers,
kataras

**Comment by kataras** [comment]
Welcome to Go @yusufsyaifudin then,

Your 'issue' is a general golang problem caused by this line: https://github.com/kataras/iris/blob/master/iris.go#L51 

**First and normal solution**


So whenever you see a package: package $name // import $store/$author/$name means that this package is allowed to be used only with `import store/author/name` , that means that you have to use Iris as examples shows:

```go
import "github.com/kataras/iris" // do this and your problem will be solved

func main() {
   iris.Get("/" , func(ctx *iris.Context){
     ctx.HTML(200, "<h1> Hello Iris!</h1>")
  })

  iris.Listen("127.0.0.1:8080")
}

```
Try to download and install the package as the [README:Installation](https://github.com/kataras/iris/blob/master/README.md#installation) points 


**Second solution**
Just go to your local iris and remove the line 51 part with the comment of `// import github.com/kataras/iris`  from the `iris.go` 

Cheers,
kataras
