### ISSUE TITLE
React,  go-duktape Integration 

### ISSUE THREAD

**Issue by sebastianmacias** [kataras/iris#503]
Hi,

Would you consider adding react rendering/integration to iris?

I would be a HUGE plus and will definitely set this framework apart.

I would recommend using https://github.com/olebedev/go-starter-kit as a starting point.

Cheers!

**Comment by kataras** [comment]
Hello @sebastianmacias , 

Very good feature request, I totally agree with you, Iris provides unique features but this will be a big plus too. 

I may ask you more information about this library on the near future (because I did not used it so far) in order to implement the react API as simple as possible for end-users. 

Last, I am recommending you to Star the repository in order to be notified when this will be ready.

Thank you very much!

**Comment by sebastianmacias** [comment]
Absolutely, let me know if you need help testing the implementation.

**Comment by sebastianmacias** [comment]
This is a related project to keep in mind: https://zeit.co/blog/next

**Comment by ahrajabi** [comment]
Can you help me how can i use react (go-starter-kit) and iris together?

**Comment by sebastianmacias** [comment]
Actually since iris already comes with a typescript editor I'm thinking we shouldn't go with react/next.js at all. I think it would be better to use a different stack: [Angular 2](https://angular.io/) (written in typescript) and [Angular Universal](https://universal.angular.io/)  (also written in typescript) for the server side rendering / isomorphic stuff.

What [go-starter-kit](https://github.com/olebedev/go-starter-kit) / [go-duktape](https://github.com/olebedev/go-duktape) allows you to do is to render isomorphic views without the need to run a separated node.js process. The idea is to allow using iris for microservices and back-end tasks and use client side rendering via Angular 2 for the UI while also having the possibility to do some server side rendering for SEO purposes all tied together. 

I'm going to spend some time figuring out the best way to integrate all of these pieces together and will post what I find.

**Comment by jnsone11** [comment]
@kataras Will this be implemented within the next 2 weeks?
I need this feature and will otherwise implement a solution by myself.
I currently don't have the time to implement a generic solution and therefore cannot contribute actively here.

**Comment by kataras** [comment]
@jnsone11 I can't answer you right now, but when I do it how you will be noticed? you aint starred iris

**Comment by jnsone11** [comment]
I'm following this thread.

**Comment by kataras** [comment]
@sebastianmacias I'm sorry to tell you, but I think you already figure it, that the link you sent me of a project ,it is just a mess... it isn't stable and has many bugs, its code and contributors are not really the best... we have to wait some time more if not declined

**Comment by thedevsaddam** [comment]
@kataras I think it won't be wise to add js library/framework to this framework. Because If I use your framework to build a service/microservice(?) I don't need any js library. I only need API's or the backend not the front-end :)

**Comment by kataras** [comment]
Yes, this was my first idea but you got many votes on your feature request and you made me to think about it, if you find something worths please let me know, today I will publish the http/2 support :)

**Comment by kataras** [comment]
@thedevsaddam You have right. To be honest with you, this was my first thought but this feature request got many votes from the community, I couldn't ignore it. I thought about it but after some research and @sebastianmacias 's last comment, I really don't know, I am letting this open in order to give an opportunity to the users to comment their ideas about it, let me know if you find something worths!
