### ISSUE TITLE
Accusations and remarks

### ISSUE THREAD

**Issue by kryptodev** [kataras/iris#504]
- Version : **V4-LTS**

- Operating System:

- [x] I have read the [book](https://docs.iris-go.com), [examples](https://github.com/iris-contrib/examples), [contributing file](https://github.com/kataras/iris/blob/master/.github/CONTRIBUTING.md) and I'm sure that this issue is not posted & answered before.

--------------

Hi,

I got the Go Newsletter in my email today, and this was linked to me: http://www.florinpatan.ro/2016/10/why-you-should-not-use-iris-for-your-go.html

It seems to me they have multiple accusations regarding Iris, going from you stealing code to as far as saying you are infringing license to a certain extent.

One of the accusations also mention that Iris benchmarks are faked, and further goes on to say that Iris caches in an overwhelming manner, and there is very less Cache control which can break API.

That being said, I have been using Iris on my production site since v2 of Iris and serve over 400000 unique people each day on my site, yet have never experienced the issues the article mentioned. My site runs blazing fast.

Of course, I never contributed to the source code of Iris, so I don't know what your stance and behavior on PRs and Commit history is, but otherwise, I'm really really impressed with Iris.

Kataras, this issue is to just take a little bit of your moment so I as well as other users of Iris can get some clarification in regards to the accusations and remarks mentioned in that article because the negativity needs to be dealt with, and issues, personal animosities(jealousy) need to be resolved.

Thank you for your time.

**Comment by kataras** [comment]
You're old iris user, what do you say?

**Comment by kataras** [comment]
Nothing to say, they are just competitors. Two people started these defamation contained edited screenshot and misdirection arguments. They just panic and don't want to accept that only one person can make a project which are better than 3-years old relative projects with 80+ contributors. 

I have never steal code, I'm working on iris 100% percent. Features were and will be implemented one by one, full nights to complete iris user's feature requests (you should know this, you're old iris user), which are unique, so from where I steal from another planet..? (See the julian's comment on this blogpot also)

**Comment by kataras** [comment]
Please the next time ask questions on the chat, you know that I can't convert iris' issues list to reddit or to a blogspot, but I can understand you, just think clear and see the big picture, I don't want to make them 'famous' because that I never commented on their posts and accusations, I am answering only on my own willing, but I made an exception because I respect you as an iris member :) Thanks!!

**Comment by kryptodev** [comment]
Thank you for the clarification @kataras I'm doing great :)

I hope you are too.

I read your replies and also read many of theirs. It clearly seems that they are jealous of you, something I told you will surely happen in due time.

Regards, and keep up the project, it's going strong!

Above all remember:
“To be successful you need friends and to be very successful you need enemies.” 
― Sidney Sheldon, The Other Side of Midnight

**Comment by kataras** [comment]
You're welcome, as always!

I had some issues with my health, I did some time off,  (~1 week) and now I feel great, I love to code so I can't be away from a keyboard for longer period of time.

Yes, I don't know if they are jealous(I'm not something special) or just they try to advertise themselves and their packages through iris... but it's ok because every time they do things like these, users eventually do their own research and understands what's happening, as a result of these defamations, iris always grows more than before, so they help us but they don't know it yet :)  

I'm sure that your web app is going very very well (400k unique people are big number!!)
I liked the last phrase, I had this feeling too ahah, nice and thanks for your support
