### ISSUE TITLE
Why you editing user comments in issues?

### ISSUE THREAD

**Issue by katarashasblockedme** [kataras/iris#505]
__MY__COMMENT__WAS__REMOVED

**Comment by rdyz85** [comment]
He also, editted the history to make it look like he never wiped it. Looks like he pulled the history from another fork.

Not to mention, two issues that really stand out.

https://github.com/kataras/iris/issues/504 - kind of funny since that guys website doesn't even work 

https://github.com/kataras/iris/issues/502 - question asked literally right after history was  restored

Looks like paid for issues...

**Comment by katarashasblockedme** [comment]
@rdyz85 I have asked the question in #502 and got blocked, my question was wiped by @kataras.

Yes, history looks like pulled from one of forks. This looks messy and probably users don't even know what going on really. There is bad citizen in opensource world :(

**Comment by kryptodev** [comment]
@rdyz85 My website is not publicly associated with me. If you're talking about kryptodev.com then I only use it for email purposes currently. Add me on skype 'kryptodev' and I'll make you feel so sorry you wrote that. lol
I don't think someone can pay me with the money I make on a daily basis if you get to know me. :)

I can see how jealous you guys are here, clearly. @kataras is a young guy, much younger than me and quite smart. It's better to encourage smart minds like them rather than doting on them and discouraging them.

However, brats like yourself can't help it right? I don't want to make it into a dramafest but since you brought me up, I decided you should acquaint yourself with who you are talking about. Yes I'm narcissistic, but also a supporter of talent. 

Good day.

**Comment by katarashasblockedme** [comment]
@kryptodev when you talking about talent you talking about supporting the faking of user comments and opinions? If yes then we have nothing to talk.

**Comment by kataras** [comment]
@katarashasblockedme If you are going to insulting iris members yes, I will block you, and remove your comments and everything else I want to do on you, You are not in position to tell me what to do and what not.

**Comment by katarashasblockedme** [comment]
@kataras I haven't insulted any people, but I have been insulting when my comments got wiped.

**Comment by kataras** [comment]
@kryptodev No need to write comments on them, I am blocking and removing these comments, they are copying sentences from blogs and writing here.. lol these are not their opinions, they are just bots, so we can act like game players controlling bots :)

**Comment by itsmeagain11** [comment]
So... @kataras, please, answer a questions from me. Why you editing user comments in a manner that comfortable to you? Why you deleting them even if they not insulting someone? What you trying to achieve with repository history resets, user comments amendment and user blocking?

**Comment by itsmeagain11** [comment]
Blocking me will not help you escape from questions.

**Comment by kataras** [comment]
I told you, you are just a bot you don't have opinion, Read the 504 issue and you will understand why I act like you are a bot

**Comment by itsmeagain11** [comment]
Well, I see. You just a kid ;)

**Comment by kataras** [comment]
Can you tell me now, why I have to explain every movement to you? you the f are you exactly , a type of 'policeman' in your child mind? Listen to this boy: I dont own you

**Comment by ryoungio** [comment]
It's cool man, I got the pictures.
