### ISSUE TITLE
Named parameters don't work as first URL component

### ISSUE THREAD

**Issue by chocolatkey** [kataras/iris#510]
- Version : latest

- Operating System: Windows, Go 1.7

Hi,
I have a problem getting the named parameters to work if it is at the root level. Here is my code:

```go
// Frontend pages
frontend_pages := []string{
    "about",
    "members",
    "support",
    "why",
}
iris.Get("/:page", func(ctx *iris.Context){
    page := ctx.Param("page")
    println(page)
    sort.Strings(frontend_pages)
    i := sort.SearchStrings(frontend_pages, page)
    if i < len(frontend_pages) && frontend_pages[i] == page {
        fmt.Printf("matches \"%s\" at frontend_pages[%d]\n", frontend_pages[i], i)
        ctx.MustRender("frontend/" + frontend_pages[i] + ".html", _base)
        return
    }
    if(page == ""){// No page specified
        ctx.MustRender("frontend/index.html", _base)
        return
    }
    ctx.Next() // Move on to static files
})
```

If I visit /about or / I just get a 404, but if I change the get to _/anything/:page_ it will work just fine (I see the printed lines), and I can visit the pages. Am I misunderstanding how the parameters work? Can they not be used as the first thing in the url (I noticed there were no examples of this)?

**Comment by kataras** [comment]
Hello,

`iris.Get("/:page")` will never be work for your own good, try to use `iris.Get("/*page")` instead.

Please the next time read older post issues and the book before posting a new one post


Cheers,,
kataras

**Comment by chocolatkey** [comment]
/*page doesn't work either

**Comment by chocolatkey** [comment]
![popop](https://cloud.githubusercontent.com/assets/13407784/19653196/e47f439a-9a13-11e6-964a-017fd77af91a.gif)

**Comment by kataras** [comment]
It seems to work on me (`StaticWeb`) .

Maybe something other causes this issue and not the route itself, if you want help, star iris please

**Comment by chocolatkey** [comment]
I could've sworn I had already starred it, well now it is.

**Comment by kataras** [comment]
Ok, wait for 10-15 minutes and you will have the fix :) thanks!

**Comment by kataras** [comment]
Ok, we found the problem is not inside iris.

Now you saw me all the code and I can understand that you are registering `/login` ,`/users` that's fine but when you go to register `/*page` it cannot be happen, static and dynamic cannot be combined in the same route prefix, as **book** says and other post issues...

**Comment by chocolatkey** [comment]
I'm sorry I don't understand where I'm combining the two, could you please link me to the page in the book that explains that?
THanks

**Comment by kataras** [comment]
- https://github.com/kataras/iris/issues/454
- https://github.com/kataras/iris/issues/178

And much more which I give the same solution...

**Comment by kataras** [comment]
Before post a new issue, the template ask you this thing:

- [x] I have read the [book](https://docs.iris-go.com), [examples](https://github.com/iris-contrib/examples), [contributing file](https://github.com/kataras/iris/blob/master/.github/CONTRIBUTING.md) and **I'm sure that this issue is not posted & answered before**


- https://github.com/kataras/iris/issues/454
- https://github.com/kataras/iris/issues/178

And much more which I gave the same solution, its not personal, you are a nice guy but you have to see that I am alone here it is not possible to answer the same things again and again on each one :/

You're welcome and do not hesitate to ask again!

**Comment by chocolatkey** [comment]
Thank you. I will research more carefully next time!

**Comment by kataras** [comment]
I thanks for your patient, I am not an easy person !
