### ISSUE TITLE
api swagger browser

### ISSUE THREAD

**Issue by jjhesk** [kataras/iris#511]
- Version : **V4-LTS**

- Operating System:

- [x] I have read the [book](https://docs.iris-go.com), [examples](https://github.com/iris-contrib/examples), [contributing file](https://github.com/kataras/iris/blob/master/.github/CONTRIBUTING.md) and I'm sure that this issue is not posted & answered before.

--------------

Hi,
Are there any plans to implement api swagger browser like alot other framework has provided. Are there a list of hierarchy that filter of the query can be done by other event listener.

**Comment by kataras** [comment]
Hello @jjhesk , 

You checked **I'm sure that this issue is not posted & answered before.** so I'm sure that you know that this is asked two times before... I don't know about other frameworks support this, and if they do it without reason. 

At Iris you can create a `plugin` which can suit your needs, there is no reason to be built'n feature in the core iris library, maybe if you have asked this from the [community plugins repository](https://github.com/iris-contrib/plugin) the answer could be positive.

Reference: https://github.com/kataras/iris/issues/177


Thanks for your interest,
kataras
