### ISSUE TITLE
Package confusion 

### ISSUE THREAD

**Issue by cristian-sima** [kataras/iris#517]
On old versions, there were only packages from `github.com`. 

On `v.4` there are packages only from `gopkg.in`. Aside from [documentation](https://github.com/iris-contrib/examples/blob/master/template_engines/template_html_0/main.go) where I find `import "github.com/kataras/iris`

Can someone clarify this as I am getting really confused. When to use `github` and when the new `gopkg.in` ?

**Comment by kataras** [comment]
Hello @cristian-sima , All repositories have `v4` branch, including the book and the examples. The `docs.iris-go.com` didn't changed because for now we have no changes from v4 to master. **Use the `gopkg.in/kataras/iris.v4` when you build something for production use and you don't want any future changes to conflict your application ** . As I understand you are new to go, it's pretty simple, most of golang packages uses the gopkg.in for stable versions

**Comment by cristian-sima** [comment]
@kataras Thanks for your help.

I'm not new to Go, but I didn't used gopck.in

**Comment by kataras** [comment]
You better do if you want to secure your app from any future changes :) , You're welcome as always!!

**Comment by cristian-sima** [comment]
Did `github.com/iris-contrib/templates` moved to `github.com/kataras/go-templates` ?

**Comment by kataras** [comment]
Yes, 4 months ago... book & examples were also updated back then, the stable repo is `gopkg.in/kataras/go-template.v0`

**Comment by cristian-sima** [comment]
@kataras getting a strange error with these packages 

![image](https://cloud.githubusercontent.com/assets/12199042/19850256/348bc06a-9f60-11e6-8eb6-d37ab399187e.png)

**Comment by cristian-sima** [comment]
Solved it

**Comment by kataras** [comment]
I tested all packages on a clean machine, I don't believe there is an error through the last changes, but if you find something just write it here and I'll fix it fast

**Comment by kataras** [comment]
Oh you solved it, nice, could you ,please, tell me what was the issue?

**Comment by cristian-sima** [comment]
Yep.

It seems it is from [somewhere here](https://github.com/search?utf8=%E2%9C%93&q=Error%3A+Serializer+with+key+index+couldn%27t+be+found&type=Code&ref=searchresults)

So I have this code:

```go

	iris.UseTemplate(html.New(html.Config{})).Directory("./server/templates", ".html")

	iris.Config.IsDevelopment = IsDevelopmentMode

	iris.Static("static", "./server", 0)
```

and somewhere

```
	func(c *iris.Context) {
			c.Next()
			c.MustRender("index", nil)
		},
```

and the errors says that `index` key is not found. Then to test if from there is the error I changed `index` to `index0` and the error was with `index0`.

**I solved it ** by changing `index` to `index.html`. It seems strange cause I already specify the extension `html` for `Directory` method, but it gave that problem

**Comment by kataras** [comment]
No, you have to put `extension` on your files, it's not strange because (after the re-write and move to kataras/go-template) now you can ** register more than one template engine in the same directory, so you need to specify the extension in order to let iris find the correct template engine, and you set an extension on the .Directory because you can have more than one extension for the same template engine (many-to-many thing) **

**Comment by cristian-sima** [comment]
I see :) Thanks

**Comment by kataras** [comment]
Can I ask something? The github changes the markdown for comments? My asterix doesn't works!! :P

**Comment by cristian-sima** [comment]
Yes. It is strange formatted.

**Comment by cristian-sima** [comment]
It may be from keyboard

**Comment by kataras** [comment]
Hmm I have to investigate it, thanks!

**Comment by cristian-sima** [comment]
Asterix is this ? `*` ?

if you want to `bold` or `italic` the text, you must not leave space between asterix and your phrase. Otherwise it does not work

**Comment by kataras** [comment]
Because I see that you had to update iris a long time, you can take a look at the [HISTORY.md](https://github.com/kataras/iris/blob/4.0.0/HISTORY.md) for any new changes and added features that happened in the past months.


Yes, I am not leaving space I don't know what's happens but I think '`' and parenthesis conflicts it (I use github for a long time and that's my first day of trouble with markdown lol)

**Comment by cristian-sima** [comment]
Do you think it is better to use an Iris server instand of Nginx.

As a public server (I have another server using Iris which is the main one (API, templates, etc... ))

**Comment by kataras** [comment]
Nginx is more like balancer, not a web framework, you mean in front, so you need a load balancer or something like this to manage your traffic. You can use `caddy` and `nginx`, many iris developers uses caddy, but I didn't tried caddy, yet.

**Comment by kataras** [comment]
Keep note that the last months I'm building a load balancer for Iris too, but this can late so use `nginx` which is a tested solution*

**Comment by cristian-sima** [comment]
Is it so much problem without balancer ?

**Comment by cristian-sima** [comment]
Nginx is so complicated and the configuration is awful

**Comment by kataras** [comment]
I know.... no it's not problem without balancer, if you use only one machine and you don't afraid for ''''hackers'''' or you don't have so much user traffic, then a proxy or a load balancer will slow your app

**Comment by kataras** [comment]
We can discuss this on the [community chat](https://kataras.rocket.chat/channel/iris) because here we are just spamming the iris repository's followers xD

**Comment by kataras** [comment]
Just to update: https://docs.iris-go.com/ are now use the `4.0.0` branch, so you should be able to see the stable import paths from there too
