### ISSUE TITLE
How to check that a request JSON body fit in certain struct?

### ISSUE THREAD

**Issue by karlos1337** [kataras/iris#523]
- Version : **V5.0.1**

- Operating System: Arch Linux

- [x] I have read the [book](https://docs.iris-go.com), [examples](https://github.com/iris-contrib/examples), [contributing file](https://github.com/kataras/iris/blob/master/.github/CONTRIBUTING.md) and I'm sure that this issue is not posted & answered before.

--------------

Hi, I am trying to check that a request JSON body fit in certain struct but it dont works at all, I can send a random request JSON body and ReadJSON never return an error, my code:

```
SignupReq struct {
  Name     string        `json:"name" bson:"name" form:"name"`
  Email    string        `json:"email" bson:"email" form:"email"`
  Password string        `json:"password" bson:"password" form:"password"`
}

signupBody := new(SignupReq)
if errReq := ctx.ReadJSON(signupBody); errReq != nil {
  ctx.JSON(iris.StatusBadRequest, errReq)
} else {
  [...]
```

**Comment by dxvgef** [comment]
Version : V5.0.1 😛

**Comment by kataras** [comment]
You're trying to use the `StatusBadRequest` which is a integer of value `400` as JSON and send it, how you think of that?... I don't understand your question, please give me an example of what you want to do, what results you expect and what you already tried and worked to your own project, thanks

**Comment by karlos1337** [comment]
I suppose might be ctx.EmitError(iris.StatusBadRequest) instead ctx.JSON...

But that's not the question.
I assume that if I need to use an struct ro ReadJSON it will check that the request json body has the struct parameters.

I expect something like this:

```
Client: POST({"name": "myName", "email": "my@email.com", "password": "myPass"})
Server: (204)

Client: POST({"randomParam": "test"})
Server: (400, "missing 'name' field...")
```

But ReadJSON never return an error so I always obtain a 204 response dispite an "invalid" json request body.

**Comment by kataras** [comment]
@karlos1337 

Are you sure? Because I just tested it with the missing `Other` field and is receiving the Company object with an empty `Other` field, please share with us the full handler's source code and struct in order to help you

```go
package main

import (
	"fmt"

	"github.com/kataras/iris"
)

type Company struct {
	Name  string
	City  string
	Other string
}

func MyHandler(ctx *iris.Context) {
	c := &Company{}
	if err := ctx.ReadJSON(c); err != nil {
		panic(err.Error())
	} else {
		fmt.Printf("Company: %#v", c)
		ctx.Write("Company: %#v", c)
	}
}

func main() {
	// use postman or whatever to do a POST request to the localhost:8080/bind_json with BODY: JSON PAYLOAD and HEADERS content type to application/json
	iris.Post("/bind_json", MyHandler)
	iris.Listen(":8080")
}
```

**Comment by karlos1337** [comment]
Sorry, my english is not good enought and maybe I am not explaining the question correctly, in the code you post, if I send a post with a json body like:

` POST("/bind_json", { "paramNotInStruct": "test" })`

server writes
 
`Company: &main.Company{Name:"", City:"", Other:""}`,  

I thought, and clearly I'm wrong, that ReadJSON detect that  "paramNotInStruct" are not in the struct and will `panic(err.Error())`, maybe I need to do an extra iteration over the object to detect that cases with something like a JSON Schema...

**Comment by kataras** [comment]
@karlos1337 Yes, but if you have a `struct` with `Name` and `City` how do you expect the `paramNotInStruct` to be injected inside the `struct`? Golang doesn't works like this.  **If you want `dynamic`** binding then you should use the `map[string]interface{}` not a `struct` , these are basic golang steps, not iris-specific

**Comment by karlos1337** [comment]
@kataras I don't expect param to be injected, I expect that ReadJSON return an error (err!=nil) because it is trying to inject a param that is not in the struct provided.

By the way, I will implement my desider behaviour using an external validation library after read the JSON body so my doubt has been resolved, I misunderstood ReadJSON method responsabilities.

Sorry for the inconvinients and thanks for your time, I really apreciate your job, keep it up!

**Comment by kataras** [comment]
@karlos1337 ReadJSON returns an error if body has no valid json data, but other cases should be checked by the developer, there are so many usages, we can't provide all of them in the `ReadJSON` because it will make it very very slow even for simple things, and we don't want it.

You're welcome and do not hesitate to ask again!

**Comment by kataras** [comment]
@karlos1337 ReadJSON returns an error if body has no valid json data, but other cases should be checked by the developer, there are so many usages, we can't provide all of them in the `ReadJSON` because it will make it very very slow (reflection and data validation can be done from the handler itself and it should be done by you, as developer, you have full control) even for simple things, and we don't want it.

You're welcome and do not hesitate to ask again!

**Comment by kataras** [comment]
@karlos1337 ReadJSON returns an error if body has no valid json data, but other cases should be checked by the developer, there are so many usages, we can't provide all of them in the `ReadJSON` because it will make it very very slow even for simple things and we don't want it. (reflection and data validation can be done from the handler itself and it should be done by you, as developer, you have full control) 

You're welcome and do not hesitate to ask again!

**Comment by udtrokia** [comment]
WONDER
