### ISSUE TITLE
Suggestions / feature requests 

### ISSUE THREAD

**Issue by sebastianmacias** [kataras/iris#528]
- Version : **5.0.1**

- Operating System: Lubuntu 16.04

- [x] I have read the [book](https://docs.iris-go.com), [examples](https://github.com/iris-contrib/examples), [contributing file](https://github.com/kataras/iris/blob/master/.github/CONTRIBUTING.md) and I'm sure that this issue is not posted & answered before.

--------------

Hi there,

I have a few feature requests that I could split in separated posts if you are interested:

* Integration with [Authboss](https://github.com/go-authboss/authboss): one of the great features frameworks like django has is that it gives you an user module for free, this is extremely helpful when starting new projects as most of the time implementing user registrations, authentication and authorization is a repetitive, boring task that could be avoided if this comes with the framework.

* [GORM](http://jinzhu.me/gorm/) integration and integrated [admin](https://github.com/qor/admin): It looks like [GORM](http://jinzhu.me/gorm) won the golang ORM war and [QOR](http://getqor.com/en) build a beautiful [admin](https://github.com/qor/admin) app for GORM that could be integrated with iris as well.

* [Transitions](https://doc.getqor.com/plugins/transition.html): again developed by QOR  this module allows you to quickly implement workflows for your structs.

Tnx

**Comment by jackey** [comment]
I think GORM is a good idea . + 1

**Comment by kataras** [comment]
The community already answered on GORM: **don't need and we should NOT put it as built'n inside Iris**, what stops you on using your favorite GORM library? Why we should make a new one or use existing, for what reason? to make its API easier than it's already is, it can't be easier than it is. I'm sorry but these typess of limited-integration is bad attribute for a low-level access framework like Iris, which you can do whatever you like with no limits by design.
