### ISSUE TITLE
Issue while registering route

### ISSUE THREAD

**Issue by sameersanatkpatro** [kataras/iris#529]
- Version : **5.0.1**

- Operating System:

- [x] I have read the [book](https://docs.iris-go.com), [examples](https://github.com/iris-contrib/examples), [contributing file](https://github.com/kataras/iris/blob/master/.github/CONTRIBUTING.md) and I'm sure that this issue is not posted & answered before.

--------------

Hi @kataras ,
I am facing an issue while registering the route.I am using the below url for two GET methods separately as below:

app.Get("/account/summary/:email",func(c *iris.Context){
.....
}

app.Get("/account/:email",func(c *iris.Context){
.....
}

The above is failing as below:
[IRIS] 2016/11/10 00:14:38 Error: Router: Path's part: 'summary/:email' conflicts with wildcard ':email' in the route path: '/account/summary/:email' !
panic: Error: Router: Path's part: 'summary/:email' conflicts with wildcard ':email' in the route path: '/account/summary/:email' !

Can you please help me know if I am missing something?
Thanks for the help in advance.

**Comment by kataras** [comment]
Before post a new issue, the template ask you this thing:

- [x] I have read the [book](https://docs.iris-go.com), [examples](https://github.com/iris-contrib/examples), [contributing file](https://github.com/kataras/iris/blob/master/.github/CONTRIBUTING.md) and **I'm sure that this issue is not posted & answered before**

You will find the solution there:

- https://github.com/kataras/iris/issues/454
- https://github.com/kataras/iris/issues/178



Do not hesitate to ask again!

**Comment by sameersanatkpatro** [comment]
Thanks a lot @kataras .

**Comment by kataras** [comment]
You're welcome @sameersanatkpatro
