### ISSUE TITLE
Error return from iris.Framework.Listen

### ISSUE THREAD

**Issue by wolfgangmeyers** [kataras/iris#532]
Can iris.Framework.ListenXXX methods return an error so that the calling code can capture and log it? Currently it panics, which is fine for most use cases. When running iris inside of a windows service, however, it is hard to capture that output and troubleshoot the cause of the panic.

**Comment by kataras** [comment]
Use `iris.Serve() error` if you want to manage the error.

`iris.Serve(iris.TCP4(":8080"))` or `iris.Serve(iris.LETSENCRYPT("mydomain.com"))` what ever you like, just pass a `net.Listener` and Iris will work just fine with that

**Comment by kataras** [comment]
`ListenXXX` **don't return an error, you have to take a closer look when you open an issue, please** 


Use `iris.Serve() error` if you want to manage the error.

`iris.Serve(iris.TCP4(":8080"))` or `iris.Serve(iris.LETSENCRYPT("mydomain.com"))` what ever you like, just pass a `net.Listener` and Iris will work just fine with that

**Comment by wolfgangmeyers** [comment]
Thank you - I was aware that ListenXXX methods do not return an error. I was opening this as a feature request, however your alternative examples look like they will work just fine. Thanks!

**Comment by kataras** [comment]
Oh sorry for my tune then, I though you told that they return `error`

A little history behind `ListenXXX`:

Before v4  the `ListenXXX` functions were actually return an error instead of panic but the whole community, back then, told me that they wanted to just panic on server startup errors, I didn't liked it but they all agreed so I changed it to panic on errors and I added a `Serve` function which let you customize the `net.Listener` and catch any error in the same time, the result is the best for each of usecase, I think :)

You're welcome!!
