### ISSUE TITLE
How to get the HTTP context in the OnConnection function of the websocket?

### ISSUE THREAD

**Issue by dxvgef** [kataras/iris#536]
- Version : **5.0.1**

```Go
package main

import (
	"github.com/kataras/iris"
)

func main() {
	iris.Config.Websocket.Endpoint = "/ws"
	iris.Websocket.OnConnection(func(c iris.WebsocketConnection) {
		//How do I get the http context or session here?
	})
	iris.Listen(":8080")
}
```

**Comment by kataras** [comment]
Before post a new issue, the template ask you this thing:

- [x] I have read the [book](https://docs.iris-go.com), [examples](https://github.com/iris-contrib/examples), [contributing file](https://github.com/kataras/iris/blob/master/.github/CONTRIBUTING.md) and **I'm sure that this issue is not posted & answered before**

You will find the solution there:

- https://github.com/kataras/iris/issues/508
- https://github.com/kataras/iris/issues/372

You don't have access to context inside `OnConnection`, websocket is an upgrade of http subprotocol. You should find correct ways to interact with your clients via websockets, at some of the older issues users found the solution, I'm sure if you read you will find yours solutions to your question too.

Do not hesitate to ask again!

**Comment by dxvgef** [comment]
Well, thank you!

**Comment by kataras** [comment]
You're welcome my friend!

**Comment by kataras** [comment]
*http.Request access from Websockets

Example:

- https://github.com/iris-contrib/examples/blob/master/websocket/main.go#L34

Relative commits to kataras/go-websocket:

- kataras/go-websocket@550fc8b

- kataras/go-websocket@62c2d98

> use the `c.Request()` only when you really need it, websockets have everything you need already.
