### ISSUE TITLE
About proxy() function in http.go file.

### ISSUE THREAD

**Issue by jackey** [kataras/iris#544]
It's not real issue. 

Here's the code. My question is what is OptionDisableBanner(true) returned ? i checked it should be OptionSet but i really didn't see any Router field in OptionsSet. I was confused so please help me to explain what is OptionDisableBanner(true)  returned . 

```
func Proxy(proxyAddr string, redirectSchemeAndHost string) func() error {
	proxyAddr = ParseHost(proxyAddr)

	// override the handler and redirect all requests to this addr
	h := ProxyHandler(proxyAddr, redirectSchemeAndHost)
	prx := New(OptionDisableBanner(true))
	prx.Router = h

	go prx.Listen(proxyAddr)

	return prx.Close
}
```

**Comment by kataras** [comment]
Hello @jackey this probably is a general programming question about `option(al) design pattern` .

You have 3 ways to configure your iris, these are explained on book but I'm happy to explain them here too :) 

-  first is by passing a `iris.Configuration` inside the `iris.New(conf)` method
- second is by passing an `OptionSetter` inside the `iris.New(OptionDisableBanner(true))` for example is the same as `iris.New(iris.Configuration{ DisableBanner: true, AND ALL OTHER FIELDS TO THEIR DEFAULTS})`, the `iris.OptionXXX` is just a pattern which allows you passing configuration fields one by one, optionally while the rest of the configuration's fields stays to their defaults
- third, is by passing an `iris.Config = iris.Configuration{myfield:myvalue}` after the `iris.New()//which is making a new iris station with the default configuration and returns it` or `iris.Set(iris.OptionDisableBanner(true))` for example, if you press `iris.Option` in your code editor(with auto-complete popup support) you should see all `OptionXXX` methods available, all configuration fields in iris are converted also in Options in order to help you avoid writing code something, meaning: ` conf := iris.DefaultConfiguration(); conf.DisableBanner = true; iris.New(conf)`  is the same as `iris.New(iris.OptionDisableBanner(true))` 

For more information about option pattern works I made a repository, take a look [here](https://github.com/kataras/go-options).

Hope that I helped you, but note that I'm not a native english speaker, so it will be better if you just search on google about design patterns for further research.

Do not hesitate to ask more!

**Comment by kataras** [comment]
Hello @jackey this probably is a general programming question about `option(al) design pattern` .

You have 3 ways to configure your iris, these are explained on book but I'm happy to explain them here too :) 

-  first is by passing a `iris.Configuration` inside the `iris.New(conf)` method
- second is by passing an `OptionSetter` inside the `iris.New(OptionDisableBanner(true))` for example is the same as `iris.New(iris.Configuration{ DisableBanner: true, AND ALL OTHER FIELDS TO THEIR DEFAULTS})`, the `iris.OptionXXX` is just a pattern which allows you passing configuration fields one by one, optionally while the rest of the configuration's fields stays to their defaults
- third, is by passing an `iris.Config = iris.Configuration{myfield:myvalue}` after the `iris.New()//which is making a new iris station with the default configuration and returns it` or `iris.Set(iris.OptionDisableBanner(true))` for example, if you press `iris.Option` in your code editor(with auto-complete popup support) you should see all `OptionXXX` methods available, all configuration fields in iris are converted also in Options in order to help you avoid writing code something, meaning: ` conf := iris.DefaultConfiguration(); conf.DisableBanner = true; iris.New(conf)`  is the same as `iris.New(iris.OptionDisableBanner(true))` 

So the `New` method always returns a new *Iris, you can leave it empty, means that default configuration will be used, or passing OptionXXX methods or passing a Configuration iteral.

The Proxy question is something other, is just a pure and not well-written function  but it does the job I wanted to do, it is used when `iris.ListenLETSENCRYPT("mydomain.com")` is called, it just navigates all `http://mydomain.com/$path` to `https://mydomain.com/$path` this is the only job that proxy handler does in the http.go file, nothing more, nothing special, it is used automatically you don't have to call it manually.

For more information about how option pattern works I made a repository, take a look [here](https://github.com/kataras/go-options).

Hope that I helped you, but note that I'm not a native english speaker, so it will be better if you just search on google about design patterns for further research.

Do not hesitate to ask more!
