### ISSUE TITLE
Websocket reconnecting multiple times just stops connecting

### ISSUE THREAD

**Issue by danielfbm** [kataras/iris#555]
- Version : **5.0.4**

- Operating System: Linux Ubuntu 14.04 on Docker

- [x] I have read the [book](https://docs.iris-go.com), [examples](https://github.com/iris-contrib/examples), [contributing file](https://github.com/kataras/iris/blob/master/.github/CONTRIBUTING.md) and **I'm sure that this issue is not posted** & answered before.

--------------

I created a server to manage multiple websocket connections and everything works smoothly but...
I will try to describe the scenario here:

In my team we met a problem when using Iris websockets, in a development environment the developers are used to compile the javascript very often and that would automatically reload the webpage and reconnect to the webserver. It all works well, but we notice that after some reconnects the webserver seems to not execute the OnConnection method. If I restart the webserver it generally works out.

My question is quite simple: Is there any way for me to debug if the reconnection is really being processed as a new connection or as an attempt to reconnect? 

My other guess would be that at some point the server meets a deadlock somehow and I cant really connect anymore..

Any clues or ideas on these?

Thanks

**Comment by kataras** [comment]
My question is quite simple: Is there any way for me to debug if the reconnection is really being processed as a new connection or as an attempt to reconnect? 

No, at its current implementation iris can't tell you if it's reconnecting because of fault or it's new connection, because all the times it creates a new connection, in the code we don't have 'reconnected' meaning, only 'connected'

**Comment by kataras** [comment]
My question is quite simple: Is there any way for me to debug if the reconnection is really being processed as a new connection or as an attempt to reconnect? 

No, at its current implementation iris can't tell you if it's reconnecting because of fault or it's new connection, because all the times it creates a new connection, in the code we don't have 'reconnected' meaning, only 'connected' . But if you have team you will figure it out, I already though a couple of ways to do manage it without the need of special `reconnected` event...

**Comment by kataras** [comment]
My question is quite simple: Is there any way for me to debug if the reconnection is really being processed as a new connection or as an attempt to reconnect? 

No, at its current implementation iris can't tell you if it's reconnecting because of fault or it's new connection, because all the times it creates a new connection, in the code we don't have 'reconnected' meaning, only 'connected' . But if you have team you will figure it out, I already though a couple of ways to manage it without the need of special `reconnected` event ( don't forget that you can collect all incoming websocket connections and keep them in a list, and OnDisconnect just remove them, so you will always have connected, there you can add a second list on disconnect and check if that element is equal to the new connected and it passed only 1 second before the previous disconnection (for example), if it's then probably it's reconnecting)

**Comment by danielfbm** [comment]
yes, I actually already handle it like this, but after reconnecting even in the client side when I emit an event I dont get it in the server side, actually even new connections are not able to be stablished. I will first try to find a reproducible scenario and I will post it here later. 

Thanks

**Comment by kataras** [comment]
Xmm that's strange I'll wait, thanks!!

**Comment by kataras** [comment]
Xmm that's strange I'll wait, thanks!!

Theissue is not coupled with iris as I could understand, so I please you post the new issue with a scenario and code snippet to the correct repository this time, here: https://github.com/kataras/go-websocket (as the [contribution file](https://github.com/kataras/iris/blob/master/.github/CONTRIBUTING.md) says)

**Comment by kataras** [comment]
Xmm that's strange I'll wait, thanks!!

This issue is not strong coupled with iris as I could understand, so I please you post the new issue with a scenario and code snippet to the correct repository this time, here: https://github.com/kataras/go-websocket (as the [contribution file](https://github.com/kataras/iris/blob/master/.github/CONTRIBUTING.md) says)
