### ISSUE TITLE
ctx.EmitError in a middleware makes an infinite loop

### ISSUE THREAD

**Issue by jarnix** [kataras/iris#566]
- Version : **5.1.3**

- Operating System:

Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02) x86_64 GNU/Linux

- [x] I have read the [book](https://docs.iris-go.com), [examples](https://github.com/iris-contrib/examples), [contributing file](https://github.com/kataras/iris/blob/master/.github/CONTRIBUTING.md) and **I'm sure that this issue is not posted** & answered before.

--------------

Hello,

I'm using a middleware that could emit an error. This simple code:

```
package middlewares

import "github.com/kataras/iris"

// CookieHandler manages the cookie in the headers
func CookieHandler(ctx *iris.Context) {

	ctx.EmitError(iris.StatusUnauthorized)

	ctx.Next()
}

```
instantiated from this line:

```
server.Get("/", middlewares.CookieHandler, handlers.Home)("home")
```

will throw this in the console: (and the app will halt)

```
runtime: goroutine stack exceeds 1000000000-byte limit
fatal error: stack overflow

runtime stack:
runtime.throw(0xa99d8d, 0xe)
        /usr/local/go/src/runtime/panic.go:566 +0x95
runtime.newstack()
        /usr/local/go/src/runtime/stack.go:1061 +0x416
runtime.morestack()
        /usr/local/go/src/runtime/asm_amd64.s:366 +0x7f

(snip)
```

**Comment by kataras** [comment]
Hello @jarnix ,

Normally you don't have to run`ctx.Next()` after EmitError, because EmitError calls the `ctx.StopExecution()` so it 'should' ignore the `ctx.Next()` , the bug was exactly here, because of `ctx.Pos` was uint8 (255 max) and `ctx.StopExecution()` sets this to the value of 255, but on `ctx.Next()` I did ctx.Pos++ so it was resetted back to `0` , this was the bug[the flow of ctx.EmitError -> ctx.Next] .

It should be fixed now, please verify it and **thank you**, I though that no one will run `ctx.Next()` after `ctx.EmitError` , anyway is better that we fixed that for any case!

**Comment by jarnix** [comment]
Hell @kataras,

Oh okay I understand it was a strange! Anyway, it's okay now and should prevent this issue from happening. I also changed my code.

Thank you :-)

**Comment by kataras** [comment]
You're welcome, I thank you for your contribution
