### ISSUE TITLE
/iris-ws.js is not served automatically in mongo-example

### ISSUE THREAD

**Issue by msowka-ninja** [kataras/iris#579]
- Version : **6.0.5**

- Operating System: debian

- [x] I have read the [book](https://docs.iris-go.com), [examples](https://github.com/iris-contrib/examples), [contributing file](https://github.com/kataras/iris/blob/master/.github/CONTRIBUTING.md) and **I'm sure that this issue is not posted** & answered before.

--------------
I tried the mongo example.
It seems that /iris-ws.js is not served automatically.

**Comment by kataras** [comment]
Are you sure? Try to clear your browser's history and try again... I just tested all websockets examples, try yourself: https://github.com/iris-contrib/examples/tree/master/websocket .

Please next time post examples issues in its repository not at the core, iris-ws is served here. Give more information, please, if the history clear didn't helped you.

**Comment by msowka-ninja** [comment]
I investigated a little bit more into it. Browser cache is not the issue as i get an 404 using curl on it.
iris-ws.js is served on the websocket example.
I was able to reproduce the error but I still didn't found the exact issue.
I've uploading the example on my other gihub account https://github.com/godofdream/example

(Offtopic) It's not possible to post issues on the iris-contrib/example project.

**Comment by kataras** [comment]
On the example is not served because your `main.go` didn't fired the `OnConnection`. Websocket server runs only when you want to use it(on first `iris.OnConnection(ws iris.WebsocketConnection)` and that its by-design as you can understand. I didn't [find](https://github.com/godofdream/example/search?utf8=%E2%9C%93&q=OnConnection) the `OnConnection` on the repository. About the examples' issues I don't know what they turned off I will re-open them after. thanks for the info. Tell me if my answer helped you understand why and when iris websocket server is running and when not

**Comment by kataras** [comment]
Dear @msowka-ninja , you don't use any websocket function in the example, because of this you don't see the client-side served, it's by-design.

Explaination:
On the example is not served because your `main.go` didn't fired the `OnConnection`, so the client side it will be useless so it is not served, for your own good of course.

**Websocket server runs only when you intend to use it** (on the first `iris.OnConnection(ws iris.WebsocketConnection) event callback registration`.

If you want just to serve the client side (.js) without use the server (no logic but...) then you can just pass an empty callback on the `OnConnection`, as bellow:
```go
// This will start the websocket server and serve the client side .js, if not started already 
// and after it will register the event to the websocket server,
// it has no impact to runtime: it's initialize itself when the event is registered
// (even before  the http server starts (`.Listen` functions)), 
// and not when a websocket client connected.
iris.Websocket.OnConnection(func(c iris.WebsocketConnection) {

})
```

I couldn't [find](https://github.com/godofdream/example/search?utf8=%E2%9C%93&q=OnConnection) the `OnConnection` on the repository. 


Please view the websocket [examples](https://github.com/iris-contrib/examples/blob/master/websocket/main.go#L27), it's very easy to understand how is working, it's like socket.io but only for websockets. 


> About the examples' issues list: I will re-open them later, thanks for the info.
