### ISSUE TITLE
i got received a event with several websocket datas at the same time.

### ISSUE THREAD

**Issue by ngleader** [kataras/iris#581]
- Version : **6.0.8**

- Operating System: OSX

- [x] I have read the [book](https://docs.iris-go.com), [examples](https://github.com/iris-contrib/examples), [contributing file](https://github.com/kataras/iris/blob/master/.github/CONTRIBUTING.md) and **I'm sure that this issue is not posted** & answered before.

--------------

I send simple text data over websocket.
such as "message 1", "message 2", ... by goroutine

but sometimes 2 or 3 text datas combined
u can see following browser debug console.

![2017-01-10 10 12 13](https://cloud.githubusercontent.com/assets/199256/21807421/f42c244c-d781-11e6-8b5c-06835490a349.png)

**Comment by kataras** [comment]
Dear @ngleader ,

You did the post in the wrong [repository](https://github.com/kataras/go-websocket) but at least please do not try to report a bug(?) without a code snippet. I'm waiting for a complete post.

Thanks,
kataras

**Comment by kataras** [comment]
Dear @ngleader , thanks for posting but I can't help or fix something that because: 

You did the post in the wrong [repository](https://github.com/kataras/go-websocket) but that's ok for your first time, I'm guessing that you didn't read the [contributingfile](https://github.com/kataras/iris/blob/master/.github/CONTRIBUTING.md), yet.  At least please do not try to report a bug(?) without a code snippet. I'm waiting for a complete post.

Thanks,
kataras

**Comment by kataras** [comment]
Dear @ngleader , thanks for posting but I can't help or fix something, because: 

You did the post in the wrong [repository](https://github.com/kataras/go-websocket) but that's ok for your first time, I'm guessing that you didn't read the [contributingfile](https://github.com/kataras/iris/blob/master/.github/CONTRIBUTING.md), yet.  At least please do not try to report a bug(?) without a code snippet. I'm waiting for a complete post.

Thanks,
kataras

**Comment by kataras** [comment]
Dear @ngleader , thanks for posting but I can't help or fix something, because: 

You did the post in the wrong [repository](https://github.com/kataras/go-websocket) but that's ok for your first time, I'm guessing that you didn't read the [contributing file](https://github.com/kataras/iris/blob/master/.github/CONTRIBUTING.md), yet.  At least please do not try to report a bug(?) without a code snippet. I'm waiting for a complete post.

Thanks,
kataras

**Comment by ngleader** [comment]
@kataras 
sorry, i made a following sample code.

I send messages "aaaa {number}" and "aaaa2 {number}" by two goroutines
but sometimes, browser(client) got received **"aaaa2 290go-websocket-message:chat;0;aaaa 290"**.
that is **"aaaa2 290"** and **"aaaa 290"** are merged.

```
package main

import (
	"fmt"
	"time"
	"runtime"

	"github.com/kataras/iris"
	"sync"
)

type clientPage struct {
	Title string
	Host  string
}

func main() {
	runtime.GOMAXPROCS(runtime.NumCPU())

	iris.StaticWeb("/js", "./static/js")

	iris.Get("/", func(ctx *iris.Context) {
		ctx.Render("client.html", clientPage{"Client Page", ctx.ServerHost()})
	})

	iris.Config.Websocket.Endpoint = "/endpoint"
	Conn := make(map[iris.WebsocketConnection]bool)
	var myChatRoom = "room1"


	iris.Websocket.OnConnection(func(c iris.WebsocketConnection) {
		c.Join(myChatRoom)
		Conn[c] = true
		c.OnDisconnect(func() {
			delete(Conn, c)
			fmt.Printf("\nConnection with ID: %s has been disconnected!\n", c.ID())
		})
	})

	var mutex = new(sync.Mutex)

	go func() {
		i := 0
		for {
			mutex.Lock()
			broadcast(Conn, fmt.Sprintf("aaaa %d", i))
			mutex.Unlock()
			time.Sleep(100 * time.Millisecond)
			i++
		}
	}()

	go func() {
		i := 0
		for {
			mutex.Lock()
			broadcast(Conn, fmt.Sprintf("aaaa2 %d", i))
			mutex.Unlock()
			time.Sleep(100 * time.Millisecond)
			i++
		}
	}()


	iris.Listen(":8888")
}

func broadcast(Conn map[iris.WebsocketConnection]bool, message string) {
	for k, _ := range Conn {
		k.Emit("chat", message)
	}
}
```

**Comment by kataras** [comment]
You miss the route and please add the relative snippet for the client side(.js) and a minimal .html in order to be in your exactly steps.

**Comment by kataras** [comment]
OK I did re-produce that and it's very strange, I think the client-side script has the issue, I'll investigate more and I'll answer you when I fix that (it should be easy but I have to do some other things first).

>  Don't forget that you can use any third-party websocket package with Iris, I'll never limit your options and your behaviors.

**Comment by kataras** [comment]
@ngleader Fixed, thanks for the report upgrade your iris `go get -u github.com/kataras/iris` and you should be fine, if you have any issues please let me know!
