### ISSUE TITLE
iris 5.0 can not be installed by go get

### ISSUE THREAD

**Issue by wolfkdy** [kataras/iris#582]
- Version : **5.0.0**

- Operating System: ubuntu 14.04

goprojs/src/gopkg.in/kataras/iris.v5/websocket.go:92: cannot use s.Server.HandleConnection (type func(*http.Request, "github.com/kataras/go-websocket".UnderlineConnection)) as type func("github.com/kataras/go-websocket".UnderlineConnection) in argument to "github.com/iris-contrib/websocket".Custom

It is certainly that you changed the code for iris 6.0. But the new code is not compatible with iris 5.0
I think you should make a new branch of go-websocket. old iris 5.0 relys on old go-websocket branch and the newer iris relys on the newer go-websocket
--------------

**Comment by kataras** [comment]
I did create branches before pushing the iris tag 5.0.0. For example: go-websocket has the 0.0.3 for the iris.v5 compatibility, the problem is that you have to download them manually and drop them to your $GOPATH/src/github.com/kataras folder because I didn't changed all  import paths (gitbook, examples, middleware, plugin, and other 20+ packages relative to iris) to `gopkg.in` as I did with `iris.v4`. Iris.v5 is more linked with fasthttp's server than before(v4) and you would have big problems to extend your iris.v5 web app in a case when fasthttp updates something critical. If you don't know what to do next please comment in order to give you the steps of downloading a branch and copying to the gopath.
