### ISSUE TITLE
Plz Provide the benchmark data and methods

### ISSUE THREAD

**Issue by wolfkdy** [kataras/iris#584]
Fake profile, one of other web framework's account.

**Comment by wolfkdy** [comment]
btw， I tested iris5.0 with the same code(client/server).
iris5.0 is at least 3x faster than iris6.0(e.g: I got 18W QPS use iris5.0)

But I did not see the difference between the benchmark results you posted in iris5.0 and iris6.0

**Comment by kataras** [comment]
Yes iris.v5 is the fastest in the world, faster than iris.v6 in benchmarks, but in real applications iris.v6 is even with iris.v5 and in the future faster than iris.v5, I didn't made new benchmarks because we don't need them for now, I'm waiting for the go v1.8 (for the .Push feature) , if you knew about web programming you wouldn't made that question.
