### ISSUE TITLE
performance decline in 6.1.2

### ISSUE THREAD

**Issue by wangcn** [kataras/iris#597]
I have a ip service for querying area with ip.When using iris v4, its qps was about 250,000.But when using iris6.1.2, it became to about 120,000. Is there something wrong?

my env:
OS: openSUSE42.1
go ver: 1.7.4
performance testing tool: wrk

**Comment by kataras** [comment]
If your benchmark code is the same, then the result is expected. Iris v6 is http/2 enabled by-default.So you have to re-write your benchmarks in order to match with HTTP/2 features (use go1.8 rc) and use the Push feature then you will see about +25% performance difference from Iris v5. When go 1.8 released I will publish new benchmarks, for now we have the v5 only.
