### ISSUE TITLE
hot-reload dosn't work

### ISSUE THREAD

**Issue by hooklife** [kataras/iris#598]
- Version : **6.1.2**

- Operating System: windows 7

- [x] I have read the [book](https://docs.iris-go.com), [examples](https://github.com/iris-contrib/examples), [contributing file](https://github.com/kataras/iris/blob/master/.github/CONTRIBUTING.md) and **I'm sure that this issue is not posted** & answered before.

--------------
`iris run main.go` 
 (i can't find hot reload method in docs,but find this in https://github.com/kataras/iris/tree/master/iris , it is the right way to hot reload? )

when i change code by sublime is ok,buy change code by JetBrains Gogland it dosn't work
Is this a iris bug or gogland bug?

I recorded a video http://recordit.co/JyFkIt2VKi

**Comment by kataras** [comment]
It doesn't works on JetBrains because JetBrains saves the files to the cache and it injects the disk classic method like sublime, atom, vscode and other editors and IDEs like eclipse, do. 

Do not use JetBrains+ Go plugin or the new alpha JetBrans Gogland, it is not ready yet and it doesn't offers you something more than atom + go-plus plugin or eclipse + go eclipse plugin.

My recommendation: Wait for the [activestate's Go Commercial IDE](http://www.activestate.com/go). Until then use atom + go-plus plugin.

I don't want to say that JetBrains is not a good IDE, it's the best for Java (and JavaEE) development and its company's Resharper for visual studio but at the Go industry it is a fail step, you may use it because you had read a lot articles about it, but believe me it is not good, especially its plugin, it will slow down your development and code skills.

**Comment by kataras** [comment]
It doesn't works on JetBrains because JetBrains saves the files to the cache it injects the disk classic method. Sublime, atom, vscode and other editors and IDEs like eclipse, works just fine with hot-reload. 

Do not use JetBrains+ Go plugin or the new alpha JetBrans Gogland, it is not ready yet and it doesn't offers you something more than atom + go-plus plugin or eclipse + go eclipse plugin.

My recommendation: Wait for the [activestate's Go Commercial IDE](http://www.activestate.com/go). Until then use atom + go-plus plugin.

I don't want to say that JetBrains is not a good IDE, it's the best for Java (and JavaEE) development and its company's Resharper for visual studio but at the Go industry it is a fail step, you may use it because you had read a lot articles about it, but believe me it is not good, especially its plugin, it will slow down your development and code skills.

**Comment by kataras** [comment]
It doesn't works on JetBrains because JetBrains saves the files to the cache it injects the disk classic method. Sublime, atom, vscode and other editors and IDEs like eclipse, works just fine with hot-reload. 

Do not use JetBrains+ Go plugin or the new alpha JetBrans Gogland, it is not ready yet and it doesn't offers you something more than atom + go-plus plugin or eclipse + go plugin or [LiteIDE](https://github.com/kataras/iris/tree/master/examples#run) (:I use LiteIDE when I'm creating the iris' examples, it offers nice features with one-click, for the most part of my day I use atom).

My recommendation: Wait for the [activestate's Go Commercial IDE](http://www.activestate.com/go). Until then use atom + go-plus plugin.

I don't want to say that JetBrains is not a good IDE, it's the best for Java (and JavaEE) development and its company's Resharper for visual studio but at the Go industry it is a fail step, you may use it because you had read a lot articles about it, but believe me it is not good, especially its plugin, it will slow down your development and code skills.

**Comment by kataras** [comment]
It doesn't works on JetBrains because JetBrains saves the files to the cache it injects the operating system's file signals (disk classic method for files). 

**Why?**: Iris' hot-reload (aka [rizla](https://github.com/kataras/rizla) ) uses `file operating system's events` to fire the app relad, other 'hot-reloaders' may using an infinitive loop over the `.walk` golang's stdlib every ~500ms to determinate the source code changes, but I decided (over benchmarks on big applications) that OS file 'events' is a more lightweight and more smarter solution, iris always uses the smartest and faster solutions for general purpose features.

Sublime, atom, vscode and other editors and IDEs like eclipse, works just fine with hot-reload. 

Do not use JetBrains+ Go plugin or the new alpha JetBrans Gogland, it is not ready yet and it doesn't offers you something more than atom + go-plus plugin or eclipse + go plugin or [LiteIDE](https://github.com/kataras/iris/tree/master/examples#run) (:I use LiteIDE when I'm creating the iris' examples, it offers nice features with one-click, for the most part of my day I use atom).

My recommendation: Wait for the [activestate's Go Commercial IDE](http://www.activestate.com/go) (I have inside information about its code and I tell you that it will change the way of go coding for the best) . Until then, use atom + go-plus plugin.

Don't get me wrong, JetBrains Intellij is the best IDE for Java(and JavaEE) development, the same for the Resharper visual studio tool.

But at the Go industry JetBrains makes failing steps from the begin of the go-plugin... now they are trying to fix the awful external go-plugin by pushing a new Family IDE, so-called, Gogland. 

Gogland is not ready and safe solution (I hope: yet). You may use it because you had read a lot articles about it, but believe me it is not good, especially its plugin, it will slow down your development and 'kill' your code skills as programmer.

**Comment by hooklife** [comment]
@kataras OK, i got it，thank you for your detailed answer。

**Comment by kataras** [comment]
You're welcome, any time! 

I'll let this issue open for a while, because many go developers may have the same question.

**Comment by Vorror** [comment]
@kataras Are you willing to make a flag that uses a different approach to checking for file changes?(Even if it's slower/more intensive?) Maybe something like -useSystemEvents, or -usePolling. Just a thought. I'm an IntelliJ(mutli-produce license) and would love to continue using their family of products if possible.

**Comment by kataras** [comment]
Of course, I can implement a way with the `walk` , like other go hot reloaders do but I 'warn' you that it will consume more cpu, open an issue [here](https://github.com/kataras/rizla) please.

**Comment by Vorror** [comment]
@kataras Will do :) Thanks for being accepting :D

**Comment by kataras** [comment]
Sorry @Vorror,  but can I ask you why you just don't use other go hot reloaders if you don't care about cpu?

**Comment by kataras** [comment]
Sorry @Vorror, but can I ask you why you just don't use other go hot reloaders if you don't care about cpu? (please don't missunderstood my question, I still can make a flag with rizla too*)

**Comment by Vorror** [comment]
@kataras Sorry, I wasn't sure if this hot reloader was specific to Iris or not. If it isn't then I can do that too. I'm new to Go+Ecosystem.

**Comment by kataras** [comment]
It's not specific to Iris, iris just uses its internal [Run](https://github.com/kataras/iris/blob/master/iris/run.go#L42), but open an issue with your feature request at the rizla's repository, I should code it sometime

**Comment by kataras** [comment]
Done: https://github.com/kataras/rizla/commit/b91b5bbfdf58e0d63b8033753efb85f345c537a0 

Usage: `rizla -walk main.go`. (`iris run main.go` will use that method on its **next** version)
