### ISSUE TITLE
CORS not working

### ISSUE THREAD

**Issue by es-lab** [kataras/iris#600]
- Version : **6.1.1**

- Operating System: mac os

- [x] I have read the [book](https://docs.iris-go.com), [examples](https://github.com/iris-contrib/examples), [contributing file](https://github.com/kataras/iris/blob/master/.github/CONTRIBUTING.md) and **I'm sure that this issue is not posted** & answered before.

--------------

@kataras I know this issue should be posted in the iris-contrib/middleware repo but there is no option to add issues there anymore so I'll write this here.

My usecase is as following:
I have my iris website on `domain.local:8080`, and an api on `api.domain.local:8080`.
I'm currently developing my angular2 app on `localhost:4200`.

Without applying any cors setup to the iris website, if my angular app makes requests to the api I get this error in the console: 
```
XMLHttpRequest cannot load http://api.domain.local:8080/test-api. 
Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. 
Origin 'http://localhost:4200' is therefore not allowed access. 
The response had HTTP status code 404.
```

After applying the default cors settings as following:
```
app.Use(cors.Default())
```
it should set the header `Access-Control-Allow-Origin:'*'` and allow any origin to make requests, but I still get the same error.
  
Now when I add the cors setup to the iris website as following:
```
app.Use(cors.New(cors.Options{
	AllowedOrigins:[]string{
		"localhost:4200",
	},
}))
```
again I'm getting the same error. 
  
I don't know what am I doing wrong. 
Please help me solving this.

Thanks

**Comment by kataras** [comment]
@es-lab Don't be sorry, 

Let's put some words because I'm getting this issue a lot of times, on some users it works on some others doesn't.

1. You can pass any middleware inside Iris, using the `iris.ToHandler` helper func.
2. So, you can use **any cors middleware** with iris if the existing doesn't suits you (and probably I will re-write it to fit the most cases) , a good alternative option is: https://github.com/rs/cors

This `rs/cors` middleware is not like other middleware which you can use with `iris.Use/UseFunc`, because it's better to use it as 'Router', so you should replace the iris.Router with the cors' handler (which should wraps the original 'Router' too). So I am re-writing an example of this (it's one way), here too: 
```go
import(
   "github.com/kataras/iris"
    "https://github.com/rs/cors"
)
// your routes here
iris.Get(...)
iris.Post(...)
// ...
// any code here 
// ...
// 
// then before iris.Listen make the replacement: 
originalRouter:= iris.Router
corsRouter := cors.Default().Handler(originalRouter)
iris.Router = corsRouter

iris.Listen(":4200")

```

Please test it in your environment ( clear your browser's cache first) and tell me the results :)

**Comment by kataras** [comment]
@es-lab Don't be sorry, 

Let's put some words because I'm getting this issue a lot of times, on some users it works on some others doesn't.

You can pass any middleware inside Iris, using the `iris.ToHandler` helper func.

------

So, you can use **any cors middleware** with iris if the existing doesn't suits you (and probably I will re-write it to fit the most cases) , a good alternative option is: https://github.com/rs/cors

This `rs/cors` middleware is not like other middleware which you can use with `iris.Use/UseFunc`, because it's better to use it as 'Router', so you should replace the iris.Router with the cors' handler (which should wraps the original 'Router' too). So I am re-writing an example of this (it's one way), here too: 
```go
import(
   "github.com/kataras/iris"
   "github.com/rs/cors"
)
// your routes here
iris.Get(...)
iris.Post(...)
// ...
// any code here 
// ...
// 
// then before iris.Listen make the replacement: 
originalRouter:= iris.Router
corsRouter := cors.Default().Handler(originalRouter)
iris.Router = corsRouter

iris.Listen(":4200")

```

Please test it in your environment ( clear your browser's cache first) and tell me the results please :)

**Comment by kataras** [comment]
@es-lab Don't be sorry, 

Let's put some words because I'm getting this issue a lot of times, on some users it works on some others doesn't. Also this middleware is **(I think the only one) which was not written by me,  it was a PR**,  and the most issues were reported for this middleware only, I'm tired to answer to others mistakes. This is why I am not allowing PRs to the main kataras/iris repository :). 

Be patient in order to make a middleware which will just convert the rs/cors handler to iris handler. 

**BUT**, You can pass any middleware inside Iris, using the `iris.ToHandler` helper func.

------

So, you can use **any cors middleware** with iris if the existing doesn't suits you (and probably I will re-write it to fit the most cases) , a good alternative option is: https://github.com/rs/cors

This `rs/cors` middleware is not like other middleware which you can use with `iris.Use/UseFunc`, because it's better to use it as 'Router', so you should replace the iris.Router with the cors' handler (which should wraps the original 'Router' too). So I am re-writing an example of this (it's one way), here too: 
```go
import(
   "github.com/kataras/iris"
   "github.com/rs/cors"
)
// your routes here
iris.Get(...)
iris.Post(...)
// ...
// any code here 
// ...
// 
// then before iris.Listen make the replacement: 

iris.Build() // use of Build in order to get the iris.Router
originalRouter:= iris.Router
corsRouter := cors.Default().Handler(originalRouter)
iris.Router = corsRouter

iris.Listen(":4200")

```

Please test it in your environment ( clear your browser's cache first) and tell me the results please :) 

> Note: if you can wait some minutes I will fix the cors issue, but I wanted you to understand that you can use any net/http middlware that already exists, you are not limited and restricted to the 9 middleware that I can provide for you, they exists mostly for your learning curve,read more here: https://github.com/kataras/iris/tree/master/middleware

**Comment by kataras** [comment]
@es-lab Don't be sorry, I should be.

Let's put some words because I'm getting this issue a lot of times, on some users it works on some others doesn't. Also this middleware is **(I think the only one) which was not written by me,  it was a PR**,  and the most issues were reported for this middleware only, I'm tired to answer to others mistakes. This is why I am not allowing PRs to the main kataras/iris repository :). 

Be patient in order to make a middleware which will just convert the rs/cors handler to iris handler. 

**BUT**, You can pass any middleware inside Iris, using the `iris.ToHandler` helper func.

------

So, you can use **any cors middleware** with iris if the existing doesn't suits you (and probably I will re-write it to fit the most cases) , a good alternative option is: https://github.com/rs/cors

This `rs/cors` middleware is not like other middleware which you can use with `iris.Use/UseFunc`, because it's better to use it as 'Router', so you should replace the iris.Router with the cors' handler (which should wraps the original 'Router' too). So I am re-writing an example of this (it's one way), here too: 
```go
import(
   "github.com/kataras/iris"
   "github.com/rs/cors"
)
// your routes here
iris.Get(...)
iris.Post(...)
// ...
// any code here 
// ...
// 
// then before iris.Listen make the replacement: 

iris.Build() // use of Build in order to get the iris.Router
originalRouter:= iris.Router
corsRouter := cors.Default().Handler(originalRouter)
iris.Router = corsRouter

iris.Listen(":4200")

```

Please test it in your environment ( clear your browser's cache first) and tell me the results please :) 

> Note: if you can wait some minutes I will fix the cors issue, but I wanted you to understand that you can use any net/http middlware that already exists, you are not limited and restricted to the 9 middleware that I can provide for you, they exists mostly for your learning curve,read more here: https://github.com/kataras/iris/tree/master/middleware

**Comment by es-lab** [comment]
I've tried your solution as following:
```go
// my routes initialize here..

app.Build()
originalRouter := app.Router
corsRouter := cors.Default().Handler(originalRouter)
app.Router = corsRouter
	
app.Listen("domain.local:8080")
```

But a build time it panics:
```go
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x13ccd3]

goroutine 1 [running]:
panic(0x610620, 0xc420156080)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
log.(*Logger).Panic(0xc420019540, 0xc4201f3bd0, 0x1, 0x1)
	/usr/local/go/src/log/log.go:206 +0xc7
github.com/kataras/iris.(*Framework).Serve.func1(0xc4201b1ad0)
	/Users/***/Documents/Projects/go/src/github.com/kataras/iris/iris.go:497 +0x8b
panic(0x64c0e0, 0xc42000c070)
	/usr/local/go/src/runtime/panic.go:458 +0x243
net/http.(*Server).setupHTTP2_Serve(0x0, 0xa38d90, 0xc420256000)
	/usr/local/go/src/net/http/server.go:2454 +0x33
net/http.(*Server).Serve(0x0, 0xa38d60, 0xc420256000, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2263 +0xaf
github.com/kataras/iris.(*Framework).Serve(0xc4201b1ad0, 0xa38d60, 0xc420256000, 0x0, 0x0)
	/Users/***/Documents/Projects/go/src/github.com/kataras/iris/iris.go:516 +0x135
github.com/kataras/iris.(*Framework).Listen(0xc4201b1ad0, 0x711fec, 0x11)
	/Users/***/Documents/Projects/go/src/github.com/kataras/iris/iris.go:601 +0xf1
main.main()
	/Users/***/Documents/Projects/go/src/orar/main.go:48 +0xeb
```

**Comment by kataras** [comment]
iris.go:497 is a comment but please wait I'm working on a solution (it takes a long because we should by-pass the iris.Router (because of the method matching) , if you do with `iris.Any` the iris-contrib/middleware/cors works but this is not what we want.

**Comment by kataras** [comment]
@es-lab I cleared the topic, could you please update the cors middleware with `go get -u github.com/iris-contrib/middleware/cors` , test one of these instead, and tell me the results?

```go
package main

import (
    "github.com/kataras/iris"
    "github.com/iris-contrib/middleware/cors"
)

func main() {
    iris.Use(cors.Default()) // enable all origins, disallow credentials

    iris.Get("/home", func(c *iris.Context) {
        c.Write("Hello from /home")
    })

    iris.Listen(":8080")

}
```
**OR** 
```go
package main

import (
    "github.com/kataras/iris"
    "github.com/iris-contrib/middleware/cors"
)

func main() {
  c := cors.New()
  // to enable credentials headers
  c.AllowCredentials()

  // allow origin per-domain
  c.AddOrigin("http://yourdomainhere.com")
  c.AddOrigin("http://otherdomainhere.com")

    iris.Use(c)
    // or per-route iris.Get("/mypath", c.Serve, myPathHandler) 

    iris.Get("/home", func(c *iris.Context) {
        c.Write("Hello from /home")
    })

    iris.Listen(":8080")

}
```


I remove the old middleware and created a new very basic and simple, `it is just works` . For more advanced things I pushed a cors router `plugin` which will act like a wrapper for an existing iris' router, see more [here](https://github.com/iris-contrib/middleware/tree/master/cors).

Thanks!

**Comment by es-lab** [comment]
@kataras I can't make it work.

Maybe I'm doing something wrong. So I'll explain my whole env. Maybe you see the error.

I'm executing all this on my macbook (localhost). I've edited the `/etc/hosts` to achieve the local domain `domain.local`.

`domain.local/*wildcard` returns the index.html
`ng.domain.local/*files` returns the final static files (js, css, etc..)
`api.domain.local` responds for my api requests

Code inside the JS files returned from `ng.domain.local` are making requests to the api `api.domain.local`.
Without cors setup, in the console I get this error:
```
XMLHttpRequest cannot load http://api.orarmd.local. 
Redirect from 'http://api.domain.local' to 'http://api.domain.local' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. 
Origin 'http://ng.domain.local' is therefore not allowed access.
```
  
Now, after adding `app.Use(cors.Default())` (new version), nothing changes, the error remains the same. 
What I've noticed is that the header `Access-Control-Allow-Origin` is empty, it does not contain the `*`. Is this normal?

Even declaring it the other way the header stays empty and the error persists:
```go
c := cors.New("*")
app.Use(c)
```
or
```go
c := cors.New()
c.AddOrigin("*")
app.Use(c)
```

I've tried to add a domain in the allowed origins:
```go
c := cors.New()

c.AddOrigin("ng.domain.local")

app.Use(c)
```
but now the entire website does not work, it return 200 OK with empty response (no matter the kind of response (eg: index.html, json, etc), the responses are empty).

How is your env setup? How do you test it, why it's working on your env but not on mine?

Thanks.

**Comment by es-lab** [comment]
Now, why I've mentioned the `localhost:4200` in the first comment is that I'm developing an angular app and I'm serving it to this host:port and a whatcher is setup to recompile/refresh on changes.

At the first I though that is the host difference that makes it not work properly, but now that I've tested it with a basic js file returned by iris, and a basic ajax request fails for the same reason. 
I don't know what else to try.

**Comment by kataras** [comment]
````go
c := cors.New()
c.AddOrigin("*")
app.Use(c) // or app.Use(c.Default()) should work
```

At the other hand, this should not pass the test, this is why you got empty responses: 
```go
c.AddOrigin("ng.domain.local")
```

Because you have to pass the whole origin, with the `http://` scheme: `c.AddOrigin("http://ng.domain.local"), this should work too` .

I have tested the cors on external machine and with a pure ajax script and is working fine...both middleware and plugin, so I have to ask you one thing more, did you get fail responses with the `cors plugin` too ?:

```go

import (
   "github.com/kataras/iris"
   "github.com/iris-contrib/plugin/cors"
)

func main(){
   app := iris.New()
   app.Plugins.Add(cors.Default())
   // your rest routes here...


   app.Listen(":4200")
}

```

**Comment by kataras** [comment]
```go
c := cors.New()
c.AddOrigin("*")
app.Use(c) // or app.Use(c.Default()) should work
```

At the other hand, this should not pass the test, this is why you got empty responses: 

```go
c.AddOrigin("ng.domain.local")
```

Because you have to pass the whole origin, with the `http://` scheme: `c.AddOrigin("http://ng.domain.local"), this should work too` .

I have tested the cors on external machine and with a pure ajax script and is working fine...both middleware and plugin, so I have to ask you one thing more, did you get fail responses with the `cors plugin` too ?:

```go

import (
   "github.com/kataras/iris"
   "github.com/iris-contrib/plugin/cors"
)

func main(){
   app := iris.New()
   app.Plugins.Add(cors.Default())
   // your rest routes here...


   app.Listen(":4200")
}

```

**Comment by kataras** [comment]
```go
c := cors.New()
c.AddOrigin("*")
app.Use(c) // or app.Use(c.Default()) should work
```

At the other hand, this should not pass the test, this is why you got empty responses: 

```go
c.AddOrigin("ng.domain.local")
```

Because you have to pass the whole origin, with the `http://` scheme: `c.AddOrigin("http://ng.domain.local"), this should work too` .

I have tested the cors on external machine and with a pure ajax script and is working fine...both middleware and plugin, so I have to ask you one thing more, did you get fail responses with the `cors plugin` too ?:

```go

import (
   "github.com/kataras/iris"
   "github.com/iris-contrib/plugin/cors"
)

func main(){
   app := iris.New()
   app.Plugins.Add(cors.Default())
   // your rest routes here...


   app.Listen(":4200")
}

```

Please clear your browser's cache and history before re-trying.

**Comment by es-lab** [comment]
@kataras I've solved the issue using the plugins option because I needed some custom headers to allow. Now everything works well. Thanks for support. 

P.S.: The initial problem was calling the api without a `/` at the end, iris somehow redirects it to a url with the `/` at the end, and in the response no `Access-Control-Allow-Origin` header is present. Is this normal?

**Comment by kataras** [comment]
So what do you propose? you remove entirely the cors middleware and keep the new cors plugin only? (the cors plugin works as wrapper to the router, the cors middleware can be registered to a route path alone too, plugin can't do that but it has more options...) 

For your question, it exists on book and examples but I'm happy to describe that again:

If the page is the root:  "/" then it becomes "http://localhost" without "/", this is the correct specification, you can read more by searching ' http specification '.

 But in other routes it just searching if you have a handler registered to "/user/" and your request is "/user" then it searches for "/user" registered handlers, if found then it redirects(permanently) to the "/user" and the same for the opposite direction, `if you want to disable this feature` use the `iris.Config.DisablePathCorrection = true ` as the book and examples says.

**Comment by kataras** [comment]
So what do you propose? remove entirely the cors middleware and keep the new cors plugin only? (the cors plugin works as wrapper to the router, the cors middleware can be registered to a route path alone too, plugin can't do that but it has more options...) 

For your question, it exists on book and examples but I'm happy to describe that again:

If the page is the root:  "/" then it becomes "http://localhost" without "/", this is the correct specification, you can read more by searching ' http specification '.

 But in other routes it just searching if you have a handler registered to "/user/" and your request is "/user" then it searches for "/user" registered handlers, if found then it redirects(permanently) to the "/user" and the same for the opposite direction, `if you want to disable this feature` use the `iris.Config.DisablePathCorrection = true ` as the book and examples says.

**Comment by kataras** [comment]
So what do you propose? remove entirely the cors middleware and keep the new cors plugin only? (the cors plugin works as wrapper to the router, the cors middleware can be registered to a route path alone too, plugin can't do that but it has more options...) 

For your question, it exists on book and examples but I'm happy to describe that again:

If the page is the root:  "/" then it becomes "http://localhost" without "/", this is the correct specification, you can read more by searching ' http specification '.

 But in other routes it just searching if you have a handler registered to "/user/" and your request is "/user" then it searches for "/user" registered handlers, if found then it redirects(permanently) to the "/user" and the same for the opposite direction, `if you want to disable this feature` use the `iris.Config.DisablePathCorrection = true ` as the book and examples says, my recommendation: keep that setting on.

**Comment by es-lab** [comment]
Cors setup is good. 

But.. I think it somehow breaks my cookies. I have a cookie `XSRF-TOKEN`:
domain: `.domain.local`
httpOnly: `false`, I need this to be read from javascript, and be sent as a header, and it does all correctly, in my middleware I'm able to read that header.
From postman I'm able to send the cookie, and can read it.
But from the browser it comes as empty, however in the browser inspect element I can see the cookie.
