### ISSUE TITLE
build faile

### ISSUE THREAD

**Issue by elvizlai** [kataras/iris#608]
- Version : **6.2.0**

- Operating System:

- [x] I have read the [book](https://docs.iris-go.com), [examples](https://github.com/iris-contrib/examples), [contributing file](https://github.com/kataras/iris/blob/master/.github/CONTRIBUTING.md) and **I'm sure that this issue is not posted** & answered before.

--------------

### Build failed because some middleware move from iris-contrib to iris.

```
/Users/elvizlai/GoLib/src/github.com/kataras/iris/middleware/recover/recover.go:8:2: cannot find package "gopkg.in/kataras/iris.v6" in any of:
        /Users/elvizlai/GoLib/src/github.com/kataras/iris/vendor/gopkg.in/kataras/iris.v6 (vendor tree)
        /usr/local/go/src/gopkg.in/kataras/iris.v6 (from $GOROOT)
        /Users/elvizlai/GoglandProjects/clserver/src/gopkg.in/kataras/iris.v6 (from $GOPATH)
        /Users/elvizlai/GoLib/src/gopkg.in/kataras/iris.v6
```

So I tried fetch from gopkg using  `go get gopkg.in/kataras/iris.v6`

But I got:

```
# cd .; git clone https://gopkg.in/kataras/iris.v6 /Users/elvizlai/GoLib/src/gopkg.in/kataras/iris.v6
Cloning into '/Users/elvizlai/GoLib/src/gopkg.in/kataras/iris.v6'...
error: RPC failed; HTTP 301 curl 22 The requested URL returned error: 301
fatal: The remote end hung up unexpectedly
package gopkg.in/kataras/iris.v6: exit status 128
```

Is this gopkg net work err?

**Comment by kataras** [comment]
@elvizlai The issue you're describing is caused by latest `git` it's `gopkg.in` temporary issue which wil lbe fixed very soon. Its fix is one-line for users. open your terminal and execute:  `git config --global http.https://gopkg.in.followRedirects true` . 

Read more at the previous issue posted 4 days ago:  https://github.com/kataras/iris/issues/605

Use only `gopkg.in/kataras/iris.v6` I will keep this pattern for each version separate in order to keep the balance between my features and your stability.

Thanks,
kataras

**Comment by kataras** [comment]
**UPDATE:** Issue solved, gopkg.in is fixed now, as its author says here : https://github.com/kataras/iris/issues/605#issuecomment-281407174
