### ISSUE TITLE
Feature: Cname resolution for specific parties

### ISSUE THREAD

**Issue by SilverCory** [kataras/iris#611]
To resolve cname records for specific parties could be really useful. Recursively of course!

If I don't make a PR just remember to limit the number of iterations of resolution because cname loops can be evil!

**Comment by kataras** [comment]
Man I didn't create the Policies(aka plugin ecosystem) for myself. You can create an iris feature without need to touch the main software, why you people can't believe that in 2017?.... 

Community repositories: the https://github.com/iris-contrib/adaptors neither the https://github.com/iris-contrib/middleware neither the https://github.com/iris-contrib/examples,

**Comment by kataras** [comment]
Look, my friend I didn't create the Policies(aka plugin ecosystem) for myself. You can create an iris feature without need to touch the main software, why you people can't believe that in 2017?.... 

Community repositories: 

the https://github.com/iris-contrib/adaptors 

the https://github.com/iris-contrib/middleware and the https://github.com/iris-contrib/examples,

**Comment by SilverCory** [comment]
Oh sweet I thought it was all one big thing, seen wip ;)

**Comment by kataras** [comment]
Why you ugry now...? You didn't explain anything about your idea yet..

**Comment by kataras** [comment]
@SilverCory You know that I am trying to keep the core of this framework as small as possible in order to be clear and light, there is no need to bring all in one.  If we can't make a `x` feature happen via adaptor or middleware then and only then we modify the main source code. 

Could you please now explain your idea?

**Comment by kataras** [comment]
@SilverCory You know that I am trying to keep the core of this framework as small as possible in order to be clear and light, there is no need to bring all in one.  If we can't make a `x` feature happen via adaptor or middleware then and only then I modify the main source code. 

Could you explain your idea, please?

**Comment by SilverCory** [comment]
Literally what it says on the tin, you could do it with middleware I'm pretty sure.

Just resolving the cname of a domain name on request (recursively so that you get right to the base), then allowing it to be matched on "Party" methods and what not.

I knew the core was being kept as small as possible, I wasn't sure on where to discuss this however.

Example: 
Cname test.testdomain.com -> something.example.com
With app.Party(".*") the subdomain is "test", when I'd be great if it was "something"
