### ISSUE TITLE
v6 Redirect method not work?

### ISSUE THREAD

**Issue by yunhor** [kataras/iris#614]
- Version : **6.2.0**

- Operating System: ubuntu 16.10,chrome,firefox
iris can work properly
`	iris.Get("/", func(ctx *iris.Context) {
		ctx.Redirect("/redirected")
	})

	iris.Get("/redirected", func(ctx *iris.Context) {
		ctx.Writef("Hello, you have been redirected!")
	})
`
but in iris.v6 do nothing
`
        app = iris.New()
        app.Adapt(httprouter.New())
	app.Get("/", func(ctx *iris.Context) {
		ctx.RedirectTo("/redirected")
	})
	app.Get("/redirected", func(ctx *iris.Context) {
		ctx.Writef("Hello, you have been redirected!")
	})
`
How to use Redirect method correctly?

**Comment by kataras** [comment]
Hello @yunhor , why you write 'v6 redirect doesnt work'? It's working as before, nothing changed from the context implementation

**Comment by kataras** [comment]
You use wrong method my friend... `ctx.Redirect` on your first example and you use `ctx.RedirectTo` on your second....

`ctx.Redirect` works and `ctx.RedirectTo` but `ctx.RedirectTo` its for redirecting to a `named route`, `ctx.Redirect` redirects to a path or url, so, try this: 

```go
package main

import (
	"gopkg.in/kataras/iris.v6"
	"gopkg.in/kataras/iris.v6/adaptors/httprouter"
)

func main() {
	app := iris.New()
	app.Adapt(iris.DevLogger())
	app.Adapt(httprouter.New())
	app.Get("/", func(ctx *iris.Context) {
		ctx.RedirectTo("/redirected")
	})
	app.Get("/redirected", func(ctx *iris.Context) {
		ctx.Writef("Hello, you have been redirected!")
	})

	app.Listen(":8080")
}

```

I added tests for redirect in order to help you, redirect with https and redirect to a named route, look here: https://github.com/kataras/iris/blob/v6/context_test.go#L243

**Comment by kataras** [comment]
You use wrong method my friend... `ctx.Redirect` on your first example and you use `ctx.RedirectTo` on your second....

`ctx.Redirect` works and `ctx.RedirectTo` but `ctx.RedirectTo` its for redirecting to a `named route`, `ctx.Redirect` redirects to a path or url, so, try this: 

```go
package main

import (
	"gopkg.in/kataras/iris.v6"
	"gopkg.in/kataras/iris.v6/adaptors/httprouter"
)

func main() {
	app := iris.New()
	app.Adapt(iris.DevLogger())
	app.Adapt(httprouter.New())
	app.Get("/", func(ctx *iris.Context) {
		ctx.Redirect("/redirected")
	})
	app.Get("/redirected", func(ctx *iris.Context) {
		ctx.Writef("Hello, you have been redirected!")
	})

	app.Listen(":8080")
}

```

I added tests for redirect in order to help you, redirect with https and redirect to a named route, look here: https://github.com/kataras/iris/blob/v6/context_test.go#L243

**Comment by yunhor** [comment]
Ah,I see,I used wrong method,but in iris 6.1.4,I use RedirectTo method,it can work.
Thanks a lot .

**Comment by kataras** [comment]
On iris 6.1.4 the name of the route was pre-defined to the route's PATH (you could/can change it via `.ChangeName`) . In this version the name is the METHOD+NAME. 

The function to redirect was always the `.Redirect` and to redirect to a named route with dynamic path parameters was and is the `.RedirectTo`.

You're welcome!!
