### ISSUE TITLE
Feature: Add adapt Bone

### ISSUE THREAD

**Issue by pcariel** [kataras/iris#640]
Hi, @kataras, It is possible to add this Multiplexer?
[https://github.com/go-zoo/bone](url)
thx

**Comment by kataras** [comment]
Yes, just a quick question, does it supports subdomains or I have to edit the whole library?

**Comment by kataras** [comment]
Hello @pcariel , It doesn't supports reverse routing, subdomains and named routes... I am working on this for two hours, I have managed to do all of them but with a lot of 'hacks' and I don't like this. The biggest part of mine dirty 'hacks' was for subdomain and wildcard subdomains support. I don't have time to contribute to golang routers BUT you requested this feature very politely, so I can't ignore you. I think that I can clone the repo ,re-rewrite this and push a PR to the bone repo in order to make it more extensible and useful. You should wait because I am tired today and I'll continue the job tomorrow, ok my friend? Thanks!

**Comment by kataras** [comment]
@pcariel Good morning from me, except the features missing, they say at README that this mux is faster than httprouter, but I did different types of benchmarks and it's actually very slower than the Iris' adaptors/httprouter and it doesn't offers any special features, so why we should adapt this? if you want regexp path validation per-route and you don't want to use the adaptors/gorillamux you can use the `app:= iris.New(); app.Adapt(httprouter.New()); app.Get("/users/:userid", app.Regex("userid","[0-9]+$"), handler)`  it will work faster than bone's regexp too. Please explain me why and if you need this router, it doesn't offers anything special as I can see

**Comment by pcariel** [comment]
hi, @kataras Good morning. Thanks for seeing my requirement, and check the performance of it, then I am with adaptors / gorillamux, there is no need for you to lose in time on this.
Thank you.
Sorry for my bad English.

**Comment by kataras** [comment]
Okey, I agree with you, thanks for your feature request and don't worry mine english are worst, yours is good!!

**Comment by kataras** [comment]
Thanks @pcariel for understanding.  I agree with you, thanks for your feature request and don't worry mine english are worst, yours *are* fine!!
