### ISSUE TITLE
reproduce benchmark result

### ISSUE THREAD

**Issue by tooooolong** [kataras/iris#645]
Hi, how can i reproduce the benchmark result in http://iris-go.com

**Comment by tooooolong** [comment]
```
import (
    "gopkg.in/kataras/iris.v6"
    "gopkg.in/kataras/iris.v6/adaptors/httprouter"
)

func main() {
    app := iris.New()
    // Adapt the "httprouter", faster,
    // but it has limits on named path parameters' validation,
    // you can adapt "gorillamux" if you need regexp path validation!
    app.Adapt(httprouter.New())

    app.HandleFunc("GET", "/", func(ctx *iris.Context) {
        ctx.Writef("hello world\n")
    })

    app.Listen(":8080")
}
```

**Comment by kataras** [comment]
Did you do benchmarks with hello-world app? lol. The benchmarks are not updated but Iris still the fastest net/http framework (if you read its code you will understand why, its open source). Search on google for benchmarks suites and open a new issue with your results comparing with other web frameworks. The source code for iris-go's benchmarks is private because I used that on a company-project (and I can't publish it without agreement). We ware waiting for the techempower's new results and will be published on the new iris-go.com site which I'm designing these days. If you have time please make a benchmark suite repository comparing all go web frameworks and I'll be glad to publish your results instead!
