### ISSUE TITLE
Future way of Iris and the next step to a community driven framework?

### ISSUE THREAD

**Issue by Dexus** [kataras/iris#666]
Hello @hiveminded & @kataras,
i'm asking me what is the next step to be a community driven framework?
I don't like it to use a framework that change all 1-2 month the apis and give a fuck of the community and developers that kill the git history and anything else like issues etc.

I like a community that can work together without a dictatorship. Not fakes and currupcy.

So please let us all know, what is the way you like to go? When Iris should be free and community based - it should be a own organisation. Not that we have in 1-2 month again a f*ing change and all historys/issues and more are gone again!

So please give us a statement in that we can have trust and that for a long term...

Think I can talk as the voice of the main community...

Thanks,
Dexus

**Comment by kataras** [comment]
Hello @Dexus ,

I think you're reading a lot of articles from people that you shouldn't, remember that the people who tried to deflated Iris via hitting me personally (a.k.a bullying) are finally rejected from the golang wide community and the official go conduct team.

However, I want to give an answer to your comments and questions.

Iris is stable, look the API for the last 6-9 months, the commits and the history all kept, the git rewrite was never my intention to "remove" someone from "contributor", as they did not provided anything useful to the code, you can see it.

The history was staged back to zero because we had reports that downloading of Iris took a lot of time, so I checked and the reports were correct, **we had an issue with large size (~100MB .git folder)**, the only solution was to re-write it.  Back then Iris was based on fasthttp(v4) but I did explain that before the article, as well. Now iris is on version 8, so the generic statement  of: "git history and give a f*ck to community" is not a wise thought and criticism. It's actually unfair from some of you to give me these type of comments, I was/am doing everything I can, beyond my strength as a human being with many sacrifices and commitment to the community to achieve the results we all enjoy today.

> So please give us a statement in that we can have trust and that for a long term...

You know that I've a new position at Dubai right now, but that doesn't mean that Iris is dead, I had an agreement with the company some days ago and they let me keep the **iris open-source repository open**, I have  explain them that this is for the best and they understood. 

**Yesterday I announced the new lead maintainer** who is looking for new developers to help him (not all people are asleep to work on Iris, like me :P ), so **Iris is on the best possible hands right now** it's was updated with a lot of fixes and improvements with the minimum number of changes.

Iris is here and it will be, I'm spending  money from my new job to Iris things, as the people donating to open-source projects are not the majority, I hope this will change soon. 

> Think I can talk as the voice of the main community...

Friendly advice, I think nobody can speak for others without election, as I remember you never helped to keep iris alive, It is an insult for people who give actually money and time to Iris to see from other person to say that he "is the voice of the main community"...

Last, 
Beside the young of your age(I'm young too) I want to thank you personally that  you're interesting on open-source projects and that you want to join to a larger community than yourself!

**Comment by godofdream** [comment]
@kataras You could at least explain: https://github.com/kataras/iris/issues/658

**Comment by kataras** [comment]
The project was always community-driven, didn't you see the feature requests that are being implemented? The good PRs that are being accepted, the discussions for many days for critical decisions and many other things are going on for the last 1 and a half years...

Please speak on  [chat](https://kataras.rocket.chat/channel/iris) , as I know @hiveminded is looking for a responsible team, you and @Dexus  have already made your own team on an iris-based fork, you can join to Iris now, it's totally your decision, I can't force you to join to the community if you're not confident yet, this is not my problem.

**Comment by kataras** [comment]
I think this should be closed, read the HISTORY.md file for more, I already explain everything, #658 too. I don't have to duplicate myself and consume my strength for these things.
