### ISSUE TITLE
Share session between packages in Iris v8

### ISSUE THREAD

**Issue by speedwheel** [kataras/iris#667]
I can't seem to understand how to share the session between packages for the new Iris version.

If I write this on every package, then the session is not recognized between packages:

```go
var (
	cookieNameForSessionID = "mycookiesessionnameid"
	sess                   = sessions.New(sessions.Config{Cookie: cookieNameForSessionID})
)
```

Any examples?

**Comment by kataras** [comment]
Like you do with your own variables, how do you share variables between your packages? Examples on how to use sessions located there: https://github.com/kataras/iris/tree/master/sessions/_examples .

There are many ways, the easier is to make a package-level exported variable and use that variable between your packages, i.e: 

```go
// file: $GOPATH/src/github.com/myname/myproject/store/sessions.go
package store

import (
	"github.com/kataras/iris/sessions"
)

var (
	cookieNameForSessionID = "mycookiesessionnameid"
	Sessions                   = sessions.New(sessions.Config{Cookie: cookieNameForSessionID})
)
```
```go
// file: $GOPATH/src/github.com/myname/myproject/main.go
package main

import (
    "github.com/kataras/iris"
    "github.com/kataras/riis/context"

    "github.com/myname/myproject/store"
)
func main() {
	app := iris.New()
        app.Get("/set", func(ctx context.Context){
           sess:= store.Sessions.Start(ctx)
           sess.Set("key", "value")
        })

        app.Get("/get", func(ctx context.Context){
           sess:= store.Sessions.Start(ctx)
           value:= sess.GetString("key")
           ctx.WriteString(value)
        })

        app.Run(iris.Addr(":8080"))
}

```

You can also create and use a custom `Context` which will hold the sessions at the `ctx.Session()` as we did on iris v7, you're lucky because we have an example of this exactly usage located there: https://github.com/kataras/iris/tree/master/_examples/routing/custom-context/new-implementation

**Comment by speedwheel** [comment]
@kataras Thanks for the explanation, I really like the second implementation, that's exactly what I was looking for.

P.S. Glad to see the Original Iris back.

**Comment by kataras** [comment]
Thank you @speedwheel , I have some free time as I finished some tasks for this week already :)  but  do not underestimate the new lead maintainer too, he is really a good developer
