### ISSUE TITLE
Return ERRO[0000]

### ISSUE THREAD

**Issue by charlesduarte019** [kataras/iris#668]
ERR:
Now listening on: http://127.0.0.1:3001
Application started. Press CTRL+C to shut down.
^CERRO[0000] http: Server closed

How are doing:
func (app *Application) Run(serve Runner, withOrWithout ...Configurator) error {
	// first Build because it doesn't need anything from configuration,
	//  this give the user the chance to modify the router inside a configurator as well.
	if err := app.Build(); err != nil {
		return errors.PrintAndReturnErrors(err, app.logger.Errorf)
	}

	app.Configure(withOrWithout...)

	// this will block until an error(unless supervisor's DeferFlow called from a Task).
	err := serve(app)
	if err != nil {
		app.Logger().Errorln(err)
	}
	return err
}

Suggestion:
func (app *Application) Run(serve Runner, withOrWithout ...Configurator) error {
	// first Build because it doesn't need anything from configuration,
	//  this give the user the chance to modify the router inside a configurator as well.
	if err := app.Build(); err != nil {
		return errors.PrintAndReturnErrors(err, app.logger.Errorf)
	}

	app.Configure(withOrWithout...)

	// this will block until an error(unless supervisor's DeferFlow called from a Task).
	err := serve(app)
	if err != nil {
		return err
	}
	return nil
}

In main (Example):
func main() {

	app := iris.New()

	err := app.Run(iris.Addr(":3000"))
	if err != nil {
		if err != iris.ErrServerClosed {
			app.Logger().Warnf("Shutdown with error: %v\n", err.Error())
		} else {
			fmt.Print("\n")
		}
	}

}

**Comment by hiveminded** [comment]
@charlesduarte019 Look this commented code snippet there: https://github.com/kataras/iris/blob/master/core/host/supervisor.go#L107 
```go
if err == http.ErrServerClosed {
 // 	return
 // }
```

Some developers may want to catch this error this is why we let it return, ignoring it is easy, you just have to check if the err is the `iris.ErrServerClosed`,  but we can add an option for ignore/not ignore the ErrServerClosed, if you think that's better

**Comment by charlesduarte019** [comment]
Can it be like this too:
[DIR] .../github.com/kataras/iris/iris.go
[Linha] 531
```
func (app *Application) Run(serve Runner, withOrWithout ...Configurator) error {
   // first Build because it doesn't need anything from configuration,
   // this give the user the chance to modify the router inside a configurator as well.
   if err := app.Build(); err != nil {
      return errors.PrintAndReturnErrors(err, app.logger.Errorf)
   }

   app.Configure(withOrWithout...)

   // this will block until an error(unless supervisor's DeferFlow called from a Task).
   err := serve(app)
   if err != nil {
      if err == http.ErrServerClosed {
         return nil
      }
      app.Logger().Errorln(err)
   }
   return err
}
```

**Comment by hiveminded** [comment]
@charlesduarte019 we can't ignore errors like these because many applications depends on this error, as you can imagine, but we could (and we just did) pass ignored errors by configuration (functional, by struct, via `yaml` or `toml` files).

Navigate through changelog for details: https://github.com/kataras/iris/blob/master/HISTORY.md#th-13-july-2017--v801

Example:  github.com/kataras/iris/tree/master/_examples/http-listening/listen-addr/omit-server-errors

**Comment by hiveminded** [comment]
@charlesduarte019 we can't ignore errors like these because many applications depends on this error, as you can imagine, but we could (and we just did) pass ignored errors by configuration (functional, by struct, via `yaml` or `toml` files).

Navigate through changelog for details: https://github.com/kataras/iris/blob/master/HISTORY.md#th-13-july-2017--v801

Example:  https://github.com/kataras/iris/tree/master/_examples/http-listening/listen-addr/omit-server-errors
