### ISSUE TITLE
Support Casbin as the authorization (AuthZ) middleware

### ISSUE THREAD

**Issue by hsluoyz** [kataras/iris#670]
Hi, [Casbin](https://github.com/casbin/casbin) is an authorization library that supports models like ACL, RBAC, ABAC.

Related to RBAC, Casbin has several advantages:
1. roles can be cascaded, aka roles can have roles.
2. support resource roles, so users have their roles and resource have their roles too. role = group here.
3. the permission assignments (or policy in Casbin's language) can be persisted in files or database (MySQL and Cassandra).

And you can even customize your own access control model, for example, mix RBAC and ABAC together by using roles and attributes at the same time. It's very flexible.

Casbin can provide more flexibility and security for the authorization. What do you think about adding it as a middleware for iris? Let me know if there's any question:) Thanks.

**Comment by hiveminded** [comment]
@hsluoyz You're the author of this library, I have to admit that you did a very good job!

These types of middleware can be added to the [iris-contrib/middleware](https://github.com/iris-contrib/middleware), it's easy a very easy process (look the rest of the handlers there).  I think it's better to let you push a PR for that, otherwise I'll do it in the afternoon.

**Comment by hiveminded** [comment]
Actually @hsluoyz , this should be a wrapper like we did with rs/cors`  because it manages the routes before the router itself in order to work as expected, always.

I did manage to do it without any middleware:

**casbinmodel.conf**
```sh
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && keyMatch(r.obj, p.obj) && (r.act == p.act || p.act == "*")
```

**casbinpolicy.csv**
```sh
p, alice, /dataset1/*, GET
p, alice, /dataset1/resource1, POST
p, bob, /dataset2/resource1, *
p, bob, /dataset2/resource2, GET
p, bob, /dataset2/folder1/*, POST
p, dataset1_admin, /dataset1/*, *
g, cathrin, dataset1_admin
```

**main.go**
```go
package main

import (
	"net/http"

	"github.com/kataras/iris"
	"github.com/kataras/iris/context"

	"github.com/casbin/casbin"
)

// Enforcer maps the model and the policy for the casbin service, we use this variable on the main_test too.
var Enforcer = casbin.NewEnforcer("casbinmodel.conf", "casbinpolicy.csv")

// Check checks the username, request's method and path and
// returns true if permission grandted otherwise false.
func Check(r *http.Request) bool {
	username := Username(r)
	method := r.Method
	path := r.URL.Path
	return Enforcer.Enforce(username, path, method)
}

// Username gets the user name from the request.
// Currently, only HTTP basic authentication is supported
func Username(r *http.Request) string {
	username, _, _ := r.BasicAuth()
	return username
}

func newApp() *iris.Application {
	app := iris.New()

	app.WrapRouter(func(w http.ResponseWriter, r *http.Request, router http.HandlerFunc) {
		if !Check(r) {
			w.WriteHeader(403)
			w.Write([]byte("403 Forbidden"))
			return
		}
		router(w, r)
	})

	app.Get("/", hi)

	app.Any("/dataset1/{p:path}", hi) // p, dataset1_admin, /dataset1/*, * && p, alice, /dataset1/*, GET

	app.Post("/dataset1/resource1", hi)

	app.Get("/dataset2/resource2", hi)
	app.Post("/dataset2/folder1/{p:path}", hi)

	app.Any("/dataset2/resource1", hi)

	return app
}

func main() {
	app := newApp()
	app.Run(iris.Addr(":8080"))
}

func hi(ctx context.Context) {
	ctx.Writef("Hello %s", Username(ctx.Request()))
}

```

**Its test, main_test.go**:
```go
package main

import (
	"testing"

	"github.com/iris-contrib/httpexpect"
	"github.com/kataras/iris/httptest"
)

func TestCasbin(t *testing.T) {
	app := newApp()
	e := httptest.New(t, app, httptest.Debug(true))

	type ttcasbin struct {
		username string
		path     string
		method   string
		status   int
	}

	tt := []ttcasbin{
		{"alice", "/dataset1/resource1", "GET", 200},
		{"alice", "/dataset1/resource1", "POST", 200},
		{"alice", "/dataset1/resource2", "GET", 200},
		{"alice", "/dataset1/resource2", "POST", 403},

		{"bob", "/dataset2/resource1", "GET", 200},
		{"bob", "/dataset2/resource1", "POST", 200},
		{"bob", "/dataset2/resource1", "DELETE", 200},
		{"bob", "/dataset2/resource2", "GET", 200},
		{"bob", "/dataset2/resource2", "POST", 403},
		{"bob", "/dataset2/resource2", "DELETE", 403},

		{"bob", "/dataset2/folder1/item1", "GET", 403},
		{"bob", "/dataset2/folder1/item1", "POST", 200},
		{"bob", "/dataset2/folder1/item1", "DELETE", 403},
		{"bob", "/dataset2/folder1/item2", "GET", 403},
		{"bob", "/dataset2/folder1/item2", "POST", 200},
		{"bob", "/dataset2/folder1/item2", "DELETE", 403},
	}

	for _, tt := range tt {
		check(e, tt.method, tt.path, tt.username, tt.status)
	}

	println("ADMIN ROLES")
	ttAdmin := []ttcasbin{
		{"cathrin", "/dataset1/item", "GET", 200},
		{"cathrin", "/dataset1/item", "POST", 200},
		{"cathrin", "/dataset1/item", "DELETE", 200},
		{"cathrin", "/dataset2/item", "GET", 403},
		{"cathrin", "/dataset2/item", "POST", 403},
		{"cathrin", "/dataset2/item", "DELETE", 403},
	}

	for _, tt := range ttAdmin {
		check(e, tt.method, tt.path, tt.username, tt.status)
	}

	println("ADMIN ROLE FOR cathrin DELETED")
	Enforcer.DeleteRolesForUser("cathrin")

	ttAdminDeleted := []ttcasbin{
		{"cathrin", "/dataset1/item", "GET", 403},
		{"cathrin", "/dataset1/item", "POST", 403},
		{"cathrin", "/dataset1/item", "DELETE", 403},
		{"cathrin", "/dataset2/item", "GET", 403},
		{"cathrin", "/dataset2/item", "POST", 403},
		{"cathrin", "/dataset2/item", "DELETE", 403},
	}

	for _, tt := range ttAdminDeleted {
		check(e, tt.method, tt.path, tt.username, tt.status)
	}

}

func check(e *httpexpect.Expect, method, path, username string, status int) {
	e.Request(method, path).WithBasicAuth(username, "password").Expect().Status(status)
}
```

So we have the start code to work on it, I can do it with two versions:

The first one will work with normal iris handlers as a middleware attached to a specific route which will check the same things but this middleware will respond to `404 not found` if a route is not registered via iris, instead of `403 forbidden` which casbin do whatever the route is. 

And the other will be the wrapper which will be used to the entire application, for all routes and it will provide all casbin's features.

**Comment by hiveminded** [comment]
@hsluoyz It's done, both wrapper and middleware usage examples with its tests and models can be found at https://github.com/iris-contrib/middleware/tree/master/casbin#table-of-contents

**Comment by hsluoyz** [comment]
Hi @hiveminded ,

Many thanks for the quick response! I'm just starting to consider how to integrate Casbin but I then found you have finished it! 

It is very helpful that you designed two modes to use Casbin, a wrapper way and a middleware way. What I don't quite understand why middleware returns 404 and why wrapper provides all Casbin's features? Is there any feature that is not supported by the middleware way? Thanks.

**Comment by hiveminded** [comment]
@hsluoyz  middlewares are executing after the router, they are being registered to route's handlers, on the other side a wrapper before the router, this way we can give control to something to control the way routing works.   ( wrapper func is an `iris` functionality but it's on its `net/http` native form in order to support third-party handlers that should be registered before the router, i.e security handlers that should be executed before even the router decide what path and method owns to what route)
