### ISSUE TITLE
People, slow down with so many changes to API

### ISSUE THREAD

**Issue by cristian-sima** [kataras/iris#671]

**Comment by kataras** [comment]
It's not accident that Iris is the first choice for many companies and new developers, we're keeping up-to-date with the latest tech trends  we will not use deprecated code for the sake of "stability", see the quotes.

But to be honest there is no API changes expect one single function, since version 7. Iris is fully vendored so you don't have to upgrade if you feel that you don't need it,  just copy-paste the folder on any machine and it will work for ever no matter what ( do you know other framework gives that real stability?).
