### ISSUE TITLE
Not being able to compile Hello World example

### ISSUE THREAD

**Issue by christiansaiki** [kataras/iris#672]
I was receiving this errors after running `go run main.go` in the [Hello World Example](https://github.com/kataras/iris/blob/master/_examples/hello-world/main.go)
command-line-arguments
./main.go:22: undefined: iris.Context
./main.go:29: undefined: iris.Map

I'll make a PR soon to fix this example.

**Comment by hiveminded** [comment]
@christiansaiki That's already fixed yesterday, you don't need to make a PR just upgrade with `$ go get -u github.com/kataras/iris` , it was an issue because we had go1.9 and go1.8 example versions on the same folder :)

**Comment by hiveminded** [comment]
@christiansaiki That's already fixed with this commit: https://github.com/kataras/iris/commit/e09ff72e072211891daa483740c2784dcfcd797e 9 hours ago, you don't need to make a PR just upgrade with $ go get -u github.com/kataras/iris , it was an issue because we had go1.9 and go1.8 example versions on the same folder :)

**Comment by hiveminded** [comment]
Oh no you have right, we have `iris.Context` in the go1.8 version and that's a mistake, your PR is approved!
