### ISSUE TITLE
Suggestion: Stable API

### ISSUE THREAD

**Issue by danielfbm** [kataras/iris#700]
Documentation for the _iris_ project can be found at
<https://github.com/kataras/iris#-learn>.

hi guys, first of all I really enjoy using Iris, and have been using it in production for almost a year now and so far haven't really had any issues with iris, but....

I really appreciate the effort you guys put on improving the engine day by day but the thing that hurts the most is how the API changes completely from version to version.

The situation is: I have been using Iris in different micro services and every time we start a new service we try to keep up with the latest Iris version, and now we currently have v4, v5 and v6 in production. Although we keep effort on updating things, most of the times a change in version means a full refactoring of the services and that just sucks. Maybe I just want to make use of a new functionality available in the new version but now I have to spend hours or even days refactoring the whole thing instead of focusing in the task at hand. We want to update all the services to the latest version but that is just not reasonable anymore... 

My suggestion is: Add new APIs once the signature changes but also keep the old APIs to make it backwards compatible, that would make the transition so easy and we could change one part at a time to the new API.

Just a suggestion. Keep up with the good work!

**Comment by kataras** [comment]
Hello @danielfbm, first of all thanks for using Iris despite the API changes.

I think I have already talk about it, the versions are quite different between them for a reason, it's like an improvement Iris everytime but this doesn't mean that developers must upgrade immediately, most of the bugfixes are already fixed from v3 so you gain mostly new features and easier API each new version, easier API cannot be done if we keep old API for "stability" reasons. I know that stability is a major player but we couldn't sacrifice the overall progress because of it.

This is why I put long changelog entry on [HISTORY](HISTORY.md) file, devs can look for them when they want to upgrade and do the transaction. We do have services that are running with Iris too, I'm responsible to upgrade them all so I understand the "pain" sometimes, but it worth it, every single time.

However these days, Iris is on version 8 , this is a big history, most of the things I had in mind are completed and they're not going to be change. Note that the whole routing API is almost the same from v4!

We will try not to change the default behavior and the current API, it's safe to say that the 99% of the code will not change any time soon, **It's true that we already done a great job with the API, no need for any other improvements in my opinion, I agree with you**. **Stability is our main responsibility now, we did all the things we wanted so far, no need for front changes.**

**Comment by danielfbm** [comment]
ok, thank you. Do you mind if we keep this open until you release v8 in gopkg.in?

It will be easier for people to follow the progress...

Thank you very much for the endless ours you guys put in this work, it is much appreciated

**Comment by hiveminded** [comment]
There's no need to keep an opinion as an open issue, it was a mistake from the first place to post it here. This is not a feature in progress neither a bug report or feature request relative to the framework. We have the [chat room](https://kataras.rocket.chat/channel/iris) for general discussion, please continue there, we don't have to "spamm" project watchers without reason.
