### ISSUE TITLE
Can Iris be used in production after Dubai purchase?

### ISSUE THREAD

**Issue by krypton97** [kataras/iris#711]
Documentation for the _iris_ project can be found at
<https://github.com/kataras/iris#-learn>.

I heard that Iris was bought and I was wondering if it could still be used in production without any copyright issue. Also I'm looking to know if it's good for using in companies as well. Thank you!

**Comment by kataras** [comment]
Hello @krypton97 

It's true that we are working on a different private closed-source version of Iris for company's needs only but after some days of productively negotiations I did manage to convince the team that we should keep the open-source version of Iris (this repository) online and active for our benefit too. 

This proposal was accepted, they all understand that this decision is better for both parts, we get bug reports and features that we may not catch by ourselves and you, as users, get the best support you could find on a golang open-source project, as always. 

>  it could still be used in production without any copyright issue

The License is not changed as you can see, you can use Iris on production, as before.

>  Also I'm looking to know if it's good for using in companies as well

Imagine that a company hired me  because of Iris(the most part, I think:P), other companies are looking for iris-experienced developers too(look readme), so I can tell for sure that it's totally safe and a `must` for large-scale websites that running on a production environment.

Thank you for your question, if you need anything else we'll be here:)

**Comment by krypton97** [comment]
Wow, nice to hear this! This issue may be closed since I've no more question about it ;)

**Comment by MapleGu** [comment]
nice~
