### ISSUE TITLE
Active development mode.

### ISSUE THREAD

**Issue by krokite** [kataras/iris#722]
Just read - `Star or watch this repository, it is still in active development mode.`

Does this mean, is this project not suitable for production mode , yet - Is there any heavy changes happening ?

Thanks

**Comment by hiveminded** [comment]
Actually we've added that note because many developers and companies asked us if Iris is still under development after the purchase, look there for proof of concept: https://github.com/kataras/iris/issues/711

To answer to your question a bit deeper, as @kataras told me, he's planning to push a surprise feature based on a solution that he already provides to some company-scale teams, he didn't give me any crucial details, but to prepare for even more extensibility and maintainability over large web applications codebases. 

Iris is suitable for production use and it has not any breaking changes since the last version neither will, many servers are running iris over the globe (unfortunately, I am not the person authorized to publish the number but there are a lot :) ).

**Comment by krokite** [comment]
@hiveminded - Thanks for the great answer. 

It's a relief. The team is doing an Amazing job. (y) Kataras and You have done amazing job in creating and maintaining it.

More power to you guys.
