### ISSUE TITLE
Orm support?

### ISSUE THREAD

**Issue by krypton97** [kataras/iris#724]
Documentation for the _iris_ project can be found at
<https://github.com/kataras/iris#-learn>.

Since Iris started to include mvc model, is it going to support ORM for dealing with databases? In Node.JS there's something called Mongoose who's very productive;)

**Comment by kataras** [comment]
Hello @krypton97 ,

There are plenty ORM libraries out there,  we will not try to reinvent the wheel with these things. But why you ask, do you thing that everything we build is better than the rest open-source developers? 
This is not the case, I'm sure that you'll find what you need with a little search. 

However my opinion is to use raw sql, we are using raw sql everywhere for quite long time because the performance cost for ORM is not worth the "ease of use".

> Just an info: Iris does not "started to include the mvc model", we invent the mvc pattern inside Go world, there is a small difference.

**Comment by krypton97** [comment]
Ok, thanks!

**Comment by kataras** [comment]
If someone searching for a postgres library instead, I've just publish my new project: https://github.com/kataras/pg.
