### ISSUE TITLE
Mobiles

### ISSUE THREAD

**Issue by joeblew99** [kataras/iris#725]
Is running iris on mobiles and desktops considered plausible ?

The MCV functionality is server side and so the client will refresh each page. But if it's fast enough it can be enough for many apps.

**Comment by kataras** [comment]
> Is running iris on mobiles and desktops considered plausible ?

I don't know it depends on your needs, but I'm running an iris web server in my mobile phone for personal file transferring and message contacts, works perfectly. There is an article I wrote about `running Iris over android` which got a lot of reactions and good feedback, you can take a look here: https://twitter.com/ThePracticalDev/status/892022594031017988

> The MCV functionality is server side and so the client will refresh each page. But if it's fast enough it can be enough for many apps.

It's fast enough, it is not like other MVC implementations you used to watch, this is Iris so they should run fast otherwise I will never push that feature here. Didn't you see the benchmarks yet?

Yesterday I wrote an article about this on hackernoon.com, follow the link if you're interesting: 
https://hackernoon.com/go-vs-net-core-in-terms-of-http-performance-7535a61b67b8

Iris MVC vs Iris Handlers benchmarks can be found at the [_benchmarks](_benchmarks) folder, read its README.md, at the end it shows the difference between the three of them ( .NET Core, Iris MVC, Iris Handlers)

Thank you!

**Comment by joeblew99** [comment]
thanks. benchmark looks good. Ha i used to do c# for 10 years. never going back.

As far as mobile, what about writing a webview into iris or as as some sort of contrib ? There are bits of golang based webviews floating around for android and web view.

**Comment by kataras** [comment]
If you or somebody else can do something better/or different termux, I would be into that but I don't have any personal experience with that field, I am not used to code something on production level when I am not allowed to because I have not the experience to do that.

@joeblew99  The only thing I can do for that is to create you a repository on the [iris-contrib](https://github.com/iris-contrib) organization and give ownership of that repo  to start push your code and ideas there.

**Comment by joeblew99** [comment]
@kataras  i am working on this in my own repo for now.

will holler if i have questions...
