### ISSUE TITLE
build error after dep init

### ISSUE THREAD

**Issue by lkmadushan** [kataras/iris#731]
I used golang `dep` package to vendor 3rd party iris packages and tried to build project after running `dep init`. I got following error.

```
# github.com/lkmadushan/test-app/vendor/github.com/kataras/iris/view
vendor/github.com/kataras/iris/view/django.go:170:19: undefined: pongo2.NewLocalFileSystemLoader
vendor/github.com/kataras/iris/view/django.go:175:22: too many arguments in call to pongo2.NewSet
vendor/github.com/kataras/iris/view/django.go:234:22: too many arguments in call to pongo2.NewSet
        have (string, *tDjangoAssetLoader)
        want (string)
```

How can I fix this issues?

**Comment by kataras** [comment]
It seems that pongo package is missing, I'm from the office right now so I can't test it right now, solve it by 'go get u github.com/kataras/iris/...' tell me how is going

**Comment by lkmadushan** [comment]
@kataras no luck. still same issue.

**Comment by kataras** [comment]
It's strange because Iris has the pongo2 on its vendors, look here: https://github.com/kataras/iris/tree/master/vendor/github.com/flosch/pongo2 .

Something is strange with your workspace, can you manually install `go get -u github.com/kataras/iris`? If that works (which it's) then you should post this issue on go dep, not inside iris

**Comment by kataras** [comment]
@lkmadushan I'm at home and I was able to reproduce that, you have right, it seems that `go dep` doesn't care about the `vendor` folder (is this a go dep bug or what? I really don't know, we have to ask them) and it downloads the pongo2 version 3(released at Oct 28, 2014)  which has a different API, we use the `dev` version which is newer and has more features...

**Comment by kataras** [comment]
@lkmadushan I'm at home and I was able to reproduce that, you have right, it seems that `go dep` doesn't care about the package's `vendor` folder (is this a go dep bug or what? I really don't know, we have to ask them) and it downloads the pongo2 version 3(released at Oct 28, 2014)  which has a different API, we use the `dev` version which is newer and has more features...

**Comment by kataras** [comment]
@lkmadushan Here 's the answer I got from one of the go dep maintainers: https://github.com/golang/dep/issues/1075#issuecomment-325504907 , this is by-design of the go dep tool and of course has nothing to do with Iris. 

There are three solutions you have:

1. change the tool you're using, there are some others like `glide`
2. Wait for pongo2 to release a newer version 
3. `copy-paste` the whole iris folder to your vendors, you can download it from [here](https://github.com/kataras/iris/archive/master.zip), I would choose the third one if I was you :)

**Comment by kataras** [comment]
@lkmadushan Here 's the answer I got from one of the go dep maintainers: https://github.com/golang/dep/issues/1075#issuecomment-325504907 on your behalf , this is by-design of the go dep tool and of course has nothing to do with Iris. 

There are three solutions you have:

1. change the tool you're using, there are some others like `glide`
2. Wait for pongo2 to release a newer version 
3. `copy-paste` the whole iris folder to your vendors, you can download it from [here](https://github.com/kataras/iris/archive/master.zip), I would choose the third one if I was you :)

**Comment by lkmadushan** [comment]
@kataras Thank you. Managed to fix the issue using your 3rd option.

**Comment by kataras** [comment]
There is one more "solution", to move all vendors to iris-contrib/x_package repositories but this will change the API because end-developers will have to change their import path from x_author/x_package to iris-contrib/x_package therefore we can't accept that solution atm. You're welcome @lkmadushan happy to helped!

**Comment by kataras** [comment]
@lkmadushan You're welcome, I tried everything to solve it I either created `Gopkg.toml` and `Gopkg.lock` files because I locally thought that `dep init` will respect those files when fetching a dependency but no... I was wrong **it doesn't** , they will make me to make my own tool at the end of the day!

**Comment by kataras** [comment]
@lkmadushan **FIXED** Please remove your `/vendor` folder and execute `dep init` again, the `dep` tool doesn't care about dependency's  vendor folder  but it cares about `Gopkg.toml` and `Gopkg.loc` files. 

The new Iris  `8.4.0` release tag has `Gopkg.toml` and `Gopkg.lock` files which helps the `dep` tool to fetch the correct iris' dependencies (your app's dependency's dependencies)
