### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by ishworgurung** [kataras/iris#733]
Nice work mate. 

Would you have any documentation on your benchmarking strategy along with network stack customisation for Linux?

In particular, I am looking for any customisations, benchmark scripts (or howtos) so that I can repro the numbers I see in `iris` performance benchmark mentioned in its readme.

Thanks!

**Comment by kataras** [comment]
Hello @ishworgurung I was waiting for somebody ask me that, could you please join to the [chat](https://kataras.rocket.chat/channel/iris)? I had to sold my one of two laptops to survive when I started Iris so I have no a test machine to test unix-only features for networks listeners like reuse port.

**Comment by ishworgurung** [comment]
Hey @kataras. Definitely feel the pain you're going through.

Would you have any benchmarking guideline you used in your Linux environment so I can repro? I am trying to help here cause I want to be able to repro the same level of numbers I see in your readme. I did some preliminary bench and found `iris` to be *very* bad - almost to an extent where most tcp connections are reset and clients effectively give up. The successful requests ratio was less than 30-35% on multiple runs.

**Comment by kataras** [comment]
But I didn't run them from Linux, the benchmarks ran with the specific hardware and the operating system written at the _benchmarks/README.md. Yes it seems 'very bad' because I assume that you 're new to Go, unix has different methods of network listening and you should use that instead, net.core does that automatically. I told you to join to the chat in order to help you build your machine ready for those machines, we can't do it here because we'll spam other developers who don't care about linux network specification

**Comment by kataras** [comment]
But I didn't run them from Linux, the benchmarks ran with the specific hardware and the operating system written at the _benchmarks/README.md. Yes it seems 'very bad' because I assume that you 're new to Go, unix has different methods of network listening and you should use that instead, net.core does that automatically. I told you to join to the chat in order to help you build your machine ready for those tests, we can't do it here because we'll spam other developers who don't care about linux network specification
