### ISSUE TITLE
Should use Handler interface instead of function.

### ISSUE THREAD

**Issue by iamybj** [kataras/iris#735]
Look at this code:
`
package context

// A Handler responds to an HTTP request.
// It writes reply headers and data to the Context.ResponseWriter() and then return.
// Returning signals that the request is finished;
// it is not valid to use the Context after or concurrently with the completion of the Handler call.
//
// Depending on the HTTP client software, HTTP protocol version,
// and any intermediaries between the client and the iris server,
// it may not be possible to read from the Context.Request().Body after writing to the context.ResponseWriter().
// Cautious handlers should read the Context.Request().Body first, and then reply.
//
// Except for reading the body, handlers should not modify the provided Context.
//
// If Handler panics, the server (the caller of Handler) assumes that the effect of the panic was isolated to the active request.
// It recovers the panic, logs a stack trace to the server error log, and hangs up the connection.
type Handler func(Context)

// Handlers is just a type of slice of []Handler.
//
// See Handler for more.
type Handlers []Handler
`

iris use a lot of this Handler, but I think it should be better if declared it as interface . just like

`
type Handler interface {
    Handle(Context)
}

type HandleFunc func(Context)

func (f *HandleFunc) Handle(Context c) {
    f(c)
}
`

**Comment by iamybj** [comment]
change func to interface

**Comment by kataras** [comment]
@iamybj Hello,

We had that kind of implementation before v5 but you don't win something it just made things more complicated (i.e we had UseFunc and Use... what's the reason to have 2 functions doing the same thing but accept different type of request handlers, it's silly, do not be so mad about net/http package, it has its wrong too). We choose to move forward to simple functions, but you will not miss `new(something)` to handle the requests **because we have full MVC support**, look the [mvc examples](https://github.com/kataras/iris/tree/master/_examples)

**Comment by iamybj** [comment]
haha, you have MVC controllers, but OnErrorCode still use function. This is not the same.
User interface instead of function, bcz function usually bounded to structs.
