### ISSUE TITLE
The iris listener protocol is not a http2.0 . Is there a mistake in my configuration?

### ISSUE THREAD

**Issue by JermineHu** [kataras/iris#736]
**The iris listener protocol is not a http2.0 .  Screenshot as follows**

![tim 20170905170812](https://user-images.githubusercontent.com/18027793/30054208-ec1fbf6a-925d-11e7-8559-e2b64fff627c.png)

**Comment by kataras** [comment]
Yes, HTTP/2 is enabled when HTTPS is enabled, it seems that you don't correctly setup your HTTPS connection. Google chrome will not recognise your website as **secure** because you use localhosts and you don't have a key from a verified source. **take a look at https://iris-go.com, it's build with Iris**  it's transferring via HTTP/2, for a simple test you can navigate there too: https://tools.keycdn.com/http2-test , write https://iris-go.com and press "test". 

As docs says, the iris' `TLS` functions (`iris.TLS` and `iris.AutoTLS`) should be used with a real domains at production only and keys should be verified.

**Comment by Kisesy** [comment]
@JermineHu 
https://github.com/kataras/iris/blob/f4f945b18eacf205bcd11a4dd29e985d78887559/core/host/supervisor.go#L243-L263
line 253, insert the code: `cfg.NextProtos = []string{"h2", "http/1.1"}`

```go
func (su *Supervisor) ListenAndServeTLS(certFile string, keyFile string) error {
	su.manuallyTLS = true

	if certFile != "" && keyFile != "" {
		cfg := new(tls.Config)
		var err error
		cfg.Certificates = make([]tls.Certificate, 1)
		if cfg.Certificates[0], err = tls.LoadX509KeyPair(certFile, keyFile); err != nil {
			return err
		}
		cfg.NextProtos = []string{"h2", "http/1.1"}
		su.Server.TLSConfig = cfg
		return su.ListenAndServe()
	}

	if su.Server.TLSConfig == nil {
		return errors.New("certFile or keyFile missing")
	}

	return su.supervise(func() error { return su.Server.ListenAndServeTLS("", "") })
}

```


![image](https://user-images.githubusercontent.com/5843694/30057630-050ba21c-926a-11e7-9a7d-db21868ed2c7.png)

**Comment by kataras** [comment]
What version of Go are you using? Because the latest one `go 1.9` will handle this by `ListenAndServeTLS("", "")` which is being called on **supervisor.go** line 262: 
https://github.com/kataras/iris/blob/master/core/host/supervisor.go#L262 and https://github.com/golang/go/blob/master/src/net/http/server.go#L2752 but we can re-add this line you recommend ( we had the same thing,  the manually h2 header at previous versions before go 1.9 released)

**Comment by Kisesy** [comment]
I use go1.9，i think this is a bug...
maybe just delete this line？
https://github.com/kataras/iris/blob/1054844e040fb1c19cc95dcf8004fbce3d1e2656/core/host/supervisor.go#L257

**Comment by Kisesy** [comment]
I use go1.9, I think this is a bug...
maybe just delete this line？
https://github.com/kataras/iris/blob/1054844e040fb1c19cc95dcf8004fbce3d1e2656/core/host/supervisor.go#L257

**Comment by hiveminded** [comment]
@Kisesy Please explain us the problem on your machine because you're the first one reporting something like this Iris was the first web framework with full HTTP/2 support. We're running Iris HTTP/2 and secure https with manually `TLS` and `AutoTLS` on our servers in the company, we never experienced a problem with these before.

**Comment by hiveminded** [comment]
Take a quick look at the simple localhost manual TLS example of this repository, https://github.com/kataras/iris/tree/master/_examples/http-listening/listen-tls.

Run it with `go run main.go`

![h2](https://user-images.githubusercontent.com/29665371/30161789-ae447cca-93da-11e7-8c14-74e30e3316a4.png)

Ran with the latest go version, 1.9

![h2goversion](https://user-images.githubusercontent.com/29665371/30161757-944f98b8-93da-11e7-8918-769e34216482.png)

**Comment by Kisesy** [comment]
@hiveminded 
you can test this version https://github.com/kataras/iris/tree/f4f945b18eacf205bcd11a4dd29e985d78887559

![image](https://user-images.githubusercontent.com/5843694/30187783-ad2dffd6-945d-11e7-8d50-116882cb88f4.png)

if run ListenAndServe
![image](https://user-images.githubusercontent.com/5843694/30187810-d603b356-945d-11e7-904a-8ec34a075c6b.png)
![image](https://user-images.githubusercontent.com/5843694/30187965-b70ec250-945e-11e7-81f1-c5d6db472206.png)

if remove `return su.ListenAndServe()`
![image](https://user-images.githubusercontent.com/5843694/30187873-3afeff40-945e-11e7-91d1-56c051f4ae20.png)

su.ListenAndServe() != su.Server.ListenAndServeTLS()

**Comment by hiveminded** [comment]
Upgrade your Go host, the latest one is the `go 1.9` **not** the RC2 and your Iris, the latest one is 8.4.1, and tls works even if we kept  the `su.ListenAndServe` although I removed it yesterday, why don't upgrade?
