### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by krypton97** [kataras/iris#739]
Seems that with the new updates echo outperform iris as seen below, any ideas why?

https://github.com/tbrand/which_is_the_fastest

**Comment by esemplastic** [comment]
That benchmark shows gorilla mux which is using `regexp` to be faster than echo and iris, it's an invalid benchmark, this issue should be closed.

**Comment by hiveminded** [comment]
Yes it seems it's running some web frameworks or routers(like gorilla mux) from a static ipv4 address and others (like iris, fasthttprouter and echo) from an ipv6 dynamic address and this is not a fair test because network acts differently on that case. @krypton97 plaese post this issue to the tbrand/which_is_the_fastest repository instead of here, iris is still fastest, don't doubt on this :)

**Comment by esemplastic** [comment]
@hiveminded I posted an issue for that, we will get an answer for those invalid results very soon, hopefully!

**Comment by hiveminded** [comment]
@esemplastic Yes, I was doing the same thing sorry for the delay. 

You had right, those benchmarks are invalid, any go developer knows that gorilla mux is slower because of regex and some of them are fine with it, I've alos see on its last commit: https://github.com/tbrand/which_is_the_fastest/commit/70ac42b1312602bce695683ee5e886ae08951e59  that iris was the fastest 1 day before but now it's not, even if the framework is not changed at all xD

https://github.com/tbrand/which_is_the_fastest/issues/73
https://github.com/tbrand/which_is_the_fastest/issues/71

**Comment by esemplastic** [comment]
It seems that @krypton97 added the code for iris on that repository, he used a stored variable for path parameters while the rest of the routers and web frameworks' benchmark source code is not uses this approach, the :3000 and localhost:3000 is also touched by him, he made those changes and after post this issue here, I can only assume that this is a bad plan...  https://github.com/krypton97/which_is_the_fastest/commit/905d7f7b4258f3588fbd20d688e6a49b415a29c3

**Comment by krypton97** [comment]
@esemplastic what do you mean? If you can optimize that, go ahead ;)

**Comment by esemplastic** [comment]
I already push a PR for that don't worry :) , look @hiveminded 's comments too, it seems like 1 day before iris was faster, what's changed?

**Comment by hiveminded** [comment]
@esemplastic and @krypton97 I did remove both of your comments. I'm locking this issue, we don't want any drama or spam here, devs who care can see the above posted issues. 

For the record, @krypton97 I just saw a PR from @esemplastic  which can fix your benchmark code on that repository modified  by yourself and open a fake issue here, this was not a good move of you, you could inform us before however I decide to give you a second chance, sorry but you have no write access to this repository any more for (1 month penalty for your behavior, not permanently)

**Comment by hiveminded** [comment]
@esemplastic and @krypton97 I did remove both of your comments. I'm locking this issue, we don't want any drama or spam here, devs who care can see the above posted issues. 

For the record, @krypton97 I just saw a PR from @esemplastic  which can fix your benchmark code on that repository modified  by yourself and open a fake issue here, this was not a good move of you, you could inform us before that, **however** I decide to give you a second chance, sorry but you have no write access to this repository any more for (1 month penalty for your behavior, not permanently)
