### ISSUE TITLE
undefined: iris.Context - has iris.Context changed to context.Context?

### ISSUE THREAD

**Issue by adamjaso** [kataras/iris#741]
When registering routes on "iris.Application", I get "iris.Context" errors like ".../main.go:14 undefined: iris.Context" even though "github.com/kataras/iris" has been imported. Changing to import "github.com/kataras/iris/context" and using "context.Context" seems to fix this, but I haven't found any docs that explain this change... Is this just a oversight of refactoring, or am I missing something?

**Comment by krokite** [comment]
Yes, it is now `context.Context`

**Comment by hiveminded** [comment]
@adamjaso  and @krokite 

The docs are updated, the real context is located at `context.Context` so use it as `import "github.com/kataras/iris/context"` **BUT** if you're using go version 1.9 you can use the `iris.Context` instead and omit the context import statement because it's a type alias, a new feature.

The `iris.Context` is described at the **README.md** under the `Hello World with Go 1.8` section, if you're hosting from go 1.8 it tells you why you want to import the `context` package.

@krokite It was always `context.Context`  the @adamjaso 's question was about docs because they see `iris.Context` I updated the docs to go 1.9 but I kept a section on README for people who using the old go version as well.

**Comment by hiveminded** [comment]
The docs are updated, the real context is located at `context.Context` so use it as `import "github.com/kataras/iris/context"` **BUT** if you're using go version 1.9 you can use the `iris.Context` instead and omit the context import statement because it's a type alias, a new feature.

The `iris.Context` is described at the **README.md** under the `Hello World with Go 1.8` section, if you're hosting from go 1.8 it tells you why you want to import the `context` package.

@krokite It was always `context.Context`  the @adamjaso 's question was about docs because they see `iris.Context` I updated the docs to go 1.9 but we kept a section on README for people who using the old go version as well.

**Comment by hiveminded** [comment]
The docs are updated to go 1.9, the real context is located at `context.Context` so use it as `import "github.com/kataras/iris/context"` **BUT** if you're using go version 1.9 you can use the `iris.Context` instead and omit the context import statement because it's a type alias, a new feature.

The `iris.Context` is described at the **README.md** under the `Hello World with Go 1.8` section, if you're hosting from go 1.8 it tells you why you want to import the `context` package.

@krokite It was always `context.Context`  the @adamjaso 's question was about docs because they see `iris.Context` I updated the docs to go 1.9 but we kept a section on README for people who using the old go version as well.
