### ISSUE TITLE
MVC: Support for ByByBy... functions without names

### ISSUE THREAD

**Issue by NextGringo** [kataras/iris#751]
Hello and thank you for this nice framework.

Can you please add the Support for `GetByBy...` functions without names/seperators like `GetByItemBy` to build URL like `/shop/12/98/` and not `/shop/12/item/98` ?

Thank you.

**Comment by kataras** [comment]
`GetByBy` is already checked but it's translated as `/12/by` because users may want to add `/by` into their paths and not be restricted by the Iris' keyword... however your question should be answered so I will think of it and I'll push a commit for that, star or watch the project to be notified for any updates

**Comment by kataras** [comment]
Done, thanks for your nice words and good point!

**Comment by kataras** [comment]
@NextGringo You can now do `GetBy(int, int)` for `shop/12/98` instead of `GetByBy(int, int)`.
