### ISSUE TITLE
iris.WithConfiguration doesn't set config.

### ISSUE THREAD

**Issue by SilverCory** [kataras/iris#772]
Setting the configuration either with app.Configure or app.Run doesn't actually set the config if you're using the `iris.WithConfiguration(...)` function.

For anyone who has experienced this, I have this vile snippet that can help.
```golang
func setConfiguration(i interface{}, configuration iris.Configuration) {
	configField := reflect.ValueOf(i).Elem().FieldByName("config")
	configField = reflect.NewAt(configField.Type(), unsafe.Pointer(configField.UnsafeAddr())).Elem()

	ptr := configField.Addr().Interface().(**iris.Configuration)
	**ptr = configuration
}

**Comment by kataras** [comment]
Hello @SilverCory , `WithConfiguration` works fine, the problem was with one single field `DisableVersionChecker` it was missing from the `WithConfiguration`'s validation, it has been fixed now, please close your PR as it's meanless now and it introduces a new function without reason, **the fix was 3 LOC**;

```go
// at configuration.go:L537
		if v := c.DisableVersionChecker; v {
			main.DisableVersionChecker = v
		}
```
