### ISSUE TITLE
i18n translate to specific language

### ISSUE THREAD

**Issue by gale93** [kataras/iris#789]
iris: 8.5.2
go: 1.9

It would be handy if we have a function to translate where you can choose the lang manually.

In my case, I need to generate a one time text for **all** languages my app supports.
Or is there already a way to achieve this ?

Thank you

**Comment by kataras** [comment]
Hello, I didn't understand exactly what you need from the `i18n` middleware. You can change the language manually by the `ctx.Values().Set("iris.language", "el-GR")` before calling the `ctx.Translate` . The `iris.language` key is also configurable via the `iris.Configuration` struct.  About your second question, what do you mean `one time text` ? The key-value language translate are saved in `.ini` files, if you want to parse them in order to do something else, is up to you.

**Comment by gale93** [comment]
All it is clear now.

I was mislead by the documentation that said it tries to take the lang from:
`ctx.Values().GetString("language")`
and that's why I couldnt get it done. 

Thank you very much.

**Comment by kataras** [comment]
It's `iris.language` I think but as mentioned you can change it to "language" as well :)

You're welcome, if you need anything else we're here!
