### ISSUE TITLE
Cannot install this framework

### ISSUE THREAD

**Issue by oneassasin** [kataras/iris#816]
Golang repository delete this repository
`golang.org/x/net/was-internal/iana`
And I cannot install framework

**Comment by kataras** [comment]
Installation works fine you're mistaken and you posted a repository that was never used and never existed at all!

Just tested on: windows, linux debian and macosx. The package you mention is named `golang.org/x/net/internal/iana` and one of the iris' session databases uses internally and it's vendored, so even if you were true, you could be able to install and use Iris forever because with Iris you get truly reproducible builds, iris guards against upstream renames and deletes.
