### ISSUE TITLE
Match trailing slash in the URL

### ISSUE THREAD

**Issue by ithemant09** [kataras/iris#820]
hi @kataras 
how to handle trailing space, I am always getting 404
http://localhost:8080/route/

app.Post("/route/", func(ctx iris.Context) {
		ctx.JSON(iris.Map{"result": "pass"})
	})

**Comment by kataras** [comment]
You don't have to and it's not correct to register `/route/` as route paths, if you learn this on any previous web framework you used, **it's wrong**.  Iris will match the request path `/route/` to the `/route` route, so you don't have to manually register that. There is an option for `DisablePathCorrection` but if you set that to true, this will just give 404 for `/route/` in order to give you the option to manually handle this error.
