### ISSUE TITLE
Roadmap or feature request list?

### ISSUE THREAD

**Issue by Velocity-** [kataras/iris#821]
I've been using Iris heavily over the past months and it's a web framework that beats every other one out there. I really feel inclined to help Iris become even better, but I can't find a roadmap. Is there a list of things that are desired or other ways to contribute?

**Comment by kataras** [comment]
Hey @Velocity- thank you for your green feedback!!

You don't need a roadmap or anything like that, you just open an issue and ask for a feature request, if it's not already implemented and it worths it, then I start coding it and push a new version, we don't have any "roadmap" because the framework is on version 8 now, most of the things you ever want as web developer are already implemented

**Comment by Velocity-** [comment]
Hey @kataras! No worries - I'm very enthusiastic about the framework you made. It's smooth as butter, performs super fast and lets me build web applications without hating it!

Keep up the good work. If I have new ideas or suggestions (or a bug) I'll let you know!

Thank you once again for your beautiful framework.
