### ISSUE TITLE
Recommended structure for large application

### ISSUE THREAD

**Issue by joefazee** [kataras/iris#83]
Hi,

Can you recommend a structure for large applications, e.g controller, route, model, service, middleware etc kind of structure? Basically where do we keep stuffs?

I think this will helpful when we need to share ideas and possible small projects with the community.

Convention keeps us on track and also gives us some kind of expectation where to find stuffs when you are looking at someone else project.

**Comment by kataras** [comment]
Hello, 

Beside the fact that Iris doesn't tell you 'must to do this way', you did right to open this issue, we can discuss it, I am not taking decisions alone for this kind of things, it's a community-driven project and I want to know the thoughts of this framework's users.  

Currently Iris doesn't have a database driver/framework/gorm (for model section). I want to keep the balance between simplicity and features, but you can always give ideas about it also and if the community wants it, it will be a feature!

For project structure, maybe it will be nice to great a full website example on the [iris-contrib repository](https://github.com/iris-contrib) but again we have to discuss it, how did you used to do with other languages or frameworks ?

**Comment by joefazee** [comment]
Personally i think i prefer your approach of keeping it simple, that was the idea that sold Codeigniter to most of us and today same idea is selling Flask to the Python community. Nothing is wrong with full-stack framework with batteries included but who want to learn a framework in 4 months?

Can we look at the style in Flask http://flask.pocoo.org/docs/0.10/blueprints/?

**Comment by kataras** [comment]
Yes you're right, the framework is important because it's the first part, after this you are responsible to design your code as you liked, I never liked frameworks who told me what to do, and how to do it. 

I read the docs you show me, I didn't like it neither.. I think `iris.Get("/", func(ctx *iris.Context){})` is simpler and more readable than the flask's, flask is making limitations, for example why a web framework must contains only templates? why you are forbidden to use  your template system, maybe with cache or a network layer based on the http and tcp? with flask you can't do it simple, with iris you can... also you can do just `ctx.Render("yourpage",pageContext{},"layout")` how much simpler that could be done? I don't know... if you give me examples on 'this is simpler,better and more extensible than this Iris' way' we can discuss to change the whole API, until then I can't change the public API(iris.Get,..Post)
