### ISSUE TITLE
iris.StaticWeb won't refresh static files!

### ISSUE THREAD

**Issue by luochuanyuewu** [kataras/iris#837]
This is the way i use(listening on :3000):
Router.StaticWeb("/","./public")
Under the public is a vue.js app(something like react or angular).
Every time i edited my frontend content(such as vue component, index.html file.), 
I can't see the changes by pressed F5 unless i change to another browser or clear my browser cache.
if i put my public file to apache's document root. everthing works fine!

anyone can help me?  Thank you very much!

**Comment by rebootcode** [comment]
Instead of `F5` - Press `Ctrl + F5`

**Comment by kataras** [comment]
@luochuanyuewu as @rebootcode told, do a hard refresh with ctrl/cmd+F5 instead because `StaticWeb` is for **static files** like favicons, static html, css, javascript files and things like these. 

If you want, check the `context`'s methods like `context#ServeFile` or `context#ServeContent` instead.

**Comment by luochuanyuewu** [comment]
Thanks !

**Comment by kataras** [comment]
You're welcome mate, have fun and when you finish your website post it here if you wanna:)
