### ISSUE TITLE
Suggest：run Iris as a service like caddy hook.service

### ISSUE THREAD

**Issue by Zeno-Code** [kataras/iris#855]
I think caddy's hook.service is great.
Go program daemon is easy to deploy
Suggest Iris native support
[github.com/kardianos/service](github.com/kardianos/service)

**Comment by kataras** [comment]
It's very easy to do it already, I think it's better to keep iris as a clear web framework package and not include daemon things because it will cause a little bit of confusion to the users. https://iris-go.com is running behind caddy and it works fine, if you have any questions about how to do it please post them
