### ISSUE TITLE
github.com/satori/go.uuid breaks iris

### ISSUE THREAD

**Issue by jeffisabel** [kataras/iris#864]
Latest github.com/satori/go.uuid breaks building:
> vendor/github.com/kataras/iris/core/errors/errors.go:35:22: multiple-value uuid.NewV4() in single-value context
```
func New(errMsg string) Error {
	return Error{
		ID:      uuid.NewV4().String(),   <--- error is not handled
		Message: Prefix + errMsg,
	}
}
```
Suggest fix: add error handling.

----------------------->%-------------------------

Examples for the Iris project can be found at
<https://github.com/kataras/iris/tree/master/_examples>.

Documentation for the Iris project can be found at
<https://godoc.org/github.com/kataras/iris>.

Love iris? Please consider supporting our collective:
👉  https://opencollective.com/iris/donate
👉  https://iris-go.com/donate

**Comment by kataras** [comment]
Althouh this is a duplicated post: https://github.com/kataras/iris/issues/861.

No, Iris doesn't break from those things. `go.uuid` is vendored here: https://github.com/kataras/iris/tree/master/vendor/github.com/satori/go.uuid. And even `Gopkg.toml` has a revision target instead of the master branch. If you had issues installing Iris please post below in order to help you
