### ISSUE TITLE
dep init won't work, github.com/iris-contrib/letsencrypt does not exist

### ISSUE THREAD

**Issue by luochuanyuewu** [kataras/iris#866]
As the tile said.

**Comment by kataras** [comment]
Hello and good morning dear @luochuanyuewu,

First of all `iris-contrib/letsencrypt` is **not used anywhere and it's not inside the [Gopkg.toml](https://github.com/kataras/iris/blob/master/Gopkg.toml)**, it doesn't exist at all I dont know how u find it.

Secondly, unlike other libraries, with Iris **you don't have to you use `dep`**, Iris is **fully fendored**, just do `go get -u github.com/kataras/iris`  and you're ready to go, the installation section never talks about `dep`.

Please next time post real issues in order to help all us, thank you very much!

**Comment by mohuishou** [comment]
I encountered the same problem，I found that is the reason cited jwt middleware， `github.com/iris-contrib/middleware` last releases is `5.0.0`，so `dep` will get  `iris.v5`.
`iris-contrib/letsencrypt` is used in `iris.v5`
add the following code to `Gopkg.toml` can be solved
```toml
[[constraint]]
  name = "github.com/iris-contrib/middleware"
  branch = "v8"
```

English is not very good

**Comment by kataras** [comment]
@mohuishou I didn't think of that, the branch there is "master" why it takes from "5.0.0" is another story... I just add `v10` branch to the releases of the `iris-contrib/middleware`, so this should fix the problem you had, thank you very much!

**Comment by mohuishou** [comment]
I just tried it a moment ago, it's work well
Thanks
Additional instructions, this package `github.com/iris-contrib/middleware`  was introduced manually
