### ISSUE TITLE
Change gopkg.in references to github

### ISSUE THREAD

**Issue by amansx** [kataras/iris#868]
Hi
Some of the dependencies are reference from gopkg.in such as "gopkg.in/yaml.v2" 
would be ideal if they are referenced from github such as "github.com/go-yaml/yaml/tree/v2"
due to
1. Consistency
2. Reliability

**Comment by kataras** [comment]
Go can't handle this, we can't import something like `tree/v2`, this is why `gopkg.in` exist in the first place. But you're lucky because Iris is fully vendored, you don't need no third-party tools, you don't have to worry about import paths that are used inside the framework's core, like that you noticed, because you will never have to download that dependency if  you use `go get -u github.com/kataras/iris` if you're `dep` or `glide` user it's another story and you may need to ask them for a more stable solution than they offer

**Comment by amansx** [comment]
Hey @kataras 
not exactly a new Gopher but my problem is the latter I'm using glide and it doesn't handle gopkg.in urls very well was wondering if it'd be worthwhile to make all gopkg.in packages in Iris as git submodules (~1) linked to the URL provided for example or maybe even fork it since Iris has versioned releases until dep can truely solve the multi version problem instead of using gopkg.in which is fairly unreliable..

**Comment by kataras** [comment]
Welcome to Go and third-party dependency managers like `glide` and `dep` :) However If you have any realistic suggestion I'm here for discussion

**Comment by amansx** [comment]
@kataras Thanks for all the hard work, I'll see what I can do
