### ISSUE TITLE
request: websocket connections & rooms, change from array lookups to hash tables

### ISSUE THREAD

**Issue by akiraho** [kataras/iris#869]
@kataras first off thx for accepting #862, where in your comments you touched on the performance of the code, speaking of which i actually have some concerns about the current websocket implementation.

the current code uses arrays for both connections & rooms (map of arrays) so every single add / get / delete operation is O(n); i.e. in the worst case scenario every such operation would loop thru all its elements. in the average case, well, at least it still needs to loop thru a certain number of them. potentially a problem in large scale real time websocket apps particularly if the rooms feature is relied upon.

so, would you consider changing them to hash table implementations? e.g. map for connections, map of maps for rooms. in that case, it changes everything to near O(1) constant time access. so then it doesn't matter how many connections the system's serving and is more scalable.

thanks.

**Comment by kataras** [comment]
Hello @akiraho ,

Yes I have thought it a lot before the implementation at all, we use slices to reduce the `locks`, it loops when we "get" a connection but that works in parallel if cores > 1, if we change it to a map we will have to use a `sync.RWMutex` each time, so the connection will wait for read and write access to the map. I don't think the slice instead of a map that are used there is performance problem, I think our library works faster than everything else in go so far, did you find other results? if yes then I am open for more detailed discussion about changing that else we have to chat about ideas that may improve the performance even more at https://chat.iris-go.com (this will reduce the spamming for github watchers for a subject that maybe they don't care at all)

**Comment by kataras** [comment]
@yz124 feel free to contribute by pushing a PR if you think something is not feeling right as you already did at https://github.com/kataras/iris/pull/862 and with my tiny additions it accepted! If you don't have time or don't feel ready to do it, at least give me an example to reproduce the issue you're talking about in order  to fix it myself at the coming days, no problem for me
