### ISSUE TITLE
Not work BeginRequest

### ISSUE THREAD

**Issue by krubenrc** [kataras/iris#873]
![2018-01-13 12_02_58-c__users_ruben_desktop_go2_routes_index_controller go login iris-master fz3-1](https://user-images.githubusercontent.com/33639842/34905486-c10bc15e-f859-11e7-99b2-b63534ed4721.png)
![2018-01-13 12_03_09-c__users_ruben_desktop_go2_main go login iris-master fz3-15145004127370 fz3-](https://user-images.githubusercontent.com/33639842/34905487-c124e44a-f859-11e7-95e9-ee5ea2fda72f.png)

Hi, im having problems with beginrequest in the controller of mvc app. This not work, it does not run.

main.go
```
index := mvc.New(app.Party("/"))
index.Register(&Jwt)
index.Router.Use(Jwt.Before)
index.Router.Done(Jwt.After)
index.Handle(new(Index.Controller))
```
index.go

```
type Controller struct {
	Ctx iris.Context

	Jwt *Jwt.Controller


	jwtValid bool
	jwtClaims *Jwt.ClaimsModel
}

func (this *Controller) BeginRequest(ctx context.Context) {
	fmt.Println("HI")
}
```

I  have tried with many combinations, but this not work.
You can help me? is a bug? issue? or i have error in the code?
I attach two images with the code complete.

Thanks you!!

**Comment by kataras** [comment]
Hello @krubenrc!

First of all you don't have to import the `github.com/kataras/iris/context`, you have already the `github.com/kataras/iris` imported so just use `iris.Context`.

Now **about your question**, yes `BeginRequest(Context)` can't work itself, **you have to delcare an `EndRequest(Context)` func** in order to complete the optional `mvc.BaseController` interface, examples says that, just add `func(this *Controller) EndRequest(_ iris.Context) {}` and you're fine.

I saw a generic "bad practise" on your code, you use `this` keyword, if I was you I would use just a `c` letter, as I did for the [_examples/mvc](_examples/mvc), this is just Go thing.

Another suggestion is to use the `dynamic dependencies (func(ctx iris.Context) <AnyValue> {})`  instead of require the `Ctx iris.Context` in your controller, with the new implementation you can entirely get rid of the "low-level" context inside your controllers and the `hero` funcs. 

Don't hesitate to post if you have any further questions!

**Comment by krubenrc** [comment]
thank you very very much!
Now it work!!

i do not know yet about Hero, that's why I do not use it
I will listen to your advice.

And again, thank you!

**Comment by kataras** [comment]
I made images for hero funcs as well, they are very easy and all examples contains comments so it's up to you to take advandage of them! Good job and you're welcome!!
