### ISSUE TITLE
session cache problem

### ISSUE THREAD

**Issue by heyouzhi** [kataras/iris#885]
1. iris version:git commmit hash:677f1e567754659f2d02afae0f40aa614a5f202e
1. go version: go version go1.9.2 linux/amd64
1. problem: I have two servers a and b,both share the same redis session,and they are behind a nginx proxy. When server a get session content before server b set content to redis db, server a will get a empty session object,and server a always cache this empty object in memory. Then,if server b change session in redis,server a's session cache is not same as redis db or server a!! Because,server a never update session cache after session created.
[provider.read](https://github.com/kataras/iris/blob/master/sessions/provider.go#L166) function mybe need update.

**Comment by kataras** [comment]
I think you have to configure your Redis for sync read and writes (either by iris' sessiondb/redis or via redis internal configuration, keep note that I am not a super expert on redis therefore I prefer you, as the consumer, to give me ideas on how I can help you to solve it) , if you have any suggestions feel free to update the `sessions/sessiondb/redis`.  `provider.Read` is just an interface, the implementation of each session database and its back-end storage's configuration is the key main thing here

**Comment by kataras** [comment]
Hello @heyouzhi and thanks for your interest on Iris but you have to fix the issue's title, the problem you're describing is not "session cache". The problem you're referring to is the `redis sync`, iris has nothing to do with it **you're running two different Iris web servers, but one redis back-end**.

You may want to read the `sessions/sessiondb` folder to learn how you can create your own session database and extend the `redis session db` by adding logic which will **communicate between your two web servers** and make decisions (yes you can do that, this is why the `RemoteStore` interface exists (`provider.read` is not the problem)) instead of recommend new changes to the core of the framework (which can't happen because of the nature of the problem you're describing, keep note you're using two web servers, so they can't communicate by the framework's core, you (or by using any third-party option) have to design it for your own needs). 

However I will be very glad to help you do that or/and add more options to the Redis configuration or any other database (if that's the case), but I have to tell you that most of the databases have options for internal synchronizations when `fetch` and `put`, feel free to [contact with me on chat](https://chat.iris-go.com) I am always free to help anyone using Iris, even if they are having problems that are not relative to Iris!

You have to configure your Redis for sync read and writes (either by iris' sessiondb/redis new implementation customized to your two web servers or via redis internal configuration, keep note that I am not a super expert on redis therefore I prefer you, as the consumer, to give me ideas on how I can help you to solve it) , if you have any suggestions feel free to update the `sessions/sessiondb/redis` or even create a new one, generelized.  `provider.read` is other thing, if you look the problem from top you will see that `provider.read` or any iris/sessions's function can help on this because you're running two different, compiled web servers, so I have to assume that you're talking about `RemoteStore` which is just an interface, the implementation of each session database and its back-end storage's configuration is the main key here, **even if the problem could be solved by changes to the iris code** we could endup with slower performance even if the session's storage is located on just one server and that's very bad, so you must think it out of go or Iris, the problem you're describing is not language's or framework's issue, it's generic and you can find a lot of solutions if you search about it on google, I am sure you will find a solution even if it's not implemented in Go, I can help you write that as well :)

**Comment by kataras** [comment]
Hello @heyouzhi and thanks for your interest on Iris but you have to fix the issue's title, the problem you're describing is not "session cache". The problem you're referring to is the `redis sync`, iris has nothing to do with it **you're running two different Iris web servers, but one redis back-end**.

You may want to read the `sessions/sessiondb` folder to learn how you can create your own session database and extend the `redis session db` by adding logic which will **communicate between your two web servers** and make decisions (yes you can do that, this is why the `RemoteStore` interface exists (`provider.read` is not the problem)) instead of recommend new changes to the core of the framework (which can't happen because of the nature of the problem you're describing, keep note you're using two web servers, so they can't communicate by the framework's core, you (or by using any third-party option) have to design it for your own needs). 

However I will be very glad to help you do that or/and add more options to the Redis configuration or any other database (if that's the case), but I have to tell you that most of the databases have options for internal synchronizations when `fetch` and `put`, feel free to [contact with me on chat](https://chat.iris-go.com) I am always free to help anyone using Iris, even if they are having problems that are not relative to Iris!

You have to configure your Redis for sync read and writes (either by iris' sessiondb/redis new implementation customized to your two web servers or via redis internal configuration, keep note that I am not a super expert on redis therefore I prefer you, as the consumer, to give me ideas on how I can help you to solve it) , if you have any suggestions feel free to update the `sessions/sessiondb/redis` or even create a new one, generelized.  `provider.read` is other thing, **if you go back and look the problem from top you will see that `provider.read` or any iris/sessions's function can't help on this because you're executing two different, compiled programs** 

The `RemoteStore` is the correct interface that a sessiondb must implement. The implementation of each session database and its back-end storage's configuration is the main key here. 

Last,  **even if the problem could be solved by changes to the iris/sessions** we could endup with slower performance even if the session's storage is located on just one server and that's very bad.

I recommend you think the issue out-of-the-box, out of golang or Iris, the problem you're describing is not language's or framework's issue, it's generic and you're not the only one having this problem, it's just your first time you have to do that, you will find a solution once and you will adapt that on every program you'll do on the future. I am sure that you will find a decent solution if you search on engines like google, you will learn about algorithms and more, when you find what you're looking for, then try to write it on Go, I can contritube to that as well if you [ask me](https://chat.iris-go.com) 

Good luck, don't hesitate to ask more, but please prefer to ask questions that are not closed-relative to Iris on that [chat](https://chat.iris-go.com) instead of the Iris' github repository. Thank you very much for reading all that (I edited it some times because of misspells and more explaination in order to help you find the correct origin of the problem you're described), hope that I helped enough!
