### ISSUE TITLE
Add ViewBaseDir for Party same as Layout?

### ISSUE THREAD

**Issue by Zeno-Code** [kataras/iris#886]
Each Party has a different template subdirectory
I have to write this way
```go
func main() {
    mvc.New(app).Handle(&controller{dir: "desktop"})
}

type controller struct {
	dir string
}

func (c controller) view(file string) string {
	return path.Join(c.dir, file)
}

func (c controller) Get() mvc.Result {
	return mvc.View{
		Layout: c.view("layout"),
		Name:   c.view("index"),
	}
}
```
If like this

```go
app.RegisterView(iris.HTML("./view", ".html"))
mvc.New(app.Party("m.").SubViewDir("mobile")).Layout("layout.html").Handle(...)

// ./view/mobile/layout.html
// ./view/mobile/index.html
```

**Comment by kataras** [comment]
Hello @Zeno-Code , that's a good idea but you can already do that by a middleware and `context#View` override ( we have examples for context function override).

If we do that the `ctx.View` must check the `ctx.Values().Get("_iris_sub_view") for a value, if it's string and it is not empty then prepend that to the view template's filename(the 1st argument of `ctx.View`), why? because `Party` and the executed handler are not in direct communication, so the `SubViewDir` will add a whole, extra, middleware just for this, in my opinion these are totally unnecessary steps that the function must make every time, no matter if you use the `SubViewDir` or not. 

Are you sure you want to implement this in the core framework instead of  just having `const MobileTmplDir = "mobile/" ` and do that like `ctx.View(MobileTmplDir+"index")` ?

**Comment by kataras** [comment]
Hello @Zeno-Code , that's a good idea but you can already do that by a middleware and `context#View` override ( we have examples for context function override).

If we do that the `ctx.View` must check the `ctx.Values().Get("_iris_sub_view")` for a value, if it's string and it is not empty then prepend that to the view template's filename(the 1st argument of `ctx.View`), why? because `Party` and the executed handler are not in direct communication, so the `SubViewDir` will add a whole, extra, middleware just for this, in my opinion these are totally unnecessary steps that the function must make every time, no matter if you use the `SubViewDir` or not. 

Are you sure you want to implement this in the core framework instead of  just having `const MobileTmplDir = "mobile/" ` and do that like `ctx.View(MobileTmplDir+"index")` ?

**Comment by kataras** [comment]
Hello @Zeno-Code , that's a good idea but you can already do that by a middleware and `context#View` override ( we have examples for context function override) or even by setting up a local variable and use that (the way I do it, it's the faster way [yes even that things matters to me]).

If we do that the `ctx.View` must check the `ctx.Values().Get("_iris_sub_view")` for a value, if it's string and it is not empty then prepend that to the view template's filename(the 1st argument of `ctx.View`), why? because `Party` and the executed handler are not in direct communication, so the `SubViewDir` will add a whole, extra, middleware just for this, in my opinion these are totally unnecessary steps that the function must make every time, no matter if you use the `SubViewDir` or not. 

Are you sure you want to implement this in the core framework instead of  just having `const MobileTmplDir = "mobile/" ` and do that like `ctx.View(MobileTmplDir+"index")` ?

**Comment by Zeno-Code** [comment]
I see in the core framework Will affect the speed
That's okay, I'm also very concerned about speed

**Comment by kataras** [comment]
Yeap, for mvc you can just set a controller field and create a function like `func (c *MyController) viewPath(rel string) string { return c.tmplPath+rel })` and use it like `return mvc.View{ Name: c.viewPath("index") }`

**Comment by kataras** [comment]
Yeap, for mvc you can just set a controller field and create a function like `func (c *MyController) viewPath(rel string) string { return c.tmplPath+rel })` and use it like `return mvc.View{ Name: c.viewPath("index.html") }`
