### ISSUE TITLE
Discussion: IsMobile distinguishes between phones and tablets？

### ISSUE THREAD

**Issue by Zeno-Code** [kataras/iris#887]
I think phone and Pad Should be check separately
or 
Split `IsMobile` 
`IsPhone` and `IsTablet` ( IsPad )

**Comment by kataras** [comment]
It can't happen, I already tried that but failed because the server have limited information sent by the client by-default. `IsMobile` says explicitly that it used for "mobile" when mobile means tablets and phones. I think it's wrong to depend on the `ctx.IsMobile` for client-side things, you can just use javascript there, use `ctx.IsMobile` as a server-side decision marker.
