### ISSUE TITLE
`Charset` with gzip. Response Header Content-Type Incorrect 

### ISSUE THREAD

**Issue by imkos** [kataras/iris#898]
#894 

I'm still ready to report the issue.

**Comment by kataras** [comment]
Now it's more specific issue, so charset with gzip isn't working, not the charset global configuration not used as you previously posted. Let me take a look on this then :)

**Comment by kataras** [comment]
![](https://user-images.githubusercontent.com/22900943/35797273-d9fcd336-0a67-11e8-9eca-15f4f7f11b8d.PNG)
![](https://user-images.githubusercontent.com/22900943/35797274-da22f606-0a67-11e8-8b9b-60d41d1c8ab3.PNG)

@imkos Still wrong, charset configuration is applied even with `app.Use(iris.Gzip)`, give us a code-snippet not just open duplicated issues, because they are invalid. Open the _examples/overview/main.go and add a `app.Use(iris.Gzip)` go to `app.Run..` and change the "UTF-8" to something like "ISO-8859-7", this is working so the issue on your case is something else but we can't help you if you don't want to...

**Comment by imkos** [comment]
app.Use(iris.Gzip)
....
ctx.Text(...), ctx.HTML(...) Response Header  Content-Type Incorrect

ctx.JSON(...)  Response Header Content-Type correct.
