### ISSUE TITLE
MVC GetBy(id int) Zero start

### ISSUE THREAD

**Issue by Zeno-Code** [kataras/iris#917]
```go
func (c *controller) GetBy(id int) string { return "Hey" }
`
abc.com/1
abc.com/01
abc.com/001

Hey

**Comment by Dexus** [comment]
You should use `string` instand of `int` if need.
Or what would you us say with this?

**Comment by Zeno-Code** [comment]
I just think there is unreasonable, it should be improved

**Comment by kataras** [comment]
@Zeno-Code 00001 is 1 as we know from scrools, even if we weren't programmers. If you put `000001` the golang, correctly, says it's `1` so **it's an expected and correct result**, why you want to change it and destroy the word as we already know?:P

If you don't want numbers and you rely on one character then as @Dexus says, just use `string` instead of `int` and make your own checks there, although I think that this is not a problem, do we reach the point that we can't find any bugs here and we post theoritical things about re-inverting maths? :P

**Comment by kataras** [comment]
@Zeno-Code 00001 is 1 as we know from scrools, even if we weren't programmers. If you put `000001` the golang, correctly, says it's `1` so **it's an expected and correct result**, why you want to change it and destroy the known world as we know it?:P

If you don't want numbers and you rely on one character then as @Dexus says, just use `string` instead of `int` and make your own checks there, although I think that this is not a problem, do we reach the point that we can't find any bugs here and we post theoritical things about re-inverting maths? :P

**Comment by kataras** [comment]
@Zeno-Code 00001 is 1 as we know from scrools, even if we weren't programmers. If you put `000001` the golang, correctly, says it's `1` so **it's an expected and correct result**, why you want to change it and destroy the known world as we know it?:P

If you don't want numbers and you rely on chars then as @Dexus says, just use `string` instead of `int` and make your own checks there, although I think that this is not a problem, do we reach the point that we can't find any bugs here and we post theoritical things about re-inverting maths? :P

**Comment by Zeno-Code** [comment]
00001 is 1 That's right
But We should see what it is under
When in route path, 1 01 001 0001 return same result if do not care about the beginning of the zero
Different URLs return the same content，Not good, this is a consensus

Filter at the beginning of the zero ,Do more appropriate at the framework level
