### ISSUE TITLE
Global handler controller.

### ISSUE THREAD

**Issue by Jinfaa** [kataras/iris#932]
Hello! I had a problem in preprocessing a controller request.
When the user communicates to any "admin" controller country: /admin/{param}/user, /admin/{param}/base, etc. I need to first check in the database whether the current user has access to these pages. I could just add a check in each function, but can I do a global check?
Now I did this:

```
type AdminController struct {
	Ctx     iris.Context
	Service services.ApplicationService // repository connected with database
}

func (c *AdminController) BeforeActivation(b mvc.BeforeActivation) {
	b.Router().Use(userCheck)

       // c.Service.GetByParam("param") // c.Service is nil
}

func userCheck(ctx iris.Context) {
	currentPath := ctx.GetCurrentRoute().Path()
	session := middleware.SessionsManager.Start(ctx)
	currentUser := middleware.GetCurrentUser(session)
	param := ctx.Params().Get("param")

        // But I can not access the service here to access the database.
       
        c.Ctx.Next() // if there is access
        с.Ctx.StatusCode(403) // if not
}
```

**Comment by Jinfaa** [comment]
Now I did this and it works:

```
func (c *AdminController) BeforeActivation(b mvc.BeforeActivation) {
	b.Router().Use(c.userCheck)
}

func (c *AdminController) userCheck(ctx iris.Context) {
	currentPath := ctx.GetCurrentRoute().Path()
	session := middleware.SessionsManager.Start(ctx)
	currentUser := middleware.GetCurrentUser(session)
	param := ctx.Params().Get("param")

        // c.Service isn't nil!
}
```

That's the right decision? I am confused only by the fact that the context I have and the variable "c" and "ctx".

**Comment by kataras** [comment]
You had a ` func(ctx iris.Context) {}` and you tried to access a variable that you didn't define, no it's not if you don't need the `userCheck` to access the `c.Service` then you dont need to be inside the `AdminController` but if you do, yes do it. If you have `func(ctx iris.Context)` in your controller functions then you can delete the `c.Ctx` at all, what's the reason to have that if you don't use it? You can also make use of the function dynamic bindings to get rid of the `iris..Context` inside your controllers and have a better code, but you have to know a little Go before that

**Comment by Jinfaa** [comment]
Thanks for the answer!
Here is my main.go:

```
fun main(){
...
session, err := mgo.Dial("mongodb://192.168.0.133/")
if nil != err {
	panic(err)
}
defer session.Close()
session.SetMode(mgo.Monotonic, true)
db := session.DB("mydb")

applicationService := services.NewApplicationService(db)

adminPrt := app.Party("/admin")
adminPrt.Layout("admin/layout.html")
adminController := mvc.New(adminPrt)
adminController.Register(applicationService, sessManager.Start)
adminController.Handle(new(controllers.AdminController))
...
}
```

The controller I described above.
I could get rid of "Ctx", but I in some functions use the function "c.Ctx.JSON ()".

I just want everything to be right. :)

I really like working with Iris.

**Comment by kataras** [comment]
> I could get rid of "Ctx", but I in some functions use the function "c.Ctx.JSON ()".

That's why I told you about dynamic bindings, we even [have screenshots](https://github.com/kataras/iris/blob/master/HISTORY.md#hero) about those things @Jinfaa 

The dynamic function, it gets the `iris.Context` use inside a hero func(all hero features are mvc features as well, i.e `hero.Register` is your `mvc application.Register` ) The hero (or mvc) handler expects a `LoginForm`, so we `Register` the dynamic dependency  and set the `LoginForm` by using the `ctx.ReadForm`, the rest are taking cared by the framework: 
 
![](https://raw.githubusercontent.com/kataras/explore/master/iris/hero/hero-3-monokai.png)

Another example, is the `websocket` controller which binds the result of the `websocket.Upgrade` function to a `Conn websocket.Connection` field inside the controller, look here: https://github.com/kataras/iris/blob/master/_examples/mvc/websocket/main.go#L35 and https://github.com/kataras/iris/blob/master/_examples/mvc/websocket/main.go#L53.

You can read full code examples about all those, these things will make your **app a next-level app** and you, a real **rock star developer**.

**Comment by kataras** [comment]
> I could get rid of "Ctx", but I in some functions use the function "c.Ctx.JSON ()".

That's why I told you about dynamic bindings, we even [have screenshots](https://github.com/kataras/iris/blob/master/HISTORY.md#hero) about those things @Jinfaa 

The dynamic function, it gets rid the `iris.Context` use inside a hero handler (all hero features are mvc features as well, i.e `hero.Register` is your `mvc application.Register` ) by using dependencies that are depending on the Context and can be registered via the `Register.

The hero (or mvc) handler expects a `LoginForm`, so we `Register` the dynamic dependency  and set the `LoginForm` by using the `ctx.ReadForm`, the rest are taking cared by the framework: 
 
![](https://raw.githubusercontent.com/kataras/explore/master/iris/hero/hero-3-monokai.png)

Another example, is the `websocket` controller which binds the result of the `websocket.Upgrade` function to a `Conn websocket.Connection` field inside the controller, look here: https://github.com/kataras/iris/blob/master/_examples/mvc/websocket/main.go#L35 and https://github.com/kataras/iris/blob/master/_examples/mvc/websocket/main.go#L53.

You can read full code examples about all those, these things will make your **app a next-level app** and you, a real **rock star developer**.



If you will love to see more of that please give +1 and tomorrow you will have a whole new example, although all the above resources are enough, but in any case, no problem for me :)
