### ISSUE TITLE
Context PostValueIntDefault method should be return (int, error) ?

### ISSUE THREAD

**Issue by jefurry** [kataras/iris#937]
`iris/context/context.go`

i think PostValueIntDefault method should be return int. if happend error, given it zero.

same as PostValueInt64Default, PostValueFloat64Default, URLParamIntDefault, URLParamInt64Default, URLParamFloat64Default etc. because i want to get a value only.

**Comment by kataras** [comment]
Hello @jefurry,

The feature you're asking for it's already there.

The `PostValueXXXDefault` methods were added in order to give a default value if an error occurred, that's the reason they've added. If you want to manually check for errors then use the `PostValueXXX` i.e `ctx.PostValueInt` which [returns an (int,error)](https://github.com/kataras/iris/blob/master/context/context.go#L534).

Thanks,
Gerasimos Maropoulos

**Comment by kataras** [comment]
Hello @jefurry,

The feature you're asking for it's absolutely logical and I was thinking the same when I added those.

The `PostValueXXXDefault` methods should do what you're describing, they were added for that reason but when I though it better I selected to return the error as well, because you may want to know if it's a `parse error` (0 value and the error returned) or just not found by the request (the default value that caller passed an a nil error).

Unfortunaly(?) I can't change it now, because it will bring breaking changes.  Both `PostValueXXX(key) error` and `PostValueXXXDefault(key, defaultValue) (XXX, error)` are very useful, including the returned error of the second. 

What we can do instead? We can create new functions to complete your request, if you're OK with this, you can also recommend some names for those :) 

Thanks,
Gerasimos Maropoulos

**Comment by kataras** [comment]
Hello @jefurry,

The implementation you're asking for is absolutely logical and I was thinking the same when I decide to add them. 

The `PostValueXXXDefault` methods should do that you're describing of. To be honest, they were added for that reason but before push I thought it a bit further and I selected to return the error as well, because you may want to know if it's a `parse error` (0 value and the error returned) or just not found by the request (the default value the caller passed and a nil error).

Unfortunaly(?) I can't change it now, because it will bring breaking changes.  
Both `PostValueXXX(key) error` and `PostValueXXXDefault(key, defaultValue) (XXX, error)` are very useful, including the returned error of the second. 

What we can do instead? We can create new functions to complete your request, if you're OK with this, **you can also recommend some names for those** :) 

Thanks,
Gerasimos Maropoulos

**Comment by kataras** [comment]
Hello @jefurry,

The implementation you're asking for is absolutely logical and I was thinking the same when I decide to add them. 

The `PostValueXXXDefault` methods should do that you're describing of. To be honest, they were added for that reason but before push I thought it a bit further and I selected to return the error as well, because you may want to know if it's a `parse error` (0 value and the error returned) or just not found by the request (the default value the caller passed and a nil error).

Unfortunately (?) I can't change it now, because it will bring breaking changes.  
Both `PostValueXXX(key) (XXX, error)` and `PostValueXXXDefault(key, defaultValue) (XXX, error)` are very useful, including the returned error of the second. 

What we can do instead? We can create new functions to complete your request, if you're OK with this, **you can also recommend some names for those** :) 

Thanks,
Gerasimos Maropoulos

**Comment by jefurry** [comment]
I think there was a problem at the beginning.

PostValueXXX is not need to a default value, if want to catch any error, uses PostValueXXX, otherwise uses PostValueXXXDefault. now It's confusing!

```
func (ctx *context) PostValueIntDefault(name string, def int) (int, error) {
	v := ctx.PostValue(name)
	if v == "" {
		return def, nil
	}
	return strconv.Atoi(v)
}

func (ctx *context) PostValueInt(name string) (int, error) {
	return ctx.PostValueIntDefault(name, 0)
}
```

change to:

```
func (ctx *context) PostValueInt(name string) (int, error) {
	return strconv.Atoi(ctx.PostValueTrim(name))
}

func (ctx *context) PostValueIntDefault(name string, def int) int {
	if v, err := ctx.PostValueInt(name); err == nil {
            return v
        }

        return def
}
```

As you said, it will bring breaking changes if you change it now. But you will eventually do it!

**Comment by jefurry** [comment]
`ViewData` Exposed too much detail. nobody using it like this:
```
ctx.ViewData("title", "this is title")
...
ctx.ViewData(...)
```

and `View` method should be:
```
func (ctx *context) View(filename string, optionalBindingData ...interface{}) error {
    ...
    if len(optionalBindingData) > 0 {
        ctx.ViewData("", optionalBindingData)
    }
    bindingData := ctx.values.Get(cfg.GetViewDataContextKey())
    ...
}
```
we hope so.

raw body should be cached. because sometimes we want to deal with it ourselves!

**Comment by kataras** [comment]
You didn't suggest any names, so I will follow my instinct and if you like it we are fine otherwise there is no any issue, all works as expected.

**Comment by kataras** [comment]
OK @jefurry so you want to propose a breaking API change there, I am fine with it but you have to answer to users about this, right? The result will be the same. The `ViewData` is used by many people, you're wrong about it, it's code is fine, we don't have any issues there, it was a user proposal in order to modify view data from other handlers in the request chain.

**Comment by kataras** [comment]
This will change the `sessions.GetIntDefault` as well.

**Comment by kataras** [comment]
Done @jefurry , upgrade to the latest version, *10.5.0*, with `go get -u github.com/kataras/iris`, the commit: https://github.com/kataras/iris/commit/efd6e86eaf8f7c3f5a8c3a051d4afe6124f3ff0b. Example change: 

old:
`count,_ := c.Session.GetIntDefault("count", 1)` 

now (_>=v10.5_):
`count := c.Session.GetIntDefault("count", 1)`

**Comment by jefurry** [comment]
i mean that `ViewData` exposed too much details, such as ViewData("key", "value"), ViewData("", ...) etc.

in summary, iris's api is very unfriendly, so i will give up using `iris`. thanks!
