### ISSUE TITLE
pongo2 custom template directory error

### ISSUE THREAD

**Issue by sanqi** [kataras/iris#94]
go run web.go
panic: template: index:1: function "message" not defined

web.go
```
package main

import (
    "github.com/kataras/iris"
    "github.com/kataras/iris/middleware/pongo2"
)

func main() {
    iris.Use(pongo2.Pongo2())

    iris.Get("/", func(ctx *iris.Context) {
        ctx.Set("template", "./templates/index.html")
        ctx.Set("data", map[string]interface{}{"message": "Hello World!"})
    })

    iris.Listen(":8080")
}
```
templates/index.html
`{{message}}`

**Comment by kataras** [comment]
@sanqi  You propably doing something wrong, because this example is working:
```go
//main.go
package main

import (
	"github.com/kataras/iris"
	"github.com/kataras/iris/middleware/pongo2"
)

func main() {
	iris.Use(pongo2.Pongo2())

	iris.Get("/", func(ctx *iris.Context) {
		ctx.Set("template", "./index.html")
		ctx.Set("data", map[string]interface{}{"username": "iris", "is_admin": true})
	})

	iris.Listen(":8080")
}
```

```html
<!-- index.html -->
<HTML>
<head><title>Hello Pongo2 from Iris</title></head>
<body>
	 {% if is_admin %}<p>{{username}} is an admin!</p>{% endif %}
</body>
</HTML>
```

please provide more info.

**Comment by kataras** [comment]
Yes, this is happening only if you have your templates inside `./templates` directory, because this directory is used by the iris.Render, wait I will fix it

**Comment by sanqi** [comment]
Perhaps you can let pongo2 use iris.Render?

**Comment by kataras** [comment]
Ok I found many solutions but let things simple and just do that: 

```go
	iris.Use(pongo2.Pongo2("./templates")) // or .Pongo2() defaults to "./"

        // this is the important
	iris.Config().Render.Directory = "change_this_because_its_defaults_to_templates_directory_also"

	iris.Get("/", func(ctx *iris.Context) {
		ctx.Set("template", "index.html")
		ctx.Set("data", map[string]interface{}{"message": "Hello World!"})
	})

	iris.Listen(":8080")

```

Yes now you have the option to delcare the templates directory from Pongo2 middleware, you cannot use the same template's directory for html/template and pongo2 because they have different parser, thanks for your notice!

P.S: Community was decidede that Iris must keep the things simple as possible and not use other template engines/parsers than the html/template, with the Iris' render the html/template are also useful, I'm using just this also :)

**Comment by sanqi** [comment]
Thank you, That's great.
