### ISSUE TITLE
Failed to customize Content-Type when serving files

### ISSUE THREAD

**Issue by pyrostrex** [kataras/iris#954]
Hi, good to know that iris is still in development until today. I'm currently using iris v10.5.0.

I have this one use case where I am trying to use `ctx.ServeFile` such below

```go
// taken from database
filePath := "./uploads/f7b01b04-9739-400e-9fa4-c64b33daa96a"
fileContentType := "image/jpeg"

ctx.ServeFile(filePath, false)
ctx.ContentType(fileContentType)

// also tested with
// ctx.ContentType(fileContentType)
// ctx.ServeFile(filePath, false)
```

My expected response headers should be something like
```
Content-Type: image/jpeg; charset=UTF-8
```
But instead i get something like
```
Content-Type: f7b01b04-9739-400e-9fa4-c64b33daa96a; charset=UTF-8
```

By studying the context.go on iris repository, i found out that this might be due to `ServeContext` was modifying the `Content-Type` by filename.

Umm, do i have to create my own ServeContext implementation on this?

Related question (I'm not sure if i should open a new issue for this):
- Is the resumable sendfile related to #359 still working on the current iris?

Best regards!. Iris is awesome!

**Comment by pyrostrex** [comment]
I just solved my problem :sweat_smile:. In case anyone else wondering:
```go
// taken from database
filePath := "./uploads/f7b01b04-9739-400e-9fa4-c64b33daa96a"
fileContentType := "image/jpeg"

ctx.ContentType(fileContentType )
http.ServeFile(ctx.ResponseWriter(), ctx.Request(), filePath)
```
I'm not sure if this is the supposed way to do this. But at least this works for me. :grin:

I will leave this one open as i still think `ctx.ServeFile`, `ctx.SendFile` and `ctx.ServeContent` requires attention. @kataras, feel free to close if you think otherwise.

Again, thank you for this framework.

**Comment by kataras** [comment]
Hello @pyrostrex , this is expected behavior, this is documented, this is why I'm writing on the examples to learn `net/http` first and after Iris, you're missing some important, but basic, things. This is not a problem, you just write everything else before the actual body write, all examples do this, all iris starters kits repositories and also other web frameworks that are aligned with the net/http by-default, it's not Iris-specific thing, it's Go.

When using the default `ResponseWriter`: Header should be defined before any content write(`ctx.Write`, `ctx.WriteGzip`, `ctx.WriteString`, `ctx.Writef`, `ctx.ServeFile` and so on...) **This is basic thing**.

If you change it to `ctx.Recorder() -> context.ResponseRecorder -> ctx.ResponseWriter() == context.ResponseRecorder` then the order doesn't matter and you can reset or retrieve the written body at any handler in the request chain. 


Thanks for your time opening this issue though, but please look the previous one or the examples before spend your precious time for an issue, for your own good :P

**Comment by pyrostrex** [comment]
Hi @kataras, thanks for the answer! 😄 

To be honest, I am still quite a beginner when it comes to Go. 

Anyway, i'm still curious heheh, actually I was following the `File Server > Send File` example which states to use `ctx.ServeFile` and here is where I start to face this problem. 

While traversing through the code, I noticed that `ctx.SendFile` is calling `ctx.ServeFile` which then calls `ctx.ServeContent` that uses it's own basic implementation rather than to use the more complete `http.ServeContent` implementation. 

Is this `ctx.ServeContent` implementation intentional? because as far as I can see (sorry if I'm wrong), the current implementation is quite minimal (no `Content-Range` support and no fallback `Content-Type` support).

With how the current `ctx.ServeContent` behave combined with [context.go#L2952](https://github.com/kataras/iris/blob/0ff15f7408184631109754d6ad8c14ea464a5d2c/context/context.go#L2952) it really does confused me, at least until I realized the solution above hehe :laughing:.

Also thanks for the tips really appreciate it!
