### ISSUE TITLE
Concurrent access issues in HTMLEngine.ExecuteWriter

### ISSUE THREAD

**Issue by planerist** [kataras/iris#956]
ExecureWriter works in parallel for many requests. But it calls runtimeFuncsFor for each request:

`func (s *HTMLEngine) runtimeFuncsFor(name string, binding interface{}) {
	funcs := template.FuncMap{
		"render": func(fullPartialName string) (template.HTML, error) {
			buf, err := s.executeTemplateBuf(fullPartialName, binding)
			return template.HTML(buf.String()), err
		},
	}

	if tpl := s.Templates.Lookup(name); tpl != nil {
		tpl.Funcs(funcs)
	}
}`

So tpl.Funcs(funcs) is called concurrently for parallel request. 
But "render" implementation depends on each request context "bindings". So we get classical data race condition here.

**Comment by kataras** [comment]
No you don't get "classical data race", new map is creating every time to be unique per template, you pasted the code yourself: `template.FuncMap{...}` is that we return. Also you don't have any issue *because you define the funcs BEFORE the server ran and you don't change them, if you do change the view engine's functions are serve time inside a handler, then it's wrong, you must follow the examples*.
