### ISSUE TITLE
vendor build broken: github.com/satori/go.uuid made incompatible change

### ISSUE THREAD

**Issue by sc-rz** [kataras/iris#961]
Hi,

`github.com/satori/go.uuid` made a change that was not backwards compatible (https://github.com/satori/go.uuid/commit/0ef6afb2f6cdd6cdaeee3885a95099c63f18fc8c#diff-18f04d9ad3369192f1154eb2a981af41). I had to update my vendor copy of `github.com/satori/go.uuid` so now `iris` can't build. I'm using a vendoring tool that flattens vendor directories so I can't build despite `iris` having a `vendor` directory. 

The return value of `uuid.NewV4` changed from `(UUID)` to `(UUID, error)`

I believe the fix is 
```
github.com/kataras/iris/core/errors/errors.go:35: 	
ID:      uuid.Must(uuid.NewV4()).String(),

github.com/kataras/iris/sessions/config.go:117
id := uuid.Must(uuid.NewV4())
```
which will panic on error, which was the old behavior.

**Comment by kataras** [comment]
again? I think the `vendor` has the correct version, the old because because `session databases like badgerdb ` uses that version, what's the problem?

**Comment by kataras** [comment]
I can't do anything for that mate, the `vendor for uuid` we have it's not because of Iris but one of its session databases, if you just let iris out of your `flattern vendoring` by using a third-party tool, you will be fine and remember this can happen with every other dependency on the future so `flat dependencies` are not the Go way, change that behavior now.

**Comment by kataras** [comment]
@sc-rz fixed with the latest commit.

**Comment by sc-rz** [comment]
@kataras thanks!
