### ISSUE TITLE
Jade import is broken

### ISSUE THREAD

**Issue by rocketbitz** [kataras/iris#968]
master: Could not introduce github.com/Joker/jade@master, as its subpackage github.com/Joker/jade does not contain usable Go code (*pkgtree.LocalImportsError).. (Package is required by github.com/kataras/iris@v10.4.0.)

**Comment by kataras** [comment]
I don't see this problem here, I install the Iris on a fresh machine and worked without any issues, could you please provide me more info (note that if you use an external dependency manager you have to configure that or open an issue to the corresponding repository).

Thank you @rocketbitz ,
Gerasimos Maropoulos

**Comment by rocketbitz** [comment]
Ya, it appears it was resolved by the jade repo, but could have been avoided if iris depended on the versioned tag instead of just master branch.

Thanks.

**Comment by kataras** [comment]
Why? Iris uses the vendor folder, you mean by tagging in on the `Gopkg.toml` file? (I will say it again, iris is fully vendored the issue you described was not caused by iris side but by your side by not using this vendor folder iris provides and use an external tool instead)  If that's the case then no, the issue will be there *because jade* does not provide tags, it has only one (4 days ago, the fix you mention is made 3 days ago, so you would still had this issue even with tagging).
