### ISSUE TITLE
How to config AutoTls

### ISSUE THREAD

**Issue by loveumore** [kataras/iris#973]
hi, I use freessl.org create let's encryt file with ECC algorithm.
Then got two file : full_chain.pem(include cert and ca) and private.pem.
then how to config my tls connect with iris framework?

**Comment by loveumore** [comment]
it seems like I use free cloudflare cdn service, so can't use let's crypt.

**Comment by kataras** [comment]
You can always use custom *http.Server via `iris.Server`  or pass a cert and key via `iris.TLS` instead of `iris.Addr`  inside the `iris.Run`, there are examples in the [_examples/http-listening](https://github.com/kataras/iris/tree/master/_examples/http-listening) folder, which contains a README as well.
