### ISSUE TITLE
How to close WebSocket connection with message?

### ISSUE THREAD

**Issue by Kirguir** [kataras/iris#976]
Hi, how do it with Iris?

**Comment by kataras** [comment]
You can use the `Disconnect` method to close a connection and to throw any garbage data that may had, like connection's room and etc but, for reasons I can't really follow now, you don't want to do this, you want to let data exist in your server-side and just close the websocket connection, you can do it by sending a `websocket.CloseMessage` via the connection's low-access `Write` method (`c.Write(websocket.CloseMessage, nil)`), do a `go get -u github.com/kataras/iris` because I've just exposed this method to public.

**Comment by Kirguir** [comment]
Thank you @kataras

**Comment by kataras** [comment]
You're very welcomed @Kirguir! , if you want star the repository to get updates
